// This file is automatically generated.

package adila.db;

/*
 * Archos 50e Helium
 *
 * DEVICE: ac50ehe
 * MODEL: Archos 50e Helium
 */
final class ac50ehe {
    public static final String DATA = "Archos|50e Helium|Helium";
}
