// This file is automatically generated.

package adila.db;

/*
 * Archos 55 Cobalt Plus
 *
 * DEVICE: ac55cop
 * MODEL: Archos 55 Cobalt Plus
 */
final class ac55cop_archos205520cobalt20plus {
    public static final String DATA = "Archos|55 Cobalt Plus|Cobalt";
}
