// This file is automatically generated.

package adila.db;

/*
 * Archos 55b Platinum
 *
 * DEVICE: ac55bpl
 * MODEL: Archos 55B Platinum
 */
final class ac55bpl {
    public static final String DATA = "Archos|55b Platinum|Platinum";
}
