// This file is automatically generated.

package adila.db;

/*
 * Cubot Note S
 *
 * DEVICE: CUBOT_NOTE_S
 * MODEL: CUBOT_NOTE_S
 */
final class cubot5fnote5fs_cubot5fnote5fs {
    public static final String DATA = "Cubot|Note S|";
}
