// This file is automatically generated.

package adila.db;

/*
 * i-mobile IQ II
 *
 * DEVICE: imobileiq2_sprout
 * MODEL: i-mobile IQ II
 */
final class imobileiq25fsprout {
    public static final String DATA = "i-mobile|IQ II|";
}
