// This file is automatically generated.

package adila.db;

/*
 * Myphone My86 DTV
 *
 * DEVICE: MyPhone_my86_DTV
 * MODEL: MyPhone_my86_DTV
 */
final class myphone5fmy865fdtv_myphone5fmy865fdtv {
    public static final String DATA = "Myphone|My86 DTV|";
}
