// This file is automatically generated.

package adila.db;

/*
 * Allview V2 Viper X
 *
 * DEVICE: V2_Viper_X
 * MODEL: V2_Viper_X
 */
final class v25fviper5fx_v25fviper5fx {
    public static final String DATA = "Allview|V2 Viper X|Viper";
}
