// This file is automatically generated.

package adila.db;

/*
 * Allview X3 Soul Mini
 *
 * DEVICE: X3_Soul_mini
 * MODEL: X3_Soul_mini
 */
final class x35fsoul5fmini_x35fsoul5fmini {
    public static final String DATA = "Allview|X3 Soul Mini|Soul";
}
