// This file is automatically generated.

package adila.db;

/*
 * Archos 101d Neon
 *
 * DEVICE: ac101dne
 * MODEL: Archos 101d Neon
 */
final class ac101dne {
    public static final String DATA = "Archos|101d Neon|Neon";
}
