// This file is automatically generated.

package adila.db;

/*
 * Archos 52 Platinum
 *
 * DEVICE: ac52pl
 * MODEL: Archos 52 Platinum
 */
final class ac52pl {
    public static final String DATA = "Archos|52 Platinum|Platinum";
}
