// This file is automatically generated.

package adila.db;

/*
 * Fly Nimbus 1
 *
 * DEVICE: Nimbus1
 * MODEL: FS451
 */
final class nimbus1_fs451 {
    public static final String DATA = "Fly|Nimbus 1|Nimbus";
}
