// This file is automatically generated.

package adila.db;

/*
 * Allview V1 Viper S4G
 *
 * DEVICE: V1_Viper_S4G
 * MODEL: V1_Viper_S4G
 */
final class v15fviper5fs4g_v15fviper5fs4g {
    public static final String DATA = "Allview|V1 Viper S4G|Viper";
}
