// This file is automatically generated.

package adila.db;

/*
 * Mecer 101P51C
 *
 * DEVICE: 101P51C
 * MODEL: 101P51C
 */
final class _101p51c_101p51c {
    public static final String MANUFACTURER = "Mecer";
    public static final String NAME = "101P51C";
}
