// This file is automatically generated.

package adila.db;

/*
 * Coolpad 3700A
 *
 * DEVICE: 3700A
 * MODEL: CP3700A
 */
final class _3700a_cp3700a {
    public static final String DATA = "Coolpad|3700A|";
}
