// This file is automatically generated.

package adila.db;

/*
 * NEC PC-508T1W
 *
 * DEVICE: 508T1W
 * MODEL: PC-TS508T1W
 */
final class _508t1w_pc2dts508t1w {
    public static final String DATA = "NEC|PC-508T1W|";
}
