// This file is automatically generated.

package adila.db;

/*
 * Coolpad CP5660S
 *
 * DEVICE: 5560S
 * MODEL: 5560S
 */
final class _5560s_5560s {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "CP5660S";
}
