// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH Victory
 *
 * DEVICE: 7046T
 * MODEL: Alcatel 7046T
 */
final class _7046t_alcatel207046t {
    public static final String DATA = "Alcatel|ONETOUCH Victory|";
}
