// This file is automatically generated.

package adila.db;

/*
 * Hipstreet 785TB4
 *
 * DEVICE: 785TB4
 * MODEL: 785TB4
 */
final class _785tb4_785tb4 {
    public static final String DATA = "Hipstreet|785TB4|";
}
