// This file is automatically generated.

package adila.db;

/*
 * Mecer 800P31C
 *
 * DEVICE: 800P31C
 * MODEL: 800P31C
 */
final class _800p31c_800p31c {
    public static final String MANUFACTURER = "Mecer";
    public static final String NAME = "800P31C";
}
