// This file is automatically generated.

package adila.db;

/*
 * Coolpad CP8750
 *
 * DEVICE: 8750
 * MODEL: Coolpad8750
 */
final class _8750 {
    public static final String DATA = "Coolpad|CP8750|";
}
