// This file is automatically generated.

package adila.db;

/*
 * Sharp A01SH
 *
 * DEVICE: A01SH
 * MODEL: A01SH
 */
final class a01sh_a01sh {
    public static final String DATA = "Sharp|A01SH|";
}
