// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: A065
 * MODEL: Micromax A065
 */
final class a065_micromax20a065 {
    public static final String DATA = "Micromax|Bolt|";
}
