// This file is automatically generated.

package adila.db;

/*
 * Micromax UNITE
 *
 * DEVICE: A092
 * MODEL: Micromax A092
 */
final class a092_micromax20a092 {
    public static final String DATA = "Micromax|UNITE|";
}
