// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Fire3
 *
 * DEVICE: A096
 * MODEL: Micromax A096
 */
final class a096_micromax20a096 {
    public static final String DATA = "Micromax|Canvas Fire3|";
}
