// This file is automatically generated.

package adila.db;

/*
 * Lenovo A1000L
 *
 * DEVICE: A1000LF
 * MODEL: IdeaTabA1000L-F
 */
final class a1000lf_ideataba1000l2df {
    public static final String DATA = "Lenovo|A1000L|";
}
