// This file is automatically generated.

package adila.db;

/*
 * Archos 101 G9
 *
 * DEVICE: A101
 * MODEL: ARCHOS 101G9
 */
final class a101_archos20101g9 {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "101 G9";
}
