// This file is automatically generated.

package adila.db;

/*
 * Archos 101 Neon
 *
 * DEVICE: A101NE
 * MODEL: Archos 101 Neon
 */
final class a101ne_archos2010120neon {
    public static final String DATA = "Archos|101 Neon|";
}
