// This file is automatically generated.

package adila.db;

/*
 * Lenovo IdeaTab A1020
 *
 * DEVICE: A1020T
 * MODEL: IdeaTabA1020-T
 */
final class a1020t_ideataba10202dt {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "IdeaTab A1020";
}
