// This file is automatically generated.

package adila.db;

/*
 * Garmin 
 *
 * DEVICE: a10
 * MODEL: Garmin-Asus A10
 */
final class a10_garmin2dasus20a10 {
    public static final String MANUFACTURER = "Garmin";
}
