// This file is automatically generated.

package adila.db;

/*
 * Oppo A11
 *
 * DEVICE: A11
 * MODEL: A11
 */
final class a11_a11 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "A11";
}
