// This file is automatically generated.

package adila.db;

/*
 * Oppo A11f
 *
 * DEVICE: A11
 * MODEL: A11f
 */
final class a11_a11f {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "A11f";
}
