// This file is automatically generated.

package adila.db;

/*
 * Lenovo A2016a40
 *
 * DEVICE: A2016a40
 * MODEL: Lenovo A2016a40
 */
final class a2016a40_lenovo20a2016a40 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A2016a40";
}
