// This file is automatically generated.

package adila.db;

/*
 * Lenovo A2016b30
 *
 * DEVICE: A2016b30
 * MODEL: Lenovo A2016b30
 */
final class a2016b30_lenovo20a2016b30 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A2016b30";
}
