// This file is automatically generated.

package adila.db;

/*
 * Lenovo A208t
 *
 * DEVICE: A208t
 * MODEL: Lenovo A208t
 */
final class a208t_lenovo20a208t {
    public static final String DATA = "Lenovo|A208t|";
}
