// This file is automatically generated.

package adila.db;

/*
 * Lenovo A269
 *
 * DEVICE: A269
 * MODEL: Lenovo A269
 */
final class a269_lenovo20a269 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A269";
}
