// This file is automatically generated.

package adila.db;

/*
 * Lenovo A308t
 *
 * DEVICE: A308t
 * MODEL: Lenovo A308t
 */
final class a308t_lenovo20a308t {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A308t";
}
