// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas 4+
 *
 * DEVICE: A315
 * MODEL: Micromax A315
 */
final class a315_micromax20a315 {
    public static final String DATA = "Micromax|Canvas 4+|";
}
