// This file is automatically generated.

package adila.db;

/*
 * Oppo A33w
 *
 * DEVICE: A33w
 * MODEL: A33w
 */
final class a33w_a33w {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "A33w";
}
