// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: A34
 * MODEL: Micromax A34
 */
final class a34_micromax20a34 {
    public static final String DATA = "Micromax|Bolt|";
}
