// This file is automatically generated.

package adila.db;

/*
 * Lenovo A355e
 *
 * DEVICE: A355e
 * MODEL: Lenovo A355e
 */
final class a355e_lenovo20a355e {
    public static final String DATA = "Lenovo|A355e|";
}
