// This file is automatically generated.

package adila.db;

/*
 * Lenovo A358t
 *
 * DEVICE: A358t
 * MODEL: Lenovo A358t
 */
final class a358t_lenovo20a358t {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A358t";
}
