// This file is automatically generated.

package adila.db;

/*
 * Oppo A37tm
 *
 * DEVICE: A37
 * MODEL: OPPO A37tm
 */
final class a37_oppo20a37tm {
    public static final String DATA = "Oppo|A37tm|";
}
