// This file is automatically generated.

package adila.db;

/*
 * Oppo A39tm
 *
 * DEVICE: A39
 * MODEL: OPPO A39tm
 */
final class a39_oppo20a39tm {
    public static final String DATA = "Oppo|A39tm|";
}
