// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A3
 *
 * DEVICE: a3lte
 * MODEL: SM-A300M
 */
final class a3lte_sm2da300m {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A3";
    public static final String SERIES = "Galaxy A";
}
