// This file is automatically generated.

package adila.db;

/*
 * Southern Telecom a4
 *
 * DEVICE: a4
 * MODEL: a4
 */
final class a4_a4 {
    public static final String MANUFACTURER = "Southern Telecom";
    public static final String NAME = "a4";
}
