// This file is automatically generated.

package adila.db;

/*
 * Acer LiquidMT
 *
 * DEVICE: a4
 * MODEL: Liquid MT
 */
final class a4_liquid20mt {
    public static final String DATA = "Acer|LiquidMT|";
}
