// This file is automatically generated.

package adila.db;

/*
 * Garmin Nuvifone
 *
 * DEVICE: a50
 * MODEL: nuvifone A50
 */
final class a50_nuvifone20a50 {
    public static final String MANUFACTURER = "Garmin";
    public static final String NAME = "Nuvifone";
}
