// This file is automatically generated.

package adila.db;

/*
 * Garmin-Asus Nuvifone A50
 *
 * DEVICE: a50
 * MODEL: Garmin-Asus A50
 */
final class a50_garmin2dasus20a50 {
    public static final String DATA = "Garmin-Asus|Nuvifone A50|";
}
