// This file is automatically generated.

package adila.db;

/*
 * Lenovo A536
 *
 * DEVICE: A536
 * MODEL: Lenovo A536
 */
final class a536_lenovo20a536 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A536";
}
