// This file is automatically generated.

package adila.db;

/*
 * Lenovo A5500-HV
 *
 * DEVICE: A5500-HV
 * MODEL: Lenovo A5500-HV
 */
final class a55002dhv_lenovo20a55002dhv {
    public static final String DATA = "Lenovo|A5500-HV|";
}
