// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: A556C
 * MODEL: A556C
 */
final class a556c_a556c {
    public static final String MANUFACTURER = "Alcatel";
}
