// This file is automatically generated.

package adila.db;

/*
 * AllView A5 Ready
 *
 * DEVICE: A5_Ready
 * MODEL: A5_Ready_TM
 */
final class a55fready_a55fready5ftm {
    public static final String DATA = "AllView|A5 Ready|";
}
