// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: A560e_msm7627a
 * MODEL: LNV-Lenovo_A560e
 */
final class a560e5fmsm7627a_lnv2dlenovo5fa560e {
    public static final String MANUFACTURER = "Lenovo";
}
