// This file is automatically generated.

package adila.db;

/*
 * Oppo A59
 *
 * DEVICE: A59
 * MODEL: OPPO A59
 */
final class a59_oppo20a59 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "A59";
}
