// This file is automatically generated.

package adila.db;

/*
 * Oppo A59t
 *
 * DEVICE: A59
 * MODEL: OPPO A59t
 */
final class a59_oppo20a59t {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "A59t";
}
