// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: a59wg
 * MODEL: Lenovo A500+
 */
final class a59wg_lenovo20a5002b {
    public static final String MANUFACTURER = "Lenovo";
}
