// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5
 *
 * DEVICE: a5lte
 * MODEL: SM-A500F
 */
final class a5lte_sm2da500f {
    public static final String DATA = "Samsung|Galaxy A5|Galaxy A";
}
