// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5
 *
 * DEVICE: a5lte
 * MODEL: SM-A500M
 */
final class a5lte_sm2da500m {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A5";
    public static final String SERIES = "Galaxy A";
}
