// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5
 *
 * DEVICE: a5ulteskt
 * MODEL: SM-A500S
 */
final class a5ulteskt_sm2da500s {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A5";
    public static final String SERIES = "Galaxy A";
}
