// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5 (2016)
 *
 * DEVICE: a5xeltecmcc
 * MODEL: SM-A5108
 */
final class a5xeltecmcc {
    public static final String DATA = "Samsung|Galaxy A5 (2016)|Galaxy A";
}
