// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5 (2016)
 *
 * DEVICE: a5xeltektt
 * MODEL: SM-A510K
 */
final class a5xeltektt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A5 (2016)";
    public static final String SERIES = "Galaxy A";
}
