// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A5 (2016)
 *
 * DEVICE: a5xltechn
 * MODEL: SM-A5100
 */
final class a5xltechn_sm2da5100 {
    public static final String DATA = "Samsung|Galaxy A5 (2016)|Galaxy A";
}
