// This file is automatically generated.

package adila.db;

/*
 * Lenovo A606
 *
 * DEVICE: A606
 * MODEL: Lenovo A606
 */
final class a606_lenovo20a606 {
    public static final String DATA = "Lenovo|A606|";
}
