// This file is automatically generated.

package adila.db;

/*
 * AllView A6 Lite
 *
 * DEVICE: A6_Lite
 * MODEL: A6_Lite
 */
final class a65flite_a65flite {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "A6 Lite";
}
