// This file is automatically generated.

package adila.db;

/*
 * Lenovo A6600
 *
 * DEVICE: A6600d40
 * MODEL: Lenovo A6600d40
 */
final class a6600d40_lenovo20a6600d40 {
    public static final String DATA = "Lenovo|A6600|";
}
