// This file is automatically generated.

package adila.db;

/*
 * Lenovo A678t
 *
 * DEVICE: A678t
 * MODEL: Lenovo A678t
 */
final class a678t_lenovo20a678t {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A678t";
}
