// This file is automatically generated.

package adila.db;

/*
 * Lava A67
 *
 * DEVICE: A67
 * MODEL: A67
 */
final class a67_a67 {
    public static final String MANUFACTURER = "Lava";
    public static final String NAME = "A67";
}
