// This file is automatically generated.

package adila.db;

/*
 * Lenovo A6800
 *
 * DEVICE: A6800
 * MODEL: Lenovo A6800
 */
final class a6800_lenovo20a6800 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A6800";
}
