// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: A69
 * MODEL: Micromax A69
 */
final class a69_micromax20a69 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Bolt";
}
