// This file is automatically generated.

package adila.db;

/*
 * Archos GamePad 2
 *
 * DEVICE: A70GP2
 * MODEL: ARCHOS GAMEPAD2
 */
final class a70gp2_archos20gamepad2 {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "GamePad 2";
}
