// This file is automatically generated.

package adila.db;

/*
 * Micromax A72
 *
 * DEVICE: A72
 * MODEL: Micromax A72
 */
final class a72_micromax20a72 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "A72";
}
