// This file is automatically generated.

package adila.db;

/*
 * Lenovo A7-30H
 *
 * DEVICE: A7-30H
 * MODEL: Lenovo TAB 2 A7-30H
 */
final class a72d30h_lenovo20tab20220a72d30h {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A7-30H";
}
