// This file is automatically generated.

package adila.db;

/*
 * Micromax A73
 *
 * DEVICE: A73
 * MODEL: Micromax A73
 */
final class a73_micromax20a73 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "A73";
}
