// This file is automatically generated.

package adila.db;

/*
 * Lenovo A7600-H
 *
 * DEVICE: A7600-H
 * MODEL: Lenovo A7600-H
 */
final class a76002dh_lenovo20a76002dh {
    public static final String DATA = "Lenovo|A7600-H|";
}
