// This file is automatically generated.

package adila.db;

/*
 * Lenovo A766
 *
 * DEVICE: A766
 * MODEL: Lenovo A766
 */
final class a766_lenovo20a766 {
    public static final String DATA = "Lenovo|A766|";
}
