// This file is automatically generated.

package adila.db;

/*
 * Lenovo A7700
 *
 * DEVICE: A7700
 * MODEL: Lenovo A7700
 */
final class a7700_lenovo20a7700 {
    public static final String DATA = "Lenovo|A7700|";
}
