// This file is automatically generated.

package adila.db;

/*
 * Lenovo A780e
 *
 * DEVICE: A780e
 * MODEL: LNV-Lenovo A780e
 */
final class a780e_lnv2dlenovo20a780e {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A780e";
}
