// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A7
 *
 * DEVICE: a7ltelgt
 * MODEL: SM-A700L
 */
final class a7ltelgt {
    public static final String DATA = "Samsung|Galaxy A7|Galaxy A";
}
