// This file is automatically generated.

package adila.db;

/*
 * Archos Quechua Tablet 8
 *
 * DEVICE: A80RG11
 * MODEL: A80RG11
 */
final class a80rg11_a80rg11 {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "Quechua Tablet 8";
}
