// This file is automatically generated.

package adila.db;

/*
 * Lenovo A820t
 *
 * DEVICE: A820t
 * MODEL: Lenovo A820t
 */
final class a820t_lenovo20a820t {
    public static final String DATA = "Lenovo|A820t|";
}
