// This file is automatically generated.

package adila.db;

/*
 * Lenovo A828
 *
 * DEVICE: A858
 * MODEL: Lenovo A858
 */
final class a858_lenovo20a858 {
    public static final String DATA = "Lenovo|A828|";
}
