// This file is automatically generated.

package adila.db;

/*
 * Lava A89
 *
 * DEVICE: A89
 * MODEL: Lava A89
 */
final class a89_lava20a89 {
    public static final String MANUFACTURER = "Lava";
    public static final String NAME = "A89";
}
