// This file is automatically generated.

package adila.db;

/*
 * Archos 97b Titanium
 *
 * DEVICE: A97BTI
 * MODEL: ARCHOS 97B TITANIUM
 */
final class a97bti_archos2097b20titanium {
    public static final String DATA = "Archos|97b Titanium|";
}
