// This file is automatically generated.

package adila.db;

/*
 * Archos ChefPad
 *
 * DEVICE: A97CFP
 * MODEL: Archos Chefpad
 */
final class a97cfp_archos20chefpad {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "ChefPad";
}
