// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Xpress
 *
 * DEVICE: A99
 * MODEL: Micromax A99
 */
final class a99_micromax20a99 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Canvas Xpress";
}
