// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A9 Pro
 *
 * DEVICE: a9xproltesea
 * MODEL: SM-A910F
 */
final class a9xproltesea {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A9 Pro";
    public static final String SERIES = "Galaxy A";
}
