// This file is automatically generated.

package adila.db;

/*
 * Archos Bush 10''
 *
 * DEVICE: ac101dplv2
 * MODEL: Bush 10" Android
 */
final class ac101dplv2 {
    public static final String DATA = "Archos|Bush 10''|";
}
