// This file is automatically generated.

package adila.db;

/*
 * Archos 101b Xenon
 *
 * DEVICE: ac101bxev2
 * MODEL: Archos 101b Xenon v2
 */
final class ac101bxev2 {
    public static final String DATA = "Archos|101b Xenon|";
}
