// This file is automatically generated.

package adila.db;

/*
 * Archos 101 Xenon
 *
 * DEVICE: ac101xev2
 * MODEL: Archos 101 Xenon v2
 */
final class ac101xev2 {
    public static final String DATA = "Archos|101 Xenon|";
}
