// This file is automatically generated.

package adila.db;

/*
 * Archos My Tablet 101
 *
 * DEVICE: ac101bu
 * MODEL: BUSH 10.1 TABLET
 */
final class ac101bu {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "My Tablet 101";
}
