// This file is automatically generated.

package adila.db;

/*
 * Archos Alba 4" Android
 *
 * DEVICE: ac40dti
 * MODEL: Alba 4" Android
 */
final class ac40dti_alba2042220android {
    public static final String DATA = "Archos|Alba 4\" Android|";
}
