// This file is automatically generated.

package adila.db;

/*
 * Auchan Smartphone 5" Q.4094
 *
 * DEVICE: ac50bhe
 * MODEL: Q.4094
 */
final class ac50bhe_q2e4094 {
    public static final String MANUFACTURER = "Auchan";
    public static final String NAME = "Smartphone 5\" Q.4094";
}
