// This file is automatically generated.

package adila.db;

/*
 * Bush Spira B3 5
 *
 * DEVICE: ac50co
 * MODEL: BUSH SPIRA B3 5
 */
final class ac50co_bush20spira20b3205 {
    public static final String DATA = "Bush|Spira B3 5|";
}
