// This file is automatically generated.

package adila.db;

/*
 * Archos 50 d Helium
 *
 * DEVICE: ac50dhe
 * MODEL: AC50DHE
 */
final class ac50dhe {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "50 d Helium";
}
