// This file is automatically generated.

package adila.db;

/*
 * Archos 50 Diamond
 *
 * DEVICE: ac50da
 * MODEL: Archos 50 Diamond
 */
final class ac50da {
    public static final String DATA = "Archos|50 Diamond|";
}
