// This file is automatically generated.

package adila.db;

/*
 * Archos 50b Neon
 *
 * DEVICE: ac50bne
 * MODEL: Archos 50b Neon
 */
final class ac50bne_archos2050b20neon {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "50b Neon";
}
