// This file is automatically generated.

package adila.db;

/*
 * Archos Diamond Plus
 *
 * DEVICE: ac55diplus
 * MODEL: Archos 55 Diamond Plus
 */
final class ac55diplus_archos205520diamond20plus {
    public static final String DATA = "Archos|Diamond Plus|";
}
