// This file is automatically generated.

package adila.db;

/*
 * Archos 59 Titanium
 *
 * DEVICE: ac59ti
 * MODEL: Archos 59 Titanium
 */
final class ac59ti {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "59 Titanium";
}
