// This file is automatically generated.

package adila.db;

/*
 * Archos 70 platinum
 *
 * DEVICE: ac70plv3
 * MODEL: Archos 70 Platinum v3
 */
final class ac70plv3 {
    public static final String DATA = "Archos|70 platinum|";
}
