// This file is automatically generated.

package adila.db;

/*
 * Archos 70c Xenon
 *
 * DEVICE: ac70cxe
 * MODEL: Archos 70c Xenon
 */
final class ac70cxe {
    public static final String DATA = "Archos|70c Xenon|";
}
