// This file is automatically generated.

package adila.db;

/*
 * Archos 70c Cobalt
 *
 * DEVICE: ac70cco
 * MODEL: Archos 70c Cobalt
 */
final class ac70cco {
    public static final String DATA = "Archos|70c Cobalt|";
}
