// This file is automatically generated.

package adila.db;

/*
 * Archos 70b Xenon
 *
 * DEVICE: ac70bxe
 * MODEL: Archos 70b Xenon
 */
final class ac70bxe {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "70b Xenon";
}
