// This file is automatically generated.

package adila.db;

/*
 * Archos 80 Platinum
 *
 * DEVICE: ac80cplv2_16G
 * MODEL: Archos 80 Platinum
 */
final class ac80cplv25f16g_archos208020platinum {
    public static final String DATA = "Archos|80 Platinum|";
}
