// This file is automatically generated.

package adila.db;

/*
 * Archos 97c Platinum
 *
 * DEVICE: ac97cpl
 * MODEL: Archos 97c Platinum
 */
final class ac97cpl {
    public static final String DATA = "Archos|97c Platinum|";
}
