// This file is automatically generated.

package adila.db;

/*
 * HTC Desire HD
 *
 * DEVICE: ace
 * MODEL: Desire HD
 */
final class ace_desire20hd {
    public static final String DATA = "HTC|Desire HD|";
}
