// This file is automatically generated.

package adila.db;

/*
 * HTC Desire HD
 *
 * DEVICE: ace
 * MODEL: HTC Desire HD A9191
 */
final class ace_htc20desire20hd20a9191 {
    public static final String DATA = "HTC|Desire HD|";
}
