// This file is automatically generated.

package adila.db;

/*
 * Acer Liquid Z205
 *
 * DEVICE: acer_z205p
 * MODEL: Z205P
 */
final class acer5fz205p_z205p {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "Liquid Z205";
}
