// This file is automatically generated.

package adila.db;

/*
 * Acer Iconia Tab 10
 *
 * DEVICE: acer_harleyfhd
 * MODEL: A3-A20FHD
 */
final class acer5fharleyfhd {
    public static final String DATA = "Acer|Iconia Tab 10|";
}
