// This file is automatically generated.

package adila.db;

/*
 * Acer Liquid Jade
 *
 * DEVICE: acer_S55
 * MODEL: S55
 */
final class acer5fs55_s55 {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "Liquid Jade";
}
