// This file is automatically generated.

package adila.db;

/*
 * Acer Iconia TalkTab 7
 *
 * DEVICE: acer_a1_724
 * MODEL: A1-724
 */
final class acer5fa15f724 {
    public static final String DATA = "Acer|Iconia TalkTab 7|";
}
