// This file is automatically generated.

package adila.db;

/*
 * Acer Liquid Z205
 *
 * DEVICE: acer_z205p
 * MODEL: Z205
 */
final class acer5fz205p_z205 {
    public static final String DATA = "Acer|Liquid Z205|";
}
