// This file is automatically generated.

package adila.db;

/*
 * Acer Liquid E3
 *
 * DEVICE: acer_e3
 * MODEL: E380
 */
final class acer5fe3 {
    public static final String DATA = "Acer|Liquid E3|";
}
