// This file is automatically generated.

package adila.db;

/*
 * Smartfren Andromax AD687G
 *
 * DEVICE: AD687G
 * MODEL: Andromax AD687G
 */
final class ad687g_andromax20ad687g {
    public static final String MANUFACTURER = "Smartfren";
    public static final String NAME = "Andromax AD687G";
}
