// This file is automatically generated.

package adila.db;

/*
 * Smartfren Andromax AD682H
 *
 * DEVICE: AD682H
 * MODEL: Smartfren Andromax AD682H
 */
final class ad682h_smartfren20andromax20ad682h {
    public static final String DATA = "Smartfren|Andromax AD682H|";
}
