// This file is automatically generated.

package adila.db;

/*
 * ZTE Z730
 *
 * DEVICE: ada
 * MODEL: Z730
 */
final class ada {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z730";
}
