// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core LTE
 *
 * DEVICE: afyonlte
 * MODEL: SM-G386F
 */
final class afyonlte {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core LTE";
}
