// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Avant
 *
 * DEVICE: afyonltetmo
 * MODEL: SM-G386T
 */
final class afyonltetmo {
    public static final String DATA = "Samsung|Galaxy Avant|";
}
