// This file is automatically generated.

package adila.db;

/*
 * AG Mobile AG Ultra2
 *
 * DEVICE: AG_Ultra2
 * MODEL: Ultra 2
 */
final class ag5fultra2_ultra202 {
    public static final String MANUFACTURER = "AG Mobile";
    public static final String NAME = "AG Ultra2";
}
