// This file is automatically generated.

package adila.db;

/*
 * BenQ Agora_4G_Pro
 *
 * DEVICE: Agora_4G_Pro
 * MODEL: Agora 4G Pro
 */
final class agora5f4g5fpro_agora204g20pro {
    public static final String DATA = "BenQ|Agora_4G_Pro|";
}
