// This file is automatically generated.

package adila.db;

/*
 * BenQ Agora 4G
 *
 * DEVICE: Agora_4G
 * MODEL: Agora 4G
 */
final class agora5f4g_agora204g {
    public static final String DATA = "BenQ|Agora 4G|";
}
