// This file is automatically generated.

package adila.db;

/*
 * ZTE A2017
 *
 * DEVICE: ailsa_ii
 * MODEL: ZTE A2017
 */
final class ailsa5fii_zte20a2017 {
    public static final String DATA = "ZTE|A2017|";
}
