// This file is automatically generated.

package adila.db;

/*
 * ZTE A2017G
 *
 * DEVICE: ailsa_ii
 * MODEL: ZTE A2017G
 */
final class ailsa5fii {
    public static final String DATA = "ZTE|A2017G|";
}
