// This file is automatically generated.

package adila.db;

/*
 * Lenovo A7600
 *
 * DEVICE: aiocmcc_ttp
 * MODEL: Lenovo A7600-m
 */
final class aiocmcc5fttp {
    public static final String DATA = "Lenovo|A7600|";
}
