// This file is automatically generated.

package adila.db;

/*
 * LG AKA
 *
 * DEVICE: aka
 * MODEL: LG-H788
 */
final class aka_lg2dh788 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "AKA";
}
