// This file is automatically generated.

package adila.db;

/*
 * LG G5 SE
 *
 * DEVICE: alicee
 * MODEL: LG-H845
 */
final class alicee_lg2dh845 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G5 SE";
}
