// This file is automatically generated.

package adila.db;

/*
 * AllView Viva H8 LTE
 *
 * DEVICE: Allview_VivaH8LTE_KK
 * MODEL: VivaH8LTE
 */
final class allview5fvivah8lte5fkk_vivah8lte {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "Viva H8 LTE";
}
