// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 6032
 *
 * DEVICE: Alpha
 * MODEL: ALCATEL ONE TOUCH 6032
 */
final class alpha_alcatel20one20touch206032 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 6032";
}
