// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH 6032
 *
 * DEVICE: Alpha
 * MODEL: ALCATEL ONETOUCH 6032
 */
final class alpha_alcatel20onetouch206032 {
    public static final String DATA = "Alcatel|ONETOUCH 6032|";
}
