// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 6032X
 *
 * DEVICE: Alpha
 * MODEL: ALCATEL ONE TOUCH 6032X
 */
final class alpha_alcatel20one20touch206032x {
    public static final String DATA = "Alcatel|ONE TOUCH 6032X|";
}
