// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP 2
 *
 * DEVICE: Alto45
 * MODEL: 5042D
 */
final class alto45_5042d {
    public static final String DATA = "Alcatel|POP 2|";
}
