// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP2 (4)
 *
 * DEVICE: alto4_8g
 * MODEL: 4045O
 */
final class alto45f8g_4045o {
    public static final String DATA = "Alcatel|POP2 (4)|";
}
