// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP 2 (5)
 *
 * DEVICE: alto5
 * MODEL: 7043Y
 */
final class alto5_7043y {
    public static final String DATA = "Alcatel|POP 2 (5)|";
}
