// This file is automatically generated.

package adila.db;

/*
 * iView iView SupraPad i785Q
 *
 * DEVICE: anchor
 * MODEL: i785Q
 */
final class anchor {
    public static final String MANUFACTURER = "iView";
    public static final String NAME = "iView SupraPad i785Q";
}
