// This file is automatically generated.

package adila.db;

/*
 * Lenovo A2020a40
 *
 * DEVICE: angus3A41
 * MODEL: Lenovo A2020a40
 */
final class angus3a41_lenovo20a2020a40 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A2020a40";
}
