// This file is automatically generated.

package adila.db;

/*
 * ZTE Q301C
 *
 * DEVICE: APT_TW_P810N30
 * MODEL: ZTE Q301C
 */
final class apt5ftw5fp810n30_zte20q301c {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Q301C";
}
