// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Hue
 *
 * DEVICE: AQ5000
 * MODEL: Micromax AQ5000
 */
final class aq5000_micromax20aq5000 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Canvas Hue";
}
