// This file is automatically generated.

package adila.db;

/*
 * bq Aquaris A4.5
 *
 * DEVICE: Aquaris_A45_sprout
 * MODEL: Aquaris_A4.5
 */
final class aquaris5fa455fsprout_aquaris5fa42e5 {
    public static final String DATA = "bq|Aquaris A4.5|";
}
