// This file is automatically generated.

package adila.db;

/*
 * bq Aquaris M10 FHD
 *
 * DEVICE: Aquaris_M10_FHD
 * MODEL: Aquaris M10 FHD
 */
final class aquaris5fm105ffhd_aquaris20m1020fhd {
    public static final String DATA = "bq|Aquaris M10 FHD|";
}
