// This file is automatically generated.

package adila.db;

/*
 * Intex Aqua Ring
 *
 * DEVICE: Aqua_Ring
 * MODEL: Aqua_Ring
 */
final class aqua5fring_aqua5fring {
    public static final String MANUFACTURER = "Intex";
    public static final String NAME = "Aqua Ring";
}
