// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy A
 *
 * DEVICE: archer
 * MODEL: archer
 */
final class archer_archer {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy A";
}
