// This file is automatically generated.

package adila.db;

/*
 * Motorola 
 *
 * DEVICE: ArgonSpin
 * MODEL: XT550
 */
final class argonspin_xt550 {
    public static final String DATA = "Motorola||";
}
