// This file is automatically generated.

package adila.db;

/*
 * Xiaomi HM 1SC
 *
 * DEVICE: armani
 * MODEL: HM 1S
 */
final class armani_hm201s {
    public static final String MANUFACTURER = "Xiaomi";
    public static final String NAME = "HM 1SC";
}
