// This file is automatically generated.

package adila.db;

/*
 * Xiaomi HM 1SC
 *
 * DEVICE: armani
 * MODEL: HM 1SW
 */
final class armani_hm201sw {
    public static final String DATA = "Xiaomi|HM 1SC|";
}
