// This file is automatically generated.

package adila.db;

/*
 * Lenovo A860e
 *
 * DEVICE: artini
 * MODEL: Lenovo A860e
 */
final class artini {
    public static final String DATA = "Lenovo|A860e|";
}
