// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Safe
 *
 * DEVICE: arubaslimss
 * MODEL: SHW-M585D
 */
final class arubaslimss_shw2dm585d {
    public static final String DATA = "Samsung|Galaxy Core Safe|";
}
