// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core
 *
 * DEVICE: arubaslimss
 * MODEL: GT-I8260
 */
final class arubaslimss_gt2di8260 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core";
}
