// This file is automatically generated.

package adila.db;

/*
 * LG Optimus 2
 *
 * DEVICE: as680
 * MODEL: LG-AS680
 */
final class as680 {
    public static final String DATA = "LG|Optimus 2|";
}
