// This file is automatically generated.

package adila.db;

/*
 * Motorola Photon
 *
 * DEVICE: asanti_c
 * MODEL: XT897
 */
final class asanti5fc_xt897 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Photon";
}
