// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 4 (A400CG)
 *
 * DEVICE: ASUS_T00I
 * MODEL: ASUS_T00I-D
 */
final class asus5ft00i_asus5ft00i2dd {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenFone 4 (A400CG)";
}
