// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone Go (ZB552KL)
 *
 * DEVICE: ASUS_X007D
 * MODEL: ASUS_X007D
 */
final class asus5fx007d_asus5fx007d {
    public static final String DATA = "Asus|ZenFone Go (ZB552KL)|";
}
