// This file is automatically generated.

package adila.db;

/*
 * Asus Zenfone GO
 *
 * DEVICE: ASUS_X013D_2
 * MODEL: ASUS_X013DA
 */
final class asus5fx013d5f2_asus5fx013da {
    public static final String DATA = "Asus|Zenfone GO|";
}
