// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 2 Laser (ZE500KG)
 *
 * DEVICE: ASUS_Z00RD_7
 * MODEL: ASUS_Z00RD
 */
final class asus5fz00rd5f7_asus5fz00rd {
    public static final String DATA = "Asus|ZenFone 2 Laser (ZE500KG)|";
}
