// This file is automatically generated.

package adila.db;

/*
 * Asus MeMO Pad HD7 Dual SIM (ME175KG)
 *
 * DEVICE: ASUS-K00S
 * MODEL: ASUS K00S
 */
final class asus2dk00s_asus20k00s {
    public static final String DATA = "Asus|MeMO Pad HD7 Dual SIM (ME175KG)|";
}
