// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone Selfie (ZD551KL)
 *
 * DEVICE: ASUS_Z00U_2
 * MODEL: ASUS_Z00UD
 */
final class asus5fz00u5f2_asus5fz00ud {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenFone Selfie (ZD551KL)";
}
