// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 5 LTE (A500KL)
 *
 * DEVICE: ASUS_T00P
 * MODEL: ASUS_T00P
 */
final class asus5ft00p_asus5ft00p {
    public static final String DATA = "Asus|ZenFone 5 LTE (A500KL)|";
}
