// This file is automatically generated.

package adila.db;

/*
 * Asus PadFone X mini (PF450CL)
 *
 * DEVICE: ASUS-T00S
 * MODEL: ASUS PadFone X mini
 */
final class asus2dt00s_asus20padfone20x20mini {
    public static final String DATA = "Asus|PadFone X mini (PF450CL)|";
}
