// This file is automatically generated.

package adila.db;

/*
 * Asus X00AD_2
 *
 * DEVICE: ASUS_X00AD_2
 * MODEL: ASUS_X00AD
 */
final class asus5fx00ad5f2_asus5fx00ad {
    public static final String DATA = "Asus|X00AD_2|";
}
