// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 3 Max (ZC520TL)
 *
 * DEVICE: ASUS_X008_1
 * MODEL: ASUS_X008DA
 */
final class asus5fx0085f1_asus5fx008da {
    public static final String DATA = "Asus|ZenFone 3 Max (ZC520TL)|";
}
