// This file is automatically generated.

package adila.db;

/*
 * Asus Zenfone Max
 *
 * DEVICE: ASUS_Z010_2
 * MODEL: ASUS_Z010DD
 */
final class asus5fz0105f2_asus5fz010dd {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "Zenfone Max";
}
