// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 5
 *
 * DEVICE: ASUS_T00J
 * MODEL: ASUS_T00J
 */
final class asus5ft00j_asus5ft00j {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenFone 5";
}
