// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto G (4)
 *
 * DEVICE: athene
 * MODEL: Moto G (4)
 */
final class athene {
    public static final String DATA = "Motorola|Moto G (4)|";
}
