// This file is automatically generated.

package adila.db;

/*
 * Lenovo A770e
 *
 * DEVICE: athenaep
 * MODEL: Lenovo A770e
 */
final class athenaep {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "A770e";
}
