// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto G4 Plus
 *
 * DEVICE: athene_f
 * MODEL: Moto G (4)
 */
final class athene5ff {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Moto G4 Plus";
}
