// This file is automatically generated.

package adila.db;

/*
 * ZTE Momodesign MD Droid
 *
 * DEVICE: atlas40
 * MODEL: Momodesign MD Droid
 */
final class atlas40_momodesign20md20droid {
    public static final String DATA = "ZTE|Momodesign MD Droid|";
}
