// This file is automatically generated.

package adila.db;

/*
 * Hisense PX1900
 *
 * DEVICE: atm7039c
 * MODEL: PX1900
 */
final class atm7039c_px1900 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "PX1900";
}
