// This file is automatically generated.

package adila.db;

/*
 * Hisense PX1900ES
 *
 * DEVICE: atm7039c
 * MODEL: PX7
 */
final class atm7039c_px7 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "PX1900ES";
}
