// This file is automatically generated.

package adila.db;

/*
 * Geniatech Enjoy TV Quad-Core Box
 *
 * DEVICE: ATV581
 * MODEL: Enjoy TV Quad-Core Box
 */
final class atv581_enjoy20tv20quad2dcore20box {
    public static final String MANUFACTURER = "Geniatech";
    public static final String NAME = "Enjoy TV Quad-Core Box";
}
