// This file is automatically generated.

package adila.db;

/*
 * Pioneer CyberNavi
 *
 * DEVICE: AVIC_CZ900
 * MODEL: jupiter
 */
final class avic5fcz900_jupiter {
    public static final String MANUFACTURER = "Pioneer";
    public static final String NAME = "CyberNavi";
}
