// This file is automatically generated.

package adila.db;

/*
 * AllView AX4 Nano Plus
 *
 * DEVICE: AX4Nano_plus
 * MODEL: AX4Nano_plus
 */
final class ax4nano5fplus_ax4nano5fplus {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "AX4 Nano Plus";
}
