// This file is automatically generated.

package adila.db;

/*
 * Panasonic AX600C
 *
 * DEVICE: AX600C
 * MODEL: AX600C
 */
final class ax600c_ax600c {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "AX600C";
}
