// This file is automatically generated.

package adila.db;

/*
 * Acer B1-711
 *
 * DEVICE: B1-711
 * MODEL: B1-711
 */
final class b12d711_b12d711 {
    public static final String DATA = "Acer|B1-711|";
}
