// This file is automatically generated.

package adila.db;

/*
 * Panasonic JT-B1
 *
 * DEVICE: B1
 * MODEL: JT-B1
 */
final class b1_jt2db1 {
    public static final String DATA = "Panasonic|JT-B1|";
}
