// This file is automatically generated.

package adila.db;

/*
 * LG G3 Stylus
 *
 * DEVICE: b2lss
 * MODEL: LG-D693TR
 */
final class b2lss_lg2dd693tr {
    public static final String DATA = "LG|G3 Stylus|";
}
