// This file is automatically generated.

package adila.db;

/*
 * Medion E5005
 *
 * DEVICE: B5060
 * MODEL: B5060
 */
final class b5060_b5060 {
    public static final String DATA = "Medion|E5005|";
}
