// This file is automatically generated.

package adila.db;

/*
 * BenQ Kogan Agora 4G Lite
 *
 * DEVICE: B506
 * MODEL: Kogan Agora 4G Lite
 */
final class b506_kogan20agora204g20lite {
    public static final String DATA = "BenQ|Kogan Agora 4G Lite|";
}
