// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand
 *
 * DEVICE: baffinvektt
 * MODEL: SHV-E275K
 */
final class baffinvektt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Grand";
}
