// This file is automatically generated.

package adila.db;

/*
 * ZTE Z716BL
 *
 * DEVICE: baffin
 * MODEL: Z716BL
 */
final class baffin_z716bl {
    public static final String DATA = "ZTE|Z716BL|";
}
