// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand
 *
 * DEVICE: baffin3gduosctc
 * MODEL: SCH-I879
 */
final class baffin3gduosctc {
    public static final String DATA = "Samsung|Galaxy Grand|";
}
