// This file is automatically generated.

package adila.db;

/*
 * Dell Venue 8
 *
 * DEVICE: BB
 * MODEL: Venue 8 7840
 */
final class bb_venue208207840 {
    public static final String DATA = "Dell|Venue 8|";
}
