// This file is automatically generated.

package adila.db;

/*
 * Walton Primo ZX2 Lite
 *
 * DEVICE: BBL7505WA
 * MODEL: Primo ZX2 Lite
 */
final class bbl7505wa_primo20zx220lite {
    public static final String DATA = "Walton|Primo ZX2 Lite|";
}
