// This file is automatically generated.

package adila.db;

/*
 * ZTE Z995
 *
 * DEVICE: becky
 * MODEL: Z995
 */
final class becky {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z995";
}
