// This file is automatically generated.

package adila.db;

/*
 * Beeline Smart 6
 *
 * DEVICE: Beeline_Smart_6
 * MODEL: Beeline Smart 6
 */
final class beeline5fsmart5f6_beeline20smart206 {
    public static final String DATA = "Beeline|Smart 6|";
}
