// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 4030X
 *
 * DEVICE: Beetle_GSM
 * MODEL: ALCATEL ONE TOUCH 4030Y
 */
final class beetle5fgsm_alcatel20one20touch204030y {
    public static final String DATA = "Alcatel|ONE TOUCH 4030X|";
}
