// This file is automatically generated.

package adila.db;

/*
 * ZTE Z777
 *
 * DEVICE: betty
 * MODEL: Z777
 */
final class betty {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z777";
}
