// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade
 *
 * DEVICE: blade
 * MODEL: ZTE-Libra
 */
final class blade_zte2dlibra {
    public static final String DATA = "ZTE|Blade|";
}
