// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade
 *
 * DEVICE: blade
 * MODEL: San Francisco
 */
final class blade_san20francisco {
    public static final String DATA = "ZTE|Blade|";
}
