// This file is automatically generated.

package adila.db;

/*
 * ZTE Telenor Touch Plus
 *
 * DEVICE: blade2
 * MODEL: Telenor Touch Plus
 */
final class blade2_telenor20touch20plus {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Telenor Touch Plus";
}
