// This file is automatically generated.

package adila.db;

/*
 * Blaupunkt Endeavour101
 *
 * DEVICE: Blaupunkt
 * MODEL: Endeavour101
 */
final class blaupunkt_endeavour101 {
    public static final String MANUFACTURER = "Blaupunkt";
    public static final String NAME = "Endeavour101";
}
