// This file is automatically generated.

package adila.db;

/*
 * Blu R1 HD
 *
 * DEVICE: BLU_R1_HD
 * MODEL: BLU R1 HD
 */
final class blu5fr15fhd_blu20r120hd {
    public static final String MANUFACTURER = "Blu";
    public static final String NAME = "R1 HD";
}
