// This file is automatically generated.

package adila.db;

/*
 * Blu Studio XL
 *
 * DEVICE: BLU_STUDIO_XL_LTE
 * MODEL: BLU STUDIO XL LTE
 */
final class blu5fstudio5fxl5flte_blu20studio20xl20lte {
    public static final String DATA = "Blu|Studio XL|Studio";
}
