// This file is automatically generated.

package adila.db;

/*
 * Blu Energy Diamond
 *
 * DEVICE: BLU_ENERGY_DIAMOND
 * MODEL: BLU ENERGY DIAMOND
 */
final class blu5fenergy5fdiamond_blu20energy20diamond {
    public static final String DATA = "Blu|Energy Diamond|Energy";
}
