// This file is automatically generated.

package adila.db;

/*
 * Blu Vivo 6
 *
 * DEVICE: BLU_Vivo_6
 * MODEL: Vivo 6
 */
final class blu5fvivo5f6_vivo206 {
    public static final String DATA = "Blu|Vivo 6|";
}
