// This file is automatically generated.

package adila.db;

/*
 * Blu Vivo 5
 *
 * DEVICE: BLU_VIVO_5
 * MODEL: VIVO 5
 */
final class blu5fvivo5f5_vivo205 {
    public static final String DATA = "Blu|Vivo 5|Vivo";
}
