// This file is automatically generated.

package adila.db;

/*
 * Blu Neo X
 *
 * DEVICE: BLU_NEO_X
 * MODEL: BLU NEO X
 */
final class blu5fneo5fx_blu20neo20x {
    public static final String DATA = "Blu|Neo X|Neo";
}
