// This file is automatically generated.

package adila.db;

/*
 * ZTE T28
 *
 * DEVICE: bluetick
 * MODEL: ZTE T28 Prepaid
 */
final class bluetick_zte20t2820prepaid {
    public static final String DATA = "ZTE|T28|";
}
