// This file is automatically generated.

package adila.db;

/*
 * GeneralMobile E-Tab10
 *
 * DEVICE: blue_eye
 * MODEL: E-Tab10
 */
final class blue5feye {
    public static final String MANUFACTURER = "GeneralMobile";
    public static final String NAME = "E-Tab10";
}
