// This file is automatically generated.

package adila.db;

/*
 * Bluebird BM180
 *
 * DEVICE: BM180
 * MODEL: BM180
 */
final class bm180_bm180 {
    public static final String MANUFACTURER = "Bluebird";
    public static final String NAME = "BM180";
}
