// This file is automatically generated.

package adila.db;

/*
 * BMobile AX685
 *
 * DEVICE: Bmobile_AX685
 * MODEL: AX685
 */
final class bmobile5fax685_ax685 {
    public static final String MANUFACTURER = "BMobile";
    public static final String NAME = "AX685";
}
