// This file is automatically generated.

package adila.db;

/*
 * HP Slate 10 HD
 *
 * DEVICE: bonsai10
 * MODEL: HP Slate 10 HD
 */
final class bonsai10 {
    public static final String MANUFACTURER = "HP";
    public static final String NAME = "Slate 10 HD";
}
