// This file is automatically generated.

package adila.db;

/*
 * BKAV Bphone
 *
 * DEVICE: Bphone
 * MODEL: Bphone B1115
 */
final class bphone_bphone20b1115 {
    public static final String MANUFACTURER = "BKAV";
    public static final String NAME = "Bphone";
}
