// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Black
 *
 * DEVICE: bproj_302-220
 * MODEL: LG-P970g
 */
final class bproj5f3022d220 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Black";
}
