// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: bproj_VDF-XXX
 * MODEL: LG-P970
 */
final class bproj5fvdf2dxxx_lg2dp970 {
    public static final String DATA = "LG||";
}
