// This file is automatically generated.

package adila.db;

/*
 * Xiaomi China
 *
 * DEVICE: braveheart
 * MODEL: MiTV
 */
final class braveheart {
    public static final String DATA = "Xiaomi|China|";
}
