// This file is automatically generated.

package adila.db;

/*
 * GSmart SX1
 *
 * DEVICE: bravo
 * MODEL: GSmart SX1
 */
final class bravo_gsmart20sx1 {
    public static final String MANUFACTURER = "GSmart";
    public static final String NAME = "SX1";
}
