// This file is automatically generated.

package adila.db;

/*
 * Acer Liquid E2
 *
 * DEVICE: C11
 * MODEL: V370
 */
final class c11_v370 {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "Liquid E2";
}
