// This file is automatically generated.

package adila.db;

/*
 * KD Interactive Kurio Phone
 *
 * DEVICE: C14500
 * MODEL: KurioPhone
 */
final class c14500_kuriophone {
    public static final String MANUFACTURER = "KD Interactive";
    public static final String NAME = "Kurio Phone";
}
