// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: c1lgt
 * MODEL: SHV-E210L
 */
final class c1lgt {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
