// This file is automatically generated.

package adila.db;

/*
 * LG Leon 4G LTE
 *
 * DEVICE: c50
 * MODEL: LG-H340
 */
final class c50_lg2dh340 {
    public static final String DATA = "LG|Leon 4G LTE|";
}
