// This file is automatically generated.

package adila.db;

/*
 * LG Leon 4G LTE
 *
 * DEVICE: c50
 * MODEL: LG-H340GT
 */
final class c50_lg2dh340gt {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Leon 4G LTE";
}
