// This file is automatically generated.

package adila.db;

/*
 * LG Leon 4G LTE
 *
 * DEVICE: c50n
 * MODEL: LG-H340n
 */
final class c50n {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Leon 4G LTE";
}
