// This file is automatically generated.

package adila.db;

/*
 * Kyocera Hydro
 *
 * DEVICE: C5171
 * MODEL: Hydro
 */
final class c5171_hydro {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "Hydro";
}
