// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia SP
 *
 * DEVICE: C5302
 * MODEL: C5302
 */
final class c5302_c5302 {
    public static final String DATA = "Sony|Xperia SP|";
}
