// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy C5
 *
 * DEVICE: c5pltechn
 * MODEL: SM-C5000
 */
final class c5pltechn {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy C5";
    public static final String SERIES = "Galaxy C";
}
