// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z
 *
 * DEVICE: C6602
 * MODEL: C6602
 */
final class c6602_c6602 {
    public static final String DATA = "Sony|Xperia Z|";
}
