// This file is automatically generated.

package adila.db;

/*
 * Kyocera Hydro AIR
 *
 * DEVICE: C6745
 * MODEL: KYOCERA-C6745
 */
final class c6745_kyocera2dc6745 {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "Hydro AIR";
}
