// This file is automatically generated.

package adila.db;

/*
 * Kyocera Hydro VIEW
 *
 * DEVICE: C6742
 * MODEL: KYOCERA-C6742
 */
final class c6742_kyocera2dc6742 {
    public static final String DATA = "Kyocera|Hydro VIEW|";
}
