// This file is automatically generated.

package adila.db;

/*
 * Kyocera Hydro WAVE
 *
 * DEVICE: C6740N
 * MODEL: C6740N
 */
final class c6740n_c6740n {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "Hydro WAVE";
}
