// This file is automatically generated.

package adila.db;

/*
 * Kyocera Hydro VIEW
 *
 * DEVICE: C6742
 * MODEL: C6742
 */
final class c6742_c6742 {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "Hydro VIEW";
}
