// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z Ultra
 *
 * DEVICE: C6802
 * MODEL: C6802
 */
final class c6802_c6802 {
    public static final String DATA = "Sony|Xperia Z Ultra|";
}
