// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z Ultra
 *
 * DEVICE: C6833
 * MODEL: C6833
 */
final class c6833_c6833 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia Z Ultra";
}
