// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia Z1
 *
 * DEVICE: C6903
 * MODEL: C6903
 */
final class c6903_c6903 {
    public static final String DATA = "Sony Ericsson|Xperia Z1|";
}
