// This file is automatically generated.

package adila.db;

/*
 * NEC Casio G'zOne Commando
 *
 * DEVICE: C771
 * MODEL: C771
 */
final class c771_c771 {
    public static final String DATA = "NEC|Casio G'zOne Commando|";
}
