// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy C7
 *
 * DEVICE: c7ltechn
 * MODEL: SM-C700X
 */
final class c7ltechn_sm2dc700x {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy C7";
}
