// This file is automatically generated.

package adila.db;

/*
 * Cellon Houston
 *
 * DEVICE: C8680
 * MODEL: Houston
 */
final class c8680_houston {
    public static final String MANUFACTURER = "Cellon";
    public static final String NAME = "Houston";
}
