// This file is automatically generated.

package adila.db;

/*
 * Cellon HW-W900
 *
 * DEVICE: C8690
 * MODEL: HW-W900
 */
final class c8690_hw2dw900 {
    public static final String DATA = "Cellon|HW-W900|";
}
