// This file is automatically generated.

package adila.db;

/*
 * LG G4c
 *
 * DEVICE: c90
 * MODEL: LG-H525
 */
final class c90_lg2dh525 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G4c";
}
