// This file is automatically generated.

package adila.db;

/*
 * LG G4c
 *
 * DEVICE: c90n
 * MODEL: LG-H525n
 */
final class c90n {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G4c";
}
