// This file is automatically generated.

package adila.db;

/*
 * Alcatel MTC975
 *
 * DEVICE: Camry_GSM
 * MODEL: MTC975
 */
final class camry5fgsm_mtc975 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "MTC975";
}
