// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 5035D
 *
 * DEVICE: Camry_GSM
 * MODEL: ALCATEL ONE TOUCH 5035X
 */
final class camry5fgsm_alcatel20one20touch205035x {
    public static final String DATA = "Alcatel|ONE TOUCH 5035D|";
}
