// This file is automatically generated.

package adila.db;

/*
 * Xiaomi MI 4LTE
 *
 * DEVICE: cancro
 * MODEL: MI 4C
 */
final class cancro_mi204c {
    public static final String MANUFACTURER = "Xiaomi";
    public static final String NAME = "MI 4LTE";
}
