// This file is automatically generated.

package adila.db;

/*
 * Enspert Carrefour CT1010
 *
 * DEVICE: Carrefour
 * MODEL: CT1010
 */
final class carrefour_ct1010 {
    public static final String MANUFACTURER = "Enspert";
    public static final String NAME = "Carrefour CT1010";
}
