// This file is automatically generated.

package adila.db;

/*
 * Cat S30
 *
 * DEVICE: CatS30
 * MODEL: S30
 */
final class cats30_s30 {
    public static final String MANUFACTURER = "Cat";
    public static final String NAME = "S30";
}
