// This file is automatically generated.

package adila.db;

/*
 * Motorola Droid 4
 *
 * DEVICE: cdma_maserati
 * MODEL: DROID4
 */
final class cdma5fmaserati {
    public static final String DATA = "Motorola|Droid 4|";
}
