// This file is automatically generated.

package adila.db;

/*
 * Motorola 
 *
 * DEVICE: cdma_spyder
 * MODEL: IS12M
 */
final class cdma5fspyder_is12m {
    public static final String MANUFACTURER = "Motorola";
}
