// This file is automatically generated.

package adila.db;

/*
 * Motorola Droid X
 *
 * DEVICE: cdma_shadow
 * MODEL: Milestone X
 */
final class cdma5fshadow_milestone20x {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Droid X";
}
