// This file is automatically generated.

package adila.db;

/*
 * Cell C Nitro
 *
 * DEVICE: CELLC_Nitro
 * MODEL: CELLC_Nitro
 */
final class cellc5fnitro_cellc5fnitro {
    public static final String DATA = "Cell C|Nitro|";
}
