// This file is automatically generated.

package adila.db;

/*
 * Cell C Fantasy
 *
 * DEVICE: Cell_C
 * MODEL: Fantasy
 */
final class cell5fc_fantasy {
    public static final String MANUFACTURER = "Cell C";
    public static final String NAME = "Fantasy";
}
