// This file is automatically generated.

package adila.db;

/*
 * LG Wine Smart
 *
 * DEVICE: cf
 * MODEL: LGS01
 */
final class cf_lgs01 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Wine Smart";
}
