// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S 10.5
 *
 * DEVICE: chagallwifikx
 * MODEL: SM-T800
 */
final class chagallwifikx {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab S 10.5";
    public static final String SERIES = "Galaxy Tab";
}
