// This file is automatically generated.

package adila.db;

/*
 * Pegatron chagall
 *
 * DEVICE: chagall
 * MODEL: chagall
 */
final class chagall_chagall {
    public static final String MANUFACTURER = "Pegatron";
    public static final String NAME = "chagall";
}
