// This file is automatically generated.

package adila.db;

/*
 * Huawei Che1-CL10
 *
 * DEVICE: Che1
 * MODEL: Che1-CL10
 */
final class che1_che12dcl10 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Che1-CL10";
}
