// This file is automatically generated.

package adila.db;

/*
 * Fly FS502
 *
 * DEVICE: Cirrus_1
 * MODEL: FS502
 */
final class cirrus5f1_fs502 {
    public static final String DATA = "Fly|FS502|";
}
