// This file is automatically generated.

package adila.db;

/*
 * Fly Cirrus 8
 *
 * DEVICE: Cirrus_8
 * MODEL: FS514
 */
final class cirrus5f8_fs514 {
    public static final String DATA = "Fly|Cirrus 8|";
}
