// This file is automatically generated.

package adila.db;

/*
 * Fly Cirrus 2
 *
 * DEVICE: Cirrus_2
 * MODEL: FS504
 */
final class cirrus5f2_fs504 {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "Cirrus 2";
}
