// This file is automatically generated.

package adila.db;

/*
 * Acer B1-820
 *
 * DEVICE: citizen
 * MODEL: B1-820
 */
final class citizen {
    public static final String DATA = "Acer|B1-820|";
}
