// This file is automatically generated.

package adila.db;

/*
 * Coolpad CK2-01
 *
 * DEVICE: CK2-01
 * MODEL: CK2-01
 */
final class ck22d01_ck22d01 {
    public static final String DATA = "Coolpad|CK2-01|";
}
