// This file is automatically generated.

package adila.db;

/*
 * Coolpad CK3-01
 *
 * DEVICE: CK3-01
 * MODEL: CK3-01
 */
final class ck32d01_ck32d01 {
    public static final String DATA = "Coolpad|CK3-01|";
}
