// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto X Style
 *
 * DEVICE: clark
 * MODEL: XT1572
 */
final class clark_xt1572 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Moto X Style";
}
