// This file is automatically generated.

package adila.db;

/*
 * Clementoni Clempad 4.4 Basic Special
 *
 * DEVICE: Clempad2_special
 * MODEL: Clempad2_special
 */
final class clempad25fspecial_clempad25fspecial {
    public static final String DATA = "Clementoni|Clempad 4.4 Basic Special|";
}
