// This file is automatically generated.

package adila.db;

/*
 * Clementoni Clempad Call
 *
 * DEVICE: CLEMPADCALL
 * MODEL: CLEMPADCALL
 */
final class clempadcall_clempadcall {
    public static final String MANUFACTURER = "Clementoni";
    public static final String NAME = "Clempad Call";
}
