// This file is automatically generated.

package adila.db;

/*
 * Clementoni Clempad_6_S
 *
 * DEVICE: Clempad_6_S
 * MODEL: Clempad_6_S
 */
final class clempad5f65fs_clempad5f65fs {
    public static final String DATA = "Clementoni|Clempad_6_S|";
}
