// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Exhibit
 *
 * DEVICE: codinaMetroPCS
 * MODEL: SGH-T599N
 */
final class codinametropcs_sgh2dt599n {
    public static final String DATA = "Samsung|Galaxy Exhibit|";
}
