// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Exhibit
 *
 * DEVICE: codinavid
 * MODEL: SGH-T599V
 */
final class codinavid {
    public static final String DATA = "Samsung|Galaxy Exhibit|";
}
