// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade G LTE
 *
 * DEVICE: coeus
 * MODEL: ZTE Blade G LTE
 */
final class coeus_zte20blade20g20lte {
    public static final String DATA = "ZTE|Blade G LTE|";
}
