// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto E (1st Gen)
 *
 * DEVICE: condor_cdma
 * MODEL: XT1019
 */
final class condor5fcdma_xt1019 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Moto E (1st Gen)";
}
