// This file is automatically generated.

package adila.db;

/*
 * Sourcing Creation Connect502
 *
 * DEVICE: Connect502
 * MODEL: Connect502
 */
final class connect502_connect502 {
    public static final String DATA = "Sourcing Creation|Connect502|";
}
