// This file is automatically generated.

package adila.db;

/*
 * Connectce Connect Core 6
 *
 * DEVICE: Connect_Core_6
 * MODEL: CP6001A
 */
final class connect5fcore5f6_cp6001a {
    public static final String DATA = "Connectce|Connect Core 6|";
}
