// This file is automatically generated.

package adila.db;

/*
 * Coolpad 7295A
 *
 * DEVICE: Coolpad7295A
 * MODEL: Coolpad 7295A
 */
final class coolpad7295a_coolpad207295a {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "7295A";
}
