// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5892
 *
 * DEVICE: Coolpad5892
 * MODEL: Coolpad 5892
 */
final class coolpad5892_coolpad205892 {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "5892";
}
