// This file is automatically generated.

package adila.db;

/*
 * Coolpad 8198W
 *
 * DEVICE: Coolpad8198W
 * MODEL: Coolpad 8198W
 */
final class coolpad8198w_coolpad208198w {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "8198W";
}
