// This file is automatically generated.

package adila.db;

/*
 * Coolpad 8122
 *
 * DEVICE: Coolpad8122
 * MODEL: Coolpad 8122
 */
final class coolpad8122_coolpad208122 {
    public static final String DATA = "Coolpad|8122|";
}
