// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5200
 *
 * DEVICE: Coolpad5200
 * MODEL: Coolpad 5200
 */
final class coolpad5200_coolpad205200 {
    public static final String DATA = "Coolpad|5200|";
}
