// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5270
 *
 * DEVICE: Coolpad5270
 * MODEL: Coolpad 5270
 */
final class coolpad5270_coolpad205270 {
    public static final String DATA = "Coolpad|5270|";
}
