// This file is automatically generated.

package adila.db;

/*
 * Coolpad 7620L
 *
 * DEVICE: Coolpad7620L
 * MODEL: Coolpad 7620L
 */
final class coolpad7620l_coolpad207620l {
    public static final String DATA = "Coolpad|7620L|";
}
