// This file is automatically generated.

package adila.db;

/*
 * Coolpad CP5952
 *
 * DEVICE: Coolpad5952
 * MODEL: Coolpad 5952
 */
final class coolpad5952_coolpad205952 {
    public static final String DATA = "Coolpad|CP5952|";
}
