// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5950
 *
 * DEVICE: Coolpad5950
 * MODEL: Coolpad 5950
 */
final class coolpad5950_coolpad205950 {
    public static final String DATA = "Coolpad|5950|";
}
