// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5951
 *
 * DEVICE: Coolpad5951
 * MODEL: Coolpad 5951
 */
final class coolpad5951_coolpad205951 {
    public static final String DATA = "Coolpad|5951|";
}
