// This file is automatically generated.

package adila.db;

/*
 * Coolpad Cool C1
 *
 * DEVICE: cool_c1
 * MODEL: C106-6
 */
final class cool5fc1_c1062d6 {
    public static final String DATA = "Coolpad|Cool C1|";
}
