// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Prime
 *
 * DEVICE: coreprimevelte
 * MODEL: SM-G361M
 */
final class coreprimevelte_sm2dg361m {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core Prime";
}
