// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket Neo
 *
 * DEVICE: corsica
 * MODEL: GT-S5312
 */
final class corsica_gt2ds5312 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pocket Neo";
}
