// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket Neo
 *
 * DEVICE: corsicass
 * MODEL: GT-S5310E
 */
final class corsicass_gt2ds5310e {
    public static final String DATA = "Samsung|Galaxy Pocket Neo|";
}
