// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket Neo
 *
 * DEVICE: corsica
 * MODEL: GT-S5312B
 */
final class corsica_gt2ds5312b {
    public static final String DATA = "Samsung|Galaxy Pocket Neo|";
}
