// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket Neo
 *
 * DEVICE: corsicave3g
 * MODEL: GT-S5310N
 */
final class corsicave3g_gt2ds5310n {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pocket Neo";
}
