// This file is automatically generated.

package adila.db;

/*
 * LG Optimus 3D
 *
 * DEVICE: cosmo_450-05
 * MODEL: LG-SU760
 */
final class cosmo5f4502d05 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus 3D";
}
