// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: cosmo_viv-br
 * MODEL: LG-P920h
 */
final class cosmo5fviv2dbr {
    public static final String MANUFACTURER = "LG";
}
