// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: cosmo_CIS-XXX
 * MODEL: LG-P920
 */
final class cosmo5fcis2dxxx_lg2dp920 {
    public static final String DATA = "LG||";
}
