// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: cosmo_505-XXX
 * MODEL: LG-P920
 */
final class cosmo5f5052dxxx_lg2dp920 {
    public static final String MANUFACTURER = "LG";
}
