// This file is automatically generated.

package adila.db;

/*
 * Explay Brilliant
 *
 * DEVICE: Cosmic
 * MODEL: Brilliant
 */
final class cosmic_brilliant {
    public static final String MANUFACTURER = "Explay";
    public static final String NAME = "Brilliant";
}
