// This file is automatically generated.

package adila.db;

/*
 * Foxconn MUSN COUPLE
 *
 * DEVICE: couple
 * MODEL: COUPLE
 */
final class couple {
    public static final String MANUFACTURER = "Foxconn";
    public static final String NAME = "MUSN COUPLE";
}
