// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 400 dual sim
 *
 * DEVICE: cp2dug
 * MODEL: HTC Desire 400 dual sim
 */
final class cp2dug_htc20desire2040020dual20sim {
    public static final String DATA = "HTC|Desire 400 dual sim|";
}
