// This file is automatically generated.

package adila.db;

/*
 * Cisco Cisco Desktop Collaboration Experience DX80
 *
 * DEVICE: CP-DX80
 * MODEL: CP-DX80
 */
final class cp2ddx80_cp2ddx80 {
    public static final String DATA = "Cisco|Cisco Desktop Collaboration Experience DX80|";
}
