// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 606w
 *
 * DEVICE: cp3dug
 * MODEL: HTC 606w
 */
final class cp3dug_htc20606w {
    public static final String DATA = "HTC|Desire 606w|";
}
