// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 600c Dual SIM
 *
 * DEVICE: cp3dcg
 * MODEL: HTC Desire 600c dual sim
 */
final class cp3dcg_htc20desire20600c20dual20sim {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 600c Dual SIM";
}
