// This file is automatically generated.

package adila.db;

/*
 * Coolpad 5860E
 *
 * DEVICE: CP5860E
 * MODEL: 5860E
 */
final class cp5860e_5860e {
    public static final String DATA = "Coolpad|5860E|";
}
