// This file is automatically generated.

package adila.db;

/*
 * Coolpad 7061
 *
 * DEVICE: CP7061
 * MODEL: Coolpad 7061
 */
final class cp7061_coolpad207061 {
    public static final String DATA = "Coolpad|7061|";
}
