// This file is automatically generated.

package adila.db;

/*
 * Coolpad CP8089Q
 *
 * DEVICE: CP8089Q
 * MODEL: Coolpad 8089Q
 */
final class cp8089q_coolpad208089q {
    public static final String DATA = "Coolpad|CP8089Q|";
}
