// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Prime
 *
 * DEVICE: cprimeltemtr
 * MODEL: SM-G360T1
 */
final class cprimeltemtr {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core Prime";
}
