// This file is automatically generated.

package adila.db;

/*
 * Coolpad Y803-8
 *
 * DEVICE: CPY803_8
 * MODEL: Coolpad Y803-8
 */
final class cpy8035f8_coolpad20y8032d8 {
    public static final String DATA = "Coolpad|Y803-8|";
}
