// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mega Plus
 *
 * DEVICE: craterq3g
 * MODEL: GT-I9158P
 */
final class craterq3g_gt2di9158p {
    public static final String DATA = "Samsung|Galaxy Mega Plus|";
}
