// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL M2M
 *
 * DEVICE: CROSS2
 * MODEL: TCL M2M
 */
final class cross2_tcl20m2m {
    public static final String DATA = "Alcatel|TCL M2M|";
}
