// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL S725T
 *
 * DEVICE: Cross55_TD_Plus
 * MODEL: TCL_S725T
 */
final class cross555ftd5fplus_tcl5fs725t {
    public static final String DATA = "Alcatel|TCL S725T|";
}
