// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Plus
 *
 * DEVICE: cs02ve3gss
 * MODEL: SM-G350M
 */
final class cs02ve3gss_sm2dg350m {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core Plus";
}
