// This file is automatically generated.

package adila.db;

/*
 * Honeywell CT50
 *
 * DEVICE: CT50L0N-CS15S
 * MODEL: CT50
 */
final class ct50l0n2dcs15s_ct50 {
    public static final String DATA = "Honeywell|CT50|";
}
