// This file is automatically generated.

package adila.db;

/*
 * MyPhone Cube LTE
 *
 * DEVICE: CUBE_LTE_PLAY
 * MODEL: CUBE_LTE
 */
final class cube5flte5fplay_cube5flte {
    public static final String DATA = "MyPhone|Cube LTE|";
}
