// This file is automatically generated.

package adila.db;

/*
 * MobiWire Cygnus
 *
 * DEVICE: Cygnus45
 * MODEL: Cygnus
 */
final class cygnus45_cygnus {
    public static final String DATA = "MobiWire|Cygnus|";
}
