// This file is automatically generated.

package adila.db;

/*
 * Mobiwire Cygnus mini
 *
 * DEVICE: Cygnus_mini
 * MODEL: Cygnus_mini
 */
final class cygnus5fmini_cygnus5fmini {
    public static final String MANUFACTURER = "Mobiwire";
    public static final String NAME = "Cygnus mini";
}
