// This file is automatically generated.

package adila.db;

/*
 * Mobistel Cynus F10
 *
 * DEVICE: Cynus_F10
 * MODEL: Cynus_F10
 */
final class cynus5ff10_cynus5ff10 {
    public static final String DATA = "Mobistel|Cynus F10|";
}
