// This file is automatically generated.

package adila.db;

/*
 * mobistel Cynus T6
 *
 * DEVICE: Cynus_T6
 * MODEL: Cynus T6
 */
final class cynus5ft6_cynus20t6 {
    public static final String MANUFACTURER = "mobistel";
    public static final String NAME = "Cynus T6";
}
