// This file is automatically generated.

package adila.db;

/*
 * NEC LifeTouch L
 *
 * DEVICE: D000000035
 * MODEL: NEC-STR
 */
final class d000000035_nec2dstr {
    public static final String DATA = "NEC|LifeTouch L|";
}
