// This file is automatically generated.

package adila.db;

/*
 * NEC LifeTouch Note
 *
 * DEVICE: D000000010N
 * MODEL: D000-000010-N
 */
final class d000000010n_d0002d0000102dn {
    public static final String DATA = "NEC|LifeTouch Note|";
}
