// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: D200
 * MODEL: Micromax_D200
 */
final class d200_micromax5fd200 {
    public static final String DATA = "Micromax|Bolt|";
}
