// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E1
 *
 * DEVICE: D2004
 * MODEL: D2004
 */
final class d2004_d2004 {
    public static final String DATA = "Sony|Xperia E1|";
}
