// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E3
 *
 * DEVICE: D2203
 * MODEL: D2203
 */
final class d2203_d2203 {
    public static final String DATA = "Sony|Xperia E3|";
}
