// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E3 Dual
 *
 * DEVICE: D2212
 * MODEL: D2212
 */
final class d2212_d2212 {
    public static final String DATA = "Sony|Xperia E3 Dual|";
}
