// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia M2
 *
 * DEVICE: D2306
 * MODEL: D2306
 */
final class d2306_d2306 {
    public static final String DATA = "Sony|Xperia M2|";
}
