// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia M2 Aqua
 *
 * DEVICE: D2406
 * MODEL: D2406
 */
final class d2406_d2406 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia M2 Aqua";
}
