// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: d2can
 * MODEL: SGH-I747M
 */
final class d2can_sgh2di747m {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
