// This file is automatically generated.

package adila.db;

/*
 * Huawei d-01G
 *
 * DEVICE: d-01G
 * MODEL: d-01G
 */
final class d2d01g_d2d01g {
    public static final String DATA = "Huawei|d-01G|";
}
