// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: d2lteMetroPCS
 * MODEL: SGH-T999N
 */
final class d2ltemetropcs_sgh2dt999n {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S3";
    public static final String SERIES = "Galaxy S";
}
