// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: d2lterefreshspr
 * MODEL: SPH-L710T
 */
final class d2lterefreshspr {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
