// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: D320
 * MODEL: Micromax D320
 */
final class d320_micromax20d320 {
    public static final String DATA = "Micromax|Bolt|";
}
