// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: D333
 * MODEL: Micromax D333
 */
final class d333_micromax20d333 {
    public static final String DATA = "Micromax|Bolt|";
}
