// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia T3
 *
 * DEVICE: D5103
 * MODEL: D5103
 */
final class d5103_d5103 {
    public static final String DATA = "Sony|Xperia T3|";
}
