// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z3 Compact
 *
 * DEVICE: D5833
 * MODEL: D5833
 */
final class d5833_d5833 {
    public static final String DATA = "Sony|Xperia Z3 Compact|";
}
