// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z3
 *
 * DEVICE: D6603
 * MODEL: D6603
 */
final class d6603_d6603 {
    public static final String DATA = "Sony|Xperia Z3|";
}
