// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z3
 *
 * DEVICE: D6653
 * MODEL: D6653
 */
final class d6653_d6653 {
    public static final String DATA = "Sony|Xperia Z3|";
}
