// This file is automatically generated.

package adila.db;

/*
 * Blu Dash 4.5
 *
 * DEVICE: D730
 * MODEL: Dash 4.5
 */
final class d730_dash2042e5 {
    public static final String DATA = "Blu|Dash 4.5|Dash";
}
