// This file is automatically generated.

package adila.db;

/*
 * Acer DA222HQLA
 *
 * DEVICE: da2
 * MODEL: DA222HQLA
 */
final class da2_da222hqla {
    public static final String DATA = "Acer|DA222HQLA|";
}
