// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH D668
 *
 * DEVICE: DANIEL
 * MODEL: TCL D668
 */
final class daniel_tcl20d668 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH D668";
}
