// This file is automatically generated.

package adila.db;

/*
 * Honeywell Dolphin 70e Black
 *
 * DEVICE: dblack_gn
 * MODEL: Dolphin 70e Black
 */
final class dblack5fgn {
    public static final String MANUFACTURER = "Honeywell";
    public static final String NAME = "Dolphin 70e Black";
}
