// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: deepblue
 * MODEL: ZTE N790
 */
final class deepblue_zte20n790 {
    public static final String MANUFACTURER = "ZTE";
}
