// This file is automatically generated.

package adila.db;

/*
 * ZTE N795
 *
 * DEVICE: deepblue
 * MODEL: ZTE N795
 */
final class deepblue_zte20n795 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N795";
}
