// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 7.0
 *
 * DEVICE: degaslte
 * MODEL: SM-T235
 */
final class degaslte_sm2dt235 {
    public static final String DATA = "Samsung|Galaxy Tab 4 7.0|Galaxy Tab";
}
