// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 7.0
 *
 * DEVICE: degaswifi
 * MODEL: SM-T230
 */
final class degaswifi_sm2dt230 {
    public static final String DATA = "Samsung|Galaxy Tab 4 7.0|Galaxy Tab";
}
