// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 7.0
 *
 * DEVICE: degasltevzw
 * MODEL: SM-T237V
 */
final class degasltevzw {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 4 7.0";
    public static final String SERIES = "Galaxy Tab";
}
