// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Win
 *
 * DEVICE: delosltelgt
 * MODEL: SHV-E500L
 */
final class delosltelgt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Win";
}
