// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Win
 *
 * DEVICE: delos3gss
 * MODEL: GT-I8550E
 */
final class delos3gss_gt2di8550e {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Win";
}
