// This file is automatically generated.

package adila.db;

/*
 * HP 7 Plus G2
 *
 * DEVICE: deschutes
 * MODEL: HP 7 Plus G2
 */
final class deschutes {
    public static final String MANUFACTURER = "HP";
    public static final String NAME = "7 Plus G2";
}
