// This file is automatically generated.

package adila.db;

/*
 * HTC Droid Eris
 *
 * DEVICE: desirec
 * MODEL: Pulse
 */
final class desirec_pulse {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Droid Eris";
}
