// This file is automatically generated.

package adila.db;

/*
 * Diginnos DG-D07S/GP
 *
 * DEVICE: DG-D07SGP
 * MODEL: DG-D07SGP
 */
final class dg2dd07sgp_dg2dd07sgp {
    public static final String MANUFACTURER = "Diginnos";
    public static final String NAME = "DG-D07S/GP";
}
