// This file is automatically generated.

package adila.db;

/*
 * Sumitomo Electric Networks 
 *
 * DEVICE: dhe1100
 * MODEL: Hikari-iFrame/WDPF-703SE
 */
final class dhe1100 {
    public static final String MANUFACTURER = "Sumitomo Electric Networks";
}
