// This file is automatically generated.

package adila.db;

/*
 * Alcatel Idol S
 *
 * DEVICE: DiabloHD_LTE
 * MODEL: ALCATEL ONE TOUCH 6035L
 */
final class diablohd5flte_alcatel20one20touch206035l {
    public static final String DATA = "Alcatel|Idol S|";
}
