// This file is automatically generated.

package adila.db;

/*
 * Alcatel Idol S
 *
 * DEVICE: Diablo_LTE
 * MODEL: San Remo 4G
 */
final class diablo5flte_san20remo204g {
    public static final String DATA = "Alcatel|Idol S|";
}
