// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 6040A
 *
 * DEVICE: DIABLOX
 * MODEL: ALCATEL ONE TOUCH 6040A
 */
final class diablox_alcatel20one20touch206040a {
    public static final String DATA = "Alcatel|ONE TOUCH 6040A|";
}
