// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 6030X-orange
 *
 * DEVICE: Diablo
 * MODEL: ALCATEL ONE TOUCH 6030X-orange
 */
final class diablo_alcatel20one20touch206030x2dorange {
    public static final String DATA = "Alcatel|ONE TOUCH 6030X-orange|";
}
