// This file is automatically generated.

package adila.db;

/*
 * Xiaomi HM NOTE 1LTETD
 *
 * DEVICE: dior
 * MODEL: HM NOTE 1LTEW
 */
final class dior_hm20note201ltew {
    public static final String DATA = "Xiaomi|HM NOTE 1LTETD|";
}
