// This file is automatically generated.

package adila.db;

/*
 * DIFRNCE DIT702201
 *
 * DEVICE: DIT702201
 * MODEL: NID_7010
 */
final class dit702201_nid5f7010 {
    public static final String MANUFACTURER = "DIFRNCE";
    public static final String NAME = "DIT702201";
}
