// This file is automatically generated.

package adila.db;

/*
 * DigiLand DL785D
 *
 * DEVICE: DL785D
 * MODEL: PLT7803G
 */
final class dl785d_plt7803g {
    public static final String MANUFACTURER = "DigiLand";
    public static final String NAME = "DL785D";
}
