// This file is automatically generated.

package adila.db;

/*
 * HTC Butterfly s 9060
 *
 * DEVICE: dlpdug
 * MODEL: HTC 9060
 */
final class dlpdug {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Butterfly s 9060";
}
