// This file is automatically generated.

package adila.db;

/*
 * HTC Butterfly S
 *
 * DEVICE: dlxpul
 * MODEL: HTC Butterfly s
 */
final class dlxpul_htc20butterfly20s {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Butterfly S";
}
