// This file is automatically generated.

package adila.db;

/*
 * HTC 9060
 *
 * DEVICE: dlxpul
 * MODEL: HTC 901e
 */
final class dlxpul_htc20901e {
    public static final String DATA = "HTC|9060|";
}
