// This file is automatically generated.

package adila.db;

/*
 * HTC Butterfly
 *
 * DEVICE: dlxu
 * MODEL: HTC X920e
 */
final class dlxu_htc20x920e {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Butterfly";
}
