// This file is automatically generated.

package adila.db;

/*
 * Sharp DM010SH
 *
 * DEVICE: DM010SH
 * MODEL: DM010SH
 */
final class dm010sh_dm010sh {
    public static final String DATA = "Sharp|DM010SH|";
}
