// This file is automatically generated.

package adila.db;

/*
 * Sharp DM013SH
 *
 * DEVICE: DM013SH
 * MODEL: DM013SH
 */
final class dm013sh_dm013sh {
    public static final String DATA = "Sharp|DM013SH|";
}
