// This file is automatically generated.

package adila.db;

/*
 * Sharp DM016SH
 *
 * DEVICE: DM016SH
 * MODEL: DM016SH
 */
final class dm016sh_dm016sh {
    public static final String DATA = "Sharp|DM016SH|";
}
