// This file is automatically generated.

package adila.db;

/*
 * Dreamax DMX-ST7A
 *
 * DEVICE: DMX-ST7A
 * MODEL: DMX-ST7A
 */
final class dmx2dst7a_dmx2dst7a {
    public static final String DATA = "Dreamax|DMX-ST7A|";
}
