// This file is automatically generated.

package adila.db;

/*
 * Google Pixel C
 *
 * DEVICE: dragon
 * MODEL: Pixel C
 */
final class dragon {
    public static final String MANUFACTURER = "Google";
    public static final String NAME = "Pixel C";
}
