// This file is automatically generated.

package adila.db;

/*
 * Cellon SI
 *
 * DEVICE: Dream-S1
 * MODEL: SI
 */
final class dream2ds1_si {
    public static final String MANUFACTURER = "Cellon";
    public static final String NAME = "SI";
}
