// This file is automatically generated.

package adila.db;

/*
 * Fly Dune 4
 *
 * DEVICE: Dune_4
 * MODEL: Fly IQ4508
 */
final class dune5f4_fly20iq4508 {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "Dune 4";
}
