// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP5551DUO
 *
 * DEVICE: DW55B02L
 * MODEL: PSP5551DUO
 */
final class dw55b02l_psp5551duo {
    public static final String DATA = "Prestigio|PSP5551DUO|";
}
