// This file is automatically generated.

package adila.db;

/*
 * Vestel Venus V3 5030
 *
 * DEVICE: Dyno
 * MODEL: Venus_V3_5030
 */
final class dyno_venus5fv35f5030 {
    public static final String DATA = "Vestel|Venus V3 5030|";
}
