// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L3
 *
 * DEVICE: e0_open_eur
 * MODEL: LG-E400
 */
final class e05fopen5feur {
    public static final String DATA = "LG|Optimus L3|";
}
