// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L3
 *
 * DEVICE: e0
 * MODEL: LG-E400
 */
final class e0_lg2de400 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus L3";
}
