// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Zone
 *
 * DEVICE: e0v
 * MODEL: LG-VS410PP
 */
final class e0v {
    public static final String DATA = "LG|Optimus Zone|";
}
