// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia X8
 *
 * DEVICE: E15i
 * MODEL: E15i
 */
final class e15i_e15i {
    public static final String DATA = "Sony Ericsson|Xperia X8|";
}
