// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L3 Dual
 *
 * DEVICE: e1
 * MODEL: LG-E405
 */
final class e1_lg2de405 {
    public static final String DATA = "LG|Optimus L3 Dual|";
}
