// This file is automatically generated.

package adila.db;

/*
 * LG Zone3
 *
 * DEVICE: e1q
 * MODEL: VS425PP
 */
final class e1q_vs425pp {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Zone3";
}
