// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E4g
 *
 * DEVICE: E2053
 * MODEL: E2053
 */
final class e2053_e2053 {
    public static final String DATA = "Sony|Xperia E4g|";
}
