// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E4 Dual
 *
 * DEVICE: E2115
 * MODEL: E2115
 */
final class e2115_e2115 {
    public static final String DATA = "Sony|Xperia E4 Dual|";
}
