// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia E4 Dual
 *
 * DEVICE: E2124
 * MODEL: E2124
 */
final class e2124_e2124 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia E4 Dual";
}
