// This file is automatically generated.

package adila.db;

/*
 * Hisense E260T
 *
 * DEVICE: E260T
 * MODEL: HS-E260T
 */
final class e260t_hs2de260t {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "E260T";
}
