// This file is automatically generated.

package adila.db;

/*
 * LG F60
 *
 * DEVICE: e2
 * MODEL: LG-D390
 */
final class e2_lg2dd390 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "F60";
}
