// This file is automatically generated.

package adila.db;

/*
 * Logicom E350
 *
 * DEVICE: E350
 * MODEL: E350
 */
final class e350_e350 {
    public static final String MANUFACTURER = "Logicom";
    public static final String NAME = "E350";
}
