// This file is automatically generated.

package adila.db;

/*
 * AllView E3 Jump
 *
 * DEVICE: E3_Jump
 * MODEL: E3_Jump
 */
final class e35fjump_e35fjump {
    public static final String DATA = "AllView|E3 Jump|";
}
