// This file is automatically generated.

package adila.db;

/*
 * Micromax Nitro 4G
 *
 * DEVICE: E455
 * MODEL: Micromax E455
 */
final class e455_micromax20e455 {
    public static final String DATA = "Micromax|Nitro 4G|";
}
