// This file is automatically generated.

package adila.db;

/*
 * NGM You Color E506
 *
 * DEVICE: E506
 * MODEL: E506
 */
final class e506_e506 {
    public static final String DATA = "NGM|You Color E506|";
}
