// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia C4
 *
 * DEVICE: E5353
 * MODEL: E5353
 */
final class e5353_e5353 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia C4";
}
