// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia C4 Dual
 *
 * DEVICE: E5363
 * MODEL: E5363
 */
final class e5363_e5363 {
    public static final String DATA = "Sony|Xperia C4 Dual|";
}
