// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy E5
 *
 * DEVICE: e53g
 * MODEL: SM-E500H
 */
final class e53g {
    public static final String DATA = "Samsung|Galaxy E5|";
}
