// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia C5 Ultra Dual
 *
 * DEVICE: E5533
 * MODEL: E5533
 */
final class e5533_e5533 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia C5 Ultra Dual";
}
