// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia M5
 *
 * DEVICE: E5653
 * MODEL: E5653
 */
final class e5653_e5653 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia M5";
}
