// This file is automatically generated.

package adila.db;

/*
 * Hisense E600MH02
 *
 * DEVICE: E600MH02
 * MODEL: HS-E600M
 */
final class e600mh02_hs2de600m {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "E600MH02";
}
