// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-E620M
 *
 * DEVICE: E620M
 * MODEL: HS-E620M
 */
final class e620m_hs2de620m {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-E620M";
}
