// This file is automatically generated.

package adila.db;

/*
 * Kyocera DuraForce
 *
 * DEVICE: E6560L
 * MODEL: E6560L
 */
final class e6560l_e6560l {
    public static final String DATA = "Kyocera|DuraForce|";
}
