// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z5 dual
 *
 * DEVICE: E6633
 * MODEL: E6633
 */
final class e6633_e6633 {
    public static final String DATA = "Sony|Xperia Z5 dual|";
}
