// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH EVO7HD
 *
 * DEVICE: E710
 * MODEL: MTC 1078
 */
final class e710_mtc201078 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH EVO7HD";
}
