// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH EVO8HD
 *
 * DEVICE: E720
 * MODEL: ONE TOUCH EVO8HD
 */
final class e720_one20touch20evo8hd {
    public static final String DATA = "Alcatel|ONE TOUCH EVO8HD|";
}
