// This file is automatically generated.

package adila.db;

/*
 * LG G Pad 7.0 LTE
 *
 * DEVICE: e7lte
 * MODEL: LG-V410
 */
final class e7lte_lg2dv410 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Pad 7.0 LTE";
}
