// This file is automatically generated.

package adila.db;

/*
 * Logicom LOGICOM E852GP
 *
 * DEVICE: E852GP
 * MODEL: E852GP
 */
final class e852gp_e852gp {
    public static final String DATA = "Logicom|LOGICOM E852GP|";
}
