// This file is automatically generated.

package adila.db;

/*
 * LG G Pad 8.0 L Edition
 *
 * DEVICE: e8lte
 * MODEL: LGT01
 */
final class e8lte_lgt01 {
    public static final String DATA = "LG|G Pad 8.0 L Edition|";
}
