// This file is automatically generated.

package adila.db;

/*
 * LG G Pad 8.0
 *
 * DEVICE: e8wifi
 * MODEL: LG-V480
 */
final class e8wifi {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Pad 8.0";
}
