// This file is automatically generated.

package adila.db;

/*
 * Hisense 
 *
 * DEVICE: E930
 * MODEL: HS-E930
 */
final class e930_hs2de930 {
    public static final String MANUFACTURER = "Hisense";
}
