// This file is automatically generated.

package adila.db;

/*
 * Gigabyte E9771
 *
 * DEVICE: E9771
 * MODEL: E9771
 */
final class e9771_e9771 {
    public static final String DATA = "Gigabyte|E9771|";
}
