// This file is automatically generated.

package adila.db;

/*
 * ucall EASY1
 *
 * DEVICE: EASY1
 * MODEL: EASY1
 */
final class easy1_easy1 {
    public static final String DATA = "ucall|EASY1|";
}
