// This file is automatically generated.

package adila.db;

/*
 * Ematic EBM104JB
 *
 * DEVICE: EBM104JB
 * MODEL: EBM104JB
 */
final class ebm104jb_ebm104jb {
    public static final String MANUFACTURER = "Ematic";
    public static final String NAME = "EBM104JB";
}
