// This file is automatically generated.

package adila.db;

/*
 * Alcatel 6037B
 *
 * DEVICE: Eclipse
 * MODEL: 6037B
 */
final class eclipse_6037b {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "6037B";
}
