// This file is automatically generated.

package adila.db;

/*
 * LG Android TV G3
 *
 * DEVICE: eden
 * MODEL: LG Google TV G3
 */
final class eden_lg20google20tv20g3 {
    public static final String DATA = "LG|Android TV G3|";
}
