// This file is automatically generated.

package adila.db;

/*
 * bq Edison 3
 *
 * DEVICE: Edison_3
 * MODEL: Edison 3
 */
final class edison5f3_edison203 {
    public static final String MANUFACTURER = "bq";
    public static final String NAME = "Edison 3";
}
