// This file is automatically generated.

package adila.db;

/*
 * Pantech IM-A740S
 *
 * DEVICE: ef31s
 * MODEL: IM-A740S
 */
final class ef31s {
    public static final String DATA = "Pantech|IM-A740S|";
}
