// This file is automatically generated.

package adila.db;

/*
 * Pantech IM-A800S
 *
 * DEVICE: ef39s
 * MODEL: IM-A800S
 */
final class ef39s {
    public static final String DATA = "Pantech|IM-A800S|";
}
