// This file is automatically generated.

package adila.db;

/*
 * Pantech IM-A850K
 *
 * DEVICE: ef49k
 * MODEL: IM-A850K
 */
final class ef49k {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "IM-A850K";
}
