// This file is automatically generated.

package adila.db;

/*
 * Bluebird EF500
 *
 * DEVICE: EF500
 * MODEL: EF500
 */
final class ef500_ef500 {
    public static final String DATA = "Bluebird|EF500|";
}
