// This file is automatically generated.

package adila.db;

/*
 * Pantech VEGA Secret Note
 *
 * DEVICE: EF59K
 * MODEL: IM-A890K
 */
final class ef59k_im2da890k {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "VEGA Secret Note";
}
