// This file is automatically generated.

package adila.db;

/*
 * Pantech IM-A920S
 *
 * DEVICE: ef65s
 * MODEL: IM-A920S
 */
final class ef65s {
    public static final String DATA = "Pantech|IM-A920S|";
}
