// This file is automatically generated.

package adila.db;

/*
 * EG936D Hisense
 *
 * DEVICE: EG936D
 * MODEL: HS-EG936D
 */
final class eg936d_hs2deg936d {
    public static final String MANUFACTURER = "EG936D";
    public static final String NAME = "Hisense";
}
