// This file is automatically generated.

package adila.db;

/*
 * Hisense EG950
 *
 * DEVICE: EG950TW
 * MODEL: EG950
 */
final class eg950tw_eg950 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "EG950";
}
