// This file is automatically generated.

package adila.db;

/*
 * Anydata ematic EGP010
 *
 * DEVICE: EGP010
 * MODEL: EGP010
 */
final class egp010_egp010 {
    public static final String DATA = "Anydata|ematic EGP010|";
}
