// This file is automatically generated.

package adila.db;

/*
 * Ematic EGQ223
 *
 * DEVICE: EGQ223
 * MODEL: EGQ223
 */
final class egq223_egq223 {
    public static final String DATA = "Ematic|EGQ223|";
}
