// This file is automatically generated.

package adila.db;

/*
 * Ematic EGQ307
 *
 * DEVICE: EGQ307
 * MODEL: EGQ307
 */
final class egq307_egq307 {
    public static final String MANUFACTURER = "Ematic";
    public static final String NAME = "EGQ307";
}
