// This file is automatically generated.

package adila.db;

/*
 * Ematic EGS109
 *
 * DEVICE: EGS109
 * MODEL: EGS109
 */
final class egs109_egs109 {
    public static final String MANUFACTURER = "Ematic";
    public static final String NAME = "EGS109";
}
