// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Folder2
 *
 * DEVICE: eliteltechn
 * MODEL: SM-G1600
 */
final class eliteltechn {
    public static final String DATA = "Samsung|Galaxy Folder2|";
}
