// This file is automatically generated.

package adila.db;

/*
 * Visual Land Prestige Elite8QL
 *
 * DEVICE: Elite8QL
 * MODEL: Elite8QL
 */
final class elite8ql_elite8ql {
    public static final String DATA = "Visual Land|Prestige Elite8QL|";
}
