// This file is automatically generated.

package adila.db;

/*
 * ESI Enterprises EPIK Learning Tab 8''
 *
 * DEVICE: ELT0801
 * MODEL: ELT0801
 */
final class elt0801_elt0801 {
    public static final String DATA = "ESI Enterprises|EPIK Learning Tab 8''|";
}
