// This file is automatically generated.

package adila.db;

/*
 * ESI Enterprises EPIK Learning Tab Jr.
 *
 * DEVICE: ELT0702
 * MODEL: ELT0702
 */
final class elt0702_elt0702 {
    public static final String DATA = "ESI Enterprises|EPIK Learning Tab Jr.|";
}
