// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: enterprise_U950
 * MODEL: ZTE U950
 */
final class enterprise5fu950_zte20u950 {
    public static final String MANUFACTURER = "ZTE";
}
