// This file is automatically generated.

package adila.db;

/*
 * Alcatel IDOL 2 S
 *
 * DEVICE: EOS4G
 * MODEL: 6050Y
 */
final class eos4g_6050y {
    public static final String DATA = "Alcatel|IDOL 2 S|";
}
