// This file is automatically generated.

package adila.db;

/*
 * Alcatel IDOL 2 S
 *
 * DEVICE: EOS_lte
 * MODEL: TCL S830U
 */
final class eos5flte_tcl20s830u {
    public static final String DATA = "Alcatel|IDOL 2 S|";
}
