// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4551
 *
 * DEVICE: Epic_Note
 * MODEL: IQ4551
 */
final class epic5fnote_iq4551 {
    public static final String DATA = "Fly|IQ4551|";
}
