// This file is automatically generated.

package adila.db;

/*
 * Fly Era Nano 6
 *
 * DEVICE: Era_Nano_6
 * MODEL: IQ4406
 */
final class era5fnano5f6_iq4406 {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "Era Nano 6";
}
