// This file is automatically generated.

package adila.db;

/*
 * Xolo Era X
 *
 * DEVICE: era_X
 * MODEL: era_X
 */
final class era5fx_era5fx {
    public static final String MANUFACTURER = "Xolo";
    public static final String NAME = "Era X";
}
