// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 2 7.0
 *
 * DEVICE: espressorf
 * MODEL: GT-P3100
 */
final class espressorf_gt2dp3100 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 2 7.0";
    public static final String SERIES = "Galaxy Tab";
}
