// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 2 7.0
 *
 * DEVICE: espressovzw
 * MODEL: SCH-I705
 */
final class espressovzw {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 2 7.0";
    public static final String SERIES = "Galaxy Tab";
}
