// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 2 10.1
 *
 * DEVICE: espresso10vzw
 * MODEL: SCH-I915
 */
final class espresso10vzw {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 2 10.1";
    public static final String SERIES = "Galaxy Tab";
}
