// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 2 10.1
 *
 * DEVICE: espresso10tmo
 * MODEL: SGH-T779
 */
final class espresso10tmo {
    public static final String DATA = "Samsung|Galaxy Tab 2 10.1|Galaxy Tab";
}
