// This file is automatically generated.

package adila.db;

/*
 * Zebra ET5X
 *
 * DEVICE: ET50T
 * MODEL: ET5X
 */
final class et50t_et5x {
    public static final String MANUFACTURER = "Zebra";
    public static final String NAME = "ET5X";
}
