// This file is automatically generated.

package adila.db;

/*
 * Stylis FUNDA
 *
 * DEVICE: ETAB_I1041G
 * MODEL: ETAB I1041G
 */
final class etab5fi1041g_etab20i1041g {
    public static final String DATA = "Stylis|FUNDA|";
}
