// This file is automatically generated.

package adila.db;

/*
 * Sansui Tab 7''
 *
 * DEVICE: ETAB_I7043G_VP3
 * MODEL: ETAB_I7043G_VP3
 */
final class etab5fi7043g5fvp3_etab5fi7043g5fvp3 {
    public static final String DATA = "Sansui|Tab 7''|";
}
