// This file is automatically generated.

package adila.db;

/*
 * EuroLeague Euroleague I7a
 *
 * DEVICE: Euroleague
 * MODEL: EuroleaguePhone
 */
final class euroleague_euroleaguephone {
    public static final String DATA = "EuroLeague|Euroleague I7a|";
}
