// This file is automatically generated.

package adila.db;

/*
 * LG Eve
 *
 * DEVICE: EVE
 * MODEL: LG GW620F
 */
final class eve_lg20gw620f {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Eve";
}
