// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL T500L
 *
 * DEVICE: evoque_cn
 * MODEL: TCL T500L
 */
final class evoque5fcn {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TCL T500L";
}
