// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Express
 *
 * DEVICE: expressatt
 * MODEL: SAMSUNG-SGH-I437
 */
final class expressatt_samsung2dsgh2di437 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Express";
}
