// This file is automatically generated.

package adila.db;

/*
 * Fujitsu F-03H
 *
 * DEVICE: F03H
 * MODEL: F-03H
 */
final class f03h_f2d03h {
    public static final String MANUFACTURER = "Fujitsu";
    public static final String NAME = "F-03H";
}
