// This file is automatically generated.

package adila.db;

/*
 * Fujitsu F-04G
 *
 * DEVICE: F04G
 * MODEL: F-04G
 */
final class f04g_f2d04g {
    public static final String DATA = "Fujitsu|F-04G|";
}
