// This file is automatically generated.

package adila.db;

/*
 * Fujitsu F-04H
 *
 * DEVICE: F04H
 * MODEL: F-04H
 */
final class f04h_f2d04h {
    public static final String DATA = "Fujitsu|F-04H|";
}
