// This file is automatically generated.

package adila.db;

/*
 * Fujitsu ARROWS mu F-07D
 *
 * DEVICE: f11apo
 * MODEL: F-07D
 */
final class f11apo_f2d07d {
    public static final String MANUFACTURER = "Fujitsu";
    public static final String NAME = "ARROWS mu F-07D";
}
