// This file is automatically generated.

package adila.db;

/*
 * InFocus NewTab F1
 *
 * DEVICE: f1
 * MODEL: NewTab F1
 */
final class f1_newtab20f1 {
    public static final String MANUFACTURER = "InFocus";
    public static final String NAME = "NewTab F1";
}
