// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia XA
 *
 * DEVICE: F3116
 * MODEL: F3116
 */
final class f3116_f3116 {
    public static final String DATA = "Sony|Xperia XA|";
}
