// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia XA Ultra
 *
 * DEVICE: F3212
 * MODEL: F3212
 */
final class f3212_f3212 {
    public static final String DATA = "Sony|Xperia XA Ultra|";
}
