// This file is automatically generated.

package adila.db;

/*
 * BenQ F5
 *
 * DEVICE: F5
 * MODEL: BenQ F5
 */
final class f5_benq20f5 {
    public static final String MANUFACTURER = "BenQ";
    public static final String NAME = "F5";
}
