// This file is automatically generated.

package adila.db;

/*
 * ZTE Z753G
 *
 * DEVICE: faerie
 * MODEL: Z753G
 */
final class faerie {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z753G";
}
