// This file is automatically generated.

package adila.db;

/*
 * Borqs Falcon
 *
 * DEVICE: falcon
 * MODEL: falcon
 */
final class falcon {
    public static final String DATA = "Borqs|Falcon|";
}
