// This file is automatically generated.

package adila.db;

/*
 * Explay Favorite
 *
 * DEVICE: Favorite
 * MODEL: Favorite
 */
final class favorite_favorite {
    public static final String DATA = "Explay|Favorite|";
}
