// This file is automatically generated.

package adila.db;

/*
 * Cherry Mobile FB100
 *
 * DEVICE: FB100
 * MODEL: FB100
 */
final class fb100_fb100 {
    public static final String DATA = "Cherry Mobile|FB100|";
}
