// This file is automatically generated.

package adila.db;

/*
 * Foxconn vizio VP800
 *
 * DEVICE: FCN
 * MODEL: VP800
 */
final class fcn_vp800 {
    public static final String MANUFACTURER = "Foxconn";
    public static final String NAME = "vizio VP800";
}
