// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL P502U
 *
 * DEVICE: Festa5_CU
 * MODEL: TCL P502U
 */
final class festa55fcu_tcl20p502u {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TCL P502U";
}
