// This file is automatically generated.

package adila.db;

/*
 * Royaltek FGAD
 *
 * DEVICE: FGAD
 * MODEL: FGAD
 */
final class fgad_fgad {
    public static final String MANUFACTURER = "Royaltek";
    public static final String NAME = "FGAD";
}
