// This file is automatically generated.

package adila.db;

/*
 * HP Slate8 Pro
 *
 * DEVICE: fig
 * MODEL: HP Slate 8 Pro
 */
final class fig {
    public static final String DATA = "HP|Slate8 Pro|";
}
