// This file is automatically generated.

package adila.db;

/*
 * Oppo Find 5
 *
 * DEVICE: FIND5
 * MODEL: X909T
 */
final class find5_x909t {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "Find 5";
}
