// This file is automatically generated.

package adila.db;

/*
 * HTC Flyer
 *
 * DEVICE: flyer
 * MODEL: HTC Flyer P510e
 */
final class flyer_htc20flyer20p510e {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Flyer";
}
