// This file is automatically generated.

package adila.db;

/*
 * Future Mobile Technology FMT-NM7054-01
 *
 * DEVICE: FMT-NM7054-01
 * MODEL: FMT-NM7054-01
 */
final class fmt2dnm70542d01_fmt2dnm70542d01 {
    public static final String DATA = "Future Mobile Technology|FMT-NM7054-01|";
}
