// This file is automatically generated.

package adila.db;

/*
 * Future Mobile Technology FMT-NM7058-03
 *
 * DEVICE: FMT-NM7058-03
 * MODEL: FMT-NM7058-03
 */
final class fmt2dnm70582d03_fmt2dnm70582d03 {
    public static final String DATA = "Future Mobile Technology|FMT-NM7058-03|";
}
