// This file is automatically generated.

package adila.db;

/*
 * Explay M1 Plus
 *
 * DEVICE: Fog
 * MODEL: M1_Plus
 */
final class fog_m15fplus {
    public static final String MANUFACTURER = "Explay";
    public static final String NAME = "M1 Plus";
}
