// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL-P306C
 *
 * DEVICE: Ford50
 * MODEL: TCL-P306C
 */
final class ford50_tcl2dp306c {
    public static final String DATA = "Alcatel|TCL-P306C|";
}
