// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand Prime
 *
 * DEVICE: fortuna3g
 * MODEL: SM-G530H
 */
final class fortuna3g {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Grand Prime";
}
