// This file is automatically generated.

package adila.db;

/*
 * NGM Forward Ruby
 *
 * DEVICE: ForwardRuby
 * MODEL: ForwardRuby
 */
final class forwardruby_forwardruby {
    public static final String DATA = "NGM|Forward Ruby|";
}
