// This file is automatically generated.

package adila.db;

/*
 * NVidia SHIELD Android TV
 *
 * DEVICE: foster
 * MODEL: SHIELD Android TV
 */
final class foster_shield20android20tv {
    public static final String MANUFACTURER = "NVidia";
    public static final String NAME = "SHIELD Android TV";
}
