// This file is automatically generated.

package adila.db;

/*
 * Finggo FWSP-S1000
 *
 * DEVICE: FWSP-S1000-HW
 * MODEL: FWSP-S1000
 */
final class fwsp2ds10002dhw_fwsp2ds1000 {
    public static final String MANUFACTURER = "Finggo";
    public static final String NAME = "FWSP-S1000";
}
