// This file is automatically generated.

package adila.db;

/*
 * Finggo FWTA-T1000
 *
 * DEVICE: FWTA-T1000
 * MODEL: FWTA-T1000
 */
final class fwta2dt1000_fwta2dt1000 {
    public static final String DATA = "Finggo|FWTA-T1000|";
}
