// This file is automatically generated.

package adila.db;

/*
 * LG Optimus F3
 *
 * DEVICE: fx3
 * MODEL: LG-P655H
 */
final class fx3_lg2dp655h {
    public static final String DATA = "LG|Optimus F3|";
}
