// This file is automatically generated.

package adila.db;

/*
 * LG Optimus F3
 *
 * DEVICE: fx3
 * MODEL: LG-P659H
 */
final class fx3_lg2dp659h {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus F3";
}
