// This file is automatically generated.

package adila.db;

/*
 * LG Optimus F3Q
 *
 * DEVICE: fx3q
 * MODEL: LG-D520
 */
final class fx3q_lg2dd520 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus F3Q";
}
