// This file is automatically generated.

package adila.db;

/*
 * Panasonic FZ-B2D
 *
 * DEVICE: fz_b2d
 * MODEL: FZ-B2D
 */
final class fz5fb2d {
    public static final String DATA = "Panasonic|FZ-B2D|";
}
