// This file is automatically generated.

package adila.db;

/*
 * Panasonic FZ-B2
 *
 * DEVICE: fz_b2bb
 * MODEL: FZ-B2B
 */
final class fz5fb2bb {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "FZ-B2";
}
