// This file is automatically generated.

package adila.db;

/*
 * iView iView SupraPad i700
 *
 * DEVICE: g01i
 * MODEL: i700
 */
final class g01i {
    public static final String DATA = "iView|iView SupraPad i700|";
}
