// This file is automatically generated.

package adila.db;

/*
 * Gigabyte 
 *
 * DEVICE: G1317S
 * MODEL: GSmart G1317S
 */
final class g1317s_gsmart20g1317s {
    public static final String MANUFACTURER = "Gigabyte";
}
