// This file is automatically generated.

package adila.db;

/*
 * Gigabyte GSmart G1317
 *
 * DEVICE: G1317D
 * MODEL: GSmart G1317D
 */
final class g1317d_gsmart20g1317d {
    public static final String DATA = "Gigabyte|GSmart G1317|";
}
