// This file is automatically generated.

package adila.db;

/*
 * Gigabyte GSmart G1362
 *
 * DEVICE: G1362
 * MODEL: GSmart G1362
 */
final class g1362_gsmart20g1362 {
    public static final String DATA = "Gigabyte|GSmart G1362|";
}
