// This file is automatically generated.

package adila.db;

/*
 * LG G2
 *
 * DEVICE: g2
 * MODEL: LG-D802TR
 */
final class g2_lg2dd802tr {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G2";
}
