// This file is automatically generated.

package adila.db;

/*
 * InFocus M350
 *
 * DEVICE: G30
 * MODEL: InFocus M350
 */
final class g30_infocus20m350 {
    public static final String DATA = "InFocus|M350|";
}
