// This file is automatically generated.

package adila.db;

/*
 * LG G3
 *
 * DEVICE: g3
 * MODEL: LG-D855
 */
final class g3_lg2dd855 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G3";
}
