// This file is automatically generated.

package adila.db;

/*
 * LG G3
 *
 * DEVICE: g3
 * MODEL: LG-F400L
 */
final class g3_lg2df400l {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G3";
}
