// This file is automatically generated.

package adila.db;

/*
 * LG G3
 *
 * DEVICE: g3
 * MODEL: LGV31
 */
final class g3_lgv31 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G3";
}
