// This file is automatically generated.

package adila.db;

/*
 * Explay Planet
 *
 * DEVICE: G4187
 * MODEL: Planet
 */
final class g4187_planet {
    public static final String DATA = "Explay|Planet|";
}
