// This file is automatically generated.

package adila.db;

/*
 * LG G Stylo
 *
 * DEVICE: g4stylusn
 * MODEL: LG-H631MX
 */
final class g4stylusn_lg2dh631mx {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Stylo";
}
