// This file is automatically generated.

package adila.db;

/*
 * LG G Stylo
 *
 * DEVICE: g4stylusn
 * MODEL: LG-H636
 */
final class g4stylusn_lg2dh636 {
    public static final String DATA = "LG|G Stylo|";
}
