// This file is automatically generated.

package adila.db;

/*
 * Claresta G6
 *
 * DEVICE: G6
 * MODEL: G6
 */
final class g6_g6 {
    public static final String MANUFACTURER = "Claresta";
    public static final String NAME = "G6";
}
