// This file is automatically generated.

package adila.db;

/*
 * Fossil Q Marshal
 *
 * DEVICE: gar
 * MODEL: Q Marshal
 */
final class gar {
    public static final String DATA = "Fossil|Q Marshal|";
}
