// This file is automatically generated.

package adila.db;

/*
 * QMobile E8
 *
 * DEVICE: GBL5805QM
 * MODEL: E8
 */
final class gbl5805qm_e8 {
    public static final String MANUFACTURER = "QMobile";
    public static final String NAME = "E8";
}
