// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Camera
 *
 * DEVICE: gd1can
 * MODEL: EK-GC100
 */
final class gd1can {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Camera";
}
