// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Camera
 *
 * DEVICE: gd1wifi
 * MODEL: EK-GC110
 */
final class gd1wifi {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Camera";
}
