// This file is automatically generated.

package adila.db;

/*
 * ENTITY GDENTMY7317
 *
 * DEVICE: GDENTMY7317
 * MODEL: GDENTMY7317
 */
final class gdentmy7317_gdentmy7317 {
    public static final String DATA = "ENTITY|GDENTMY7317|";
}
