// This file is automatically generated.

package adila.db;

/*
 * LG Optimus G Pro
 *
 * DEVICE: geefhd4g
 * MODEL: LG-F240L
 */
final class geefhd4g {
    public static final String DATA = "LG|Optimus G Pro|";
}
