// This file is automatically generated.

package adila.db;

/*
 * LG Optimus G Pro
 *
 * DEVICE: geefhd
 * MODEL: LG-E988
 */
final class geefhd_lg2de988 {
    public static final String DATA = "LG|Optimus G Pro|";
}
