// This file is automatically generated.

package adila.db;

/*
 * LG Optimus G
 *
 * DEVICE: geehrc
 * MODEL: LG-E975
 */
final class geehrc_lg2de975 {
    public static final String DATA = "LG|Optimus G|";
}
