// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: gelato_bal-xx
 * MODEL: LG-P690
 */
final class gelato5fbal2dxx {
    public static final String MANUFACTURER = "LG";
}
