// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: gelato_nfc_tim-it
 * MODEL: LG-P692
 */
final class gelato5fnfc5ftim2dit {
    public static final String MANUFACTURER = "LG";
}
