// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Net Dual
 *
 * DEVICE: gelatods_cis-xxx
 * MODEL: LG-P698
 */
final class gelatods5fcis2dxxx {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Net Dual";
}
