// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Spirit
 *
 * DEVICE: gelato_505-01
 * MODEL: LG-P690f
 */
final class gelato5f5052d01 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Spirit";
}
