// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3413DUO
 *
 * DEVICE: GF40B1G
 * MODEL: PSP3413DUO
 */
final class gf40b1g_psp3413duo {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PSP3413DUO";
}
