// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto X (1st Gen)
 *
 * DEVICE: ghost
 * MODEL: XT1056
 */
final class ghost_xt1056 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Moto X (1st Gen)";
}
