// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto X (1st Gen)
 *
 * DEVICE: ghost
 * MODEL: XT1055
 */
final class ghost_xt1055 {
    public static final String DATA = "Motorola|Moto X (1st Gen)|";
}
