// This file is automatically generated.

package adila.db;

/*
 * Gionee GN5002
 *
 * DEVICE: GiONEE_GBL7333
 * MODEL: GN5002
 */
final class gionee5fgbl7333_gn5002 {
    public static final String MANUFACTURER = "Gionee";
    public static final String NAME = "GN5002";
}
