// This file is automatically generated.

package adila.db;

/*
 * Gionee GN3002
 *
 * DEVICE: GIONEE_GBL7356
 * MODEL: GN3002
 */
final class gionee5fgbl7356_gn3002 {
    public static final String MANUFACTURER = "Gionee";
    public static final String NAME = "GN3002";
}
