// This file is automatically generated.

package adila.db;

/*
 * Gionee GN8001L
 *
 * DEVICE: GiONEE_BBL7505
 * MODEL: GN8001L
 */
final class gionee5fbbl7505_gn8001l {
    public static final String MANUFACTURER = "Gionee";
    public static final String NAME = "GN8001L";
}
