// This file is automatically generated.

package adila.db;

/*
 * Gionee M4
 *
 * DEVICE: GiONEE_M3
 * MODEL: M4
 */
final class gionee5fm3_m4 {
    public static final String DATA = "Gionee|M4|";
}
