// This file is automatically generated.

package adila.db;

/*
 * Gionee F105
 *
 * DEVICE: GiONEE_GBL7335
 * MODEL: F105
 */
final class gionee5fgbl7335_f105 {
    public static final String DATA = "Gionee|F105|";
}
