// This file is automatically generated.

package adila.db;

/*
 * HTC myTouch 4G
 *
 * DEVICE: glacier
 * MODEL: HTC Panache
 */
final class glacier_htc20panache {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "myTouch 4G";
}
