// This file is automatically generated.

package adila.db;

/*
 * TAG Heuer TAG Heuer Connected
 *
 * DEVICE: glacier
 * MODEL: TAG Heuer
 */
final class glacier_tag20heuer {
    public static final String DATA = "TAG Heuer|TAG Heuer Connected|";
}
