// This file is automatically generated.

package adila.db;

/*
 * General Mobile General Mobile 4G
 *
 * DEVICE: gm4gtkc_s_sprout
 * MODEL: General Mobile 4G
 */
final class gm4gtkc5fs5fsprout {
    public static final String DATA = "General Mobile|General Mobile 4G|";
}
