// This file is automatically generated.

package adila.db;

/*
 * Samsung IceTouch
 *
 * DEVICE: gokey
 * MODEL: YP-GH1
 */
final class gokey {
    public static final String DATA = "Samsung|IceTouch|";
}
