// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3 Mini Value Edition
 *
 * DEVICE: goldenvess3g
 * MODEL: GT-I8200Q
 */
final class goldenvess3g_gt2di8200q {
    public static final String DATA = "Samsung|Galaxy S3 Mini Value Edition|Galaxy S";
}
