// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3 Mini
 *
 * DEVICE: goldenlteatt
 * MODEL: SAMSUNG-SM-G730A
 */
final class goldenlteatt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S3 Mini";
    public static final String SERIES = "Galaxy S";
}
