// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3 Mini
 *
 * DEVICE: goldenltebmc
 * MODEL: SM-G730W8
 */
final class goldenltebmc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S3 Mini";
    public static final String SERIES = "Galaxy S";
}
