// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 VE 7.0
 *
 * DEVICE: goyave3g
 * MODEL: SM-T116
 */
final class goyave3g_sm2dt116 {
    public static final String DATA = "Samsung|Galaxy Tab 3 VE 7.0|Galaxy Tab";
}
