// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 V 7.0
 *
 * DEVICE: goyavewifixtc
 * MODEL: SM-T113NU
 */
final class goyavewifixtc {
    public static final String DATA = "Samsung|Galaxy Tab 3 V 7.0|Galaxy Tab";
}
