// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand Prime
 *
 * DEVICE: gprimelteacg
 * MODEL: SM-G530R7
 */
final class gprimelteacg_sm2dg530r7 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Grand Prime";
}
