// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand Prime
 *
 * DEVICE: gprimeltetmo
 * MODEL: SM-G530T
 */
final class gprimeltetmo {
    public static final String DATA = "Samsung|Galaxy Grand Prime|";
}
