// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH T10
 *
 * DEVICE: GR-TB7
 * MODEL: GR-TB7
 */
final class gr2dtb7_gr2dtb7 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH T10";
}
