// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note7
 *
 * DEVICE: graceqlteatt
 * MODEL: SAMSUNG-SM-N930A
 */
final class graceqlteatt {
    public static final String DATA = "Samsung|Galaxy Note7|";
}
