// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note7
 *
 * DEVICE: graceqltelra
 * MODEL: SM-N930R6
 */
final class graceqltelra {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note7";
}
