// This file is automatically generated.

package adila.db;

/*
 * Oceus Networks Xiphos
 *
 * DEVICE: granite
 * MODEL: Xiphos(R)TMD
 */
final class granite_xiphos28r29tmd {
    public static final String MANUFACTURER = "Oceus Networks";
    public static final String NAME = "Xiphos";
}
