// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand Max
 *
 * DEVICE: grandmaxltechn
 * MODEL: SM-G7200
 */
final class grandmaxltechn_sm2dg7200 {
    public static final String DATA = "Samsung|Galaxy Grand Max|";
}
