// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand Max
 *
 * DEVICE: grandmax3g
 * MODEL: SM-G7202
 */
final class grandmax3g {
    public static final String DATA = "Samsung|Galaxy Grand Max|";
}
