// This file is automatically generated.

package adila.db;

/*
 * Harris LMC-1000
 *
 * DEVICE: granite
 * MODEL: LMC-1000
 */
final class granite_lmc2d1000 {
    public static final String DATA = "Harris|LMC-1000|";
}
