// This file is automatically generated.

package adila.db;

/*
 * GSmart T4
 *
 * DEVICE: GSmart_T4
 * MODEL: GSmart T4
 */
final class gsmart5ft4_gsmart20t4 {
    public static final String MANUFACTURER = "GSmart";
    public static final String NAME = "T4";
}
