// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Y Duos
 *
 * DEVICE: GT-S6102B
 * MODEL: GT-S6102B
 */
final class gt2ds6102b_gt2ds6102b {
    public static final String DATA = "Samsung|Galaxy Y Duos|";
}
