// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pro
 *
 * DEVICE: GT-B7510B
 * MODEL: GT-B7510B
 */
final class gt2db7510b_gt2db7510b {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pro";
}
