// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 10.1
 *
 * DEVICE: GT-P7503
 * MODEL: GT-P7503
 */
final class gt2dp7503_gt2dp7503 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 10.1";
    public static final String SERIES = "Galaxy Tab";
}
