// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace Plus
 *
 * DEVICE: GT-S7500T
 * MODEL: GT-S7500T
 */
final class gt2ds7500t_gt2ds7500t {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Ace Plus";
}
