// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mini 2
 *
 * DEVICE: GT-S6500T
 * MODEL: GT-S6500T
 */
final class gt2ds6500t_gt2ds6500t {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Mini 2";
}
