// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Europa
 *
 * DEVICE: GT-I5510
 * MODEL: GT-I5510
 */
final class gt2di5510_gt2di5510 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Europa";
}
