// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note
 *
 * DEVICE: GT-N7005
 * MODEL: GT-N7005
 */
final class gt2dn7005_gt2dn7005 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note";
    public static final String SERIES = "Galaxy Note";
}
