// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace
 *
 * DEVICE: GT-S5830i
 * MODEL: GT-S5830i
 */
final class gt2ds5830i_gt2ds5830i {
    public static final String DATA = "Samsung|Galaxy Ace|";
}
