// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace Plus
 *
 * DEVICE: GT-S7500
 * MODEL: GT-S7500
 */
final class gt2ds7500_gt2ds7500 {
    public static final String DATA = "Samsung|Galaxy Ace Plus|";
}
