// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy W
 *
 * DEVICE: GT-I8150B
 * MODEL: GT-I8150B
 */
final class gt2di8150b_gt2di8150b {
    public static final String DATA = "Samsung|Galaxy W|";
}
