// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 7.7
 *
 * DEVICE: GT-P6810
 * MODEL: GT-P6810
 */
final class gt2dp6810_gt2dp6810 {
    public static final String DATA = "Samsung|Galaxy Tab 7.7|Galaxy Tab";
}
