// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket
 *
 * DEVICE: GT-S5302B
 * MODEL: GT-S5302B
 */
final class gt2ds5302b_gt2ds5302b {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pocket";
}
