// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S
 *
 * DEVICE: GT-I9000T
 * MODEL: GT-I9000T
 */
final class gt2di9000t_gt2di9000t {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S";
    public static final String SERIES = "Galaxy S";
}
