// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket
 *
 * DEVICE: GT-S5300B
 * MODEL: GT-S5300B
 */
final class gt2ds5300b_gt2ds5300b {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pocket";
}
