// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Y
 *
 * DEVICE: GT-S5360L
 * MODEL: GT-S5360L
 */
final class gt2ds5360l_gt2ds5360l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Y";
}
