// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Gio
 *
 * DEVICE: GT-S5660V
 * MODEL: GT-S5660V
 */
final class gt2ds5660v_gt2ds5660v {
    public static final String DATA = "Samsung|Galaxy Gio|";
}
