// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy W
 *
 * DEVICE: GT-I8150
 * MODEL: GT-I8150
 */
final class gt2di8150_gt2di8150 {
    public static final String DATA = "Samsung|Galaxy W|";
}
