// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab
 *
 * DEVICE: GT-P1000L
 * MODEL: GT-P1000L
 */
final class gt2dp1000l_gt2dp1000l {
    public static final String DATA = "Samsung|Galaxy Tab|Galaxy Tab";
}
