// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab
 *
 * DEVICE: GT-P1000L
 * MODEL: GT-P1000L
 */
final class gt2dp1000l_gt2dp1000l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab";
    public static final String SERIES = "Galaxy Tab";
}
