// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Apollo
 *
 * DEVICE: GT-I5800
 * MODEL: GT-I5800
 */
final class gt2di5800_gt2di5800 {
    public static final String DATA = "Samsung|Galaxy Apollo|";
}
