// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace 2
 *
 * DEVICE: GT-I8160L
 * MODEL: GT-I8160L
 */
final class gt2di8160l_gt2di8160l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Ace 2";
}
