// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace
 *
 * DEVICE: GT-S5830C
 * MODEL: GT-S5830C
 */
final class gt2ds5830c_gt2ds5830c {
    public static final String DATA = "Samsung|Galaxy Ace|";
}
