// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Y Pro Duos
 *
 * DEVICE: GT-B5512
 * MODEL: GT-B5512
 */
final class gt2db5512_gt2db5512 {
    public static final String DATA = "Samsung|Galaxy Y Pro Duos|";
}
