// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pro
 *
 * DEVICE: GT-B7510
 * MODEL: GT-B7510
 */
final class gt2db7510_gt2db7510 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pro";
}
