// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab
 *
 * DEVICE: GT-P1000R
 * MODEL: GT-P1000R
 */
final class gt2dp1000r_gt2dp1000r {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab";
    public static final String SERIES = "Galaxy Tab";
}
