// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Xcover
 *
 * DEVICE: GT-S5698
 * MODEL: GT-S5698
 */
final class gt2ds5698_gt2ds5698 {
    public static final String DATA = "Samsung|Galaxy Xcover|";
}
