// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mini 2
 *
 * DEVICE: GT-S6500
 * MODEL: GT-S6500
 */
final class gt2ds6500_gt2ds6500 {
    public static final String DATA = "Samsung|Galaxy Mini 2|";
}
