// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S Advance
 *
 * DEVICE: GT-I9070P
 * MODEL: GT-I9070P
 */
final class gt2di9070p_gt2di9070p {
    public static final String DATA = "Samsung|Galaxy S Advance|Galaxy S";
}
