// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 9.7
 *
 * DEVICE: gt510wifichn
 * MODEL: SM-T550X
 */
final class gt510wifichn_sm2dt550x {
    public static final String DATA = "Samsung|Galaxy Tab A 9.7|Galaxy A";
}
