// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 9.7
 *
 * DEVICE: gt510wifichn
 * MODEL: SM-T550
 */
final class gt510wifichn_sm2dt550 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab A 9.7";
    public static final String SERIES = "Galaxy A";
}
