// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 8.0
 *
 * DEVICE: gt58wifi
 * MODEL: SM-T350X
 */
final class gt58wifi_sm2dt350x {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab A 8.0";
    public static final String SERIES = "Galaxy A";
}
