// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 9.7
 *
 * DEVICE: gt5note10ltelgt
 * MODEL: SM-P555L
 */
final class gt5note10ltelgt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab A 9.7";
    public static final String SERIES = "Galaxy A";
}
