// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 9.7
 *
 * DEVICE: gt5note10ltehktw
 * MODEL: SM-P555Y
 */
final class gt5note10ltehktw {
    public static final String DATA = "Samsung|Galaxy Tab A 9.7|Galaxy A";
}
