// This file is automatically generated.

package adila.db;

/*
 * Bitmore GTAB700
 *
 * DEVICE: GTAB700
 * MODEL: NID_7010
 */
final class gtab700_nid5f7010 {
    public static final String MANUFACTURER = "Bitmore";
    public static final String NAME = "GTAB700";
}
