// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab A 10.1
 *
 * DEVICE: gtaxlwifichn
 * MODEL: SM-T580X
 */
final class gtaxlwifichn_sm2dt580x {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab A 10.1";
}
