// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab E 9.6
 *
 * DEVICE: gtelwifiue
 * MODEL: SM-T560NU
 */
final class gtelwifiue {
    public static final String DATA = "Samsung|Galaxy Tab E 9.6|Galaxy Tab";
}
