// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab E 9.6
 *
 * DEVICE: gtel3g
 * MODEL: SM-T561
 */
final class gtel3g_sm2dt561 {
    public static final String DATA = "Samsung|Galaxy Tab E 9.6|Galaxy Tab";
}
