// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab E 8.0
 *
 * DEVICE: gtesqltespr
 * MODEL: SM-T377P
 */
final class gtesqltespr {
    public static final String DATA = "Samsung|Galaxy Tab E 8.0|Galaxy Tab";
}
