// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab E 8.0
 *
 * DEVICE: gtesltetmo
 * MODEL: SM-T377T
 */
final class gtesltetmo {
    public static final String DATA = "Samsung|Galaxy Tab E 8.0|Galaxy Tab";
}
