// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 9.7
 *
 * DEVICE: gts210wifi
 * MODEL: SM-T810X
 */
final class gts210wifi_sm2dt810x {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab S2 9.7";
    public static final String SERIES = "Galaxy Tab";
}
