// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 9.7
 *
 * DEVICE: gts210lteatt
 * MODEL: SAMSUNG-SM-T817A
 */
final class gts210lteatt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab S2 9.7";
    public static final String SERIES = "Galaxy Tab";
}
