// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 9.7
 *
 * DEVICE: gts210ltespr
 * MODEL: SM-T817P
 */
final class gts210ltespr {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab S2 9.7";
    public static final String SERIES = "Galaxy Tab";
}
