// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 8.0
 *
 * DEVICE: gts28lte
 * MODEL: SM-T715Y
 */
final class gts28lte_sm2dt715y {
    public static final String DATA = "Samsung|Galaxy Tab S2 8.0|Galaxy Tab";
}
