// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 9.7
 *
 * DEVICE: gts210veltetmo
 * MODEL: SM-T818T
 */
final class gts210veltetmo {
    public static final String DATA = "Samsung|Galaxy Tab S2 9.7|Galaxy Tab";
}
