// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S2 8.0
 *
 * DEVICE: gts210lte
 * MODEL: SM-T815
 */
final class gts210lte_sm2dt815 {
    public static final String DATA = "Samsung|Galaxy Tab S2 8.0|Galaxy Tab";
}
