// This file is automatically generated.

package adila.db;

/*
 * Prestigio GV7790
 *
 * DEVICE: GV7790
 * MODEL: GV7790
 */
final class gv7790_gv7790 {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "GV7790";
}
