// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy View
 *
 * DEVICE: gvlte
 * MODEL: SM-T677
 */
final class gvlte {
    public static final String DATA = "Samsung|Galaxy View|";
}
