// This file is automatically generated.

package adila.db;

/*
 * BlackBerry DTEK50
 *
 * DEVICE: hamburg
 * MODEL: STH100-2
 */
final class hamburg_sth1002d2 {
    public static final String MANUFACTURER = "BlackBerry";
    public static final String NAME = "DTEK50";
}
