// This file is automatically generated.

package adila.db;

/*
 * HANNSpree HANNSpree HSG1279
 *
 * DEVICE: HANNSpad
 * MODEL: HSG1279
 */
final class hannspad_hsg1279 {
    public static final String MANUFACTURER = "HANNSpree";
    public static final String NAME = "HANNSpree HSG1279";
}
