// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto G4 Play
 *
 * DEVICE: harpia
 * MODEL: Moto G Play
 */
final class harpia {
    public static final String DATA = "Motorola|Moto G4 Play|";
}
