// This file is automatically generated.

package adila.db;

/*
 * Motorola RAZR D1
 *
 * DEVICE: hawk35_umts
 * MODEL: XT916
 */
final class hawk355fumts_xt916 {
    public static final String DATA = "Motorola|RAZR D1|";
}
