// This file is automatically generated.

package adila.db;

/*
 * ZTE LEO_Q1
 *
 * DEVICE: hct72_wet_jb3
 * MODEL: V765M
 */
final class hct725fwet5fjb3_v765m {
    public static final String DATA = "ZTE|LEO_Q1|";
}
