// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace Style
 *
 * DEVICE: heatqlte
 * MODEL: SM-G357FZ
 */
final class heatqlte {
    public static final String DATA = "Samsung|Galaxy Ace Style|";
}
