// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S7
 *
 * DEVICE: heroltelgt
 * MODEL: SM-G930L
 */
final class heroltelgt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S7";
    public static final String SERIES = "Galaxy S";
}
