// This file is automatically generated.

package adila.db;

/*
 * HTC Hero
 *
 * DEVICE: hero
 * MODEL: ERA G2 Touch
 */
final class hero_era20g220touch {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Hero";
}
