// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S7 Edge
 *
 * DEVICE: hero2ltebmc
 * MODEL: SM-G935W8
 */
final class hero2ltebmc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S7 Edge";
    public static final String SERIES = "Galaxy S";
}
