// This file is automatically generated.

package adila.db;

/*
 * Alcatel 8030B
 *
 * DEVICE: HERO2
 * MODEL: 8030B
 */
final class hero2_8030b {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "8030B";
}
