// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S7 Edge
 *
 * DEVICE: hero2qltetmo
 * MODEL: SM-G935T
 */
final class hero2qltetmo {
    public static final String DATA = "Samsung|Galaxy S7 Edge|Galaxy S";
}
