// This file is automatically generated.

package adila.db;

/*
 * Alcatel 8030Y
 *
 * DEVICE: HERO2
 * MODEL: 8030Y
 */
final class hero2_8030y {
    public static final String DATA = "Alcatel|8030Y|";
}
