// This file is automatically generated.

package adila.db;

/*
 * LGU+ U+ tv woofer
 *
 * DEVICE: hg2
 * MODEL: LAP250U
 */
final class hg2 {
    public static final String DATA = "LGU+|U+ tv woofer|";
}
