// This file is automatically generated.

package adila.db;

/*
 * Hisense LED46K660X3D
 *
 * DEVICE: hisense6a801
 * MODEL: LED46K660X3D
 */
final class hisense6a801 {
    public static final String DATA = "Hisense|LED46K660X3D|";
}
