// This file is automatically generated.

package adila.db;

/*
 * Hisense LED50G05
 *
 * DEVICE: hisenseLED50G05
 * MODEL: LED50G05
 */
final class hisenseled50g05_led50g05 {
    public static final String DATA = "Hisense|LED50G05|";
}
