// This file is automatically generated.

package adila.db;

/*
 * Hisense LED32G180
 *
 * DEVICE: hisenseLED32G180
 * MODEL: LED32G180
 */
final class hisenseled32g180_led32g180 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED32G180";
}
