// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 3 Neo
 *
 * DEVICE: hl3g
 * MODEL: SM-N7500Q
 */
final class hl3g_sm2dn7500q {
    public static final String DATA = "Samsung|Galaxy Note 3 Neo|Galaxy Note";
}
