// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 3 Duos
 *
 * DEVICE: hlte
 * MODEL: SM-N9008
 */
final class hlte_sm2dn9008 {
    public static final String DATA = "Samsung|Galaxy Note 3 Duos|Galaxy Note";
}
