// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 3
 *
 * DEVICE: hlte
 * MODEL: SM-N9007
 */
final class hlte_sm2dn9007 {
    public static final String DATA = "Samsung|Galaxy Note 3|Galaxy Note";
}
