// This file is automatically generated.

package adila.db;

/*
 * Xiaomi Hong Mi
 *
 * DEVICE: HM2013022
 * MODEL: 2013022
 */
final class hm2013022_2013022 {
    public static final String MANUFACTURER = "Xiaomi";
    public static final String NAME = "Hong Mi";
}
