// This file is automatically generated.

package adila.db;

/*
 * Haier HW-I509-W
 *
 * DEVICE: HM-I509-W
 * MODEL: FORZA
 */
final class hm2di5092dw_forza {
    public static final String DATA = "Haier|HW-I509-W|";
}
