// This file is automatically generated.

package adila.db;

/*
 * Bouygues Telecom Bbox Miami
 *
 * DEVICE: HMB4213H
 * MODEL: BouygtelTV
 */
final class hmb4213h_bouygteltv {
    public static final String DATA = "Bouygues Telecom|Bbox Miami|";
}
