// This file is automatically generated.

package adila.db;

/*
 * Philips HMP8100/98
 *
 * DEVICE: HMP8100_ATV
 * MODEL: HMP8100_ATV_INT
 */
final class hmp81005fatv_hmp81005fatv5fint {
    public static final String DATA = "Philips|HMP8100/98|";
}
