// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 5A
 *
 * DEVICE: HNCAM-H
 * MODEL: CAM-UL00
 */
final class hncam2dh_cam2dul00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Honor 5A";
}
