// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 5A
 *
 * DEVICE: HNNEM-H
 * MODEL: NEM-AL10
 */
final class hnnem2dh_nem2dal10 {
    public static final String DATA = "Huawei|Honor 5A|";
}
