// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 5A
 *
 * DEVICE: HNNEM-H
 * MODEL: NEM-TL00H
 */
final class hnnem2dh_nem2dtl00h {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Honor 5A";
}
