// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-T939
 *
 * DEVICE: HS-T939
 * MODEL: HS-T939
 */
final class hs2dt939_hs2dt939 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-T939";
}
