// This file is automatically generated.

package adila.db;

/*
 * Hipstreet HS-7DTB40
 *
 * DEVICE: HS-7DTB40-8GB
 * MODEL: HS-7DTB40-8GB
 */
final class hs2d7dtb402d8gb_hs2d7dtb402d8gb {
    public static final String MANUFACTURER = "Hipstreet";
    public static final String NAME = "HS-7DTB40";
}
