// This file is automatically generated.

package adila.db;

/*
 * Hipstreet HS-9DTB7A
 *
 * DEVICE: HS-9DTB7A
 * MODEL: HS-9DTB7A
 */
final class hs2d9dtb7a_hs2d9dtb7a {
    public static final String MANUFACTURER = "Hipstreet";
    public static final String NAME = "HS-9DTB7A";
}
