// This file is automatically generated.

package adila.db;

/*
 * Anydata HS_7DTB14
 *
 * DEVICE: HS_7DTB14
 * MODEL: HS_7DTB14
 */
final class hs5f7dtb14_hs5f7dtb14 {
    public static final String MANUFACTURER = "Anydata";
    public static final String NAME = "HS_7DTB14";
}
