// This file is automatically generated.

package adila.db;

/*
 * Smartfren NC36B1G
 *
 * DEVICE: HS8610QC
 * MODEL: Smartfren Andromax NC36B1G
 */
final class hs8610qc_smartfren20andromax20nc36b1g {
    public static final String DATA = "Smartfren|NC36B1G|";
}
