// This file is automatically generated.

package adila.db;

/*
 * Hisense L695
 *
 * DEVICE: HS8929QC
 * MODEL: HS-L695
 */
final class hs8929qc_hs2dl695 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "L695";
}
