// This file is automatically generated.

package adila.db;

/*
 * Hisense L681
 *
 * DEVICE: HS8916QC
 * MODEL: L681
 */
final class hs8916qc_l681 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "L681";
}
