// This file is automatically generated.

package adila.db;

/*
 * Hisense F31M
 *
 * DEVICE: HS8937QC
 * MODEL: Hisense F31M
 */
final class hs8937qc_hisense20f31m {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "F31M";
}
