// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-G610
 *
 * DEVICE: HS8916QC
 * MODEL: HS-G610
 */
final class hs8916qc_hs2dg610 {
    public static final String DATA = "Hisense|HS-G610|";
}
