// This file is automatically generated.

package adila.db;

/*
 * Hisense M821H
 *
 * DEVICE: HS8916QC
 * MODEL: M821H
 */
final class hs8916qc_m821h {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "M821H";
}
