// This file is automatically generated.

package adila.db;

/*
 * Hisense E76
 *
 * DEVICE: HS8937QC
 * MODEL: Hisense E76
 */
final class hs8937qc_hisense20e76 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "E76";
}
