// This file is automatically generated.

package adila.db;

/*
 * Hisense M30M
 *
 * DEVICE: HS9830SP
 * MODEL: Hisense M30M
 */
final class hs9830sp_hisense20m30m {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "M30M";
}
