// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 626G+ dual sim
 *
 * DEVICE: htc_a32mg_dug
 * MODEL: HTC Desire 626G dual sim
 */
final class htc5fa32mg5fdug_htc20desire20626g20dual20sim {
    public static final String DATA = "HTC|Desire 626G+ dual sim|";
}
