// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 526G+ dual sim
 *
 * DEVICE: htc_v02_dug
 * MODEL: HTC_D526h
 */
final class htc5fv025fdug_htc5fd526h {
    public static final String DATA = "HTC|Desire 526G+ dual sim|";
}
