// This file is automatically generated.

package adila.db;

/*
 * HTC D626q
 *
 * DEVICE: htc_a32ml_dtul
 * MODEL: HTC_D626q
 */
final class htc5fa32ml5fdtul_htc5fd626q {
    public static final String DATA = "HTC|D626q|";
}
