// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 628 dual sim
 *
 * DEVICE: htc_v36bml_dugl
 * MODEL: HTC Desire 628 dual sim
 */
final class htc5fv36bml5fdugl_htc20desire2062820dual20sim {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 628 dual sim";
}
