// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 620G dual sim
 *
 * DEVICE: htc_a31mg_dug
 * MODEL: HTC_D620h
 */
final class htc5fa31mg5fdug_htc5fd620h {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 620G dual sim";
}
