// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 626s
 *
 * DEVICE: htc_a32eul
 * MODEL: HTC Desire 626s
 */
final class htc5fa32eul_htc20desire20626s {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 626s";
}
