// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 526
 *
 * DEVICE: htc_a13wlpp
 * MODEL: HTCD100LVWPP
 */
final class htc5fa13wlpp {
    public static final String DATA = "HTC|Desire 526|";
}
