// This file is automatically generated.

package adila.db;

/*
 * HTC D816d
 *
 * DEVICE: htc_a5dwg
 * MODEL: HTC D816d
 */
final class htc5fa5dwg_htc20d816d {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "D816d";
}
