// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 626
 *
 * DEVICE: htc_a32ewlpp
 * MODEL: HTCD200LVWPP
 */
final class htc5fa32ewlpp {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 626";
}
