// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 501
 *
 * DEVICE: htc_csnu
 * MODEL: HTC_603h
 */
final class htc5fcsnu_htc5f603h {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 501";
}
