// This file is automatically generated.

package adila.db;

/*
 * HTC One (M8)
 *
 * DEVICE: htc_m8wl
 * MODEL: HTC6525LVW
 */
final class htc5fm8wl_htc6525lvw {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "One (M8)";
}
