// This file is automatically generated.

package adila.db;

/*
 * HTC D728w
 *
 * DEVICE: htc_a50cml_dtul
 * MODEL: HTC D728w
 */
final class htc5fa50cml5fdtul_htc20d728w {
    public static final String DATA = "HTC|D728w|";
}
