// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 816G dual sim
 *
 * DEVICE: htc_a5mg_dug
 * MODEL: HTC Desire 816G dual sim
 */
final class htc5fa5mg5fdug {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 816G dual sim";
}
