// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 830
 *
 * DEVICE: htc_a51cml_tuhl
 * MODEL: HTC_D830x
 */
final class htc5fa51cml5ftuhl_htc5fd830x {
    public static final String DATA = "HTC|Desire 830|";
}
