// This file is automatically generated.

package adila.db;

/*
 * HTC 0P9C8
 *
 * DEVICE: htc_a5dwgl
 * MODEL: HTC 0P9C8
 */
final class htc5fa5dwgl_htc200p9c8 {
    public static final String DATA = "HTC|0P9C8|";
}
