// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 516
 *
 * DEVICE: htc_v2_dcg
 * MODEL: HTC D516d
 */
final class htc5fv25fdcg_htc20d516d {
    public static final String DATA = "HTC|Desire 516|";
}
