// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 516 dual sim
 *
 * DEVICE: htc_v2_dcg
 * MODEL: HTC Desire 516 dual sim
 */
final class htc5fv25fdcg_htc20desire2051620dual20sim {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 516 dual sim";
}
