// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 820s
 *
 * DEVICE: htc_a50ml_dtul
 * MODEL: HTC D820ts
 */
final class htc5fa50ml5fdtul_htc20d820ts {
    public static final String DATA = "HTC|Desire 820s|";
}
