// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 526
 *
 * DEVICE: htc_a13wl
 * MODEL: HTCD100LVW
 */
final class htc5fa13wl_htcd100lvw {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 526";
}
