// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 526G+ dual sim
 *
 * DEVICE: htc_v02_dug
 * MODEL: HTC 0PL4100
 */
final class htc5fv025fdug_htc200pl4100 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 526G+ dual sim";
}
