// This file is automatically generated.

package adila.db;

/*
 * HTC ONE M8s
 *
 * DEVICE: htc_m8qlul
 * MODEL: HTC_0PKV1
 */
final class htc5fm8qlul_htc5f0pkv1 {
    public static final String DATA = "HTC|ONE M8s|";
}
