// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 826 dual sim
 *
 * DEVICE: htc_a52dwgl
 * MODEL: HTC Desire 826 dual sim
 */
final class htc5fa52dwgl_htc20desire2082620dual20sim {
    public static final String DATA = "HTC|Desire 826 dual sim|";
}
