// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 210 dual sim
 *
 * DEVICE: htc_v0_dug
 * MODEL: HTC Desire 210 dual sim
 */
final class htc5fv05fdug {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 210 dual sim";
}
