// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 310
 *
 * DEVICE: htc_v1_dug
 * MODEL: HTC D310w
 */
final class htc5fv15fdug_htc20d310w {
    public static final String DATA = "HTC|Desire 310|";
}
