// This file is automatically generated.

package adila.db;

/*
 * HTC 0PK72
 *
 * DEVICE: htc_hiaur_ml_tuhl
 * MODEL: HTC 0PK72
 */
final class htc5fhiaur5fml5ftuhl_htc200pk72 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "0PK72";
}
