// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 530
 *
 * DEVICE: htc_a16ul
 * MODEL: HTC Desire 530
 */
final class htc5fa16ul_htc20desire20530 {
    public static final String DATA = "HTC|Desire 530|";
}
