// This file is automatically generated.

package adila.db;

/*
 * HTC M9ew
 *
 * DEVICE: htc_hima_ace_ml_dtul
 * MODEL: HTC M9ew
 */
final class htc5fhima5face5fml5fdtul_htc20m9ew {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "M9ew";
}
