// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 626s
 *
 * DEVICE: htc_a32eul
 * MODEL: HTC Desire 625
 */
final class htc5fa32eul_htc20desire20625 {
    public static final String DATA = "HTC|Desire 626s|";
}
