// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 626s
 *
 * DEVICE: htc_a32ewhl
 * MODEL: HTC 0PM92
 */
final class htc5fa32ewhl_htc200pm92 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 626s";
}
