// This file is automatically generated.

package adila.db;

/*
 * HTC One M9+ (Prime Camera Edition)
 *
 * DEVICE: htc_hiaur2_ml_tuhl
 * MODEL: HTC 0PK71
 */
final class htc5fhiaur25fml5ftuhl_htc200pk71 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "One M9+ (Prime Camera Edition)";
}
