// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 828
 *
 * DEVICE: htc_a51bml_tuhl
 * MODEL: HTC Desire 828
 */
final class htc5fa51bml5ftuhl_htc20desire20828 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 828";
}
