// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 530
 *
 * DEVICE: htc_a16ul
 * MODEL: HTC_D530u
 */
final class htc5fa16ul_htc5fd530u {
    public static final String DATA = "HTC|Desire 530|";
}
