// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 520
 *
 * DEVICE: htc_a12ul
 * MODEL: HTC 0PGQ1
 */
final class htc5fa12ul {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 520";
}
