// This file is automatically generated.

package adila.db;

/*
 * HTC One M9+ (Prime Camera Edition)
 *
 * DEVICE: htc_hiaur2_ml_tuhl
 * MODEL: HTC One M9PLUS_Prime Camera Edition
 */
final class htc5fhiaur25fml5ftuhl_htc20one20m9plus5fprime20camera20edition {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "One M9+ (Prime Camera Edition)";
}
