// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: HuaweiU8180
 * MODEL: Huawei Ideos X1
 */
final class huaweiu8180_huawei20ideos20x1 {
    public static final String MANUFACTURER = "Huawei";
}
