// This file is automatically generated.

package adila.db;

/*
 * Aikun Solely Tab S8
 *
 * DEVICE: HV1A
 * MODEL: S8
 */
final class hv1a_s8 {
    public static final String DATA = "Aikun|Solely Tab S8|";
}
