// This file is automatically generated.

package adila.db;

/*
 * Huawei HW-03E
 *
 * DEVICE: HW-03E
 * MODEL: HW-03E
 */
final class hw2d03e_hw2d03e {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "HW-03E";
}
