// This file is automatically generated.

package adila.db;

/*
 * Huawei ALE-L02
 *
 * DEVICE: hwALE-H
 * MODEL: 503HW
 */
final class hwale2dh_503hw {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "ALE-L02";
}
