// This file is automatically generated.

package adila.db;

/*
 * Huawei P8 Youth Edition
 *
 * DEVICE: hwALE-H
 * MODEL: ALE-TL00
 */
final class hwale2dh_ale2dtl00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "P8 Youth Edition";
}
