// This file is automatically generated.

package adila.db;

/*
 * Huawei P8 Lite
 *
 * DEVICE: hwALE-H
 * MODEL: Autana LTE
 */
final class hwale2dh_autana20lte {
    public static final String DATA = "Huawei|P8 Lite|";
}
