// This file is automatically generated.

package adila.db;

/*
 * Huawei P8 Lite
 *
 * DEVICE: hwALE-H
 * MODEL: ALE-L21
 */
final class hwale2dh_ale2dl21 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "P8 Lite";
}
