// This file is automatically generated.

package adila.db;

/*
 * Huawei ATH-TL00
 *
 * DEVICE: HWATH
 * MODEL: ATH-TL00
 */
final class hwath_ath2dtl00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "ATH-TL00";
}
