// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwc8826D
 * MODEL: HUAWEI C8826D
 */
final class hwc8826d_huawei20c8826d {
    public static final String DATA = "Huawei||";
}
