// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwc8950D
 * MODEL: HUAWEI C8950D
 */
final class hwc8950d_huawei20c8950d {
    public static final String MANUFACTURER = "Huawei";
}
