// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwc8860V
 * MODEL: C8860V
 */
final class hwc8860v_c8860v {
    public static final String DATA = "Huawei||";
}
