// This file is automatically generated.

package adila.db;

/*
 * Huawei Cherry Mini
 *
 * DEVICE: hwCHC-H
 * MODEL: CHC-U01
 */
final class hwchc2dh_chc2du01 {
    public static final String DATA = "Huawei|Cherry Mini|";
}
