// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 4C Play
 *
 * DEVICE: hwCHM-H
 * MODEL: CHM-TL00
 */
final class hwchm2dh_chm2dtl00 {
    public static final String DATA = "Huawei|Honor 4C Play|";
}
