// This file is automatically generated.

package adila.db;

/*
 * Huawei Mate S
 *
 * DEVICE: HWCRR
 * MODEL: HUAWEI CRR-CL20
 */
final class hwcrr_huawei20crr2dcl20 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Mate S";
}
