// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwes8500
 * MODEL: HuaweiES8500
 */
final class hwes8500 {
    public static final String MANUFACTURER = "Huawei";
}
