// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwes8100
 * MODEL: ES8100
 */
final class hwes8100 {
    public static final String MANUFACTURER = "Huawei";
}
