// This file is automatically generated.

package adila.db;

/*
 * Huawei G350
 *
 * DEVICE: HWG350
 * MODEL: HUAWEI G350-U20
 */
final class hwg350_huawei20g3502du20 {
    public static final String DATA = "Huawei|G350|";
}
