// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwG525-U00
 * MODEL: HUAWEI Ascend G525
 */
final class hwg5252du00_huawei20ascend20g525 {
    public static final String MANUFACTURER = "Huawei";
}
