// This file is automatically generated.

package adila.db;

/*
 * Huawei G6-L22
 *
 * DEVICE: hwG6-L22
 * MODEL: HUAWEI G6-L22
 */
final class hwg62dl22_huawei20g62dl22 {
    public static final String DATA = "Huawei|G6-L22|";
}
