// This file is automatically generated.

package adila.db;

/*
 * Huawei G620-L72
 *
 * DEVICE: hwG620-L72
 * MODEL: HUAWEI G620-L72
 */
final class hwg6202dl72_huawei20g6202dl72 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "G620-L72";
}
