// This file is automatically generated.

package adila.db;

/*
 * Huawei G6-U34
 *
 * DEVICE: hwG6-U34
 * MODEL: HUAWEI G6-U34
 */
final class hwg62du34_huawei20g62du34 {
    public static final String DATA = "Huawei|G6-U34|";
}
