// This file is automatically generated.

package adila.db;

/*
 * Huawei G630-U20
 *
 * DEVICE: hwG630-U20
 * MODEL: G630-U20
 */
final class hwg6302du20_g6302du20 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "G630-U20";
}
