// This file is automatically generated.

package adila.db;

/*
 * Huawei G616-L076
 *
 * DEVICE: HWG616-L
 * MODEL: HUAWEI G616-L076
 */
final class hwg6162dl_huawei20g6162dl076 {
    public static final String DATA = "Huawei|G616-L076|";
}
