// This file is automatically generated.

package adila.db;

/*
 * Huawei G630-U00
 *
 * DEVICE: hwG630-U00
 * MODEL: HUAWEI G630-U00
 */
final class hwg6302du00_huawei20g6302du00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "G630-U00";
}
