// This file is automatically generated.

package adila.db;

/*
 * Huawei G7-L11
 *
 * DEVICE: hwG7-L11
 * MODEL: HUAWEI G7-L11
 */
final class hwg72dl11_huawei20g72dl11 {
    public static final String DATA = "Huawei|G7-L11|";
}
