// This file is automatically generated.

package adila.db;

/*
 * Huawei G700-T01
 *
 * DEVICE: hwG700-T01
 * MODEL: HUAWEI G700-T01
 */
final class hwg7002dt01_huawei20g7002dt01 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "G700-T01";
}
