// This file is automatically generated.

package adila.db;

/*
 * Huawei G Play
 *
 * DEVICE: hwG735
 * MODEL: G735-L03
 */
final class hwg735_g7352dl03 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "G Play";
}
