// This file is automatically generated.

package adila.db;

/*
 * Huawei P8
 *
 * DEVICE: HWGRA
 * MODEL: HUAWEI GRA-UL00
 */
final class hwgra_huawei20gra2dul00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "P8";
}
