// This file is automatically generated.

package adila.db;

/*
 * Huawei H882L
 *
 * DEVICE: hwh882l
 * MODEL: H882L
 */
final class hwh882l {
    public static final String DATA = "Huawei|H882L|";
}
