// This file is automatically generated.

package adila.db;

/*
 * Huawei GR5
 *
 * DEVICE: HWKII-Q
 * MODEL: HUAWEI KII-L03
 */
final class hwkii2dq_huawei20kii2dl03 {
    public static final String DATA = "Huawei|GR5|";
}
