// This file is automatically generated.

package adila.db;

/*
 * Huawei HAUWEI ECO
 *
 * DEVICE: HWLUA-L6735
 * MODEL: HUAWEI LUA-L02
 */
final class hwlua2dl6735_huawei20lua2dl02 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "HAUWEI ECO";
}
