// This file is automatically generated.

package adila.db;

/*
 * Huawei Y3II
 *
 * DEVICE: HWLUA-L6735
 * MODEL: HUAWEI LUA-L01
 */
final class hwlua2dl6735_huawei20lua2dl01 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y3II";
}
