// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 5A
 *
 * DEVICE: HWLYO-L6735
 * MODEL: LYO-L21
 */
final class hwlyo2dl6735_lyo2dl21 {
    public static final String DATA = "Huawei|Honor 5A|";
}
