// This file is automatically generated.

package adila.db;

/*
 * Huawei Y6 II Compact
 *
 * DEVICE: HWLYO-L6735
 * MODEL: HUAWEI LYO-L21
 */
final class hwlyo2dl6735_huawei20lyo2dl21 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y6 II Compact";
}
