// This file is automatically generated.

package adila.db;

/*
 * Huawei m881
 *
 * DEVICE: hwm881
 * MODEL: HUAWEI M881
 */
final class hwm881 {
    public static final String DATA = "Huawei|m881|";
}
