// This file is automatically generated.

package adila.db;

/*
 * Huawei M220
 *
 * DEVICE: hwmediaqm220
 * MODEL: M220
 */
final class hwmediaqm220_m220 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "M220";
}
