// This file is automatically generated.

package adila.db;

/*
 * Huawei M2
 *
 * DEVICE: HWMozart
 * MODEL: HUAWEI M2-802L
 */
final class hwmozart_huawei20m22d802l {
    public static final String DATA = "Huawei|M2|";
}
