// This file is automatically generated.

package adila.db;

/*
 * Huawei GT3
 *
 * DEVICE: HWNMO-H
 * MODEL: HUAWEI NMO-L31
 */
final class hwnmo2dh_huawei20nmo2dl31 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "GT3";
}
