// This file is automatically generated.

package adila.db;

/*
 * Huawei Mate 8
 *
 * DEVICE: HWNXT
 * MODEL: NXT-L09
 */
final class hwnxt_nxt2dl09 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Mate 8";
}
