// This file is automatically generated.

package adila.db;

/*
 * Huawei Mate 8
 *
 * DEVICE: HWNXT
 * MODEL: HUAWEI NXT-TL00B
 */
final class hwnxt_huawei20nxt2dtl00b {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Mate 8";
}
