// This file is automatically generated.

package adila.db;

/*
 * Huawei Mate 8
 *
 * DEVICE: HWNXT
 * MODEL: NXT-DL00
 */
final class hwnxt_nxt2ddl00 {
    public static final String DATA = "Huawei|Mate 8|";
}
