// This file is automatically generated.

package adila.db;

/*
 * Huawei P7-L07
 *
 * DEVICE: hwp7
 * MODEL: HUAWEI P7-L07
 */
final class hwp7_huawei20p72dl07 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "P7-L07";
}
