// This file is automatically generated.

package adila.db;

/*
 * Huawei P7-L09
 *
 * DEVICE: hwp7
 * MODEL: HUAWEI P7-L09
 */
final class hwp7_huawei20p72dl09 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "P7-L09";
}
