// This file is automatically generated.

package adila.db;

/*
 * Huawei PE-CL00
 *
 * DEVICE: hwPE
 * MODEL: PE-CL00
 */
final class hwpe_pe2dcl00 {
    public static final String DATA = "Huawei|PE-CL00|";
}
