// This file is automatically generated.

package adila.db;

/*
 * Huawei PE-TL20
 *
 * DEVICE: hwPE
 * MODEL: PE-TL20
 */
final class hwpe_pe2dtl20 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "PE-TL20";
}
