// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 6 Plus
 *
 * DEVICE: hwPE
 * MODEL: PE-TL10
 */
final class hwpe_pe2dtl10 {
    public static final String DATA = "Huawei|Honor 6 Plus|";
}
