// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 7
 *
 * DEVICE: HWPLK
 * MODEL: PLK-TL01H
 */
final class hwplk_plk2dtl01h {
    public static final String DATA = "Huawei|Honor 7|";
}
