// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor 7
 *
 * DEVICE: HWPLK
 * MODEL: PLK-TL00
 */
final class hwplk_plk2dtl00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Honor 7";
}
