// This file is automatically generated.

package adila.db;

/*
 * Huawei G8
 *
 * DEVICE: hwRIO-L01
 * MODEL: HUAWEI RIO-L01
 */
final class hwrio2dl01_huawei20rio2dl01 {
    public static final String DATA = "Huawei|G8|";
}
