// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad 10 Link+
 *
 * DEVICE: hws10231l
 * MODEL: SpeedTAB
 */
final class hws10231l_speedtab {
    public static final String DATA = "Huawei|MediaPad 10 Link+|";
}
