// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad 10 Link
 *
 * DEVICE: hws10201w
 * MODEL: dtab 01
 */
final class hws10201w_dtab2001 {
    public static final String DATA = "Huawei|MediaPad 10 Link|";
}
