// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hws10101w
 * MODEL: GT01
 */
final class hws10101w_gt01 {
    public static final String MANUFACTURER = "Huawei";
}
