// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwS42HW
 * MODEL: S42HW
 */
final class hws42hw_s42hw {
    public static final String MANUFACTURER = "Huawei";
}
