// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad 7
 *
 * DEVICE: hws7601us
 * MODEL: MediaPad 7 Vogue
 */
final class hws7601us {
    public static final String DATA = "Huawei|MediaPad 7|";
}
