// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad 7 Youth 2
 *
 * DEVICE: hws7721g
 * MODEL: MediaPad 7 Youth 2
 */
final class hws7721g {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "MediaPad 7 Youth 2";
}
