// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hws7300u
 * MODEL: SpringBoard
 */
final class hws7300u_springboard {
    public static final String MANUFACTURER = "Huawei";
}
