// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad M1 8.0
 *
 * DEVICE: hws8301l
 * MODEL: MediaPad M1 8.0 (LTE)
 */
final class hws8301l_mediapad20m12082e02028lte29 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "MediaPad M1 8.0";
}
