// This file is automatically generated.

package adila.db;

/*
 * Huawei MediaPad M1 8.0
 *
 * DEVICE: hws8301l
 * MODEL: HUAWEI MediaPad M1 8.0
 */
final class hws8301l_huawei20mediapad20m12082e0 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "MediaPad M1 8.0";
}
