// This file is automatically generated.

package adila.db;

/*
 * Huawei Y6
 *
 * DEVICE: hwSCL-Q
 * MODEL: SCL-L01
 */
final class hwscl2dq_scl2dl01 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y6";
}
