// This file is automatically generated.

package adila.db;

/*
 * Huawei Y6
 *
 * DEVICE: hwSCL-Q
 * MODEL: HUAWEI SCL-L01
 */
final class hwscl2dq_huawei20scl2dl01 {
    public static final String DATA = "Huawei|Y6|";
}
