// This file is automatically generated.

package adila.db;

/*
 * Huawei t1_8p0lte
 *
 * DEVICE: hwt1821l
 * MODEL: S8-821w
 */
final class hwt1821l_s82d821w {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "t1_8p0lte";
}
