// This file is automatically generated.

package adila.db;

/*
 * Huawei T102
 *
 * DEVICE: hwt102
 * MODEL: QH-10
 */
final class hwt102_qh2d10 {
    public static final String DATA = "Huawei|T102|";
}
