// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwt8950N
 * MODEL: HUAWEI T8950N
 */
final class hwt8950n_huawei20t8950n {
    public static final String MANUFACTURER = "Huawei";
}
