// This file is automatically generated.

package adila.db;

/*
 * Huawei TANGO
 *
 * DEVICE: HWTAG-L6753
 * MODEL: HUAWEI TAG-TL00
 */
final class hwtag2dl6753_huawei20tag2dtl00 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "TANGO";
}
