// This file is automatically generated.

package adila.db;

/*
 * Huawei GR3 Smart touch
 *
 * DEVICE: HWTAG-L6753
 * MODEL: HUAWEI TAG-L32
 */
final class hwtag2dl6753_huawei20tag2dl32 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "GR3 Smart touch";
}
