// This file is automatically generated.

package adila.db;

/*
 * Huawei Y6 Pro
 *
 * DEVICE: HWTIT-L6735
 * MODEL: TIT-L01
 */
final class hwtit2dl6735_tit2dl01 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y6 Pro";
}
