// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8950N-1
 * MODEL: HUAWEI U8950N-1
 */
final class hwu8950n2d1_huawei20u8950n2d1 {
    public static final String DATA = "Huawei||";
}
