// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8815n
 * MODEL: HUAWEI U8815N
 */
final class hwu8815n_huawei20u8815n {
    public static final String DATA = "Huawei||";
}
