// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8812D
 * MODEL: U8812D
 */
final class hwu8812d_u8812d {
    public static final String DATA = "Huawei||";
}
