// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8815
 * MODEL: HUAWEI Ascend G 300
 */
final class hwu8815_huawei20ascend20g20300 {
    public static final String MANUFACTURER = "Huawei";
}
