// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8650
 * MODEL: MTC 955
 */
final class hwu8650_mtc20955 {
    public static final String MANUFACTURER = "Huawei";
}
