// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8655
 * MODEL: HUAWEI IDEOS Y 200
 */
final class hwu8655_huawei20ideos20y20200 {
    public static final String MANUFACTURER = "Huawei";
}
