// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8815
 * MODEL: U8815-51
 */
final class hwu8815_u88152d51 {
    public static final String MANUFACTURER = "Huawei";
}
