// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8650
 * MODEL: U8650-1
 */
final class hwu8650_u86502d1 {
    public static final String DATA = "Huawei||";
}
