// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8666e-51
 * MODEL: HUAWEI U8666E-51
 */
final class hwu8666e2d51_huawei20u8666e2d51 {
    public static final String MANUFACTURER = "Huawei";
}
