// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8350
 * MODEL: U8350-51
 */
final class hwu8350_u83502d51 {
    public static final String MANUFACTURER = "Huawei";
}
