// This file is automatically generated.

package adila.db;

/*
 * Huawei V858
 *
 * DEVICE: hwu8160
 * MODEL: MTC 950
 */
final class hwu8160_mtc20950 {
    public static final String DATA = "Huawei|V858|";
}
