// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8650
 * MODEL: Turkcell T20
 */
final class hwu8650_turkcell20t20 {
    public static final String DATA = "Huawei||";
}
