// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8860
 * MODEL: GS02
 */
final class hwu8860_gs02 {
    public static final String MANUFACTURER = "Huawei";
}
