// This file is automatically generated.

package adila.db;

/*
 * Huawei Prism II
 *
 * DEVICE: hwu8686
 * MODEL: Prism II
 */
final class hwu8686 {
    public static final String DATA = "Huawei|Prism II|";
}
