// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu8860
 * MODEL: U8860
 */
final class hwu8860_u8860 {
    public static final String MANUFACTURER = "Huawei";
}
