// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwU9202L
 * MODEL: U9202L-1
 */
final class hwu9202l_u9202l2d1 {
    public static final String DATA = "Huawei||";
}
