// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu9200
 * MODEL: U9200
 */
final class hwu9200_u9200 {
    public static final String MANUFACTURER = "Huawei";
}
