// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: hwu9200-92
 * MODEL: GS03
 */
final class hwu92002d92_gs03 {
    public static final String DATA = "Huawei||";
}
