// This file is automatically generated.

package adila.db;

/*
 * Huawei G9 Youth Edition
 *
 * DEVICE: HWVNS-H
 * MODEL: HUAWEI VNS-DL00
 */
final class hwvns2dh_huawei20vns2ddl00 {
    public static final String DATA = "Huawei|G9 Youth Edition|";
}
