// This file is automatically generated.

package adila.db;

/*
 * Huawei P9 Lite
 *
 * DEVICE: HWVNS-Q
 * MODEL: HUAWEI VNS-L62
 */
final class hwvns2dq_huawei20vns2dl62 {
    public static final String DATA = "Huawei|P9 Lite|";
}
