// This file is automatically generated.

package adila.db;

/*
 * Huawei Y220
 *
 * DEVICE: HWY220-U
 * MODEL: Y220-U17
 */
final class hwy2202du_y2202du17 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y220";
}
