// This file is automatically generated.

package adila.db;

/*
 * Huawei Y3 Lite
 *
 * DEVICE: HWY360-U6572
 * MODEL: HUAWEI Y360-U103
 */
final class hwy3602du6572_huawei20y3602du103 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y3 Lite";
}
