// This file is automatically generated.

package adila.db;

/*
 * Huawei Y320-U30
 *
 * DEVICE: HWY320-U
 * MODEL: HUAWEI Y320-U30
 */
final class hwy3202du_huawei20y3202du30 {
    public static final String DATA = "Huawei|Y320-U30|";
}
