// This file is automatically generated.

package adila.db;

/*
 * Huawei Y320-U351
 *
 * DEVICE: HWY320-U
 * MODEL: HUAWEI Y320-U351
 */
final class hwy3202du_huawei20y3202du351 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y320-U351";
}
