// This file is automatically generated.

package adila.db;

/*
 * Huawei Y330-U01
 *
 * DEVICE: hwY330-U01
 * MODEL: HUAWEI Y330-U01
 */
final class hwy3302du01_huawei20y3302du01 {
    public static final String DATA = "Huawei|Y330-U01|";
}
