// This file is automatically generated.

package adila.db;

/*
 * Huawei Y5C
 *
 * DEVICE: HWY541-U
 * MODEL: HUAWEI Y541-U02
 */
final class hwy5412du_huawei20y5412du02 {
    public static final String DATA = "Huawei|Y5C|";
}
