// This file is automatically generated.

package adila.db;

/*
 * Huawei Y5
 *
 * DEVICE: HWY560-L
 * MODEL: HUAWEI Y560-L03
 */
final class hwy5602dl_huawei20y5602dl03 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Y5";
}
