// This file is automatically generated.

package adila.db;

/*
 * Huawei Y550-L03
 *
 * DEVICE: hwY550-L03
 * MODEL: HUAWEI Y550
 */
final class hwy5502dl03_huawei20y550 {
    public static final String DATA = "Huawei|Y550-L03|";
}
