// This file is automatically generated.

package adila.db;

/*
 * Huawei Y600-U351
 *
 * DEVICE: HWY600-U
 * MODEL: HUAWEI Y600-U351
 */
final class hwy6002du_huawei20y6002du351 {
    public static final String DATA = "Huawei|Y600-U351|";
}
