// This file is automatically generated.

package adila.db;

/*
 * Coolpad i1
 *
 * DEVICE: i1
 * MODEL: ivvi i1
 */
final class i1_ivvi20i1 {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "i1";
}
