// This file is automatically generated.

package adila.db;

/*
 * Coolpad i3-M1
 *
 * DEVICE: i3-M1
 * MODEL: ivvi i3-M1
 */
final class i32dm1_ivvi20i32dm1 {
    public static final String DATA = "Coolpad|i3-M1|";
}
