// This file is automatically generated.

package adila.db;

/*
 * Hisense I632T
 *
 * DEVICE: I632T
 * MODEL: Hisense I632T
 */
final class i632t_hisense20i632t {
    public static final String DATA = "Hisense|I632T|";
}
