// This file is automatically generated.

package adila.db;

/*
 * Click Click Tab 7''
 *
 * DEVICE: I7043G
 * MODEL: I7043G
 */
final class i7043g_i7043g {
    public static final String DATA = "Click|Click Tab 7''|";
}
