// This file is automatically generated.

package adila.db;

/*
 * Ice Phone Ice Phone Mini
 *
 * DEVICE: ice_phone_mini
 * MODEL: Ice-Phone Mini
 */
final class ice5fphone5fmini {
    public static final String DATA = "Ice Phone|Ice Phone Mini|";
}
