// This file is automatically generated.

package adila.db;

/*
 * iCraig ICRAIG_CMP_771
 *
 * DEVICE: ICRAIG_CMP_771
 * MODEL: ICRAIG_CMP771
 */
final class icraig5fcmp5f771_icraig5fcmp771 {
    public static final String MANUFACTURER = "iCraig";
    public static final String NAME = "ICRAIG_CMP_771";
}
