// This file is automatically generated.

package adila.db;

/*
 * iCraig ICRAIG_CLP_291
 *
 * DEVICE: ICRAIG_CLP_291
 * MODEL: ICRAIG_CLP291
 */
final class icraig5fclp5f291_icraig5fclp291 {
    public static final String DATA = "iCraig|ICRAIG_CLP_291|";
}
