// This file is automatically generated.

package adila.db;

/*
 * Lenovo ideatv S52
 *
 * DEVICE: ideatv_S52
 * MODEL: ideatv S52
 */
final class ideatv5fs52_ideatv20s52 {
    public static final String DATA = "Lenovo|ideatv S52|";
}
