// This file is automatically generated.

package adila.db;

/*
 * Alcatel 6055D
 *
 * DEVICE: idol4
 * MODEL: 6055D
 */
final class idol4_6055d {
    public static final String DATA = "Alcatel|6055D|";
}
