// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH IDOL 3 (5.5)
 *
 * DEVICE: idol3
 * MODEL: 6045I
 */
final class idol3_6045i {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONETOUCH IDOL 3 (5.5)";
}
