// This file is automatically generated.

package adila.db;

/*
 * Alcatel 6039K
 *
 * DEVICE: idol347
 * MODEL: 6039K
 */
final class idol347_6039k {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "6039K";
}
