// This file is automatically generated.

package adila.db;

/*
 * Lanix ILIUM L950
 *
 * DEVICE: Ilium_L950
 * MODEL: Ilium_L950
 */
final class ilium5fl950_ilium5fl950 {
    public static final String MANUFACTURER = "Lanix";
    public static final String NAME = "ILIUM L950";
}
