// This file is automatically generated.

package adila.db;

/*
 * HTC KDDI Infobar A02
 *
 * DEVICE: imnj
 * MODEL: HTX21
 */
final class imnj {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "KDDI Infobar A02";
}
