// This file is automatically generated.

package adila.db;

/*
 * IMO (In My Opinion) IMO Q
 *
 * DEVICE: IMO_Q
 * MODEL: IMO Q
 */
final class imo5fq_imo20q {
    public static final String DATA = "IMO (In My Opinion)|IMO Q|";
}
