// This file is automatically generated.

package adila.db;

/*
 * Infinix HOT 3 LTE
 *
 * DEVICE: INFINIX-X553
 * MODEL: Infinix HOT 3 LTE
 */
final class infinix2dx553_infinix20hot20320lte {
    public static final String DATA = "Infinix|HOT 3 LTE|";
}
