// This file is automatically generated.

package adila.db;

/*
 * Infinix X552
 *
 * DEVICE: INFINIX-X552-95M
 * MODEL: Infinix-X552
 */
final class infinix2dx5522d95m_infinix2dx552 {
    public static final String DATA = "Infinix|X552|";
}
