// This file is automatically generated.

package adila.db;

/*
 * Infinix X521
 *
 * DEVICE: Infinix-X521-Pro
 * MODEL: Infinix-X521
 */
final class infinix2dx5212dpro_infinix2dx521 {
    public static final String MANUFACTURER = "Infinix";
    public static final String NAME = "X521";
}
