// This file is automatically generated.

package adila.db;

/*
 * Infinix Hot Note
 *
 * DEVICE: Infinix-X551
 * MODEL: Infinix-X551
 */
final class infinix2dx551_infinix2dx551 {
    public static final String MANUFACTURER = "Infinix";
    public static final String NAME = "Hot Note";
}
