// This file is automatically generated.

package adila.db;

/*
 * NGM Infinity
 *
 * DEVICE: Infinity
 * MODEL: Infinity
 */
final class infinity_infinity {
    public static final String MANUFACTURER = "NGM";
    public static final String NAME = "Infinity";
}
