// This file is automatically generated.

package adila.db;

/*
 * Cellon IQ 1.1
 *
 * DEVICE: IQ1-1
 * MODEL: i-mobile IQ1-1
 */
final class iq12d1_i2dmobile20iq12d1 {
    public static final String DATA = "Cellon|IQ 1.1|";
}
