// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4418
 *
 * DEVICE: IQ4418
 * MODEL: IQ4418
 */
final class iq4418_iq4418 {
    public static final String DATA = "Fly|IQ4418|";
}
