// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4420 Quad
 *
 * DEVICE: IQ4420_Quad
 * MODEL: IQ4420 Quad
 */
final class iq44205fquad_iq442020quad {
    public static final String DATA = "Fly|IQ4420 Quad|";
}
