// This file is automatically generated.

package adila.db;

/*
 * Fly Era Nano 8
 *
 * DEVICE: IQ4400
 * MODEL: IQ4400
 */
final class iq4400_iq4400 {
    public static final String DATA = "Fly|Era Nano 8|";
}
