// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4513 Octa
 *
 * DEVICE: IQ4513_Octa
 * MODEL: IQ4513 Octa
 */
final class iq45135focta_iq451320octa {
    public static final String DATA = "Fly|IQ4513 Octa|";
}
