// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4514 Quad
 *
 * DEVICE: IQ4514_Quad
 * MODEL: Fly IQ4514 AF
 */
final class iq45145fquad_fly20iq451420af {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "IQ4514 Quad";
}
