// This file is automatically generated.

package adila.db;

/*
 * Fly IQ4602
 *
 * DEVICE: IQ4602_Quad
 * MODEL: IQ4602 Quad
 */
final class iq46025fquad_iq460220quad {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "IQ4602";
}
