// This file is automatically generated.

package adila.db;

/*
 * Alcatel one touch J320
 *
 * DEVICE: Iris
 * MODEL: ALCATEL one touch J320
 */
final class iris_alcatel20one20touch20j320 {
    public static final String DATA = "Alcatel|one touch J320|";
}
