// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL J600T
 *
 * DEVICE: Iris2TD
 * MODEL: TCL J600T
 */
final class iris2td_tcl20j600t {
    public static final String DATA = "Alcatel|TCL J600T|";
}
