// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL J630
 *
 * DEVICE: Iris2PlusUMTS
 * MODEL: J630
 */
final class iris2plusumts_j630 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TCL J630";
}
