// This file is automatically generated.

package adila.db;

/*
 * Motorola Motoluxe
 *
 * DEVICE: ironmax_umts
 * MODEL: XT685
 */
final class ironmax5fumts_xt685 {
    public static final String DATA = "Motorola|Motoluxe|";
}
