// This file is automatically generated.

package adila.db;

/*
 * USA111 iRULU V3
 *
 * DEVICE: iRULU_V3i
 * MODEL: iRULU_V3
 */
final class irulu5fv3i_irulu5fv3 {
    public static final String MANUFACTURER = "USA111";
    public static final String NAME = "iRULU V3";
}
