// This file is automatically generated.

package adila.db;

/*
 * USA111 IRULU X11
 *
 * DEVICE: iRULU-X11
 * MODEL: iRULU X11
 */
final class irulu2dx11_irulu20x11 {
    public static final String MANUFACTURER = "USA111";
    public static final String NAME = "IRULU X11";
}
