// This file is automatically generated.

package adila.db;

/*
 * Itel it1508
 *
 * DEVICE: itel_it1508
 * MODEL: itel it1508
 */
final class itel5fit1508 {
    public static final String MANUFACTURER = "Itel";
    public static final String NAME = "it1508";
}
