// This file is automatically generated.

package adila.db;

/*
 * Itel it1508
 *
 * DEVICE: itel_it1508C
 * MODEL: itel it1508
 */
final class itel5fit1508c_itel20it1508 {
    public static final String DATA = "Itel|it1508|";
}
