// This file is automatically generated.

package adila.db;

/*
 * Itel it1355
 *
 * DEVICE: itel_it1355
 * MODEL: itel it1355
 */
final class itel5fit1355 {
    public static final String DATA = "Itel|it1355|";
}
