// This file is automatically generated.

package adila.db;

/*
 * Itel it1408
 *
 * DEVICE: itel_it1408
 * MODEL: itel it1408
 */
final class itel5fit1408 {
    public static final String DATA = "Itel|it1408|";
}
