// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Music Duos
 *
 * DEVICE: ivory
 * MODEL: GT-S6012B
 */
final class ivory_gt2ds6012b {
    public static final String DATA = "Samsung|Galaxy Music Duos|";
}
