// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J1
 *
 * DEVICE: j1lte
 * MODEL: SM-J100F
 */
final class j1lte_sm2dj100f {
    public static final String DATA = "Samsung|Galaxy J1|Galaxy J";
}
