// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J1 Mini
 *
 * DEVICE: j1mini3g
 * MODEL: SM-J105H
 */
final class j1mini3g_sm2dj105h {
    public static final String DATA = "Samsung|Galaxy J1 Mini|Galaxy J";
}
