// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J1 Mini
 *
 * DEVICE: j1mini3gdx
 * MODEL: SM-J105B
 */
final class j1mini3gdx {
    public static final String DATA = "Samsung|Galaxy J1 Mini|Galaxy J";
}
