// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J1
 *
 * DEVICE: j1xlteatt
 * MODEL: SAMSUNG-SM-J120A
 */
final class j1xlteatt {
    public static final String DATA = "Samsung|Galaxy J1|Galaxy J";
}
