// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J1
 *
 * DEVICE: j1xqltespr
 * MODEL: SM-J120P
 */
final class j1xqltespr {
    public static final String DATA = "Samsung|Galaxy J1|";
}
