// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J2
 *
 * DEVICE: j2ltedtv
 * MODEL: SM-J200BT
 */
final class j2ltedtv {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J2";
    public static final String SERIES = "Galaxy J";
}
