// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J2
 *
 * DEVICE: j2ltedtv
 * MODEL: SM-J200BT
 */
final class j2ltedtv {
    public static final String DATA = "Samsung|Galaxy J2|Galaxy J";
}
