// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J2 (2016)
 *
 * DEVICE: j2xlteins
 * MODEL: SM-J210F
 */
final class j2xlteins {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J2 (2016)";
    public static final String SERIES = "Galaxy J";
}
