// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J3 (2016)
 *
 * DEVICE: j3ltevzw
 * MODEL: SM-J320V
 */
final class j3ltevzw_sm2dj320v {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J3 (2016)";
    public static final String SERIES = "Galaxy J";
}
