// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J3
 *
 * DEVICE: j3ltectc
 * MODEL: SM-J3109
 */
final class j3ltectc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J3";
    public static final String SERIES = "Galaxy J";
}
