// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J3 (2016)
 *
 * DEVICE: j3xlte
 * MODEL: SM-J320F
 */
final class j3xlte_sm2dj320f {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J3 (2016)";
    public static final String SERIES = "Galaxy J";
}
