// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J3 Pro
 *
 * DEVICE: j3xproltechn
 * MODEL: SM-J3110
 */
final class j3xproltechn {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J3 Pro";
    public static final String SERIES = "Galaxy J";
}
