// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J5
 *
 * DEVICE: j5lte
 * MODEL: SM-J500G
 */
final class j5lte_sm2dj500g {
    public static final String DATA = "Samsung|Galaxy J5|Galaxy J";
}
