// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J5(2016)
 *
 * DEVICE: j5xnlte
 * MODEL: SM-J510FQ
 */
final class j5xnlte_sm2dj510fq {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J5(2016)";
}
