// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J5 (2016)
 *
 * DEVICE: j5xnlte
 * MODEL: SM-J510MN
 */
final class j5xnlte_sm2dj510mn {
    public static final String DATA = "Samsung|Galaxy J5 (2016)|Galaxy J";
}
