// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J7
 *
 * DEVICE: j7e3g
 * MODEL: SM-J700H
 */
final class j7e3g {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J7";
    public static final String SERIES = "Galaxy J";
}
