// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J7
 *
 * DEVICE: j7elte
 * MODEL: SM-J700F
 */
final class j7elte_sm2dj700f {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy J7";
    public static final String SERIES = "Galaxy J";
}
