// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy J7
 *
 * DEVICE: j7ltechn
 * MODEL: SM-J7008
 */
final class j7ltechn {
    public static final String DATA = "Samsung|Galaxy J7|Galaxy J";
}
