// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: ja3gduosctc
 * MODEL: SCH-I959
 */
final class ja3gduosctc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4";
    public static final String SERIES = "Galaxy S";
}
