// This file is automatically generated.

package adila.db;

/*
 * LG G3 Beat
 *
 * DEVICE: jagdsnm
 * MODEL: LG-D729
 */
final class jagdsnm_lg2dd729 {
    public static final String DATA = "LG|G3 Beat|";
}
