// This file is automatically generated.

package adila.db;

/*
 * LG G3 Beat
 *
 * DEVICE: jagnm
 * MODEL: LG-D727
 */
final class jagnm_lg2dd727 {
    public static final String DATA = "LG|G3 Beat|";
}
