// This file is automatically generated.

package adila.db;

/*
 * ZTE K88
 *
 * DEVICE: jasmine
 * MODEL: K88
 */
final class jasmine {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "K88";
}
