// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jfltecan
 * MODEL: SGH-I337M
 */
final class jfltecan_sgh2di337m {
    public static final String DATA = "Samsung|Galaxy S4|Galaxy S";
}
