// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jflte
 * MODEL: GT-I9508C
 */
final class jflte_gt2di9508c {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4";
    public static final String SERIES = "Galaxy S";
}
