// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jflteusc
 * MODEL: SCH-R970
 */
final class jflteusc {
    public static final String DATA = "Samsung|Galaxy S4|Galaxy S";
}
