// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jfltetfntmo
 * MODEL: SGH-S970G
 */
final class jfltetfntmo {
    public static final String DATA = "Samsung|Galaxy S4|Galaxy S";
}
