// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jfltecsp
 * MODEL: SCH-R970X
 */
final class jfltecsp {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4";
    public static final String SERIES = "Galaxy S";
}
