// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jftdd
 * MODEL: GT-I9507V
 */
final class jftdd_gt2di9507v {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4";
    public static final String SERIES = "Galaxy S";
}
