// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jftdd
 * MODEL: GT-I9507
 */
final class jftdd_gt2di9507 {
    public static final String DATA = "Samsung|Galaxy S4|Galaxy S";
}
