// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4
 *
 * DEVICE: jfvelte
 * MODEL: GT-I9515L
 */
final class jfvelte_gt2di9515l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4";
    public static final String SERIES = "Galaxy S";
}
