// This file is automatically generated.

package adila.db;

/*
 * BenQ JM-250
 *
 * DEVICE: JM-250
 * MODEL: JM-250
 */
final class jm2d250_jm2d250 {
    public static final String MANUFACTURER = "BenQ";
    public static final String NAME = "JM-250";
}
