// This file is automatically generated.

package adila.db;

/*
 * Pantech SIRIUS
 *
 * DEVICE: jmasai
 * MODEL: IS06
 */
final class jmasai {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "SIRIUS";
}
