// This file is automatically generated.

package adila.db;

/*
 * Asus Fonepad 7 LTE (ME372CL)
 *
 * DEVICE: K00Y
 * MODEL: K00Y
 */
final class k00y_k00y {
    public static final String DATA = "Asus|Fonepad 7 LTE (ME372CL)|";
}
