// This file is automatically generated.

package adila.db;

/*
 * Asus Transformer Pad (TF103C)
 *
 * DEVICE: K010
 * MODEL: K010
 */
final class k010_k010 {
    public static final String DATA = "Asus|Transformer Pad (TF103C)|";
}
