// This file is automatically generated.

package adila.db;

/*
 * Asus MeMO Pad 8 (ME181CX)
 *
 * DEVICE: K011_1
 * MODEL: K011
 */
final class k0115f1_k011 {
    public static final String DATA = "Asus|MeMO Pad 8 (ME181CX)|";
}
