// This file is automatically generated.

package adila.db;

/*
 * Asus MeMO Pad 7 (ME176C)
 *
 * DEVICE: K013
 * MODEL: K013
 */
final class k013_k013 {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "MeMO Pad 7 (ME176C)";
}
