// This file is automatically generated.

package adila.db;

/*
 * Asus Fonepad 7 (FE375CXG)
 *
 * DEVICE: K019_4
 * MODEL: K019
 */
final class k0195f4_k019 {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "Fonepad 7 (FE375CXG)";
}
