// This file is automatically generated.

package adila.db;

/*
 * Asus Fonepad 7 (FE171CG)
 *
 * DEVICE: K01N_1
 * MODEL: K01N
 */
final class k01n5f1_k01n {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "Fonepad 7 (FE171CG)";
}
