// This file is automatically generated.

package adila.db;

/*
 * Asus MeMO Pad 7 (ME171C)
 *
 * DEVICE: K01U_2
 * MODEL: K01U
 */
final class k01u5f2_k01u {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "MeMO Pad 7 (ME171C)";
}
