// This file is automatically generated.

package adila.db;

/*
 * Lenovo VIBE K10
 *
 * DEVICE: K10a40
 * MODEL: Lenovo K10a40
 */
final class k10a40_lenovo20k10a40 {
    public static final String DATA = "Lenovo|VIBE K10|";
}
