// This file is automatically generated.

package adila.db;

/*
 * Lenovo K1
 *
 * DEVICE: K1
 * MODEL: K1
 */
final class k1_k1 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "K1";
}
