// This file is automatically generated.

package adila.db;

/*
 * HTC ONE SV
 *
 * DEVICE: k2u
 * MODEL: HTC One SV
 */
final class k2u_htc20one20sv {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "ONE SV";
}
