// This file is automatically generated.

package adila.db;

/*
 * HTC ONE SV
 *
 * DEVICE: k2u
 * MODEL: HTC K2_U
 */
final class k2u_htc20k25fu {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "ONE SV";
}
