// This file is automatically generated.

package adila.db;

/*
 * HTC One SV
 *
 * DEVICE: k2ul
 * MODEL: HTC One SV
 */
final class k2ul_htc20one20sv {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "One SV";
}
