// This file is automatically generated.

package adila.db;

/*
 * Lenovo K32c30
 *
 * DEVICE: K32c30
 * MODEL: Lenovo K32c30
 */
final class k32c30_lenovo20k32c30 {
    public static final String DATA = "Lenovo|K32c30|";
}
