// This file is automatically generated.

package adila.db;

/*
 * Lenovo VIBE K6 Power
 *
 * DEVICE: K33a42
 * MODEL: Lenovo K33a42
 */
final class k33a42_lenovo20k33a42 {
    public static final String DATA = "Lenovo|VIBE K6 Power|";
}
