// This file is automatically generated.

package adila.db;

/*
 * Lenovo K50
 *
 * DEVICE: K50-t5
 * MODEL: Lenovo K50-t5
 */
final class k502dt5_lenovo20k502dt5 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "K50";
}
