// This file is automatically generated.

package adila.db;

/*
 * Lenovo K5 Note
 *
 * DEVICE: k52_t58
 * MODEL: Lenovo K52t58
 */
final class k525ft58 {
    public static final String DATA = "Lenovo|K5 Note|";
}
