// This file is automatically generated.

package adila.db;

/*
 * LG X screen
 *
 * DEVICE: k5
 * MODEL: LG-F650S
 */
final class k5_lg2df650s {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "X screen";
}
