// This file is automatically generated.

package adila.db;

/*
 * LG X Style
 *
 * DEVICE: k6b
 * MODEL: LG-K200
 */
final class k6b_lg2dk200 {
    public static final String DATA = "LG|X Style|";
}
