// This file is automatically generated.

package adila.db;

/*
 * Compal TANK 4.5
 *
 * DEVICE: ka09
 * MODEL: TANK 4.5
 */
final class ka09 {
    public static final String MANUFACTURER = "Compal";
    public static final String NAME = "TANK 4.5";
}
