// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core 2
 *
 * DEVICE: kanas
 * MODEL: SM-G355M
 */
final class kanas_sm2dg355m {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core 2";
}
