// This file is automatically generated.

package adila.db;

/*
 * KAZAM TROOPER X3.5
 *
 * DEVICE: KAZAM
 * MODEL: Trooper_X35
 */
final class kazam_trooper5fx35 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "TROOPER X3.5";
}
