// This file is automatically generated.

package adila.db;

/*
 * KAZAM TROOPER X4.0
 *
 * DEVICE: KAZAM
 * MODEL: Trooper_X40
 */
final class kazam_trooper5fx40 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "TROOPER X4.0";
}
