// This file is automatically generated.

package adila.db;

/*
 * Marshall Marshall London
 *
 * DEVICE: KB-1501
 * MODEL: London
 */
final class kb2d1501_london {
    public static final String DATA = "Marshall|Marshall London|";
}
