// This file is automatically generated.

package adila.db;

/*
 * HTC EVODesign4G
 *
 * DEVICE: kingdom
 * MODEL: HTC Kingdom
 */
final class kingdom_htc20kingdom {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "EVODesign4G";
}
