// This file is automatically generated.

package adila.db;

/*
 * Lenovo K920/VIBE Z2
 *
 * DEVICE: kingdom_row
 * MODEL: Lenovo K920
 */
final class kingdom5frow {
    public static final String DATA = "Lenovo|K920/VIBE Z2|";
}
