// This file is automatically generated.

package adila.db;

/*
 * Wileyfox Storm
 *
 * DEVICE: kipper
 * MODEL: Wileyfox Storm
 */
final class kipper {
    public static final String MANUFACTURER = "Wileyfox";
    public static final String NAME = "Storm";
}
