// This file is automatically generated.

package adila.db;

/*
 * ZTE V9800
 *
 * DEVICE: kiska
 * MODEL: ZTE V9800
 */
final class kiska_zte20v9800 {
    public static final String DATA = "ZTE|V9800|";
}
