// This file is automatically generated.

package adila.db;

/*
 * Lenovo K910e
 *
 * DEVICE: kitone
 * MODEL: Lenovo K910e
 */
final class kitone_lenovo20k910e {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "K910e";
}
