// This file is automatically generated.

package adila.db;

/*
 * KLIPAD KLIPAD_SMART_D71
 *
 * DEVICE: KLIPAD_SMART_D71
 * MODEL: KLIPAD_SMART_D71
 */
final class klipad5fsmart5fd71_klipad5fsmart5fd71 {
    public static final String DATA = "KLIPAD|KLIPAD_SMART_D71|";
}
