// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5
 *
 * DEVICE: kltetfnvzw
 * MODEL: SM-S903VL
 */
final class kltetfnvzw {
    public static final String DATA = "Samsung|Galaxy S5|Galaxy S";
}
