// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 K Sport
 *
 * DEVICE: kltesprsports
 * MODEL: SM-G860P
 */
final class kltesprsports {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S5 K Sport";
    public static final String SERIES = "Galaxy S";
}
