// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5
 *
 * DEVICE: klte
 * MODEL: SM-G900FQ
 */
final class klte_sm2dg900fq {
    public static final String DATA = "Samsung|Galaxy S5|Galaxy S";
}
