// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5
 *
 * DEVICE: klteacg
 * MODEL: SM-G900R7
 */
final class klteacg {
    public static final String DATA = "Samsung|Galaxy S5|Galaxy S";
}
