// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 Active
 *
 * DEVICE: klteattactive
 * MODEL: SAMSUNG-SM-G870A
 */
final class klteattactive {
    public static final String DATA = "Samsung|Galaxy S5 Active|Galaxy S";
}
