// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 Mini
 *
 * DEVICE: kminiwifi
 * MODEL: SM-G800X
 */
final class kminiwifi {
    public static final String DATA = "Samsung|Galaxy S5 Mini|Galaxy S";
}
