// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 Mini
 *
 * DEVICE: kmini3g
 * MODEL: SM-G800H
 */
final class kmini3g_sm2dg800h {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S5 Mini";
    public static final String SERIES = "Galaxy S";
}
