// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 Mini
 *
 * DEVICE: kminilte
 * MODEL: SM-G800F
 */
final class kminilte_sm2dg800f {
    public static final String DATA = "Samsung|Galaxy S5 Mini|Galaxy S";
}
