// This file is automatically generated.

package adila.db;

/*
 * Cellon Starmobile KNIGHT
 *
 * DEVICE: KNIGHT
 * MODEL: Starmobile KNIGHT
 */
final class knight_starmobile20knight {
    public static final String DATA = "Cellon|Starmobile KNIGHT|";
}
