// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 8.0
 *
 * DEVICE: konawifiany
 * MODEL: SHW-M500W
 */
final class konawifiany {
    public static final String DATA = "Samsung|Galaxy Note 8.0|Galaxy Note";
}
