// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 8.0
 *
 * DEVICE: konalte
 * MODEL: GT-N5120
 */
final class konalte {
    public static final String DATA = "Samsung|Galaxy Note 8.0|Galaxy Note";
}
