// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 8.0
 *
 * DEVICE: konalteatt
 * MODEL: SAMSUNG-SGH-I467
 */
final class konalteatt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note 8.0";
    public static final String SERIES = "Galaxy Note";
}
