// This file is automatically generated.

package adila.db;

/*
 * Haier Konnect_350
 *
 * DEVICE: Konnect_350
 * MODEL: Konnect_350
 */
final class konnect5f350_konnect5f350 {
    public static final String MANUFACTURER = "Haier";
    public static final String NAME = "Konnect_350";
}
