// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Golden
 *
 * DEVICE: ks02lte
 * MODEL: GT-I9230
 */
final class ks02lte_gt2di9230 {
    public static final String DATA = "Samsung|Galaxy Golden|";
}
