// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Trend Duos
 *
 * DEVICE: kyleve
 * MODEL: GT-S7562C
 */
final class kyleve_gt2ds7562c {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Trend Duos";
}
