// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S Duos
 *
 * DEVICE: kylechn
 * MODEL: GT-S7562
 */
final class kylechn {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S Duos";
    public static final String SERIES = "Galaxy S";
}
