// This file is automatically generated.

package adila.db;

/*
 * Kyocera URBANO V01
 *
 * DEVICE: KYV31
 * MODEL: KYV31
 */
final class kyv31_kyv31 {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "URBANO V01";
}
