// This file is automatically generated.

package adila.db;

/*
 * Kyocera TORQUE G02
 *
 * DEVICE: KYV35
 * MODEL: KYV35
 */
final class kyv35_kyv35 {
    public static final String MANUFACTURER = "Kyocera";
    public static final String NAME = "TORQUE G02";
}
