// This file is automatically generated.

package adila.db;

/*
 * Kyocera TORQUE G01
 *
 * DEVICE: KYY24
 * MODEL: KYY24
 */
final class kyy24_kyy24 {
    public static final String DATA = "Kyocera|TORQUE G01|";
}
