// This file is automatically generated.

package adila.db;

/*
 * LG Motion 4G
 *
 * DEVICE: l0
 * MODEL: LG-MS770
 */
final class l0_lg2dms770 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Motion 4G";
}
