// This file is automatically generated.

package adila.db;

/*
 * LG Marquee
 *
 * DEVICE: L-07C
 * MODEL: L-07C
 */
final class l2d07c_l2d07c {
    public static final String DATA = "LG|Marquee|";
}
