// This file is automatically generated.

package adila.db;

/*
 * Logicom L-EMENT500
 *
 * DEVICE: L-EMENT500L
 * MODEL: L-EMENT500L
 */
final class l2dement500l_l2dement500l {
    public static final String DATA = "Logicom|L-EMENT500|";
}
