// This file is automatically generated.

package adila.db;

/*
 * Logicom L-ITE 502 PLUS
 *
 * DEVICE: L-ITE502PLUS
 * MODEL: L-ITE 502 PLUS
 */
final class l2dite502plus_l2dite2050220plus {
    public static final String DATA = "Logicom|L-ITE 502 PLUS|";
}
