// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia ZL
 *
 * DEVICE: L35h
 * MODEL: L35h
 */
final class l35h_l35h {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia ZL";
}
