// This file is automatically generated.

package adila.db;

/*
 * Wiko PULP FAB 4G
 *
 * DEVICE: l5261
 * MODEL: PULP FAB 4G
 */
final class l5261 {
    public static final String MANUFACTURER = "Wiko";
    public static final String NAME = "PULP FAB 4G";
}
