// This file is automatically generated.

package adila.db;

/*
 * Wiko FEVER
 *
 * DEVICE: l5460
 * MODEL: Ridge 4G-Fever
 */
final class l5460_ridge204g2dfever {
    public static final String DATA = "Wiko|FEVER|";
}
