// This file is automatically generated.

package adila.db;

/*
 * LG Optimus it L-05D
 *
 * DEVICE: l_dcm
 * MODEL: L-05D
 */
final class l5fdcm {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus it L-05D";
}
