// This file is automatically generated.

package adila.db;

/*
 * Toshiba L9450
 *
 * DEVICE: l9450
 * MODEL: l9450
 */
final class l9450 {
    public static final String MANUFACTURER = "Toshiba";
    public static final String NAME = "L9450";
}
