// This file is automatically generated.

package adila.db;

/*
 * Xiaomi Redmi 3S
 *
 * DEVICE: land
 * MODEL: Redmi 3S
 */
final class land {
    public static final String MANUFACTURER = "Xiaomi";
    public static final String NAME = "Redmi 3S";
}
