// This file is automatically generated.

package adila.db;

/*
 * Sharp LC-55LE860M
 *
 * DEVICE: LC-55LE860M
 * MODEL: LC-55LE860M
 */
final class lc2d55le860m_lc2d55le860m {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "LC-55LE860M";
}
