// This file is automatically generated.

package adila.db;

/*
 * Sharp LCD-xxBEL6A
 *
 * DEVICE: lcd_xxbel6a
 * MODEL: LCD-xxBEL6A
 */
final class lcd5fxxbel6a {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "LCD-xxBEL6A";
}
