// This file is automatically generated.

package adila.db;

/*
 * Sharp LCD-UF30A
 *
 * DEVICE: lcd_uf30a
 * MODEL: LCD-UF30A
 */
final class lcd5fuf30a {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "LCD-UF30A";
}
