// This file is automatically generated.

package adila.db;

/*
 * Haier LE55M7000CF
 *
 * DEVICE: LE55M7000CF
 * MODEL: LE55M7000CF
 */
final class le55m7000cf_le55m7000cf {
    public static final String MANUFACTURER = "Haier";
    public static final String NAME = "LE55M7000CF";
}
