// This file is automatically generated.

package adila.db;

/*
 * CHN TELECOM CHN-UCAN MJ
 *
 * DEVICE: lefhd
 * MODEL: CHN-UCAN MJ
 */
final class lefhd {
    public static final String DATA = "CHN TELECOM|CHN-UCAN MJ|";
}
