// This file is automatically generated.

package adila.db;

/*
 * ZTE Z955L
 *
 * DEVICE: leo
 * MODEL: Z955L
 */
final class leo_z955l {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z955L";
}
