// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z3
 *
 * DEVICE: leo
 * MODEL: D6603
 */
final class leo_d6603 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia Z3";
}
