// This file is automatically generated.

package adila.db;

/*
 * Anydata LePanII
 *
 * DEVICE: LePanII_wifi
 * MODEL: LePanII
 */
final class lepanii5fwifi_lepanii {
    public static final String MANUFACTURER = "Anydata";
    public static final String NAME = "LePanII";
}
