// This file is automatically generated.

package adila.db;

/*
 * LG Marquee
 *
 * DEVICE: LG855
 * MODEL: LG-LG855
 */
final class lg855_lg2dlg855 {
    public static final String DATA = "LG|Marquee|";
}
