// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Hub
 *
 * DEVICE: lgc800g
 * MODEL: LG-C800G
 */
final class lgc800g {
    public static final String DATA = "LG|Optimus Hub|";
}
