// This file is automatically generated.

package adila.db;

/*
 * LG OPTIMUS ZIP
 *
 * DEVICE: lgl75c
 * MODEL: LGL75C
 */
final class lgl75c {
    public static final String DATA = "LG|OPTIMUS ZIP|";
}
