// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Black
 *
 * DEVICE: lgp970
 * MODEL: LG-P970g
 */
final class lgp970_lg2dp970g {
    public static final String DATA = "LG|Optimus Black|";
}
