// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Black
 *
 * DEVICE: lgp970
 * MODEL: LG-P970h
 */
final class lgp970_lg2dp970h {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Black";
}
