// This file is automatically generated.

package adila.db;

/*
 * Doro Liberto 810
 *
 * DEVICE: Liberto810
 * MODEL: Doro Liberto 810
 */
final class liberto810_doro20liberto20810 {
    public static final String MANUFACTURER = "Doro";
    public static final String NAME = "Liberto 810";
}
