// This file is automatically generated.

package adila.db;

/*
 * Logic Instrument Fieldbook F53
 *
 * DEVICE: lifbf53
 * MODEL: Logic Instrument Fieldbook F53
 */
final class lifbf53 {
    public static final String DATA = "Logic Instrument|Fieldbook F53|";
}
