// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: LIFETAB_S9512
 * MODEL: LIFETAB_S9512
 */
final class lifetab5fs9512_lifetab5fs9512 {
    public static final String MANUFACTURER = "Lenovo";
}
