// This file is automatically generated.

package adila.db;

/*
 * Lenovo LIFETAB E7310
 *
 * DEVICE: LIFETAB_E7310
 * MODEL: LIFETAB_E7310
 */
final class lifetab5fe7310_lifetab5fe7310 {
    public static final String DATA = "Lenovo|LIFETAB E7310|";
}
