// This file is automatically generated.

package adila.db;

/*
 * Medion E731x
 *
 * DEVICE: LIFETAB_E731X
 * MODEL: LIFETAB_E731X
 */
final class lifetab5fe731x_lifetab5fe731x {
    public static final String MANUFACTURER = "Medion";
    public static final String NAME = "E731x";
}
