// This file is automatically generated.

package adila.db;

/*
 * Blu Life Max
 *
 * DEVICE: Life_Max
 * MODEL: Life Max
 */
final class life5fmax_life20max {
    public static final String DATA = "Blu|Life Max|";
}
