// This file is automatically generated.

package adila.db;

/*
 * Medion LIFETAB S1033X
 *
 * DEVICE: LIFETAB_S1033X
 * MODEL: LIFETAB_S1033X
 */
final class lifetab5fs1033x_lifetab5fs1033x {
    public static final String DATA = "Medion|LIFETAB S1033X|";
}
