// This file is automatically generated.

package adila.db;

/*
 * Listo WEBPAD1002
 *
 * DEVICE: Listo
 * MODEL: WEBPAD1002
 */
final class listo_webpad1002 {
    public static final String DATA = "Listo|WEBPAD1002|";
}
