// This file is automatically generated.

package adila.db;

/*
 * LG L60
 *
 * DEVICE: lo_1
 * MODEL: LG-X147
 */
final class lo5f1_lg2dx147 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "L60";
}
