// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace 3 Duos
 *
 * DEVICE: loganlite3g
 * MODEL: GT-S7272C
 */
final class loganlite3g {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Ace 3 Duos";
}
