// This file is automatically generated.

package adila.db;

/*
 * Reliance Smartphone JS LS-5010
 *
 * DEVICE: LS-5010
 * MODEL: LS-5010
 */
final class ls2d5010_ls2d5010 {
    public static final String DATA = "Reliance|Smartphone JS LS-5010|";
}
