// This file is automatically generated.

package adila.db;

/*
 * Lyf LS-5009
 *
 * DEVICE: LS-5009
 * MODEL: LS-5009
 */
final class ls2d5009_ls2d5009 {
    public static final String DATA = "Lyf|LS-5009|";
}
