// This file is automatically generated.

package adila.db;

/*
 * Reliance LS-4008
 *
 * DEVICE: LS-4008
 * MODEL: LS-4008
 */
final class ls2d4008_ls2d4008 {
    public static final String MANUFACTURER = "Reliance";
    public static final String NAME = "LS-4008";
}
