// This file is automatically generated.

package adila.db;

/*
 * LG Marquee
 *
 * DEVICE: LS855
 * MODEL: LG-LS855
 */
final class ls855_lg2dls855 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Marquee";
}
