// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 8.0
 *
 * DEVICE: lt01wifi
 * MODEL: SM-T310
 */
final class lt01wifi_sm2dt310 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 3 8.0";
    public static final String SERIES = "Galaxy Tab";
}
