// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3
 *
 * DEVICE: lt01wifikx
 * MODEL: SM-T310
 */
final class lt01wifikx {
    public static final String DATA = "Samsung|Galaxy Tab 3|Galaxy Tab";
}
