// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 8.0
 *
 * DEVICE: lt01lte
 * MODEL: SM-T315
 */
final class lt01lte_sm2dt315 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 3 8.0";
    public static final String SERIES = "Galaxy Tab";
}
