// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 8.0
 *
 * DEVICE: lt02lduwifi
 * MODEL: SM-T210X
 */
final class lt02lduwifi {
    public static final String DATA = "Samsung|Galaxy Tab 3 8.0|Galaxy Tab";
}
