// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 7.0
 *
 * DEVICE: lt02wifi
 * MODEL: SM-T210
 */
final class lt02wifi_sm2dt210 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 3 7.0";
    public static final String SERIES = "Galaxy Tab";
}
