// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 7.0
 *
 * DEVICE: lt02wifilgt
 * MODEL: SM-T210L
 */
final class lt02wifilgt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 3 7.0";
    public static final String SERIES = "Galaxy Tab";
}
