// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1 2014 Edition
 *
 * DEVICE: lt03ltetmo
 * MODEL: SM-P607T
 */
final class lt03ltetmo {
    public static final String DATA = "Samsung|Galaxy Note 10.1 2014 Edition|Galaxy Note";
}
