// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1
 *
 * DEVICE: lt03ltelgt
 * MODEL: SM-P605L
 */
final class lt03ltelgt {
    public static final String DATA = "Samsung|Galaxy Note 10.1|Galaxy Note";
}
