// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia arc S
 *
 * DEVICE: LT18a
 * MODEL: LT18a
 */
final class lt18a_lt18a {
    public static final String MANUFACTURER = "Sony Ericsson";
    public static final String NAME = "Xperia arc S";
}
