// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia P
 *
 * DEVICE: LT22i
 * MODEL: LT22i
 */
final class lt22i_lt22i {
    public static final String DATA = "Sony|Xperia P|";
}
