// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Ion
 *
 * DEVICE: LT28h
 * MODEL: LT28h
 */
final class lt28h_lt28h {
    public static final String DATA = "Sony|Xperia Ion|";
}
