// This file is automatically generated.

package adila.db;

/*
 * NEC LifeTouch B
 *
 * DEVICE: LTB019G
 * MODEL: D000-000019-002
 */
final class ltb019g_d0002d0000192d002 {
    public static final String DATA = "NEC|LifeTouch B|";
}
