// This file is automatically generated.

package adila.db;

/*
 * NEC LifeTouch B
 *
 * DEVICE: LTB018
 * MODEL: D000-000018-001
 */
final class ltb018_d0002d0000182d001 {
    public static final String DATA = "NEC|LifeTouch B|";
}
