// This file is automatically generated.

package adila.db;

/*
 * NEC LifeTouch L
 *
 * DEVICE: LTTLA32
 * MODEL: LT-TLA
 */
final class lttla32_lt2dtla {
    public static final String MANUFACTURER = "NEC";
    public static final String NAME = "LifeTouch L";
}
