// This file is automatically generated.

package adila.db;

/*
 * LG Optimus One
 *
 * DEVICE: lu3700
 * MODEL: LG-LU3700
 */
final class lu3700 {
    public static final String DATA = "LG|Optimus One|";
}
