// This file is automatically generated.

package adila.db;

/*
 * Archos TV Connect
 *
 * DEVICE: LUDO
 * MODEL: ARCHOS LUDOG10
 */
final class ludo_archos20ludog10 {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "TV Connect";
}
