// This file is automatically generated.

package adila.db;

/*
 * LG L20
 *
 * DEVICE: luv20ss
 * MODEL: LG-D100
 */
final class luv20ss_lg2dd100 {
    public static final String DATA = "LG|L20|";
}
