// This file is automatically generated.

package adila.db;

/*
 * LG L30 Sporty
 *
 * DEVICE: luv30ds
 * MODEL: LG-D125
 */
final class luv30ds {
    public static final String DATA = "LG|L30 Sporty|";
}
