// This file is automatically generated.

package adila.db;

/*
 * LG LBello
 *
 * DEVICE: luv80ss
 * MODEL: LG-D331
 */
final class luv80ss_lg2dd331 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "LBello";
}
