// This file is automatically generated.

package adila.db;

/*
 * LG L Bello
 *
 * DEVICE: luv80ds
 * MODEL: LG-D337
 */
final class luv80ds_lg2dd337 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "L Bello";
}
