// This file is automatically generated.

package adila.db;

/*
 * LG L Bello
 *
 * DEVICE: luv80ds
 * MODEL: LG-D335
 */
final class luv80ds_lg2dd335 {
    public static final String DATA = "LG|L Bello|";
}
