// This file is automatically generated.

package adila.db;

/*
 * LG G Pro Lite
 *
 * DEVICE: luv90ss
 * MODEL: LG-D680
 */
final class luv90ss_lg2dd680 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Pro Lite";
}
