// This file is automatically generated.

package adila.db;

/*
 * LG G Pro Lite
 *
 * DEVICE: luv90ss
 * MODEL: LG-D682
 */
final class luv90ss_lg2dd682 {
    public static final String DATA = "LG|G Pro Lite|";
}
