// This file is automatically generated.

package adila.db;

/*
 * LG G Pro Lite
 *
 * DEVICE: luv90ds
 * MODEL: LG-D686
 */
final class luv90ds_lg2dd686 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Pro Lite";
}
