// This file is automatically generated.

package adila.db;

/*
 * Sharp LCD-LX560A
 *
 * DEVICE: lx560a
 * MODEL: LCD-LX560A
 */
final class lx560a {
    public static final String DATA = "Sharp|LCD-LX560A|";
}
