// This file is automatically generated.

package adila.db;

/*
 * Fujitsu ARROWS M01
 *
 * DEVICE: M01
 * MODEL: M01
 */
final class m01_m01 {
    public static final String MANUFACTURER = "Fujitsu";
    public static final String NAME = "ARROWS M01";
}
