// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: m0ctcduos
 * MODEL: SCH-I939D
 */
final class m0ctcduos {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
