// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: m0skt
 * MODEL: SHW-M440S
 */
final class m0skt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S3";
    public static final String SERIES = "Galaxy S";
}
