// This file is automatically generated.

package adila.db;

/*
 * LG K10
 *
 * DEVICE: m216n
 * MODEL: LG-F670S
 */
final class m216n_lg2df670s {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "K10";
}
