// This file is automatically generated.

package adila.db;

/*
 * LG K10
 *
 * DEVICE: m23g
 * MODEL: LG-K410
 */
final class m23g {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "K10";
}
