// This file is automatically generated.

package adila.db;

/*
 * LG K10 LTE
 *
 * DEVICE: m253
 * MODEL: LG-K430
 */
final class m253 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "K10 LTE";
}
