// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy K Zoom
 *
 * DEVICE: m2a3g
 * MODEL: SM-C111
 */
final class m2a3g_sm2dc111 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy K Zoom";
}
