// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy K Zoom
 *
 * DEVICE: m2altecan
 * MODEL: SM-C115W
 */
final class m2altecan {
    public static final String DATA = "Samsung|Galaxy K Zoom|";
}
