// This file is automatically generated.

package adila.db;

/*
 * Fujitsu M305
 *
 * DEVICE: M305SB
 * MODEL: M305
 */
final class m305sb_m305 {
    public static final String MANUFACTURER = "Fujitsu";
    public static final String NAME = "M305";
}
