// This file is automatically generated.

package adila.db;

/*
 * InFocus M320u
 *
 * DEVICE: M320
 * MODEL: InFocus M320u
 */
final class m320_infocus20m320u {
    public static final String MANUFACTURER = "InFocus";
    public static final String NAME = "M320u";
}
