// This file is automatically generated.

package adila.db;

/*
 * Huawei Honor Box
 *
 * DEVICE: m321
 * MODEL: M321
 */
final class m321 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "Honor Box";
}
