// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: m3
 * MODEL: GT-I9305T
 */
final class m3_gt2di9305t {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
