// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3
 *
 * DEVICE: m3dcm
 * MODEL: GravityQuad
 */
final class m3dcm_gravityquad {
    public static final String DATA = "Samsung|Galaxy S3|Galaxy S";
}
