// This file is automatically generated.

package adila.db;

/*
 * HTC One mini
 *
 * DEVICE: m4
 * MODEL: HTC_PO582
 */
final class m4_htc5fpo582 {
    public static final String DATA = "HTC|One mini|";
}
