// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L5
 *
 * DEVICE: m4
 * MODEL: LG-E610v
 */
final class m4_lg2de610v {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus L5";
}
