// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L5 Dual
 *
 * DEVICE: m4ds
 * MODEL: LG-E615f
 */
final class m4ds_lg2de615f {
    public static final String DATA = "LG|Optimus L5 Dual|";
}
