// This file is automatically generated.

package adila.db;

/*
 * Navon M505
 *
 * DEVICE: M505_4G
 * MODEL: M505_4G
 */
final class m5055f4g_m5055f4g {
    public static final String DATA = "Navon|M505|";
}
