// This file is automatically generated.

package adila.db;

/*
 * Huawei M620
 *
 * DEVICE: M620
 * MODEL: M620
 */
final class m620_m620 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "M620";
}
