// This file is automatically generated.

package adila.db;

/*
 * Anydata Nextbook NX007HD Tablet
 *
 * DEVICE: M7000ND
 * MODEL: NX007HD
 */
final class m7000nd_nx007hd {
    public static final String MANUFACTURER = "Anydata";
    public static final String NAME = "Nextbook NX007HD Tablet";
}
