// This file is automatically generated.

package adila.db;

/*
 * Fujitsu STYLISTIC M702
 *
 * DEVICE: M702
 * MODEL: M702
 */
final class m702_m702 {
    public static final String DATA = "Fujitsu|STYLISTIC M702|";
}
