// This file is automatically generated.

package adila.db;

/*
 * HTC One
 *
 * DEVICE: m7
 * MODEL: HTC_PN071
 */
final class m7_htc5fpn071 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "One";
}
