// This file is automatically generated.

package adila.db;

/*
 * CZ Electronics M7 Sapphire
 *
 * DEVICE: M7
 * MODEL: M7
 */
final class m7_m7 {
    public static final String DATA = "CZ Electronics|M7 Sapphire|";
}
