// This file is automatically generated.

package adila.db;

/*
 * iRiver DMT580D
 *
 * DEVICE: m805_892x
 * MODEL: DMT580D
 */
final class m8055f892x_dmt580d {
    public static final String MANUFACTURER = "iRiver";
    public static final String NAME = "DMT580D";
}
