// This file is automatically generated.

package adila.db;

/*
 * CMCC M811
 *
 * DEVICE: m811hk
 * MODEL: M811
 */
final class m811hk {
    public static final String MANUFACTURER = "CMCC";
    public static final String NAME = "M811";
}
