// This file is automatically generated.

package adila.db;

/*
 * Orange Nura2
 *
 * DEVICE: m823_orange
 * MODEL: Nura 2
 */
final class m8235forange {
    public static final String DATA = "Orange|Nura2|";
}
