// This file is automatically generated.

package adila.db;

/*
 * Haier L50
 *
 * DEVICE: M916-D500-PAK
 * MODEL: L50
 */
final class m9162dd5002dpak_l50 {
    public static final String DATA = "Haier|L50|";
}
