// This file is automatically generated.

package adila.db;

/*
 * Acer A1-811
 *
 * DEVICE: mango
 * MODEL: A1-811
 */
final class mango_a12d811 {
    public static final String DATA = "Acer|A1-811|";
}
