// This file is automatically generated.

package adila.db;

/*
 * Samsung Nexus 10
 *
 * DEVICE: manta
 * MODEL: Nexus 10
 */
final class manta {
    public static final String DATA = "Samsung|Nexus 10|";
}
