// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 992D
 *
 * DEVICE: Martell_lite_GSM
 * MODEL: TCL S600
 */
final class martell5flite5fgsm_tcl20s600 {
    public static final String DATA = "Alcatel|ONE TOUCH 992D|";
}
