// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 997D
 *
 * DEVICE: Martell_GSM
 * MODEL: TCL S800
 */
final class martell5fgsm_tcl20s800 {
    public static final String DATA = "Alcatel|ONE TOUCH 997D|";
}
