// This file is automatically generated.

package adila.db;

/*
 * Pantech PTL21
 *
 * DEVICE: maruko
 * MODEL: PTL21
 */
final class maruko {
    public static final String DATA = "Pantech|PTL21|";
}
