// This file is automatically generated.

package adila.db;

/*
 * HTC Wildfire S A515c
 *
 * DEVICE: marvelc
 * MODEL: HTC Wildfire S A515c
 */
final class marvelc_htc20wildfire20s20a515c {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Wildfire S A515c";
}
