// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 10.1
 *
 * DEVICE: matissewifikx
 * MODEL: SM-T530
 */
final class matissewifikx {
    public static final String DATA = "Samsung|Galaxy Tab 4 10.1|Galaxy Tab";
}
