// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 10.1
 *
 * DEVICE: matissewifiue
 * MODEL: SM-T530NU
 */
final class matissewifiue {
    public static final String DATA = "Samsung|Galaxy Tab 4 10.1|Galaxy Tab";
}
