// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 4 10.1
 *
 * DEVICE: matisse10wifikx
 * MODEL: SM-T536
 */
final class matisse10wifikx {
    public static final String DATA = "Samsung|Galaxy Tab 4 10.1|Galaxy Tab";
}
