// This file is automatically generated.

package adila.db;

/*
 * Pegatron MaxiIQ
 *
 * DEVICE: MaxiIQ
 * MODEL: MaxiIQ
 */
final class maxiiq_maxiiq {
    public static final String DATA = "Pegatron|MaxiIQ|";
}
