// This file is automatically generated.

package adila.db;

/*
 * InFocus M512
 *
 * DEVICE: MC2_CN
 * MODEL: M512
 */
final class mc25fcn_m512 {
    public static final String DATA = "InFocus|M512|";
}
