// This file is automatically generated.

package adila.db;

/*
 * FarEasTone Smart503
 *
 * DEVICE: MC2
 * MODEL: Smart503
 */
final class mc2_smart503 {
    public static final String DATA = "FarEasTone|Smart503|";
}
