// This file is automatically generated.

package adila.db;

/*
 * LG Prime Plus 4G
 *
 * DEVICE: mc90ds
 * MODEL: LG-H522
 */
final class mc90ds {
    public static final String DATA = "LG|Prime Plus 4G|";
}
