// This file is automatically generated.

package adila.db;

/*
 * Lazer Lazer MD1005 Tablet
 *
 * DEVICE: MD1005
 * MODEL: MD1005
 */
final class md1005_md1005 {
    public static final String DATA = "Lazer|Lazer MD1005 Tablet|";
}
