// This file is automatically generated.

package adila.db;

/*
 * AG Mobile AG_Go-Tab_Access
 *
 * DEVICE: md789hwag
 * MODEL: AG Go-Tab Access
 */
final class md789hwag {
    public static final String DATA = "AG Mobile|AG_Go-Tab_Access|";
}
