// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mega Plus
 *
 * DEVICE: megapluslte
 * MODEL: GT-I9158V
 */
final class megapluslte {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Mega Plus";
}
