// This file is automatically generated.

package adila.db;

/*
 * Haier MEGAFON MS3A
 *
 * DEVICE: Megafon
 * MODEL: MS3A
 */
final class megafon_ms3a {
    public static final String MANUFACTURER = "Haier";
    public static final String NAME = "MEGAFON MS3A";
}
