// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 5020N
 *
 * DEVICE: Megane
 * MODEL: ALCATEL ONE TOUCH 5020N
 */
final class megane_alcatel20one20touch205020n {
    public static final String DATA = "Alcatel|ONE TOUCH 5020N|";
}
