// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 5020D
 *
 * DEVICE: Megane_GSM
 * MODEL: ALCATEL_ONE_TOUCH_5020X_Orange
 */
final class megane5fgsm_alcatel5fone5ftouch5f5020x5forange {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 5020D";
}
