// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL J300
 *
 * DEVICE: Megane
 * MODEL: ALCATEL ONE TOUCH 5020T
 */
final class megane_alcatel20one20touch205020t {
    public static final String DATA = "Alcatel|TCL J300|";
}
