// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL J300
 *
 * DEVICE: Megane
 * MODEL: TCL J300
 */
final class megane_tcl20j300 {
    public static final String DATA = "Alcatel|TCL J300|";
}
