// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mega 6.3
 *
 * DEVICE: meliusltespr
 * MODEL: SPH-L600
 */
final class meliusltespr {
    public static final String DATA = "Samsung|Galaxy Mega 6.3|";
}
