// This file is automatically generated.

package adila.db;

/*
 * ZTE Z740G
 *
 * DEVICE: metis
 * MODEL: Z740G
 */
final class metis_z740g {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Z740G";
}
