// This file is automatically generated.

package adila.db;

/*
 * Lexibook LexiTab 7''
 *
 * DEVICE: MFC146FR
 * MODEL: MFC146FR
 */
final class mfc146fr_mfc146fr {
    public static final String DATA = "Lexibook|LexiTab 7''|";
}
