// This file is automatically generated.

package adila.db;

/*
 * JP Sacouto Flag Mill v2
 *
 * DEVICE: MG101A2T_BT_W32
 * MODEL: Flag Mill v2
 */
final class mg101a2t5fbt5fw32_flag20mill20v2 {
    public static final String DATA = "JP Sacouto|Flag Mill v2|";
}
