// This file is automatically generated.

package adila.db;

/*
 * Spice Dream Uno
 *
 * DEVICE: Mi-498_sprout
 * MODEL: Spice Mi-498
 */
final class mi2d4985fsprout_spice20mi2d498 {
    public static final String MANUFACTURER = "Spice";
    public static final String NAME = "Dream Uno";
}
