// This file is automatically generated.

package adila.db;

/*
 * Spice Dream Uno
 *
 * DEVICE: Mi-498_sprout
 * MODEL: Spice Mi-498H
 */
final class mi2d4985fsprout_spice20mi2d498h {
    public static final String DATA = "Spice|Dream Uno|";
}
