// This file is automatically generated.

package adila.db;

/*
 * Foxconn CSL Spice MI700
 *
 * DEVICE: mi700
 * MODEL: Spice_MI700
 */
final class mi700_spice5fmi700 {
    public static final String DATA = "Foxconn|CSL Spice MI700|";
}
