// This file is automatically generated.

package adila.db;

/*
 * Alcatel 6016E
 *
 * DEVICE: Miata_3G
 * MODEL: 6016E
 */
final class miata5f3g_6016e {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "6016E";
}
