// This file is automatically generated.

package adila.db;

/*
 * Micromax CANVAS DOODLE 3
 *
 * DEVICE: MicromaxA102
 * MODEL: Micromax A102
 */
final class micromaxa102_micromax20a102 {
    public static final String DATA = "Micromax|CANVAS DOODLE 3|";
}
