// This file is automatically generated.

package adila.db;

/*
 * Gigabyte PROSCAN PLT1066 / MAG MAGPAD / TEAC TEACTAB / DOPO GS-1008
 *
 * DEVICE: MID1005_K
 * MODEL: PLT1066
 */
final class mid10055fk_plt1066 {
    public static final String DATA = "Gigabyte|PROSCAN PLT1066 / MAG MAGPAD / TEAC TEACTAB / DOPO GS-1008|";
}
