// This file is automatically generated.

package adila.db;

/*
 * Estar GRAND HD Quad Core
 *
 * DEVICE: MID1198
 * MODEL: eSTAR GRAND HD Quad core
 */
final class mid1198_estar20grand20hd20quad20core {
    public static final String DATA = "Estar|GRAND HD Quad Core|";
}
