// This file is automatically generated.

package adila.db;

/*
 * Estar GO! HD Quad core 3G
 *
 * DEVICE: MID7438G
 * MODEL: eSTAR GO HD Quad core 3G
 */
final class mid7438g_estar20go20hd20quad20core203g {
    public static final String DATA = "Estar|GO! HD Quad core 3G|";
}
