// This file is automatically generated.

package adila.db;

/*
 * Lazer MID9526CM
 *
 * DEVICE: MID9526CM
 * MODEL: S952
 */
final class mid9526cm_s952 {
    public static final String MANUFACTURER = "Lazer";
    public static final String NAME = "MID9526CM";
}
