// This file is automatically generated.

package adila.db;

/*
 * GSmart Mika M3
 *
 * DEVICE: Mika_M3
 * MODEL: GSmart Mika M3
 */
final class mika5fm3_gsmart20mika20m3 {
    public static final String MANUFACTURER = "GSmart";
    public static final String NAME = "Mika M3";
}
