// This file is automatically generated.

package adila.db;

/*
 * Positivo Mini I
 *
 * DEVICE: mini_i
 * MODEL: Positivo Mini I
 */
final class mini5fi_positivo20mini20i {
    public static final String DATA = "Positivo|Mini I|";
}
