// This file is automatically generated.

package adila.db;

/*
 * Pantech MIRACH_J
 *
 * DEVICE: mirachj
 * MODEL: IS11PT
 */
final class mirachj_is11pt {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "MIRACH_J";
}
