// This file is automatically generated.

package adila.db;

/*
 * LG K3 LTE
 *
 * DEVICE: mme0n
 * MODEL: LG-K100
 */
final class mme0n {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "K3 LTE";
}
