// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab Pro 8.4
 *
 * DEVICE: mondrianlte
 * MODEL: SM-T325
 */
final class mondrianlte {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab Pro 8.4";
    public static final String SERIES = "Galaxy Tab";
}
