// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab Pro 8.4
 *
 * DEVICE: mondrianwifi
 * MODEL: SM-T320X
 */
final class mondrianwifi_sm2dt320x {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab Pro 8.4";
    public static final String SERIES = "Galaxy Tab";
}
