// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab Pro 8.4
 *
 * DEVICE: mondrianwifikx
 * MODEL: SM-T320
 */
final class mondrianwifikx {
    public static final String DATA = "Samsung|Galaxy Tab Pro 8.4|Galaxy Tab";
}
