// This file is automatically generated.

package adila.db;

/*
 * Pantech Crossover
 *
 * DEVICE: moon
 * MODEL: PantechP8000
 */
final class moon {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "Crossover";
}
