// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: mooncake2
 * MODEL: Mtag 281
 */
final class mooncake2_mtag20281 {
    public static final String DATA = "ZTE||";
}
