// This file is automatically generated.

package adila.db;

/*
 * ZTE Racer
 *
 * DEVICE: mooncake
 * MODEL: MTS-SP100
 */
final class mooncake_mts2dsp100 {
    public static final String DATA = "ZTE|Racer|";
}
