// This file is automatically generated.

package adila.db;

/*
 * ZTE Racer
 *
 * DEVICE: mooncake
 * MODEL: Carl
 */
final class mooncake_carl {
    public static final String DATA = "ZTE|Racer|";
}
