// This file is automatically generated.

package adila.db;

/*
 * ZTE Racer
 *
 * DEVICE: mooncake
 * MODEL: V8402
 */
final class mooncake_v8402 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Racer";
}
