// This file is automatically generated.

package adila.db;

/*
 * Motorola CLIQ
 *
 * DEVICE: morrison
 * MODEL: MB200
 */
final class morrison_mb200 {
    public static final String DATA = "Motorola|CLIQ|";
}
