// This file is automatically generated.

package adila.db;

/*
 * Motorola Backflip
 *
 * DEVICE: motus
 * MODEL: ME600
 */
final class motus_me600 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Backflip";
}
