// This file is automatically generated.

package adila.db;

/*
 * LG G4 Stylus
 *
 * DEVICE: mp1s3gss
 * MODEL: LG-H542
 */
final class mp1s3gss {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G4 Stylus";
}
