// This file is automatically generated.

package adila.db;

/*
 * MPman MPDC706
 *
 * DEVICE: MPDC706
 * MODEL: MPDC706
 */
final class mpdc706_mpdc706 {
    public static final String DATA = "MPman|MPDC706|";
}
