// This file is automatically generated.

package adila.db;

/*
 * MPman MPDC1006
 *
 * DEVICE: MPDC1006
 * MODEL: MPDC1006
 */
final class mpdc1006_mpdc1006 {
    public static final String DATA = "MPman|MPDC1006|";
}
