// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4 Zoom
 *
 * DEVICE: mprojectlteatt
 * MODEL: SAMSUNG-SM-C105A
 */
final class mprojectlteatt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4 Zoom";
    public static final String SERIES = "Galaxy S";
}
