// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand 2
 *
 * DEVICE: ms01lteskt
 * MODEL: SM-G710S
 */
final class ms01lteskt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Grand 2";
}
