// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Grand 2
 *
 * DEVICE: ms01lte
 * MODEL: SM-G7105
 */
final class ms01lte_sm2dg7105 {
    public static final String DATA = "Samsung|Galaxy Grand 2|";
}
