// This file is automatically generated.

package adila.db;

/*
 * Maxcom MS514
 *
 * DEVICE: MS514
 * MODEL: MS514
 */
final class ms514_ms514 {
    public static final String DATA = "Maxcom|MS514|";
}
