// This file is automatically generated.

package adila.db;

/*
 * Trimble Navigation PeopleNet ConnectedTablet
 *
 * DEVICE: MS5
 * MODEL: MS5
 */
final class ms5_ms5 {
    public static final String MANUFACTURER = "Trimble Navigation";
    public static final String NAME = "PeopleNet ConnectedTablet";
}
