// This file is automatically generated.

package adila.db;

/*
 * Hisense LED48K380U
 *
 * DEVICE: msd6a918
 * MODEL: LED48K380U
 */
final class msd6a918_led48k380u {
    public static final String DATA = "Hisense|LED48K380U|";
}
