// This file is automatically generated.

package adila.db;

/*
 * Hisense LED55K380U
 *
 * DEVICE: msd6a918
 * MODEL: LED55K380U
 */
final class msd6a918_led55k380u {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED55K380U";
}
