// This file is automatically generated.

package adila.db;

/*
 * Hisense VIDAA_TV
 *
 * DEVICE: MSD6A938
 * MODEL: VIDAA_TV
 */
final class msd6a938_vidaa5ftv {
    public static final String DATA = "Hisense|VIDAA_TV|";
}
