// This file is automatically generated.

package adila.db;

/*
 * Hisense LED48K681X3DU
 *
 * DEVICE: msd6a918
 * MODEL: LED48K681X3DU
 */
final class msd6a918_led48k681x3du {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED48K681X3DU";
}
