// This file is automatically generated.

package adila.db;

/*
 * Sharp SH8118U
 *
 * DEVICE: msm7627
 * MODEL: SH8118U
 */
final class msm7627_sh8118u {
    public static final String DATA = "Sharp|SH8118U|";
}
