// This file is automatically generated.

package adila.db;

/*
 * Coolpad CP5108
 *
 * DEVICE: msm7627a_a8_5108_new
 * MODEL: Coolpad 5108
 */
final class msm7627a5fa85f51085fnew {
    public static final String DATA = "Coolpad|CP5108|";
}
