// This file is automatically generated.

package adila.db;

/*
 * Huawei 
 *
 * DEVICE: msm7225
 * MODEL: S31HW
 */
final class msm7225_s31hw {
    public static final String MANUFACTURER = "Huawei";
}
