// This file is automatically generated.

package adila.db;

/*
 * Coolpad 
 *
 * DEVICE: msm7627a_PAP4000
 * MODEL: PAP4000
 */
final class msm7627a5fpap4000_pap4000 {
    public static final String DATA = "Coolpad||";
}
