// This file is automatically generated.

package adila.db;

/*
 * Archos 45 Platinum
 *
 * DEVICE: msm8625
 * MODEL: Archos 45 Platinum
 */
final class msm8625_archos204520platinum {
    public static final String DATA = "Archos|45 Platinum|";
}
