// This file is automatically generated.

package adila.db;

/*
 * ZTE Preo Teknosa P1
 *
 * DEVICE: msm8916_32
 * MODEL: Preo Teknosa P1
 */
final class msm89165f32_preo20teknosa20p1 {
    public static final String DATA = "ZTE|Preo Teknosa P1|";
}
