// This file is automatically generated.

package adila.db;

/*
 * Hisense U688BE
 *
 * DEVICE: MSM8212
 * MODEL: HS-U688
 */
final class msm8212_hs2du688 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "U688BE";
}
