// This file is automatically generated.

package adila.db;

/*
 * ZTE TURKCELL T50
 *
 * DEVICE: msm8226
 * MODEL: TURKCELL TURBO T50
 */
final class msm8226_turkcell20turbo20t50 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "TURKCELL T50";
}
