// This file is automatically generated.

package adila.db;

/*
 * ZTE Orange Rono
 *
 * DEVICE: msm8226
 * MODEL: Orange Rono
 */
final class msm8226_orange20rono {
    public static final String DATA = "ZTE|Orange Rono|";
}
