// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade Apex2
 *
 * DEVICE: msm8226
 * MODEL: Blade Apex2
 */
final class msm8226_blade20apex2 {
    public static final String DATA = "ZTE|Blade Apex2|";
}
