// This file is automatically generated.

package adila.db;

/*
 * ZTE Orange Hi 4G
 *
 * DEVICE: msm8226
 * MODEL: Orange Hi 4G
 */
final class msm8226_orange20hi204g {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Orange Hi 4G";
}
