// This file is automatically generated.

package adila.db;

/*
 * Vivo X5MaxV
 *
 * DEVICE: msm8916_32
 * MODEL: vivo X5MaxV
 */
final class msm89165f32_vivo20x5maxv {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "X5MaxV";
}
