// This file is automatically generated.

package adila.db;

/*
 * Archos 50 Platinum
 *
 * DEVICE: msm8625
 * MODEL: Archos 50 Platinum
 */
final class msm8625_archos205020platinum {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "50 Platinum";
}
