// This file is automatically generated.

package adila.db;

/*
 * Archos 53 Platinum
 *
 * DEVICE: msm8625
 * MODEL: Archos 53 Platinum
 */
final class msm8625_archos205320platinum {
    public static final String MANUFACTURER = "Archos";
    public static final String NAME = "53 Platinum";
}
