// This file is automatically generated.

package adila.db;

/*
 * Manta MSP4507
 *
 * DEVICE: MSP4507
 * MODEL: MSP4507
 */
final class msp4507_msp4507 {
    public static final String MANUFACTURER = "Manta";
    public static final String NAME = "MSP4507";
}
