// This file is automatically generated.

package adila.db;

/*
 * Hisense LED65XT900G3DU
 *
 * DEVICE: mst901
 * MODEL: LED65XT900G3DU
 */
final class mst901_led65xt900g3du {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED65XT900G3DU";
}
