// This file is automatically generated.

package adila.db;

/*
 * JVC DM65UXR
 *
 * DEVICE: mstarnapoli_atsc
 * MODEL: DM65UXR
 */
final class mstarnapoli5fatsc {
    public static final String MANUFACTURER = "JVC";
    public static final String NAME = "DM65UXR";
}
