// This file is automatically generated.

package adila.db;

/*
 * Micromax CANVAS BLAZE
 *
 * DEVICE: MT500
 * MODEL: MT500
 */
final class mt500_mt500 {
    public static final String DATA = "Micromax|CANVAS BLAZE|";
}
