// This file is automatically generated.

package adila.db;

/*
 * Hisense LED65XT900X3DU
 *
 * DEVICE: mt5327
 * MODEL: LED65XT900X3DU
 */
final class mt5327_led65xt900x3du {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED65XT900X3DU";
}
