// This file is automatically generated.

package adila.db;

/*
 * Hisense LED58K280U
 *
 * DEVICE: mt5327
 * MODEL: LED58K280U
 */
final class mt5327_led58k280u {
    public static final String DATA = "Hisense|LED58K280U|";
}
