// This file is automatically generated.

package adila.db;

/*
 * Hisense LED85XT910G3DU
 *
 * DEVICE: mt5327
 * MODEL: Vision20
 */
final class mt5327_vision20 {
    public static final String DATA = "Hisense|LED85XT910G3DU|";
}
