// This file is automatically generated.

package adila.db;

/*
 * Hisense LED42L288
 *
 * DEVICE: mt5880
 * MODEL: LED42L288
 */
final class mt5880_led42l288 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "LED42L288";
}
