// This file is automatically generated.

package adila.db;

/*
 * Hisense LED46K280J3D
 *
 * DEVICE: mt5880
 * MODEL: LED46K280J3D
 */
final class mt5880_led46k280j3d {
    public static final String DATA = "Hisense|LED46K280J3D|";
}
