// This file is automatically generated.

package adila.db;

/*
 * Hisense LED55K360X3D
 *
 * DEVICE: mt5880
 * MODEL: Hisense LED55K360X3D
 */
final class mt5880_hisense20led55k360x3d {
    public static final String DATA = "Hisense|LED55K360X3D|";
}
