// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP5047DUO
 *
 * DEVICE: MT6589
 * MODEL: PSP5047DUO
 */
final class mt6589_psp5047duo {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PSP5047DUO";
}
