// This file is automatically generated.

package adila.db;

/*
 * Nabi nabi 2 Tablet
 *
 * DEVICE: mt799
 * MODEL: NABI2-NV7A
 */
final class mt799 {
    public static final String MANUFACTURER = "Nabi";
    public static final String NAME = "nabi 2 Tablet";
}
