// This file is automatically generated.

package adila.db;

/*
 * Memorex MTAB-09541AB
 *
 * DEVICE: MTAB-09541AB
 * MODEL: MTAB-09541AB
 */
final class mtab2d09541ab_mtab2d09541ab {
    public static final String MANUFACTURER = "Memorex";
    public static final String NAME = "MTAB-09541AB";
}
