// This file is automatically generated.

package adila.db;

/*
 * MTC MTC 982
 *
 * DEVICE: MTC_982
 * MODEL: MTC 982
 */
final class mtc5f982_mtc20982 {
    public static final String DATA = "MTC|MTC 982|";
}
