// This file is automatically generated.

package adila.db;

/*
 * MobileTeleSystem MTC SMART Surf 4G
 *
 * DEVICE: MTC_SMART_Surf_4G
 * MODEL: MTC_SMART_Surf_4G
 */
final class mtc5fsmart5fsurf5f4g_mtc5fsmart5fsurf5f4g {
    public static final String MANUFACTURER = "MobileTeleSystem";
    public static final String NAME = "MTC SMART Surf 4G";
}
