// This file is automatically generated.

package adila.db;

/*
 * MTN Group Sm@rt Mini S630
 *
 * DEVICE: MTN-S630
 * MODEL: MTN-S630
 */
final class mtn2ds630_mtn2ds630 {
    public static final String MANUFACTURER = "MTN Group";
    public static final String NAME = "Sm@rt Mini S630";
}
