// This file is automatically generated.

package adila.db;

/*
 * MTN Group Sm@rt L860
 *
 * DEVICE: MTN-L860
 * MODEL: MTN-L860
 */
final class mtn2dl860_mtn2dl860 {
    public static final String MANUFACTURER = "MTN Group";
    public static final String NAME = "Sm@rt L860";
}
