// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Pro
 *
 * DEVICE: muscat
 * MODEL: LG-C660
 */
final class muscat_lg2dc660 {
    public static final String DATA = "LG|Optimus Pro|";
}
