// This file is automatically generated.

package adila.db;

/*
 * Lazer MW6617
 *
 * DEVICE: MW6617
 * MODEL: MW6617
 */
final class mw6617_mw6617 {
    public static final String MANUFACTURER = "Lazer";
    public static final String NAME = "MW6617";
}
