// This file is automatically generated.

package adila.db;

/*
 * Fujitsu STYLISTIC M532
 *
 * DEVICE: mx532
 * MODEL: M532
 */
final class mx532 {
    public static final String DATA = "Fujitsu|STYLISTIC M532|";
}
