// This file is automatically generated.

package adila.db;

/*
 * Lazer Lazer MY1306P
 *
 * DEVICE: MY1306P
 * MODEL: MY1306P
 */
final class my1306p_my1306p {
    public static final String MANUFACTURER = "Lazer";
    public static final String NAME = "Lazer MY1306P";
}
