// This file is automatically generated.

package adila.db;

/*
 * MyPhone My95 DTV
 *
 * DEVICE: MyPhone_my95_DTV
 * MODEL: MyPhone my95 DTV
 */
final class myphone5fmy955fdtv_myphone20my9520dtv {
    public static final String DATA = "MyPhone|My95 DTV|";
}
