// This file is automatically generated.

package adila.db;

/*
 * MyPhone My92 DTV
 *
 * DEVICE: MyPhone_my92_DTV
 * MODEL: MyPhone my92 DTV
 */
final class myphone5fmy925fdtv_myphone20my9220dtv {
    public static final String DATA = "MyPhone|My92 DTV|";
}
