// This file is automatically generated.

package adila.db;

/*
 * NEC MEDIAS X N-07D
 *
 * DEVICE: N-07D
 * MODEL: N-07D
 */
final class n2d07d_n2d07d {
    public static final String DATA = "NEC|MEDIAS X N-07D|";
}
