// This file is automatically generated.

package adila.db;

/*
 * NEC MEDIAS ES N-05D
 *
 * DEVICE: N-05D
 * MODEL: N-05D
 */
final class n2d05d_n2d05d {
    public static final String MANUFACTURER = "NEC";
    public static final String NAME = "MEDIAS ES N-05D";
}
