// This file is automatically generated.

package adila.db;

/*
 * Nuu NUU N5L
 *
 * DEVICE: N5L
 * MODEL: N5L
 */
final class n5l_n5l {
    public static final String MANUFACTURER = "Nuu";
    public static final String NAME = "NUU N5L";
}
