// This file is automatically generated.

package adila.db;

/*
 * ZTE Karbonn_A1
 *
 * DEVICE: N721
 * MODEL: Karbonn_A1
 */
final class n721_karbonn5fa1 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Karbonn_A1";
}
