// This file is automatically generated.

package adila.db;

/*
 * ZTE N918St
 *
 * DEVICE: N918St
 * MODEL: N918St
 */
final class n918st_n918st {
    public static final String DATA = "ZTE|N918St|";
}
