// This file is automatically generated.

package adila.db;

/*
 * ZTE N918St
 *
 * DEVICE: N918St
 * MODEL: ZTE N918St
 */
final class n918st_zte20n918st {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N918St";
}
