// This file is automatically generated.

package adila.db;

/*
 * Nobis NB07
 *
 * DEVICE: NB07
 * MODEL: NB07
 */
final class nb07_nb07 {
    public static final String MANUFACTURER = "Nobis";
    public static final String NAME = "NB07";
}
