// This file is automatically generated.

package adila.db;

/*
 * Nabi Fisher Price Learning Tablet
 *
 * DEVICE: NBFP07PMKG
 * MODEL: NBFP07PMKG
 */
final class nbfp07pmkg_nbfp07pmkg {
    public static final String MANUFACTURER = "Nabi";
    public static final String NAME = "Fisher Price Learning Tablet";
}
