// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Fame
 *
 * DEVICE: nevisvess
 * MODEL: GT-S6790E
 */
final class nevisvess_gt2ds6790e {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Fame";
}
