// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Fame
 *
 * DEVICE: nevis
 * MODEL: GT-S6810E
 */
final class nevis_gt2ds6810e {
    public static final String DATA = "Samsung|Galaxy Fame|";
}
