// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Fame
 *
 * DEVICE: nevis
 * MODEL: GT-S6810L
 */
final class nevis_gt2ds6810l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Fame";
}
