// This file is automatically generated.

package adila.db;

/*
 * ZTE N800
 *
 * DEVICE: nex
 * MODEL: N800
 */
final class nex {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N800";
}
