// This file is automatically generated.

package adila.db;

/*
 * NGM Dynamic Racing 3
 *
 * DEVICE: NGM_Dynamic_Racing_3
 * MODEL: Dynamic Racing 3
 */
final class ngm5fdynamic5fracing5f3_dynamic20racing203 {
    public static final String DATA = "NGM|Dynamic Racing 3|";
}
