// This file is automatically generated.

package adila.db;

/*
 * ZTE Kis Pro
 *
 * DEVICE: nice
 * MODEL: ZTE Kis Pro
 */
final class nice_zte20kis20pro {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Kis Pro";
}
