// This file is automatically generated.

package adila.db;

/*
 * ZTE Cosmote Smart Share
 *
 * DEVICE: nice
 * MODEL: Cosmote Smart Share
 */
final class nice_cosmote20smart20share {
    public static final String DATA = "ZTE|Cosmote Smart Share|";
}
