// This file is automatically generated.

package adila.db;

/*
 * ZTE Kis Pro
 *
 * DEVICE: nice
 * MODEL: Optimus Zali
 */
final class nice_optimus20zali {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Kis Pro";
}
