// This file is automatically generated.

package adila.db;

/*
 * NAXA NID_7010
 *
 * DEVICE: NID_7010
 * MODEL: NID_7010
 */
final class nid5f7010_nid5f7010 {
    public static final String MANUFACTURER = "NAXA";
    public static final String NAME = "NID_7010";
}
