// This file is automatically generated.

package adila.db;

/*
 * Xiaomi Redmi Note 4
 *
 * DEVICE: nikel
 * MODEL: Redmi Note 4
 */
final class nikel {
    public static final String DATA = "Xiaomi|Redmi Note 4|";
}
