// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 5
 *
 * DEVICE: nobleltelra
 * MODEL: SM-N920R6
 */
final class nobleltelra {
    public static final String DATA = "Samsung|Galaxy Note 5|Galaxy Note";
}
