// This file is automatically generated.

package adila.db;

/*
 * Insignia NS-15AT07
 *
 * DEVICE: NS-15AT07
 * MODEL: NS-15AT07
 */
final class ns2d15at07_ns2d15at07 {
    public static final String DATA = "Insignia|NS-15AT07|";
}
