// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH Ultra 960c
 *
 * DEVICE: nTelos
 * MODEL: ONE_TOUCH_960C
 */
final class ntelos_one5ftouch5f960c {
    public static final String DATA = "Alcatel|ONE TOUCH Ultra 960c|";
}
