// This file is automatically generated.

package adila.db;

/*
 * Trio Trio MST711
 *
 * DEVICE: nuclear-MST711
 * MODEL: MST711
 */
final class nuclear2dmst711_mst711 {
    public static final String DATA = "Trio|Trio MST711|";
}
