// This file is automatically generated.

package adila.db;

/*
 * NanoTech Nuvola NP-1
 *
 * DEVICE: nuvola
 * MODEL: Nuvola NP-1
 */
final class nuvola {
    public static final String DATA = "NanoTech|Nuvola NP-1|";
}
