// This file is automatically generated.

package adila.db;

/*
 * ZTE NX403A
 *
 * DEVICE: NX403A
 * MODEL: NX403A
 */
final class nx403a_nx403a {
    public static final String DATA = "ZTE|NX403A|";
}
