// This file is automatically generated.

package adila.db;

/*
 * ZTE NX40X_APT
 *
 * DEVICE: NX40X
 * MODEL: NX40X_APT
 */
final class nx40x_nx40x5fapt {
    public static final String DATA = "ZTE|NX40X_APT|";
}
