// This file is automatically generated.

package adila.db;

/*
 * ZTE NX510J
 *
 * DEVICE: NX510J
 * MODEL: NX510J
 */
final class nx510j_nx510j {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "NX510J";
}
