// This file is automatically generated.

package adila.db;

/*
 * ZTE NX529J
 *
 * DEVICE: NX529J
 * MODEL: NX529J
 */
final class nx529j_nx529j {
    public static final String DATA = "ZTE|NX529J|";
}
