// This file is automatically generated.

package adila.db;

/*
 * ZTE NX523J_V1
 *
 * DEVICE: NX523J_V1
 * MODEL: NX523J_V1
 */
final class nx523j5fv1_nx523j5fv1 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "NX523J_V1";
}
