// This file is automatically generated.

package adila.db;

/*
 * ZTE NX541J
 *
 * DEVICE: NX541J
 * MODEL: NX541J
 */
final class nx541j_nx541j {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "NX541J";
}
