// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy On5
 *
 * DEVICE: o5lte
 * MODEL: SM-G550FY
 */
final class o5lte {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy On5";
}
