// This file is automatically generated.

package adila.db;

/*
 * Technicolor 
 *
 * DEVICE: omap4_WT3
 * MODEL: T-Hub2
 */
final class omap45fwt3_t2dhub2 {
    public static final String MANUFACTURER = "Technicolor";
}
