// This file is automatically generated.

package adila.db;

/*
 * Acer A3-A30
 *
 * DEVICE: omega
 * MODEL: A3-A30
 */
final class omega_a32da30 {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "A3-A30";
}
