// This file is automatically generated.

package adila.db;

/*
 * Acer A3-A30
 *
 * DEVICE: omega
 * MODEL: A3-A30
 */
final class omega_a32da30 {
    public static final String DATA = "Acer|A3-A30|";
}
