// This file is automatically generated.

package adila.db;

/*
 * tecmobile OmnisOne
 *
 * DEVICE: OmnisOne
 * MODEL: Omnis One
 */
final class omnisone_omnis20one {
    public static final String MANUFACTURER = "tecmobile";
    public static final String NAME = "OmnisOne";
}
