// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy On7
 *
 * DEVICE: on7elte
 * MODEL: SM-G600F
 */
final class on7elte {
    public static final String DATA = "Samsung|Galaxy On7|";
}
