// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy On7
 *
 * DEVICE: on7nlteskt
 * MODEL: SM-G600S
 */
final class on7nlteskt {
    public static final String DATA = "Samsung|Galaxy On7|";
}
