// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: one_touch_910_gsm
 * MODEL: ALCATEL_one_touch_910
 */
final class one5ftouch5f9105fgsm {
    public static final String MANUFACTURER = "Alcatel";
}
