// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 903D
 *
 * DEVICE: one_touch_903D_gsm
 * MODEL: ALCATEL ONE TOUCH 903D
 */
final class one5ftouch5f903d5fgsm_alcatel20one20touch20903d {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 903D";
}
