// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH Ultra 960c
 *
 * DEVICE: ONE_TOUCH_960C
 * MODEL: ADR3010
 */
final class one5ftouch5f960c_adr3010 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH Ultra 960c";
}
