// This file is automatically generated.

package adila.db;

/*
 * Alcatel MegaFon_SP-A10
 *
 * DEVICE: one_touch_995_gsm
 * MODEL: MegaFon_SP-A10
 */
final class one5ftouch5f9955fgsm_megafon5fsp2da10 {
    public static final String DATA = "Alcatel|MegaFon_SP-A10|";
}
