// This file is automatically generated.

package adila.db;

/*
 * Alcatel One Touch 990S
 *
 * DEVICE: one_touch_990S_gsm
 * MODEL: ALCATEL_one_touch_990S
 */
final class one5ftouch5f990s5fgsm_alcatel5fone5ftouch5f990s {
    public static final String DATA = "Alcatel|One Touch 990S|";
}
