// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: ONE_TOUCH_983A_gsm
 * MODEL: ALCATEL_one_touch_983A
 */
final class one5ftouch5f983a5fgsm_alcatel5fone5ftouch5f983a {
    public static final String MANUFACTURER = "Alcatel";
}
