// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: one_touch_988_cdma
 * MODEL: USCC_ALCATEL_one_touch_988
 */
final class one5ftouch5f9885fcdma_uscc5falcatel5fone5ftouch5f988 {
    public static final String MANUFACTURER = "Alcatel";
}
