// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 985N
 *
 * DEVICE: one_touch_985N_gsm
 * MODEL: ALCATEL ONE TOUCH 985N
 */
final class one5ftouch5f985n5fgsm_alcatel20one20touch20985n {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 985N";
}
