// This file is automatically generated.

package adila.db;

/*
 * Alcatel One Touch 990
 *
 * DEVICE: one_touch_990_gsm
 * MODEL: Alcatel one touch 990 Orange
 */
final class one5ftouch5f9905fgsm_alcatel20one20touch2099020orange {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "One Touch 990";
}
