// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 983
 *
 * DEVICE: ONE_TOUCH_983_gsm
 * MODEL: VALENCIA
 */
final class one5ftouch5f9835fgsm_valencia {
    public static final String DATA = "Alcatel|ONE TOUCH 983|";
}
