// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 918D
 *
 * DEVICE: one_touch_918D_gsm
 * MODEL: ALCATEL ONE TOUCH 918D
 */
final class one5ftouch5f918d5fgsm_alcatel20one20touch20918d {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 918D";
}
