// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: one_touch_909B_cdma
 * MODEL: USCC_ALCATEL_one_touch_909B
 */
final class one5ftouch5f909b5fcdma_uscc5falcatel5fone5ftouch5f909b {
    public static final String DATA = "Alcatel||";
}
