// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 991
 *
 * DEVICE: ONE_TOUCH_991_gsm
 * MODEL: ALCATEL ONE TOUCH 991
 */
final class one5ftouch5f9915fgsm_alcatel20one20touch20991 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 991";
}
