// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: one_touch_891_gsm
 * MODEL: ALCATEL_one_touch_891
 */
final class one5ftouch5f8915fgsm {
    public static final String DATA = "Alcatel||";
}
