// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: one_touch_908S_gsm
 * MODEL: ALCATEL_one_touch_908S
 */
final class one5ftouch5f908s5fgsm_alcatel5fone5ftouch5f908s {
    public static final String DATA = "Alcatel||";
}
