// This file is automatically generated.

package adila.db;

/*
 * Anydata Insignia NS-13T001 Tablet
 *
 * DEVICE: oracle
 * MODEL: NS-13T001
 */
final class oracle_ns2d13t001 {
    public static final String DATA = "Anydata|Insignia NS-13T001 Tablet|";
}
