// This file is automatically generated.

package adila.db;

/*
 * ZTE Orange Neva 80
 *
 * DEVICE: Orange_Neva_80
 * MODEL: Orange Neva 80
 */
final class orange5fneva5f80_orange20neva2080 {
    public static final String DATA = "ZTE|Orange Neva 80|";
}
