// This file is automatically generated.

package adila.db;

/*
 * Pantech Flex
 *
 * DEVICE: oscar
 * MODEL: PantechP8010
 */
final class oscar {
    public static final String MANUFACTURER = "Pantech";
    public static final String NAME = "Flex";
}
