// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: OT-979
 * MODEL: ALCATEL_one_touch_979_HelloKitty
 */
final class ot2d979_alcatel5fone5ftouch5f9795fhellokitty {
    public static final String DATA = "Alcatel||";
}
