// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad 7.0(Z370KL)
 *
 * DEVICE: P002_1
 * MODEL: P002
 */
final class p0025f1_p002 {
    public static final String DATA = "Asus|ZenPad 7.0(Z370KL)|";
}
