// This file is automatically generated.

package adila.db;

/*
 * Asus Commercial tablet 8'' (R800M)
 *
 * DEVICE: P00A_M
 * MODEL: P00A
 */
final class p00a5fm_p00a {
    public static final String DATA = "Asus|Commercial tablet 8'' (R800M)|";
}
