// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad 10 (Z300M)
 *
 * DEVICE: P00C_1
 * MODEL: P00C
 */
final class p00c5f1_p00c {
    public static final String DATA = "Asus|ZenPad 10 (Z300M)|";
}
