// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad 7.0 (Z370CG)
 *
 * DEVICE: P01V_1
 * MODEL: P01V
 */
final class p01v5f1_p01v {
    public static final String DATA = "Asus|ZenPad 7.0 (Z370CG)|";
}
