// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad C 7.0 (Z170CG)
 *
 * DEVICE: P01Y
 * MODEL: P01Y
 */
final class p01y_p01y {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenPad C 7.0 (Z170CG)";
}
