// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad C 7.0
 *
 * DEVICE: P01Y_S
 * MODEL: P01Y
 */
final class p01y5fs_p01y {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenPad C 7.0";
}
