// This file is automatically generated.

package adila.db;

/*
 * Asus ZenPad 10 (Z300CG)
 *
 * DEVICE: P021_1
 * MODEL: P021
 */
final class p0215f1_p021 {
    public static final String DATA = "Asus|ZenPad 10 (Z300CG)|";
}
