// This file is automatically generated.

package adila.db;

/*
 * Asus Zenpad 8.0 (Z380C)
 *
 * DEVICE: P022_1
 * MODEL: P022
 */
final class p0225f1_p022 {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "Zenpad 8.0 (Z380C)";
}
