// This file is automatically generated.

package adila.db;

/*
 * Polaroid P1000
 *
 * DEVICE: P1000
 * MODEL: P1000
 */
final class p1000_p1000 {
    public static final String MANUFACTURER = "Polaroid";
    public static final String NAME = "P1000";
}
