// This file is automatically generated.

package adila.db;

/*
 * Medion P1050X
 *
 * DEVICE: P1050X
 * MODEL: P1050X
 */
final class p1050x_p1050x {
    public static final String DATA = "Medion|P1050X|";
}
