// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade G Lux
 *
 * DEVICE: P172F10
 * MODEL: ZTE V830W
 */
final class p172f10_zte20v830w {
    public static final String DATA = "ZTE|Blade G Lux|";
}
