// This file is automatically generated.

package adila.db;

/*
 * ZTE V829
 *
 * DEVICE: P172A30
 * MODEL: ZTE V829
 */
final class p172a30_zte20v829 {
    public static final String DATA = "ZTE|V829|";
}
