// This file is automatically generated.

package adila.db;

/*
 * ZTE T520
 *
 * DEVICE: P172A40
 * MODEL: ZTE T520
 */
final class p172a40_zte20t520 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "T520";
}
