// This file is automatically generated.

package adila.db;

/*
 * ZTE G601U
 *
 * DEVICE: P172E02
 * MODEL: ZTE G601U
 */
final class p172e02_zte20g601u {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "G601U";
}
