// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade C340
 *
 * DEVICE: P172R12
 * MODEL: ZTE T220
 */
final class p172r12_zte20t220 {
    public static final String DATA = "ZTE|Blade C340|";
}
