// This file is automatically generated.

package adila.db;

/*
 * ZTE C310
 *
 * DEVICE: P172D04
 * MODEL: ZTE C310
 */
final class p172d04_zte20c310 {
    public static final String DATA = "ZTE|C310|";
}
