// This file is automatically generated.

package adila.db;

/*
 * ZTE V815W
 *
 * DEVICE: P172R10
 * MODEL: Amazing A4S
 */
final class p172r10_amazing20a4s {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V815W";
}
