// This file is automatically generated.

package adila.db;

/*
 * ZTE U879
 *
 * DEVICE: P172T30
 * MODEL: ZTE U879
 */
final class p172t30_zte20u879 {
    public static final String DATA = "ZTE|U879|";
}
