// This file is automatically generated.

package adila.db;

/*
 * ZTE Grand X Quad Lite
 *
 * DEVICE: P188F07
 * MODEL: ZTE Grand X2
 */
final class p188f07_zte20grand20x2 {
    public static final String DATA = "ZTE|Grand X Quad Lite|";
}
