// This file is automatically generated.

package adila.db;

/*
 * ZTE N5S
 *
 * DEVICE: P189F10
 * MODEL: ZTE N5S
 */
final class p189f10_zte20n5s {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N5S";
}
