// This file is automatically generated.

package adila.db;

/*
 * Lenovo P1
 *
 * DEVICE: P1a42
 * MODEL: Lenovo P1a41
 */
final class p1a42_lenovo20p1a41 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "P1";
}
