// This file is automatically generated.

package adila.db;

/*
 * LG G4s
 *
 * DEVICE: p1bds3g
 * MODEL: LG-H734
 */
final class p1bds3g {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G4s";
}
