// This file is automatically generated.

package adila.db;

/*
 * LG G Vista 2
 *
 * DEVICE: p1v
 * MODEL: LG-H740
 */
final class p1v {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Vista 2";
}
