// This file is automatically generated.

package adila.db;

/*
 * LG PRADA 3.0
 *
 * DEVICE: p2
 * MODEL: LG-SU540
 */
final class p2_lg2dsu540 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "PRADA 3.0";
}
