// This file is automatically generated.

package adila.db;

/*
 * Panasonic ELUGA V
 *
 * DEVICE: P-06D
 * MODEL: P-06D
 */
final class p2d06d_p2d06d {
    public static final String DATA = "Panasonic|ELUGA V|";
}
