// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Tabby
 *
 * DEVICE: P469
 * MODEL: P469
 */
final class p469_p469 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Canvas Tabby";
}
