// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1
 *
 * DEVICE: p4noterf
 * MODEL: GT-N8000
 */
final class p4noterf_gt2dn8000 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note 10.1";
    public static final String SERIES = "Galaxy Note";
}
