// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1
 *
 * DEVICE: p4notewifiktt
 * MODEL: SHW-M485W
 */
final class p4notewifiktt {
    public static final String DATA = "Samsung|Galaxy Note 10.1|Galaxy Note";
}
