// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1
 *
 * DEVICE: p4notelteusc
 * MODEL: SCH-I925U
 */
final class p4notelteusc {
    public static final String DATA = "Samsung|Galaxy Note 10.1|Galaxy Note";
}
