// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 10.1
 *
 * DEVICE: p4notewifiany
 * MODEL: SHW-M480W
 */
final class p4notewifiany {
    public static final String DATA = "Samsung|Galaxy Note 10.1|Galaxy Note";
}
