// This file is automatically generated.

package adila.db;

/*
 * Panasonic P51
 *
 * DEVICE: P51
 * MODEL: Panasonic P51
 */
final class p51_panasonic20p51 {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "P51";
}
