// This file is automatically generated.

package adila.db;

/*
 * AllView P5 eMagic
 *
 * DEVICE: P5_eMagic
 * MODEL: P5_eMagic_TM
 */
final class p55femagic_p55femagic5ftm {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "P5 eMagic";
}
