// This file is automatically generated.

package adila.db;

/*
 * ZTE C880
 *
 * DEVICE: P635N32
 * MODEL: ZTE C880
 */
final class p635n32_zte20c880 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "C880";
}
