// This file is automatically generated.

package adila.db;

/*
 * ZTE Q529C
 *
 * DEVICE: P635N33
 * MODEL: ZTE Q529C
 */
final class p635n33_zte20q529c {
    public static final String DATA = "ZTE|Q529C|";
}
