// This file is automatically generated.

package adila.db;

/*
 * ZTE Rook from EE
 *
 * DEVICE: P635E40
 * MODEL: Rook from EE
 */
final class p635e40_rook20from20ee {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Rook from EE";
}
