// This file is automatically generated.

package adila.db;

/*
 * ZTE BV0701
 *
 * DEVICE: P653N11
 * MODEL: ZTE BV0701
 */
final class p653n11_zte20bv0701 {
    public static final String DATA = "ZTE|BV0701|";
}
