// This file is automatically generated.

package adila.db;

/*
 * ZTE BV0710T
 *
 * DEVICE: P655A30
 * MODEL: ZTE BV0710T
 */
final class p655a30_zte20bv0710t {
    public static final String DATA = "ZTE|BV0710T|";
}
