// This file is automatically generated.

package adila.db;

/*
 * AllView P6 Lite
 *
 * DEVICE: P6_lite
 * MODEL: P6_lite
 */
final class p65flite_p65flite {
    public static final String DATA = "AllView|P6 Lite|";
}
