// This file is automatically generated.

package adila.db;

/*
 * Wiko U FEEL
 *
 * DEVICE: P6609BC
 * MODEL: U FEEL
 */
final class p6609bc_u20feel {
    public static final String MANUFACTURER = "Wiko";
    public static final String NAME = "U FEEL";
}
