// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas tab
 *
 * DEVICE: P666
 * MODEL: Micromax P666
 */
final class p666_micromax20p666 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Canvas tab";
}
