// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas tab
 *
 * DEVICE: P680
 * MODEL: MicromaxP680
 */
final class p680_micromaxp680 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Canvas tab";
}
