// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Tab
 *
 * DEVICE: P681
 * MODEL: Micromax P681
 */
final class p681_micromax20p681 {
    public static final String DATA = "Micromax|Canvas Tab|";
}
