// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade Vec
 *
 * DEVICE: P692S20_Q82
 * MODEL: ZTE Geek 2
 */
final class p692s205fq82_zte20geek202 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Blade Vec";
}
