// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: p700
 * MODEL: Lenovo P700
 */
final class p700_lenovo20p700 {
    public static final String DATA = "Lenovo||";
}
