// This file is automatically generated.

package adila.db;

/*
 * Southern Telecom P709/P716
 *
 * DEVICE: P709
 * MODEL: P709/P716
 */
final class p709_p7092fp716 {
    public static final String DATA = "Southern Telecom|P709/P716|";
}
