// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade C312
 *
 * DEVICE: P715A20
 * MODEL: ZTE Blade C312
 */
final class p715a20_zte20blade20c312 {
    public static final String DATA = "ZTE|Blade C312|";
}
