// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: P726VV
 * MODEL: ZTE-U X850
 */
final class p726vv_zte2du20x850 {
    public static final String DATA = "ZTE||";
}
