// This file is automatically generated.

package adila.db;

/*
 * Vodafone VFD 200
 *
 * DEVICE: P731V35
 * MODEL: VFD 200
 */
final class p731v35_vfd20200 {
    public static final String DATA = "Vodafone|VFD 200|";
}
