// This file is automatically generated.

package adila.db;

/*
 * Anydata HKC P776A
 *
 * DEVICE: P776A
 * MODEL: P776A
 */
final class p776a_p776a {
    public static final String DATA = "Anydata|HKC P776A|";
}
