// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade A460
 *
 * DEVICE: P809A20
 * MODEL: A460-T
 */
final class p809a20_a4602dt {
    public static final String DATA = "ZTE|Blade A460|";
}
