// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade A310
 *
 * DEVICE: P809A50
 * MODEL: ZTE BLADE A310
 */
final class p809a50_zte20blade20a310 {
    public static final String DATA = "ZTE|Blade A310|";
}
