// This file is automatically generated.

package adila.db;

/*
 * ZTE V792C
 *
 * DEVICE: P810D01
 * MODEL: ZTE V792C
 */
final class p810d01_zte20v792c {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V792C";
}
