// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade Q Lux
 *
 * DEVICE: P816A12
 * MODEL: ZTE Blade Q Lux
 */
final class p816a12_zte20blade20q20lux {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Blade Q Lux";
}
