// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade S6
 *
 * DEVICE: P839F30
 * MODEL: NOS SLIM
 */
final class p839f30_nos20slim {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Blade S6";
}
