// This file is automatically generated.

package adila.db;

/*
 * ZTE G720T
 *
 * DEVICE: P839T30
 * MODEL: ZTE G720T
 */
final class p839t30_zte20g720t {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "G720T";
}
