// This file is automatically generated.

package adila.db;

/*
 * LG Optimus 3D
 *
 * DEVICE: p920
 * MODEL: LG-P920
 */
final class p920_lg2dp920 {
    public static final String DATA = "LG|Optimus 3D|";
}
