// This file is automatically generated.

package adila.db;

/*
 * LG P990
 *
 * DEVICE: p990_262-02
 * MODEL: LG-P990
 */
final class p9905f2622d02 {
    public static final String DATA = "LG|P990|";
}
