// This file is automatically generated.

package adila.db;

/*
 * LG 
 *
 * DEVICE: p990_505-xxx
 * MODEL: LG-P990
 */
final class p9905f5052dxxx {
    public static final String MANUFACTURER = "LG";
}
