// This file is automatically generated.

package adila.db;

/*
 * Haier PAD712
 *
 * DEVICE: PAD712
 * MODEL: PAD712
 */
final class pad712_pad712 {
    public static final String DATA = "Haier|PAD712|";
}
