// This file is automatically generated.

package adila.db;

/*
 * Asus PadFone
 *
 * DEVICE: PadFone
 * MODEL: PadFone
 */
final class padfone_padfone {
    public static final String DATA = "Asus|PadFone|";
}
