// This file is automatically generated.

package adila.db;

/*
 * Panasonic P-04D
 *
 * DEVICE: pana2_4d
 * MODEL: P-04D
 */
final class pana25f4d {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "P-04D";
}
