// This file is automatically generated.

package adila.db;

/*
 * Lenovo PB2 plus
 *
 * DEVICE: PB2-670M
 * MODEL: Lenovo PB2-670M
 */
final class pb22d670m_lenovo20pb22d670m {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "PB2 plus";
}
