// This file is automatically generated.

package adila.db;

/*
 * Vivo X6A
 *
 * DEVICE: PD1415A
 * MODEL: vivo PD1415A
 */
final class pd1415a_vivo20pd1415a {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "X6A";
}
