// This file is automatically generated.

package adila.db;

/*
 * Vivo PD1419V
 *
 * DEVICE: PD1419V
 * MODEL: vivo Y923
 */
final class pd1419v_vivo20y923 {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "PD1419V";
}
