// This file is automatically generated.

package adila.db;

/*
 * Vivo V3
 *
 * DEVICE: PD1524
 * MODEL: vivo V3
 */
final class pd1524_vivo20v3 {
    public static final String DATA = "Vivo|V3|";
}
