// This file is automatically generated.

package adila.db;

/*
 * Vivo Xplay5A
 *
 * DEVICE: PD1522A
 * MODEL: vivo PD1522A
 */
final class pd1522a_vivo20pd1522a {
    public static final String DATA = "Vivo|Xplay5A|";
}
