// This file is automatically generated.

package adila.db;

/*
 * Vivo X6Plus A
 *
 * DEVICE: PD1515A
 * MODEL: vivo PD1515A
 */
final class pd1515a_vivo20pd1515a {
    public static final String DATA = "Vivo|X6Plus A|";
}
