// This file is automatically generated.

package adila.db;

/*
 * Condor PGN404
 *
 * DEVICE: PGN404
 * MODEL: PGN404
 */
final class pgn404_pgn404 {
    public static final String MANUFACTURER = "Condor";
    public static final String NAME = "PGN404";
}
