// This file is automatically generated.

package adila.db;

/*
 * Condor PGN409
 *
 * DEVICE: PGN409
 * MODEL: PGN409
 */
final class pgn409_pgn409 {
    public static final String MANUFACTURER = "Condor";
    public static final String NAME = "PGN409";
}
