// This file is automatically generated.

package adila.db;

/*
 * Condor PGN516
 *
 * DEVICE: PGN516
 * MODEL: PGN516
 */
final class pgn516_pgn516 {
    public static final String MANUFACTURER = "Condor";
    public static final String NAME = "PGN516";
}
