// This file is automatically generated.

package adila.db;

/*
 * LG Stylus 2
 *
 * DEVICE: ph1
 * MODEL: LG-F720K
 */
final class ph1_lg2df720k {
    public static final String DATA = "LG|Stylus 2|";
}
