// This file is automatically generated.

package adila.db;

/*
 * LG Stylus 2
 *
 * DEVICE: ph1
 * MODEL: LG-F720S
 */
final class ph1_lg2df720s {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Stylus 2";
}
