// This file is automatically generated.

package adila.db;

/*
 * LG Stylus2 Plus
 *
 * DEVICE: ph2n
 * MODEL: LGMS550
 */
final class ph2n_lgms550 {
    public static final String DATA = "LG|Stylus2 Plus|";
}
