// This file is automatically generated.

package adila.db;

/*
 * LG Stylus2 Plus
 *
 * DEVICE: ph2n
 * MODEL: LG-K535
 */
final class ph2n_lg2dk535 {
    public static final String DATA = "LG|Stylus2 Plus|";
}
