// This file is automatically generated.

package adila.db;

/*
 * Tecno Phantom6 plus
 *
 * DEVICE: Phantom6-Plus
 * MODEL: Phantom6-Plus
 */
final class phantom62dplus_phantom62dplus {
    public static final String DATA = "Tecno|Phantom6 plus|";
}
