// This file is automatically generated.

package adila.db;

/*
 * Philips Philips S309
 *
 * DEVICE: Philips
 * MODEL: Philips S309
 */
final class philips_philips20s309 {
    public static final String MANUFACTURER = "Philips";
    public static final String NAME = "Philips S309";
}
