// This file is automatically generated.

package adila.db;

/*
 * Philips Philips_W3500
 *
 * DEVICE: Philips_W3500
 * MODEL: Philips_W3500
 */
final class philips5fw3500_philips5fw3500 {
    public static final String MANUFACTURER = "Philips";
    public static final String NAME = "Philips_W3500";
}
