// This file is automatically generated.

package adila.db;

/*
 * Samsung SM-G9198
 *
 * DEVICE: philippeltechn
 * MODEL: SM-G9198
 */
final class philippeltechn {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "SM-G9198";
}
