// This file is automatically generated.

package adila.db;

/*
 * Philips W3568
 *
 * DEVICE: Philips_W3568
 * MODEL: Philips W3568
 */
final class philips5fw3568_philips20w3568 {
    public static final String MANUFACTURER = "Philips";
    public static final String NAME = "W3568";
}
