// This file is automatically generated.

package adila.db;

/*
 * Philips Philips Android 2014
 *
 * DEVICE: philipstv
 * MODEL: AND1E
 */
final class philipstv {
    public static final String DATA = "Philips|Philips Android 2014|";
}
