// This file is automatically generated.

package adila.db;

/*
 * TG&Co. TG-L800S
 *
 * DEVICE: PHX
 * MODEL: TG-L800S
 */
final class phx_tg2dl800s {
    public static final String DATA = "TG&Co.|TG-L800S|";
}
