// This file is automatically generated.

package adila.db;

/*
 * Philips PI3900/58
 *
 * DEVICE: PI3900_58
 * MODEL: PI3900
 */
final class pi39005f58_pi3900 {
    public static final String DATA = "Philips|PI3900/58|";
}
