// This file is automatically generated.

package adila.db;

/*
 * Philips PI7100/93
 *
 * DEVICE: PI7100_93
 * MODEL: PI7100_93
 */
final class pi71005f93_pi71005f93 {
    public static final String DATA = "Philips|PI7100/93|";
}
