// This file is automatically generated.

package adila.db;

/*
 * Lava Pixel V1
 *
 * DEVICE: PixelV1_sprout
 * MODEL: PixelV1
 */
final class pixelv15fsprout_pixelv1 {
    public static final String MANUFACTURER = "Lava";
    public static final String NAME = "Pixel V1";
}
