// This file is automatically generated.

package adila.db;

/*
 * Alcatel 8063
 *
 * DEVICE: Pixi4-7_WIFI
 * MODEL: 8063
 */
final class pixi42d75fwifi_8063 {
    public static final String DATA = "Alcatel|8063|";
}
