// This file is automatically generated.

package adila.db;

/*
 * KD Interactive C15100m
 *
 * DEVICE: Pixi3-7_KD
 * MODEL: C15100m
 */
final class pixi32d75fkd_c15100m {
    public static final String DATA = "KD Interactive|C15100m|";
}
