// This file is automatically generated.

package adila.db;

/*
 * Alcatel PIXI 4 (5)
 *
 * DEVICE: Pixi4-5
 * MODEL: 5010S
 */
final class pixi42d5_5010s {
    public static final String DATA = "Alcatel|PIXI 4 (5)|";
}
