// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH POP 3 (5)
 *
 * DEVICE: PIXI3-5
 * MODEL: 5016J
 */
final class pixi32d5_5016j {
    public static final String DATA = "Alcatel|ONETOUCH POP 3 (5)|";
}
