// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH POP 3 (5.5)
 *
 * DEVICE: PIXI3-55
 * MODEL: 5025E
 */
final class pixi32d55_5025e {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONETOUCH POP 3 (5.5)";
}
