// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5023F
 *
 * DEVICE: Pixi4PlusPower
 * MODEL: 5023F
 */
final class pixi4pluspower_5023f {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5023F";
}
