// This file is automatically generated.

package adila.db;

/*
 * Alcatel 8070
 *
 * DEVICE: Pixi3-8_WIFI
 * MODEL: 8070
 */
final class pixi32d85fwifi_8070 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "8070";
}
