// This file is automatically generated.

package adila.db;

/*
 * Alcatel 9007X
 *
 * DEVICE: Pixi3-7_4G_EE
 * MODEL: 9007X
 */
final class pixi32d75f4g5fee_9007x {
    public static final String DATA = "Alcatel|9007X|";
}
