// This file is automatically generated.

package adila.db;

/*
 * Alcatel PIXI 4 (5)
 *
 * DEVICE: PIXI4_5_4G
 * MODEL: 5045A
 */
final class pixi45f55f4g_5045a {
    public static final String DATA = "Alcatel|PIXI 4 (5)|";
}
