// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH POP 3 (5)
 *
 * DEVICE: PIXI3-5
 * MODEL: 5015X
 */
final class pixi32d5_5015x {
    public static final String DATA = "Alcatel|ONETOUCH POP 3 (5)|";
}
