// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH PIXI 4 (4)
 *
 * DEVICE: Pixi4-4
 * MODEL: 4034F
 */
final class pixi42d4_4034f {
    public static final String DATA = "Alcatel|ONETOUCH PIXI 4 (4)|";
}
