// This file is automatically generated.

package adila.db;

/*
 * Alcatel 9001D
 *
 * DEVICE: Pixi4-6_4G
 * MODEL: 9001D
 */
final class pixi42d65f4g_9001d {
    public static final String DATA = "Alcatel|9001D|";
}
