// This file is automatically generated.

package adila.db;

/*
 * Alcatel 8050E
 *
 * DEVICE: Pixi4-6_3G
 * MODEL: T600M
 */
final class pixi42d65f3g_t600m {
    public static final String DATA = "Alcatel|8050E|";
}
