// This file is automatically generated.

package adila.db;

/*
 * Alcatel 9003X
 *
 * DEVICE: Pixi4-7_3G
 * MODEL: 9003X
 */
final class pixi42d75f3g_9003x {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "9003X";
}
