// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE_TOUCH_4027A
 *
 * DEVICE: Pixi3-45
 * MODEL: ALCATEL ONE TOUCH 4027A
 */
final class pixi32d45_alcatel20one20touch204027a {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE_TOUCH_4027A";
}
