// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5098O
 *
 * DEVICE: Pixi4-6_4G_CKT
 * MODEL: Alcatel_5098O
 */
final class pixi42d65f4g5fckt_alcatel5f5098o {
    public static final String DATA = "Alcatel|5098O|";
}
