// This file is automatically generated.

package adila.db;

/*
 * Proscan PLT1065G
 *
 * DEVICE: PLT1065G
 * MODEL: PLT1065G
 */
final class plt1065g_plt1065g {
    public static final String DATA = "Proscan|PLT1065G|";
}
