// This file is automatically generated.

package adila.db;

/*
 * Proscan PLT7602G
 *
 * DEVICE: PLT7602G
 * MODEL: PLT7602G
 */
final class plt7602g_plt7602g {
    public static final String MANUFACTURER = "Proscan";
    public static final String NAME = "PLT7602G";
}
