// This file is automatically generated.

package adila.db;

/*
 * Proscan PLT9609G
 *
 * DEVICE: PLT9609G
 * MODEL: PLT9609G
 */
final class plt9609g_plt9609g {
    public static final String MANUFACTURER = "Proscan";
    public static final String NAME = "PLT9609G";
}
