// This file is automatically generated.

package adila.db;

/*
 * Proscan PLT9649G
 *
 * DEVICE: PLT9649G
 * MODEL: PLT9649G
 */
final class plt9649g_plt9649g {
    public static final String MANUFACTURER = "Proscan";
    public static final String NAME = "PLT9649G";
}
