// This file is automatically generated.

package adila.db;

/*
 * ZTE U988S
 *
 * DEVICE: pluto
 * MODEL: ZTE U988S
 */
final class pluto {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "U988S";
}
