// This file is automatically generated.

package adila.db;

/*
 * Prestigio PGPS7795
 *
 * DEVICE: PMT3057_3G
 * MODEL: PGPS7795
 */
final class pmt30575f3g_pgps7795 {
    public static final String DATA = "Prestigio|PGPS7795|";
}
