// This file is automatically generated.

package adila.db;

/*
 * Prestigio MultiPad Wize 3018
 *
 * DEVICE: PMT3018_WI
 * MODEL: PMT3018_WI
 */
final class pmt30185fwi_pmt30185fwi {
    public static final String DATA = "Prestigio|MultiPad Wize 3018|";
}
