// This file is automatically generated.

package adila.db;

/*
 * Prestigio MultiPad Wize 3017
 *
 * DEVICE: PMT3017_WI
 * MODEL: PMT3017_WI
 */
final class pmt30175fwi_pmt30175fwi {
    public static final String DATA = "Prestigio|MultiPad Wize 3017|";
}
