// This file is automatically generated.

package adila.db;

/*
 * Prestigio PMT3008_Wi
 *
 * DEVICE: PMT3008_Wi_C
 * MODEL: PMT3008_Wi_C
 */
final class pmt30085fwi5fc_pmt30085fwi5fc {
    public static final String DATA = "Prestigio|PMT3008_Wi|";
}
