// This file is automatically generated.

package adila.db;

/*
 * Prestigio PMT5001_3G
 *
 * DEVICE: PMT5001_3G
 * MODEL: PMT5001_3G
 */
final class pmt50015f3g_pmt50015f3g {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PMT5001_3G";
}
