// This file is automatically generated.

package adila.db;

/*
 * Prestigio PMT5008_3G
 *
 * DEVICE: PMT5008_3G
 * MODEL: PMT5008_3G
 */
final class pmt50085f3g_pmt50085f3g {
    public static final String DATA = "Prestigio|PMT5008_3G|";
}
