// This file is automatically generated.

package adila.db;

/*
 * Prestigio PMT7177_3G
 *
 * DEVICE: PMT7177_3G
 * MODEL: PMT7177_3G
 */
final class pmt71775f3g_pmt71775f3g {
    public static final String DATA = "Prestigio|PMT7177_3G|";
}
