// This file is automatically generated.

package adila.db;

/*
 * Prestigio PMT7287_3G
 *
 * DEVICE: PMT7287_3G
 * MODEL: PMT7287_3G
 */
final class pmt72875f3g_pmt72875f3g {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PMT7287_3G";
}
