// This file is automatically generated.

package adila.db;

/*
 * Haier PNDPP410GP
 *
 * DEVICE: PNDPP410GP
 * MODEL: PNDPP410GP
 */
final class pndpp410gp_pndpp410gp {
    public static final String DATA = "Haier|PNDPP410GP|";
}
