// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Pocket 2
 *
 * DEVICE: pocket2ss3g
 * MODEL: SM-G110H
 */
final class pocket2ss3g {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Pocket 2";
}
