// This file is automatically generated.

package adila.db;

/*
 * Polaroid PRO5044PEE01
 *
 * DEVICE: Polaroid_PRO5044PEE01
 * MODEL: PRO5044PEE01
 */
final class polaroid5fpro5044pee01_pro5044pee01 {
    public static final String DATA = "Polaroid|PRO5044PEE01|";
}
