// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5065W
 *
 * DEVICE: Pop35
 * MODEL: 5065W
 */
final class pop35_5065w {
    public static final String DATA = "Alcatel|5065W|";
}
