// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5054O
 *
 * DEVICE: Pop355
 * MODEL: Alcatel_5054O
 */
final class pop355_alcatel5f5054o {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5054O";
}
