// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5065D
 *
 * DEVICE: Pop35
 * MODEL: 5065D
 */
final class pop35_5065d {
    public static final String DATA = "Alcatel|5065D|";
}
