// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5054W
 *
 * DEVICE: Pop355
 * MODEL: 5054W
 */
final class pop355_5054w {
    public static final String DATA = "Alcatel|5054W|";
}
