// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5051A
 *
 * DEVICE: POP45
 * MODEL: 5051A
 */
final class pop45_5051a {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5051A";
}
