// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5051X
 *
 * DEVICE: POP45
 * MODEL: 5051X
 */
final class pop45_5051x {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5051X";
}
