// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5056D
 *
 * DEVICE: POP455C
 * MODEL: 5056D
 */
final class pop455c_5056d {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5056D";
}
