// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5056X
 *
 * DEVICE: POP455C
 * MODEL: 5056X
 */
final class pop455c_5056x {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "5056X";
}
