// This file is automatically generated.

package adila.db;

/*
 * Alcatel 5056A
 *
 * DEVICE: POP455C
 * MODEL: 5056A
 */
final class pop455c_5056a {
    public static final String DATA = "Alcatel|5056A|";
}
