// This file is automatically generated.

package adila.db;

/*
 * Alcatel A570BL
 *
 * DEVICE: Pop445
 * MODEL: A570BL
 */
final class pop445_a570bl {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "A570BL";
}
