// This file is automatically generated.

package adila.db;

/*
 * Alcatel 9030G
 *
 * DEVICE: POP4-10_4G
 * MODEL: 9030G
 */
final class pop42d105f4g_9030g {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "9030G";
}
