// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONETOUCH P310A
 *
 * DEVICE: POP7
 * MODEL: ALCATEL ONETOUCH P310A
 */
final class pop7_alcatel20onetouch20p310a {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONETOUCH P310A";
}
