// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE_TOUCH_P320X
 *
 * DEVICE: POP8
 * MODEL: ALCATEL ONE TOUCH P320X
 */
final class pop8_alcatel20one20touch20p320x {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE_TOUCH_P320X";
}
