// This file is automatically generated.

package adila.db;

/*
 * Fly Fly
 *
 * DEVICE: porridgek3
 * MODEL: Wileyfox Spark X
 */
final class porridgek3 {
    public static final String DATA = "Fly|Fly|";
}
