// This file is automatically generated.

package adila.db;

/*
 * HighScreen Power Four
 *
 * DEVICE: PowerFour
 * MODEL: PowerFour
 */
final class powerfour_powerfour {
    public static final String DATA = "HighScreen|Power Four|";
}
