// This file is automatically generated.

package adila.db;

/*
 * LG V10
 *
 * DEVICE: pplus
 * MODEL: LG-H900PR
 */
final class pplus_lg2dh900pr {
    public static final String DATA = "LG|V10|";
}
