// This file is automatically generated.

package adila.db;

/*
 * LG V10
 *
 * DEVICE: pplus
 * MODEL: LG-F600K
 */
final class pplus_lg2df600k {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "V10";
}
