// This file is automatically generated.

package adila.db;

/*
 * LG V10
 *
 * DEVICE: pplus
 * MODEL: LG-H901
 */
final class pplus_lg2dh901 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "V10";
}
