// This file is automatically generated.

package adila.db;

/*
 * LG V10
 *
 * DEVICE: pplus
 * MODEL: VS990
 */
final class pplus_vs990 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "V10";
}
