// This file is automatically generated.

package adila.db;

/*
 * Polaroid P7/Q7/PTAB740/PTAB741
 *
 * DEVICE: pq7-Polaroid
 * MODEL: P7/Q7/PTAB740/PTAB741
 */
final class pq72dpolaroid_p72fq72fptab7402fptab741 {
    public static final String DATA = "Polaroid|P7/Q7/PTAB740/PTAB741|";
}
