// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Rush
 *
 * DEVICE: prevail2spr
 * MODEL: SPH-M830
 */
final class prevail2spr {
    public static final String DATA = "Samsung|Galaxy Rush|";
}
