// This file is automatically generated.

package adila.db;

/*
 * Philips W8555
 *
 * DEVICE: Pride
 * MODEL: Philips W8555
 */
final class pride_philips20w8555 {
    public static final String MANUFACTURER = "Philips";
    public static final String NAME = "W8555";
}
