// This file is automatically generated.

package adila.db;

/*
 * Konrow Primo
 *
 * DEVICE: PRIMO
 * MODEL: PRIMO
 */
final class primo_primo {
    public static final String DATA = "Konrow|Primo|";
}
