// This file is automatically generated.

package adila.db;

/*
 * HTC Desire V
 *
 * DEVICE: primods
 * MODEL: HTC Desire Q
 */
final class primods_htc20desire20q {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire V";
}
