// This file is automatically generated.

package adila.db;

/*
 * HTC Desire V
 *
 * DEVICE: primods
 * MODEL: HTC T328w
 */
final class primods_htc20t328w {
    public static final String DATA = "HTC|Desire V|";
}
