// This file is automatically generated.

package adila.db;

/*
 * Walton Primo NX4 mini
 *
 * DEVICE: Primo_NX4_mini
 * MODEL: Primo NX4 mini
 */
final class primo5fnx45fmini_primo20nx420mini {
    public static final String MANUFACTURER = "Walton";
    public static final String NAME = "Primo NX4 mini";
}
