// This file is automatically generated.

package adila.db;

/*
 * Explay Discovery
 *
 * DEVICE: Prime
 * MODEL: Discovery
 */
final class prime_discovery {
    public static final String MANUFACTURER = "Explay";
    public static final String NAME = "Discovery";
}
