// This file is automatically generated.

package adila.db;

/*
 * Prestige Prestige PRO10D
 *
 * DEVICE: PRO10D
 * MODEL: PRO10D
 */
final class pro10d_pro10d {
    public static final String DATA = "Prestige|Prestige PRO10D|";
}
