// This file is automatically generated.

package adila.db;

/*
 * Cellon iris pro 30
 *
 * DEVICE: pro30
 * MODEL: iris pro 30
 */
final class pro30 {
    public static final String DATA = "Cellon|iris pro 30|";
}
