// This file is automatically generated.

package adila.db;

/*
 * Polaroid PRO5043
 *
 * DEVICE: PRO5043
 * MODEL: PRO5043
 */
final class pro5043_pro5043 {
    public static final String DATA = "Polaroid|PRO5043|";
}
