// This file is automatically generated.

package adila.db;

/*
 * Prestige PRO7DS
 *
 * DEVICE: PRO7DS
 * MODEL: PRO7DS
 */
final class pro7ds_pro7ds {
    public static final String DATA = "Prestige|PRO7DS|";
}
