// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3505DUO
 *
 * DEVICE: PSP3503DUO
 * MODEL: PSP3505DUO
 */
final class psp3503duo_psp3505duo {
    public static final String DATA = "Prestigio|PSP3505DUO|";
}
