// This file is automatically generated.

package adila.db;

/*
 * Prestigio Muze A3
 *
 * DEVICE: PSP3452DUO
 * MODEL: PSP3452DUO
 */
final class psp3452duo_psp3452duo {
    public static final String DATA = "Prestigio|Muze A3|";
}
