// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3404DUO
 *
 * DEVICE: PSP3404DUO
 * MODEL: PSP3404DUO
 */
final class psp3404duo_psp3404duo {
    public static final String DATA = "Prestigio|PSP3404DUO|";
}
