// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3456DUO
 *
 * DEVICE: PSP3456DUO
 * MODEL: PSP3456DUO
 */
final class psp3456duo_psp3456duo {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PSP3456DUO";
}
