// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP5307DUO
 *
 * DEVICE: PSP5307DUO
 * MODEL: PSP5307DUO
 */
final class psp5307duo_psp5307duo {
    public static final String DATA = "Prestigio|PSP5307DUO|";
}
