// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP5550DUO
 *
 * DEVICE: PSP5550DUO
 * MODEL: PSP5550DUO
 */
final class psp5550duo_psp5550duo {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PSP5550DUO";
}
