// This file is automatically generated.

package adila.db;

/*
 * HTC Sensation 4G
 *
 * DEVICE: pyramid
 * MODEL: HTC Sensation Z710e
 */
final class pyramid_htc20sensation20z710e {
    public static final String DATA = "HTC|Sensation 4G|";
}
