// This file is automatically generated.

package adila.db;

/*
 * HTC Sensation 4G
 *
 * DEVICE: pyramid
 * MODEL: HTC-Z710a
 */
final class pyramid_htc2dz710a {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Sensation 4G";
}
