// This file is automatically generated.

package adila.db;

/*
 * essentielb Pyxis
 *
 * DEVICE: pyxis_boulanger
 * MODEL: Essentielb-Pixis
 */
final class pyxis5fboulanger {
    public static final String DATA = "essentielb|Pyxis|";
}
