// This file is automatically generated.

package adila.db;

/*
 * Positivo Quantum Go
 *
 * DEVICE: Q2
 * MODEL: Quantum Go
 */
final class q2_quantum20go {
    public static final String DATA = "Positivo|Quantum Go|";
}
