// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: Q303
 * MODEL: Micromax Q303
 */
final class q303_micromax20q303 {
    public static final String DATA = "Micromax|Bolt|";
}
