// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: Q335
 * MODEL: Micromax Q335
 */
final class q335_micromax20q335 {
    public static final String DATA = "Micromax|Bolt|";
}
