// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: Q336
 * MODEL: Micromax Q336
 */
final class q336_micromax20q336 {
    public static final String DATA = "Micromax|Bolt|";
}
