// This file is automatically generated.

package adila.db;

/*
 * Micromax Bolt
 *
 * DEVICE: Q346
 * MODEL: Micromax Q346
 */
final class q346_micromax20q346 {
    public static final String DATA = "Micromax|Bolt|";
}
