// This file is automatically generated.

package adila.db;

/*
 * Micromax Selfie 3
 *
 * DEVICE: Q348
 * MODEL: Micromax Q348
 */
final class q348_micromax20q348 {
    public static final String MANUFACTURER = "Micromax";
    public static final String NAME = "Selfie 3";
}
