// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Selfie 4
 *
 * DEVICE: Q349
 * MODEL: Micromax Q349
 */
final class q349_micromax20q349 {
    public static final String DATA = "Micromax|Canvas Selfie 4|";
}
