// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Spark 2 Plus
 *
 * DEVICE: Q350
 * MODEL: Micromax Q350
 */
final class q350_micromax20q350 {
    public static final String DATA = "Micromax|Canvas Spark 2 Plus|";
}
