// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Spark 3
 *
 * DEVICE: Q385
 * MODEL: Micromax Q385
 */
final class q385_micromax20q385 {
    public static final String DATA = "Micromax|Canvas Spark 3|";
}
