// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Juice3
 *
 * DEVICE: Q392
 * MODEL: Micromax Q392
 */
final class q392_micromax20q392 {
    public static final String DATA = "Micromax|Canvas Juice3|";
}
