// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Pace MIni
 *
 * DEVICE: Q401
 * MODEL: Micromax Q401
 */
final class q401_micromax20q401 {
    public static final String DATA = "Micromax|Canvas Pace MIni|";
}
