// This file is automatically generated.

package adila.db;

/*
 * Micromax Canvas Play 4G
 *
 * DEVICE: Q412
 * MODEL: Micromax Q412
 */
final class q412_micromax20q412 {
    public static final String DATA = "Micromax|Canvas Play 4G|";
}
