// This file is automatically generated.

package adila.db;

/*
 * Positivo Quantum MUV PRO
 *
 * DEVICE: Q5
 * MODEL: Quantum MUV PRO
 */
final class q5_quantum20muv20pro {
    public static final String DATA = "Positivo|Quantum MUV PRO|";
}
