// This file is automatically generated.

package adila.db;

/*
 * Auchan Q5S55IN4G
 *
 * DEVICE: Q5S55IN4G
 * MODEL: Q5S55IN4G
 */
final class q5s55in4g_q5s55in4g {
    public static final String MANUFACTURER = "Auchan";
    public static final String NAME = "Q5S55IN4G";
}
