// This file is automatically generated.

package adila.db;

/*
 * Auchan Q6T7IN
 *
 * DEVICE: Q6T7IN
 * MODEL: Q6T7IN
 */
final class q6t7in_q6t7in {
    public static final String DATA = "Auchan|Q6T7IN|";
}
