// This file is automatically generated.

package adila.db;

/*
 * Positivo Quantum FLY
 *
 * DEVICE: Q7
 * MODEL: Quantum Fly
 */
final class q7_quantum20fly {
    public static final String DATA = "Positivo|Quantum FLY|";
}
