// This file is automatically generated.

package adila.db;

/*
 * ZTE Movistar Express
 *
 * DEVICE: QB7211
 * MODEL: Movistar Express
 */
final class qb7211_movistar20express {
    public static final String DATA = "ZTE|Movistar Express|";
}
