// This file is automatically generated.

package adila.db;

/*
 * Motorola Atrix HD
 *
 * DEVICE: qinara
 * MODEL: MB886
 */
final class qinara {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Atrix HD";
}
