// This file is automatically generated.

package adila.db;

/*
 * QMobile S6 PLUS
 *
 * DEVICE: QMobile_S6_PLUS
 * MODEL: QMobile S6 PLUS
 */
final class qmobile5fs65fplus_qmobile20s620plus {
    public static final String DATA = "QMobile|S6 PLUS|";
}
