// This file is automatically generated.

package adila.db;

/*
 * QMobile LT680
 *
 * DEVICE: QMobile_LT680
 * MODEL: LT680
 */
final class qmobile5flt680_lt680 {
    public static final String DATA = "QMobile|LT680|";
}
