// This file is automatically generated.

package adila.db;

/*
 * Verizon Wireless Ellipsis 7
 *
 * DEVICE: QMV7A
 * MODEL: QMV7B
 */
final class qmv7a_qmv7b {
    public static final String MANUFACTURER = "Verizon Wireless";
    public static final String NAME = "Ellipsis 7";
}
