// This file is automatically generated.

package adila.db;

/*
 * Techno H7S
 *
 * DEVICE: qp16_tecno_h7s
 * MODEL: H7S
 */
final class qp165ftecno5fh7s {
    public static final String DATA = "Techno|H7S|";
}
