// This file is automatically generated.

package adila.db;

/*
 * Dell 
 *
 * DEVICE: qsd8250_surf
 * MODEL: Dell Streak
 */
final class qsd82505fsurf_dell20streak {
    public static final String DATA = "Dell||";
}
