// This file is automatically generated.

package adila.db;

/*
 * Oppo R1001
 *
 * DEVICE: R1001
 * MODEL: R1001
 */
final class r1001_r1001 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R1001";
}
