// This file is automatically generated.

package adila.db;

/*
 * Oppo R7005
 *
 * DEVICE: R3
 * MODEL: R7005
 */
final class r3_r7005 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R7005";
}
