// This file is automatically generated.

package adila.db;

/*
 * Oppo R7
 *
 * DEVICE: R7
 * MODEL: OPPO R7
 */
final class r7_oppo20r7 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R7";
}
