// This file is automatically generated.

package adila.db;

/*
 * Oppo R7 Lite
 *
 * DEVICE: R7f
 * MODEL: R7kf
 */
final class r7f_r7kf {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R7 Lite";
}
