// This file is automatically generated.

package adila.db;

/*
 * Oppo R7Plust
 *
 * DEVICE: R7Plus
 * MODEL: R7Plust
 */
final class r7plus_r7plust {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R7Plust";
}
