// This file is automatically generated.

package adila.db;

/*
 * Oppo R7s
 *
 * DEVICE: R7s
 * MODEL: R7s
 */
final class r7s_r7s {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R7s";
}
