// This file is automatically generated.

package adila.db;

/*
 * Oppo R831
 *
 * DEVICE: R831T
 * MODEL: R831T
 */
final class r831t_r831t {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R831";
}
