// This file is automatically generated.

package adila.db;

/*
 * Oppo R9 Plus A
 *
 * DEVICE: R9PlusA
 * MODEL: OPPO R9 Plus A
 */
final class r9plusa_oppo20r920plus20a {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "R9 Plus A";
}
