// This file is automatically generated.

package adila.db;

/*
 * Oppo R9s Plus
 *
 * DEVICE: R9sPlus
 * MODEL: OPPO R9s Plust
 */
final class r9splus_oppo20r9s20plust {
    public static final String DATA = "Oppo|R9s Plus|";
}
