// This file is automatically generated.

package adila.db;

/*
 * Plaisio RainbowIII3G
 *
 * DEVICE: RainbowIII3G
 * MODEL: RainbowIII3G
 */
final class rainbowiii3g_rainbowiii3g {
    public static final String MANUFACTURER = "Plaisio";
    public static final String NAME = "RainbowIII3G";
}
