// This file is automatically generated.

package adila.db;

/*
 * HP Slate 21 Pro
 *
 * DEVICE: ranger
 * MODEL: Slate 21 Pro
 */
final class ranger {
    public static final String MANUFACTURER = "HP";
    public static final String NAME = "Slate 21 Pro";
}
