// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL P606
 *
 * DEVICE: Rav4_GSM
 * MODEL: TCL P600
 */
final class rav45fgsm_tcl20p600 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TCL P606";
}
