// This file is automatically generated.

package adila.db;

/*
 * Hipstreet HS-10DTB12A
 *
 * DEVICE: RCT6203W46
 * MODEL: HS_10DTB12A
 */
final class rct6203w46_hs5f10dtb12a {
    public static final String MANUFACTURER = "Hipstreet";
    public static final String NAME = "HS-10DTB12A";
}
