// This file is automatically generated.

package adila.db;

/*
 * Nobis NB1022
 *
 * DEVICE: RCT6203W46
 * MODEL: NB1022
 */
final class rct6203w46_nb1022 {
    public static final String DATA = "Nobis|NB1022|";
}
