// This file is automatically generated.

package adila.db;

/*
 * AV AV7
 *
 * DEVICE: RCT6773W22
 * MODEL: AV7
 */
final class rct6773w22_av7 {
    public static final String MANUFACTURER = "AV";
    public static final String NAME = "AV7";
}
