// This file is automatically generated.

package adila.db;

/*
 * RCA 7 Voyager II
 *
 * DEVICE: RCT6773W22BM
 * MODEL: RCT6773W22BM
 */
final class rct6773w22bm_rct6773w22bm {
    public static final String DATA = "RCA|7 Voyager II|";
}
