// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP S3
 *
 * DEVICE: RIO_4G
 * MODEL: 5050A
 */
final class rio5f4g_5050a {
    public static final String DATA = "Alcatel|POP S3|";
}
