// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL J938M
 *
 * DEVICE: RIO55_LTE
 * MODEL: TCL J938M
 */
final class rio555flte_tcl20j938m {
    public static final String DATA = "Alcatel|TCL J938M|";
}
