// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP S3
 *
 * DEVICE: RIO_4G
 * MODEL: 5050X
 */
final class rio5f4g_5050x {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "POP S3";
}
