// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP S9
 *
 * DEVICE: RIO6_lte
 * MODEL: 7050Y
 */
final class rio65flte_7050y {
    public static final String DATA = "Alcatel|POP S9|";
}
