// This file is automatically generated.

package adila.db;

/*
 * Explay Rio Play
 *
 * DEVICE: RioPlay
 * MODEL: RioPlay
 */
final class rioplay_rioplay {
    public static final String DATA = "Explay|Rio Play|";
}
