// This file is automatically generated.

package adila.db;

/*
 * SK Telesys ITP-R208W
 *
 * DEVICE: rk30sdk
 * MODEL: ITP-R208W
 */
final class rk30sdk {
    public static final String DATA = "SK Telesys|ITP-R208W|";
}
