// This file is automatically generated.

package adila.db;

/*
 * Hisense Sero 8
 *
 * DEVICE: rk3188
 * MODEL: E2281UK
 */
final class rk3188_e2281uk {
    public static final String DATA = "Hisense|Sero 8|";
}
