// This file is automatically generated.

package adila.db;

/*
 * Hisense Sero7
 *
 * DEVICE: rk3168
 * MODEL: E2171SS
 */
final class rk3168_e2171ss {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "Sero7";
}
