// This file is automatically generated.

package adila.db;

/*
 * HannSpree HSG1351
 *
 * DEVICE: rk3368_32
 * MODEL: HSG1351
 */
final class rk33685f32 {
    public static final String DATA = "HannSpree|HSG1351|";
}
