// This file is automatically generated.

package adila.db;

/*
 * ZTE N762
 *
 * DEVICE: roamer
 * MODEL: N762
 */
final class roamer_n762 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N762";
}
