// This file is automatically generated.

package adila.db;

/*
 * ZTE Leopard MF800
 *
 * DEVICE: roamer2
 * MODEL: Leopard MF800
 */
final class roamer2_leopard20mf800 {
    public static final String DATA = "ZTE|Leopard MF800|";
}
