// This file is automatically generated.

package adila.db;

/*
 * ZTE M8402
 *
 * DEVICE: roamer2
 * MODEL: M8402
 */
final class roamer2_m8402 {
    public static final String DATA = "ZTE|M8402|";
}
