// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Prime
 *
 * DEVICE: rossalte
 * MODEL: SM-G3608
 */
final class rossalte_sm2dg3608 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Core Prime";
}
