// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Young
 *
 * DEVICE: roy
 * MODEL: GT-S6312
 */
final class roy {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Young";
}
