// This file is automatically generated.

package adila.db;

/*
 * Samsung Roy VE DTV
 *
 * DEVICE: royssvedtv
 * MODEL: GT-S6293T
 */
final class royssvedtv {
    public static final String DATA = "Samsung|Roy VE DTV|";
}
