// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Young
 *
 * DEVICE: royss
 * MODEL: GT-S6310T
 */
final class royss_gt2ds6310t {
    public static final String DATA = "Samsung|Galaxy Young|";
}
