// This file is automatically generated.

package adila.db;

/*
 * Audi AG RSE-III
 *
 * DEVICE: RSEIII
 * MODEL: RSEIII
 */
final class rseiii_rseiii {
    public static final String DATA = "Audi AG|RSE-III|";
}
