// This file is automatically generated.

package adila.db;

/*
 * HTC Sensation XL with Beats Audio X315e
 *
 * DEVICE: runnymede
 * MODEL: HTC-X315E
 */
final class runnymede_htc2dx315e {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Sensation XL with Beats Audio X315e";
}
