// This file is automatically generated.

package adila.db;

/*
 * Cellon S21
 *
 * DEVICE: S21
 * MODEL: Q-Smart S21
 */
final class s21_q2dsmart20s21 {
    public static final String DATA = "Cellon|S21|";
}
