// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S2 Plus
 *
 * DEVICE: s2ve
 * MODEL: GT-I9105
 */
final class s2ve {
    public static final String DATA = "Samsung|Galaxy S2 Plus|Galaxy S";
}
