// This file is automatically generated.

package adila.db;

/*
 * Positivo First
 *
 * DEVICE: S410
 * MODEL: First
 */
final class s410_first {
    public static final String DATA = "Positivo|First|";
}
