// This file is automatically generated.

package adila.db;

/*
 * Logicom Logicom S504
 *
 * DEVICE: S504
 * MODEL: Connect 5
 */
final class s504_connect205 {
    public static final String MANUFACTURER = "Logicom";
    public static final String NAME = "Logicom S504";
}
