// This file is automatically generated.

package adila.db;

/*
 * Wiko PULP
 *
 * DEVICE: S5420
 * MODEL: PULP
 */
final class s5420_pulp {
    public static final String MANUFACTURER = "Wiko";
    public static final String NAME = "PULP";
}
