// This file is automatically generated.

package adila.db;

/*
 * Vestel VSP355s
 *
 * DEVICE: s55
 * MODEL: VSP355s
 */
final class s55_vsp355s {
    public static final String MANUFACTURER = "Vestel";
    public static final String NAME = "VSP355s";
}
