// This file is automatically generated.

package adila.db;

/*
 * Southern Telecom Polaroid Snap S55
 *
 * DEVICE: S55
 * MODEL: S55
 */
final class s55_s55 {
    public static final String MANUFACTURER = "Southern Telecom";
    public static final String NAME = "Polaroid Snap S55";
}
