// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S5 Neo
 *
 * DEVICE: s5neoltecan
 * MODEL: SM-G903W
 */
final class s5neoltecan {
    public static final String DATA = "Samsung|Galaxy S5 Neo|Galaxy S";
}
