// This file is automatically generated.

package adila.db;

/*
 * Lenovo IdeaTab S6000
 *
 * DEVICE: S6000
 * MODEL: IdeaTab S6000-F
 */
final class s6000_ideatab20s60002df {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "IdeaTab S6000";
}
