// This file is automatically generated.

package adila.db;

/*
 * Lenovo S6000L
 *
 * DEVICE: S6000L
 * MODEL: Lenovo S6000L-F
 */
final class s6000l_lenovo20s6000l2df {
    public static final String DATA = "Lenovo|S6000L|";
}
