// This file is automatically generated.

package adila.db;

/*
 * Lenovo S650
 *
 * DEVICE: S650
 * MODEL: Lenovo S650
 */
final class s650_lenovo20s650 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S650";
}
