// This file is automatically generated.

package adila.db;

/*
 * Lenovo S658t
 *
 * DEVICE: S658t
 * MODEL: Lenovo S658t
 */
final class s658t_lenovo20s658t {
    public static final String DATA = "Lenovo|S658t|";
}
