// This file is automatically generated.

package adila.db;

/*
 * Lenovo S668t
 *
 * DEVICE: S668t
 * MODEL: Lenovo S668t
 */
final class s668t_lenovo20s668t {
    public static final String DATA = "Lenovo|S668t|";
}
