// This file is automatically generated.

package adila.db;

/*
 * Nikon COOLPIX
 *
 * DEVICE: S800c
 * MODEL: COOLPIX S800c
 */
final class s800c_coolpix20s800c {
    public static final String DATA = "Nikon|COOLPIX|";
}
