// This file is automatically generated.

package adila.db;

/*
 * Lenovo S850t
 *
 * DEVICE: S850t
 * MODEL: Lenovo S850t
 */
final class s850t_lenovo20s850t {
    public static final String DATA = "Lenovo|S850t|";
}
