// This file is automatically generated.

package adila.db;

/*
 * Micromax CANVAS TURBO MINI
 *
 * DEVICE: s8513a
 * MODEL: Micromax A200
 */
final class s8513a {
    public static final String DATA = "Micromax|CANVAS TURBO MINI|";
}
