// This file is automatically generated.

package adila.db;

/*
 * Lenovo S870e
 *
 * DEVICE: S870e
 * MODEL: LNV-Lenovo S870e
 */
final class s870e_lnv2dlenovo20s870e {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S870e";
}
