// This file is automatically generated.

package adila.db;

/*
 * Enspert WIKO SUBLIM
 *
 * DEVICE: s9070
 * MODEL: SUBLIM
 */
final class s9070 {
    public static final String MANUFACTURER = "Enspert";
    public static final String NAME = "WIKO SUBLIM";
}
