// This file is automatically generated.

package adila.db;

/*
 * Enspert CINK KING
 *
 * DEVICE: s9081
 * MODEL: IMD501
 */
final class s9081_imd501 {
    public static final String MANUFACTURER = "Enspert";
    public static final String NAME = "CINK KING";
}
