// This file is automatically generated.

package adila.db;

/*
 * Wiko DARKNIGHT
 *
 * DEVICE: s9203
 * MODEL: DARKNIGHT
 */
final class s9203_darknight {
    public static final String DATA = "Wiko|DARKNIGHT|";
}
