// This file is automatically generated.

package adila.db;

/*
 * Wiko DARKFULL
 *
 * DEVICE: s9311
 * MODEL: DARKFULL
 */
final class s9311_darkfull {
    public static final String MANUFACTURER = "Wiko";
    public static final String NAME = "DARKFULL";
}
