// This file is automatically generated.

package adila.db;

/*
 * Wiko HIGHWAY 4G
 *
 * DEVICE: s9321
 * MODEL: HIGHWAY 4G
 */
final class s9321 {
    public static final String DATA = "Wiko|HIGHWAY 4G|";
}
