// This file is automatically generated.

package adila.db;

/*
 * Lenovo S939
 *
 * DEVICE: S939
 * MODEL: Lenovo S939
 */
final class s939_lenovo20s939 {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S939";
}
