// This file is automatically generated.

package adila.db;

/*
 * HTC Desire S
 *
 * DEVICE: saga
 * MODEL: HTC Desire S
 */
final class saga {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire S";
}
