// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 3 10.1
 *
 * DEVICE: santos10wifi
 * MODEL: GT-P5210
 */
final class santos10wifi_gt2dp5210 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 3 10.1";
    public static final String SERIES = "Galaxy Tab";
}
