// This file is automatically generated.

package adila.db;

/*
 * Gigabyte Gigabyte SB506
 *
 * DEVICE: SB506
 * MODEL: SB506
 */
final class sb506_sb506 {
    public static final String DATA = "Gigabyte|Gigabyte SB506|";
}
