// This file is automatically generated.

package adila.db;

/*
 * Gigabyte Gigabyte SB510 / IBT-102
 *
 * DEVICE: SB510
 * MODEL: SB510
 */
final class sb510_sb510 {
    public static final String DATA = "Gigabyte|Gigabyte SB510 / IBT-102|";
}
