// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE SoftBank  102SH II
 *
 * DEVICE: SBM102SH2
 * MODEL: SBM102SH2
 */
final class sbm102sh2_sbm102sh2 {
    public static final String DATA = "Sharp|AQUOS PHONE SoftBank  102SH II|";
}
