// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE SoftBank 102SH
 *
 * DEVICE: SBM102SH
 * MODEL: SBM102SH
 */
final class sbm102sh_sbm102sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE SoftBank 102SH";
}
