// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE Xx 302SH
 *
 * DEVICE: SBM302SH
 * MODEL: SBM302SH
 */
final class sbm302sh_sbm302sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE Xx 302SH";
}
