// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab
 *
 * DEVICE: SC-01C
 * MODEL: SC-01C
 */
final class sc2d01c_sc2d01c {
    public static final String DATA = "Samsung|Galaxy Tab|Galaxy Tab";
}
