// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 3
 *
 * DEVICE: SC-02F
 * MODEL: SC-02F
 */
final class sc2d02f_sc2d02f {
    public static final String DATA = "Samsung|Galaxy Note 3|Galaxy Note";
}
