// This file is automatically generated.

package adila.db;

/*
 * Samsung Droid Charge
 *
 * DEVICE: SCH-I510
 * MODEL: SCH-I510
 */
final class sch2di510_sch2di510 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Droid Charge";
}
