// This file is automatically generated.

package adila.db;

/*
 * Samsung Illusion
 *
 * DEVICE: SCH-I110
 * MODEL: SCH-I110
 */
final class sch2di110_sch2di110 {
    public static final String DATA = "Samsung|Illusion|";
}
