// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 7.7
 *
 * DEVICE: SCH-I815
 * MODEL: SCH-I815
 */
final class sch2di815_sch2di815 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 7.7";
    public static final String SERIES = "Galaxy Tab";
}
