// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note
 *
 * DEVICE: SCH-i889
 * MODEL: SCH-i889
 */
final class sch2di889_sch2di889 {
    public static final String DATA = "Samsung|Galaxy Note|Galaxy Note";
}
