// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S Continuum
 *
 * DEVICE: SCH-I400
 * MODEL: SCH-I400
 */
final class sch2di400_sch2di400 {
    public static final String DATA = "Samsung|Galaxy S Continuum|Galaxy S";
}
