// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Edge
 *
 * DEVICE: SCL24
 * MODEL: SCL24
 */
final class scl24_scl24 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note Edge";
    public static final String SERIES = "Galaxy Note";
}
