// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH SCRIBE 5
 *
 * DEVICE: Scribe5_gsm
 * MODEL: ALCATEL ONE TOUCH 8000D
 */
final class scribe55fgsm_alcatel20one20touch208000d {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH SCRIBE 5";
}
