// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 8020A
 *
 * DEVICE: SCRIBEPRO
 * MODEL: ALCATEL ONE TOUCH 8020A
 */
final class scribepro_alcatel20one20touch208020a {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 8020A";
}
