// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH SCRIBE 5
 *
 * DEVICE: Scribe5_gsm
 * MODEL: TCL Y710
 */
final class scribe55fgsm_tcl20y710 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH SCRIBE 5";
}
