// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab S 10.5
 *
 * DEVICE: SCT21
 * MODEL: SCT21
 */
final class sct21_sct21 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab S 10.5";
    public static final String SERIES = "Galaxy Tab";
}
