// This file is automatically generated.

package adila.db;

/*
 * Lenovo S858t
 *
 * DEVICE: Selected
 * MODEL: Lenovo S858t
 */
final class selected_lenovo20s858t {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S858t";
}
