// This file is automatically generated.

package adila.db;

/*
 * Wiko SELFY
 *
 * DEVICE: SELFY
 * MODEL: SELFY
 */
final class selfy_selfy {
    public static final String MANUFACTURER = "Wiko";
    public static final String NAME = "SELFY";
}
