// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4 Mini
 *
 * DEVICE: serranods
 * MODEL: GT-I9192
 */
final class serranods {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4 Mini";
    public static final String SERIES = "Galaxy S";
}
