// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4 Mini
 *
 * DEVICE: serranove3g
 * MODEL: GT-I9192I
 */
final class serranove3g {
    public static final String DATA = "Samsung|Galaxy S4 Mini|Galaxy S";
}
