// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S4 Mini
 *
 * DEVICE: serranoltebmc
 * MODEL: SGH-I257M
 */
final class serranoltebmc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S4 Mini";
    public static final String SERIES = "Galaxy S";
}
