// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS Xx 304SH
 *
 * DEVICE: SG304SH
 * MODEL: 304SH
 */
final class sg304sh_304sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS Xx 304SH";
}
