// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS CRYSTAL 2
 *
 * DEVICE: SG403SH
 * MODEL: 403SH
 */
final class sg403sh_403sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS CRYSTAL 2";
}
