// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS Xx
 *
 * DEVICE: SG404SH
 * MODEL: 404SH
 */
final class sg404sh_404sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS Xx";
}
