// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS Xx2
 *
 * DEVICE: SG502SH
 * MODEL: 502SH
 */
final class sg502sh_502sh {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS Xx2";
}
