// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS Xx2 mini
 *
 * DEVICE: SG503SH
 * MODEL: 503SH
 */
final class sg503sh_503sh {
    public static final String DATA = "Sharp|AQUOS Xx2 mini|";
}
