// This file is automatically generated.

package adila.db;

/*
 * Samsung Captivate Glide
 *
 * DEVICE: SGH-I927
 * MODEL: SGH-I927
 */
final class sgh2di927_sgh2di927 {
    public static final String DATA = "Samsung|Captivate Glide|";
}
