// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 8.9
 *
 * DEVICE: SGH-I957D
 * MODEL: SAMSUNG-SGH-I957D
 */
final class sgh2di957d_samsung2dsgh2di957d {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 8.9";
    public static final String SERIES = "Galaxy Tab";
}
