// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 8.9
 *
 * DEVICE: SGH-I957R
 * MODEL: SAMSUNG-SGH-I957R
 */
final class sgh2di957r_samsung2dsgh2di957r {
    public static final String DATA = "Samsung|Galaxy Tab 8.9|Galaxy Tab";
}
