// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z Ultra
 *
 * DEVICE: SGP412
 * MODEL: SGP412
 */
final class sgp412_sgp412 {
    public static final String DATA = "Sony|Xperia Z Ultra|";
}
