// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS EVER SH-04G
 *
 * DEVICE: SH-04G
 * MODEL: SH-04G
 */
final class sh2d04g_sh2d04g {
    public static final String DATA = "Sharp|AQUOS EVER SH-04G|";
}
