// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE si SH-07E
 *
 * DEVICE: SH-07E
 * MODEL: SH-07E
 */
final class sh2d07e_sh2d07e {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE si SH-07E";
}
