// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE ZETA  SH-01F
 *
 * DEVICE: SH-01F
 * MODEL: SH-01F
 */
final class sh2d01f_sh2d01f {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE ZETA  SH-01F";
}
