// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE SH90B
 *
 * DEVICE: SH90B
 * MODEL: SH90B
 */
final class sh90b_sh90b {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE SH90B";
}
