// This file is automatically generated.

package adila.db;

/*
 * Sharp LC-**UH30U
 *
 * DEVICE: sharp_2k15_us_android
 * MODEL: LC-Ux30US
 */
final class sharp5f2k155fus5fandroid {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "LC-**UH30U";
}
