// This file is automatically generated.

package adila.db;

/*
 * Lenovo S856
 *
 * DEVICE: shellr_s
 * MODEL: Lenovo S856
 */
final class shellr5fs {
    public static final String DATA = "Lenovo|S856|";
}
