// This file is automatically generated.

package adila.db;

/*
 * Lenovo S810t
 *
 * DEVICE: shellt
 * MODEL: Lenovo S810t
 */
final class shellt {
    public static final String DATA = "Lenovo|S810t|";
}
