// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS K SHF33
 *
 * DEVICE: SHF33
 * MODEL: SHF33
 */
final class shf33_shf33 {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS K SHF33";
}
