// This file is automatically generated.

package adila.db;

/*
 * Alcatel POP 4S
 *
 * DEVICE: shine_plus
 * MODEL: 5095Y
 */
final class shine5fplus_5095y {
    public static final String DATA = "Alcatel|POP 4S|";
}
