// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PHONE  SERIE SHL23
 *
 * DEVICE: SHL23
 * MODEL: SHL23
 */
final class shl23_shl23 {
    public static final String MANUFACTURER = "Sharp";
    public static final String NAME = "AQUOS PHONE  SERIE SHL23";
}
