// This file is automatically generated.

package adila.db;

/*
 * HTC EVO 3D
 *
 * DEVICE: shooter
 * MODEL: PG86100
 */
final class shooter_pg86100 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "EVO 3D";
}
