// This file is automatically generated.

package adila.db;

/*
 * Sharp AQUOS PAD SHT21
 *
 * DEVICE: SHT21
 * MODEL: SHT21
 */
final class sht21_sht21 {
    public static final String DATA = "Sharp|AQUOS PAD SHT21|";
}
