// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 8.9
 *
 * DEVICE: SHV-E140L
 * MODEL: SHV-E140L
 */
final class shv2de140l_shv2de140l {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 8.9";
    public static final String SERIES = "Galaxy Tab";
}
