// This file is automatically generated.

package adila.db;

/*
 * Sharp BASIO2 SHV36
 *
 * DEVICE: SHV36
 * MODEL: SHV36
 */
final class shv36_shv36 {
    public static final String DATA = "Sharp|BASIO2 SHV36|";
}
