// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S2
 *
 * DEVICE: SHW-M250S
 * MODEL: SHW-M250S
 */
final class shw2dm250s_shw2dm250s {
    public static final String DATA = "Samsung|Galaxy S2|Galaxy S";
}
