// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy K
 *
 * DEVICE: SHW-M130K
 * MODEL: SHW-M130K
 */
final class shw2dm130k_shw2dm130k {
    public static final String DATA = "Samsung|Galaxy K|";
}
