// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 10.1
 *
 * DEVICE: SHW-M300W
 * MODEL: SHW-M300W
 */
final class shw2dm300w_shw2dm300w {
    public static final String DATA = "Samsung|Galaxy Tab 10.1|Galaxy Tab";
}
