// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S
 *
 * DEVICE: SHW-M110S
 * MODEL: SHW-M110S
 */
final class shw2dm110s_shw2dm110s {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S";
    public static final String SERIES = "Galaxy S";
}
