// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 8.9
 *
 * DEVICE: SHW-M305W
 * MODEL: SHW-M305W
 */
final class shw2dm305w_shw2dm305w {
    public static final String DATA = "Samsung|Galaxy Tab 8.9|Galaxy Tab";
}
