// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab 7.0 Plus
 *
 * DEVICE: SHW-M430W
 * MODEL: SHW-M430W
 */
final class shw2dm430w_shw2dm430w {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Tab 7.0 Plus";
    public static final String SERIES = "Galaxy Tab";
}
