// This file is automatically generated.

package adila.db;

/*
 * Sharp INFOBAR A01
 *
 * DEVICE: SHX11
 * MODEL: INFOBAR A01
 */
final class shx11_infobar20a01 {
    public static final String DATA = "Sharp|INFOBAR A01|";
}
