// This file is automatically generated.

package adila.db;

/*
 * SiAL Bic camera
 *
 * DEVICE: Si01BB
 * MODEL: Si01BB
 */
final class si01bb_si01bb {
    public static final String MANUFACTURER = "SiAL";
    public static final String NAME = "Bic camera";
}
