// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: sicily
 * MODEL: Lenovo S696
 */
final class sicily {
    public static final String MANUFACTURER = "Lenovo";
}
