// This file is automatically generated.

package adila.db;

/*
 * Polaroid SIGMA 5
 *
 * DEVICE: SIGMA-5
 * MODEL: SIGMA-5
 */
final class sigma2d5_sigma2d5 {
    public static final String MANUFACTURER = "Polaroid";
    public static final String NAME = "SIGMA 5";
}
