// This file is automatically generated.

package adila.db;

/*
 * Motorola Motosmart
 *
 * DEVICE: silversmart_umts
 * MODEL: XT305
 */
final class silversmart5fumts_xt305 {
    public static final String DATA = "Motorola|Motosmart|";
}
