// This file is automatically generated.

package adila.db;

/*
 * Lenovo S60
 *
 * DEVICE: sisleylt
 * MODEL: Lenovo S60-t
 */
final class sisleylt {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S60";
}
