// This file is automatically generated.

package adila.db;

/*
 * Lenovo S90-A
 *
 * DEVICE: sisleyr
 * MODEL: Lenovo S90-A
 */
final class sisleyr {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "S90-A";
}
