// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Alpha
 *
 * DEVICE: slte
 * MODEL: SM-G850X
 */
final class slte_sm2dg850x {
    public static final String DATA = "Samsung|Galaxy Alpha|Galaxy A";
}
