// This file is automatically generated.

package adila.db;

/*
 * MobileTeleSystem Smart Surf2 4G
 *
 * DEVICE: SMART_Surf2_4G
 * MODEL: SMART Surf2 4G
 */
final class smart5fsurf25f4g_smart20surf2204g {
    public static final String DATA = "MobileTeleSystem|Smart Surf2 4G|";
}
