// This file is automatically generated.

package adila.db;

/*
 * FarEasTone Smart501
 *
 * DEVICE: Smart501
 * MODEL: Smart501
 */
final class smart501_smart501 {
    public static final String DATA = "FarEasTone|Smart501|";
}
