// This file is automatically generated.

package adila.db;

/*
 * Binatone SMART64
 *
 * DEVICE: SMART64
 * MODEL: SMART64
 */
final class smart64_smart64 {
    public static final String DATA = "Binatone|SMART64|";
}
