// This file is automatically generated.

package adila.db;

/*
 * Sourcing Creation Smart Tab 1004XS
 *
 * DEVICE: SmartTab_1004_XS
 * MODEL: SmartTab_1004_XS
 */
final class smarttab5f10045fxs_smarttab5f10045fxs {
    public static final String MANUFACTURER = "Sourcing Creation";
    public static final String NAME = "Smart Tab 1004XS";
}
