// This file is automatically generated.

package adila.db;

/*
 * LGUplus TV G
 *
 * DEVICE: smartbox
 * MODEL: TI320-DU
 */
final class smartbox {
    public static final String DATA = "LGUplus|TV G|";
}
