// This file is automatically generated.

package adila.db;

/*
 * Cellon MTC SMART Run
 *
 * DEVICE: SMART_Run
 * MODEL: MTC SMART Run
 */
final class smart5frun_mtc20smart20run {
    public static final String DATA = "Cellon|MTC SMART Run|";
}
