// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: SmartIII4
 * MODEL: Vodafone 975N
 */
final class smartiii4_vodafone20975n {
    public static final String MANUFACTURER = "Alcatel";
}
