// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia S
 *
 * DEVICE: SO-02D
 * MODEL: SO-02D
 */
final class so2d02d_so2d02d {
    public static final String MANUFACTURER = "Sony Ericsson";
    public static final String NAME = "Xperia S";
}
