// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia X Performance
 *
 * DEVICE: SO-04H
 * MODEL: SO-04H
 */
final class so2d04h_so2d04h {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia X Performance";
}
