// This file is automatically generated.

package adila.db;

/*
 * Polaroid SOHO
 *
 * DEVICE: SOHO
 * MODEL: SOHO
 */
final class soho_soho {
    public static final String DATA = "Polaroid|SOHO|";
}
