// This file is automatically generated.

package adila.db;

/*
 * Mobicel Mobicel
 *
 * DEVICE: Sonic
 * MODEL: Sonic
 */
final class sonic_sonic {
    public static final String DATA = "Mobicel|Mobicel|";
}
