// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia X10
 *
 * DEVICE: SonyEricssonSO-01B
 * MODEL: SO-01B
 */
final class sonyericssonso2d01b_so2d01b {
    public static final String MANUFACTURER = "Sony Ericsson";
    public static final String NAME = "Xperia X10";
}
