// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Z4 Tablet
 *
 * DEVICE: SOT31
 * MODEL: SOT31
 */
final class sot31_sot31 {
    public static final String DATA = "Sony|Xperia Z4 Tablet|";
}
