// This file is automatically generated.

package adila.db;

/*
 * Alcatel Soul 3.5
 *
 * DEVICE: SOUL35
 * MODEL: 4018M
 */
final class soul35_4018m {
    public static final String DATA = "Alcatel|Soul 3.5|";
}
