// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 4037N
 *
 * DEVICE: SOUL4NA
 * MODEL: ALCATEL ONE TOUCH 4037T
 */
final class soul4na_alcatel20one20touch204037t {
    public static final String DATA = "Alcatel|ONE TOUCH 4037N|";
}
