// This file is automatically generated.

package adila.db;

/*
 * Alcatel Soul 4
 *
 * DEVICE: SOUL4
 * MODEL: 4035X_Orange
 */
final class soul4_4035x5forange {
    public static final String DATA = "Alcatel|Soul 4|";
}
