// This file is automatically generated.

package adila.db;

/*
 * Alcatel Soul 4
 *
 * DEVICE: SOUL4
 * MODEL: 4035Y
 */
final class soul4_4035y {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "Soul 4";
}
