// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia XZ
 *
 * DEVICE: SOV34
 * MODEL: SOV34
 */
final class sov34_sov34 {
    public static final String DATA = "Sony|Xperia XZ|";
}
