// This file is automatically generated.

package adila.db;

/*
 * Haier SP-5100
 *
 * DEVICE: SP-5100
 * MODEL: SP-5100
 */
final class sp2d5100_sp2d5100 {
    public static final String MANUFACTURER = "Haier";
    public static final String NAME = "SP-5100";
}
