// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S2 Epic
 *
 * DEVICE: SPH-D710
 * MODEL: SPH-D710
 */
final class sph2dd710_sph2dd710 {
    public static final String DATA = "Samsung|Galaxy S2 Epic|Galaxy S";
}
