// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S2 Epic
 *
 * DEVICE: SPH-D710BST
 * MODEL: SPH-D710BST
 */
final class sph2dd710bst_sph2dd710bst {
    public static final String DATA = "Samsung|Galaxy S2 Epic|Galaxy S";
}
