// This file is automatically generated.

package adila.db;

/*
 * Spice Xlife-441Q
 *
 * DEVICE: Spice
 * MODEL: Xlife-415
 */
final class spice_xlife2d415 {
    public static final String DATA = "Spice|Xlife-441Q|";
}
