// This file is automatically generated.

package adila.db;

/*
 * Southern Telecom Smartab ST10
 *
 * DEVICE: ST10
 * MODEL: ST10/ST10x
 */
final class st10_st102fst10x {
    public static final String DATA = "Southern Telecom|Smartab ST10|";
}
