// This file is automatically generated.

package adila.db;

/*
 * Southern Telecom ST13
 *
 * DEVICE: ST13
 * MODEL: ST13
 */
final class st13_st13 {
    public static final String MANUFACTURER = "Southern Telecom";
    public static final String NAME = "ST13";
}
