// This file is automatically generated.

package adila.db;

/*
 * Sony Ericsson Xperia Tipo
 *
 * DEVICE: ST21i
 * MODEL: ST21i
 */
final class st21i_st21i {
    public static final String DATA = "Sony Ericsson|Xperia Tipo|";
}
