// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia U
 *
 * DEVICE: ST25i
 * MODEL: ST25i
 */
final class st25i_st25i {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia U";
}
