// This file is automatically generated.

package adila.db;

/*
 * SMARTAB SMARTAB ST700
 *
 * DEVICE: ST700
 * MODEL: ST700
 */
final class st700_st700 {
    public static final String MANUFACTURER = "SMARTAB";
    public static final String NAME = "SMARTAB ST700";
}
