// This file is automatically generated.

package adila.db;

/*
 * Haier StarQ_Q5002
 *
 * DEVICE: StarQ_Q5002
 * MODEL: Q5002
 */
final class starq5fq5002_q5002 {
    public static final String DATA = "Haier|StarQ_Q5002|";
}
