// This file is automatically generated.

package adila.db;

/*
 * Ematic GTB103B
 *
 * DEVICE: Stealth_GTB103M
 * MODEL: GTB103M
 */
final class stealth5fgtb103m_gtb103m {
    public static final String DATA = "Ematic|GTB103B|";
}
