// This file is automatically generated.

package adila.db;

/*
 * Smartab Smartab STJR76
 *
 * DEVICE: STJR76
 * MODEL: STJR76
 */
final class stjr76_stjr76 {
    public static final String MANUFACTURER = "Smartab";
    public static final String NAME = "Smartab STJR76";
}
