// This file is automatically generated.

package adila.db;

/*
 * Polaroid PTAB751
 *
 * DEVICE: STJR76
 * MODEL: PTAB751
 */
final class stjr76_ptab751 {
    public static final String MANUFACTURER = "Polaroid";
    public static final String NAME = "PTAB751";
}
