// This file is automatically generated.

package adila.db;

/*
 * STOREX eZee'Tab7D14-S
 *
 * DEVICE: STOREX7526
 * MODEL: NID_7010
 */
final class storex7526_nid5f7010 {
    public static final String MANUFACTURER = "STOREX";
    public static final String NAME = "eZee'Tab7D14-S";
}
