// This file is automatically generated.

package adila.db;

/*
 * ZTE N9520
 *
 * DEVICE: stormer
 * MODEL: N9520
 */
final class stormer {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "N9520";
}
