// This file is automatically generated.

package adila.db;

/*
 * Fly FS402
 *
 * DEVICE: Stratus_2
 * MODEL: FS402
 */
final class stratus5f2_fs402 {
    public static final String MANUFACTURER = "Fly";
    public static final String NAME = "FS402";
}
