// This file is automatically generated.

package adila.db;

/*
 * Blu Studio G HD
 *
 * DEVICE: STUDIO_G_HD
 * MODEL: STUDIO_G_HD
 */
final class studio5fg5fhd_studio5fg5fhd {
    public static final String DATA = "Blu|Studio G HD|Studio";
}
