// This file is automatically generated.

package adila.db;

/*
 * Blu Studio G Plus HD
 *
 * DEVICE: Studio_G_Plus_HD
 * MODEL: Studio G Plus HD
 */
final class studio5fg5fplus5fhd_studio20g20plus20hd {
    public static final String DATA = "Blu|Studio G Plus HD|Studio";
}
