// This file is automatically generated.

package adila.db;

/*
 * Lenovo 
 *
 * DEVICE: stuttgart_row
 * MODEL: Lenovo K860
 */
final class stuttgart5frow {
    public static final String MANUFACTURER = "Lenovo";
}
