// This file is automatically generated.

package adila.db;

/*
 * Lenovo K860
 *
 * DEVICE: stuttgart
 * MODEL: Lenovo K860
 */
final class stuttgart {
    public static final String DATA = "Lenovo|K860|";
}
