// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Premier
 *
 * DEVICE: superiorchn
 * MODEL: GT-I9260
 */
final class superiorchn {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Premier";
}
