// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH TAB 7
 *
 * DEVICE: T011
 * MODEL: TCL TAB 7
 */
final class t011_tcl20tab207 {
    public static final String DATA = "Alcatel|ONE TOUCH TAB 7|";
}
