// This file is automatically generated.

package adila.db;

/*
 * Alcatel TAB 7 DUAL CORE
 *
 * DEVICE: T017
 * MODEL: TAB 7 DUAL CORE
 */
final class t017_tab20720dual20core {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TAB 7 DUAL CORE";
}
