// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH TAB 8HD
 *
 * DEVICE: T021
 * MODEL: ONE TOUCH TAB 8HD
 */
final class t021_one20touch20tab208hd {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH TAB 8HD";
}
