// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 2
 *
 * DEVICE: t03gchnduos
 * MODEL: GT-N7102i
 */
final class t03gchnduos_gt2dn7102i {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note 2";
    public static final String SERIES = "Galaxy Note";
}
