// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 2
 *
 * DEVICE: t0ltecan
 * MODEL: SGH-T889V
 */
final class t0ltecan_sgh2dt889v {
    public static final String DATA = "Samsung|Galaxy Note 2|Galaxy Note";
}
