// This file is automatically generated.

package adila.db;

/*
 * Sourcing Creation ST1003S
 *
 * DEVICE: T1882R
 * MODEL: Smart_TAB_1003s
 */
final class t1882r_smart5ftab5f1003s {
    public static final String MANUFACTURER = "Sourcing Creation";
    public static final String NAME = "ST1003S";
}
