// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S2
 *
 * DEVICE: t1cmcc
 * MODEL: GT-I9108
 */
final class t1cmcc {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S2";
    public static final String SERIES = "Galaxy S";
}
