// This file is automatically generated.

package adila.db;

/*
 * Panasonic T21
 *
 * DEVICE: T21
 * MODEL: Panasonic T21
 */
final class t21_panasonic20t21 {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "T21";
}
