// This file is automatically generated.

package adila.db;

/*
 * Explay Winner
 *
 * DEVICE: T4728
 * MODEL: Winner
 */
final class t4728_winner {
    public static final String DATA = "Explay|Winner|";
}
