// This file is automatically generated.

package adila.db;

/*
 * Explay Winner 7
 *
 * DEVICE: T4729
 * MODEL: Winner7
 */
final class t4729_winner7 {
    public static final String MANUFACTURER = "Explay";
    public static final String NAME = "Winner 7";
}
