// This file is automatically generated.

package adila.db;

/*
 * Explay Winner 8
 *
 * DEVICE: T4730
 * MODEL: Winner8
 */
final class t4730_winner8 {
    public static final String DATA = "Explay|Winner 8|";
}
