// This file is automatically generated.

package adila.db;

/*
 * BenQ T47
 *
 * DEVICE: T47
 * MODEL: T47_05
 */
final class t47_t475f05 {
    public static final String MANUFACTURER = "BenQ";
    public static final String NAME = "T47";
}
