// This file is automatically generated.

package adila.db;

/*
 * HTC 8160
 *
 * DEVICE: t6uhl
 * MODEL: HTC 8160
 */
final class t6uhl {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "8160";
}
