// This file is automatically generated.

package adila.db;

/*
 * SK Telesys T720
 *
 * DEVICE: T720
 * MODEL: Clear
 */
final class t720_clear {
    public static final String MANUFACTURER = "SK Telesys";
    public static final String NAME = "T720";
}
