// This file is automatically generated.

package adila.db;

/*
 * Oysters T72HM3G
 *
 * DEVICE: T72HM3G
 * MODEL: T72HM3G
 */
final class t72hm3g_t72hm3g {
    public static final String DATA = "Oysters|T72HM3G|";
}
