// This file is automatically generated.

package adila.db;

/*
 * Haier T785B
 *
 * DEVICE: T785B
 * MODEL: T785B
 */
final class t785b_t785b {
    public static final String MANUFACTURER = "Haier";
    public static final String NAME = "T785B";
}
