// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-T968S
 *
 * DEVICE: t968s
 * MODEL: HS-T968S
 */
final class t968s {
    public static final String DATA = "Hisense|HS-T968S|";
}
