// This file is automatically generated.

package adila.db;

/*
 * Panasonic T9
 *
 * DEVICE: T9
 * MODEL: Panasonic T9
 */
final class t9_panasonic20t9 {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "T9";
}
