// This file is automatically generated.

package adila.db;

/*
 * i-Buddie TA10CA4
 *
 * DEVICE: TA10CA4
 * MODEL: TA10CA4
 */
final class ta10ca4_ta10ca4 {
    public static final String DATA = "i-Buddie|TA10CA4|";
}
