// This file is automatically generated.

package adila.db;

/*
 * Acer TA272HUL
 *
 * DEVICE: ta2
 * MODEL: TA272HUL
 */
final class ta2 {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "TA272HUL";
}
