// This file is automatically generated.

package adila.db;

/*
 * GD Classbook TA80CA1
 *
 * DEVICE: TA80CA1_2
 * MODEL: TA80CA1
 */
final class ta80ca15f2_ta80ca1 {
    public static final String DATA = "GD Classbook|TA80CA1|";
}
