// This file is automatically generated.

package adila.db;

/*
 * Casper TA80CA2
 *
 * DEVICE: TA80CA2_1
 * MODEL: TA80CA2
 */
final class ta80ca25f1_ta80ca2 {
    public static final String DATA = "Casper|TA80CA2|";
}
