// This file is automatically generated.

package adila.db;

/*
 * Panasonic TAB-A01
 *
 * DEVICE: TAB-A01
 * MODEL: TAB-A01-SD
 */
final class tab2da01_tab2da012dsd {
    public static final String DATA = "Panasonic|TAB-A01|";
}
