// This file is automatically generated.

package adila.db;

/*
 * Logicom L-IXIR TAB 701 3G
 *
 * DEVICE: TAB701
 * MODEL: L-IXIR TAB 701 3G
 */
final class tab701_l2dixir20tab20701203g {
    public static final String MANUFACTURER = "Logicom";
    public static final String NAME = "L-IXIR TAB 701 3G";
}
