// This file is automatically generated.

package adila.db;

/*
 * DL DL3920
 *
 * DEVICE: Tablet_DL_3920
 * MODEL: Tablet_DL_3920
 */
final class tablet5fdl5f3920_tablet5fdl5f3920 {
    public static final String DATA = "DL|DL3920|";
}
