// This file is automatically generated.

package adila.db;

/*
 * Explay Tab Mini
 *
 * DEVICE: TabMini
 * MODEL: TabMini
 */
final class tabmini_tabmini {
    public static final String DATA = "Explay|Tab Mini|";
}
