// This file is automatically generated.

package adila.db;

/*
 * Lenovo TAB3 8 Plus
 *
 * DEVICE: TB-8703R
 * MODEL: Lenovo TB-8703R
 */
final class tb2d8703r_lenovo20tb2d8703r {
    public static final String DATA = "Lenovo|TAB3 8 Plus|";
}
