// This file is automatically generated.

package adila.db;

/*
 * Lenovo TAB3 X70L
 *
 * DEVICE: TB3-X70L
 * MODEL: Lenovo TB3-X70L
 */
final class tb32dx70l_lenovo20tb32dx70l {
    public static final String DATA = "Lenovo|TAB3 X70L|";
}
