// This file is automatically generated.

package adila.db;

/*
 * Lenovo TAB3 730F
 *
 * DEVICE: TB3-730F
 * MODEL: Lenovo TB3-730F
 */
final class tb32d730f_lenovo20tb32d730f {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "TAB3 730F";
}
