// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Edge
 *
 * DEVICE: tbltevzw
 * MODEL: SM-N915V
 */
final class tbltevzw {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note Edge";
    public static final String SERIES = "Galaxy Note";
}
