// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Edge
 *
 * DEVICE: tblte
 * MODEL: SM-N915X
 */
final class tblte_sm2dn915x {
    public static final String DATA = "Samsung|Galaxy Note Edge|Galaxy Note";
}
