// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Edge
 *
 * DEVICE: tbltecan
 * MODEL: SM-N915W8
 */
final class tbltecan {
    public static final String DATA = "Samsung|Galaxy Note Edge|Galaxy Note";
}
