// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Edge
 *
 * DEVICE: tbltespr
 * MODEL: SM-N915P
 */
final class tbltespr {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Note Edge";
    public static final String SERIES = "Galaxy Note";
}
