// This file is automatically generated.

package adila.db;

/*
 * Ceibal TC80RA6
 *
 * DEVICE: TC80RA6_1
 * MODEL: TC80RA6
 */
final class tc80ra65f1_tc80ra6 {
    public static final String DATA = "Ceibal|TC80RA6|";
}
