// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL A506
 *
 * DEVICE: TCL_A506
 * MODEL: TCL A506
 */
final class tcl5fa506_tcl20a506 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "TCL A506";
}
