// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: TCL_S800_GSM
 * MODEL: TCL S800
 */
final class tcl5fs8005fgsm_tcl20s800 {
    public static final String MANUFACTURER = "Alcatel";
}
