// This file is automatically generated.

package adila.db;

/*
 * Alcatel 
 *
 * DEVICE: TCL_W939_gsm
 * MODEL: TCL_W939
 */
final class tcl5fw9395fgsm_tcl5fw939 {
    public static final String DATA = "Alcatel||";
}
