// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3459DUO
 *
 * DEVICE: TE45B3G
 * MODEL: PSP3459DUO
 */
final class te45b3g_psp3459duo {
    public static final String DATA = "Prestigio|PSP3459DUO|";
}
