// This file is automatically generated.

package adila.db;

/*
 * Prestigio PSP3518DUO
 *
 * DEVICE: TE50B4G
 * MODEL: PSP3518DUO
 */
final class te50b4g_psp3518duo {
    public static final String MANUFACTURER = "Prestigio";
    public static final String NAME = "PSP3518DUO";
}
