// This file is automatically generated.

package adila.db;

/*
 * Tecno Y3S
 *
 * DEVICE: TECNO-Y3S
 * MODEL: TECNO-Y3S
 */
final class tecno2dy3s_tecno2dy3s {
    public static final String MANUFACTURER = "Tecno";
    public static final String NAME = "Y3S";
}
