// This file is automatically generated.

package adila.db;

/*
 * Tecno PHANTOM5
 *
 * DEVICE: TECNO-PHANTOM5
 * MODEL: TECNO-PHANTOM5
 */
final class tecno2dphantom5_tecno2dphantom5 {
    public static final String MANUFACTURER = "Tecno";
    public static final String NAME = "PHANTOM5";
}
