// This file is automatically generated.

package adila.db;

/*
 * Tecno J5
 *
 * DEVICE: TECNO-J5
 * MODEL: TECNO-J5
 */
final class tecno2dj5_tecno2dj5 {
    public static final String MANUFACTURER = "Tecno";
    public static final String NAME = "J5";
}
