// This file is automatically generated.

package adila.db;

/*
 * Telenor Telenor Smart
 *
 * DEVICE: Telenor_Smart
 * MODEL: Telenor_Smart
 */
final class telenor5fsmart_telenor5fsmart {
    public static final String MANUFACTURER = "Telenor";
    public static final String NAME = "Telenor Smart";
}
