// This file is automatically generated.

package adila.db;

/*
 * Alcatel OWN S4010
 *
 * DEVICE: Telsa
 * MODEL: OWN S4010
 */
final class telsa_own20s4010 {
    public static final String DATA = "Alcatel|OWN S4010|";
}
