// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL_6110A
 *
 * DEVICE: Telsa
 * MODEL: TCL 6110A
 */
final class telsa_tcl206110a {
    public static final String DATA = "Alcatel|TCL_6110A|";
}
