// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 6010X
 *
 * DEVICE: Telsa
 * MODEL: ALCATEL ONE TOUCH 6010X-orange
 */
final class telsa_alcatel20one20touch206010x2dorange {
    public static final String DATA = "Alcatel|ONE TOUCH 6010X|";
}
