// This file is automatically generated.

package adila.db;

/*
 * Sony SmartWatch 3
 *
 * DEVICE: tetra
 * MODEL: SmartWatch 3
 */
final class tetra {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "SmartWatch 3";
}
