// This file is automatically generated.

package adila.db;

/*
 * Asus ETBW11AA
 *
 * DEVICE: TF101G
 * MODEL: ETBW11AA
 */
final class tf101g_etbw11aa {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ETBW11AA";
}
