// This file is automatically generated.

package adila.db;

/*
 * Asus Eee Pad TF101
 *
 * DEVICE: TF101
 * MODEL: Transformer TF101
 */
final class tf101_transformer20tf101 {
    public static final String DATA = "Asus|Eee Pad TF101|";
}
