// This file is automatically generated.

package adila.db;

/*
 * Asus Eee Pad Transformer Prime
 *
 * DEVICE: TF201
 * MODEL: Transformer Prime TF201
 */
final class tf201_transformer20prime20tf201 {
    public static final String DATA = "Asus|Eee Pad Transformer Prime|";
}
