// This file is automatically generated.

package adila.db;

/*
 * Asus Transformer Pad TF502T
 *
 * DEVICE: TF502T
 * MODEL: ASUS Transformer Pad TF502T
 */
final class tf502t_asus20transformer20pad20tf502t {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "Transformer Pad TF502T";
}
