// This file is automatically generated.

package adila.db;

/*
 * Asus Transformer Pad Infinity
 *
 * DEVICE: TF700KL
 * MODEL: ASUS Transformer Pad TF700KL
 */
final class tf700kl_asus20transformer20pad20tf700kl {
    public static final String DATA = "Asus|Transformer Pad Infinity|";
}
