// This file is automatically generated.

package adila.db;

/*
 * Fujitsu REGZA Phone T-01C
 *
 * DEVICE: tg03
 * MODEL: IS04
 */
final class tg03_is04 {
    public static final String DATA = "Fujitsu|REGZA Phone T-01C|";
}
