// This file is automatically generated.

package adila.db;

/*
 * Condor TGW801G
 *
 * DEVICE: TGW801G
 * MODEL: TGW801G
 */
final class tgw801g_tgw801g {
    public static final String DATA = "Condor|TGW801G|";
}
