// This file is automatically generated.

package adila.db;

/*
 * Panasonic TH-65DR800C
 *
 * DEVICE: TH-65DR800C
 * MODEL: TH-65DR800C
 */
final class th2d65dr800c_th2d65dr800c {
    public static final String DATA = "Panasonic|TH-65DR800C|";
}
