// This file is automatically generated.

package adila.db;

/*
 * Panasonic TH-55DX700C
 *
 * DEVICE: TH_55DX700C
 * MODEL: TH_55DX700C
 */
final class th5f55dx700c_th5f55dx700c {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "TH-55DX700C";
}
