// This file is automatically generated.

package adila.db;

/*
 * KAZAM Thunder 550L
 *
 * DEVICE: TH5L5025
 * MODEL: KAZAM Thunder 550L
 */
final class th5l5025_kazam20thunder20550l {
    public static final String DATA = "KAZAM|Thunder 550L|";
}
