// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto G with 4G LTE (2nd Gen)
 *
 * DEVICE: thea
 * MODEL: XT1072
 */
final class thea {
    public static final String DATA = "Motorola|Moto G with 4G LTE (2nd Gen)|";
}
