// This file is automatically generated.

package adila.db;

/*
 * LG Optimus One
 *
 * DEVICE: thunderc
 * MODEL: LG-MS690
 */
final class thunderc_lg2dms690 {
    public static final String DATA = "LG|Optimus One|";
}
