// This file is automatically generated.

package adila.db;

/*
 * KAZAM Thunder 347
 *
 * DEVICE: Thunder_347
 * MODEL: Thunder 347
 */
final class thunder5f347_thunder20347 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "Thunder 347";
}
