// This file is automatically generated.

package adila.db;

/*
 * InFocus M510
 *
 * DEVICE: TID_CHT
 * MODEL: M510
 */
final class tid5fcht_m510 {
    public static final String MANUFACTURER = "InFocus";
    public static final String NAME = "M510";
}
