// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto Defy XT
 *
 * DEVICE: tinboostplus_cdma
 * MODEL: XT556
 */
final class tinboostplus5fcdma_xt556 {
    public static final String DATA = "Motorola|Moto Defy XT|";
}
