// This file is automatically generated.

package adila.db;

/*
 * Motorola Moto G (2nd Gen)
 *
 * DEVICE: titan_umts
 * MODEL: XT1064
 */
final class titan5fumts_xt1064 {
    public static final String DATA = "Motorola|Moto G (2nd Gen)|";
}
