// This file is automatically generated.

package adila.db;

/*
 * Gigabyte TM105
 *
 * DEVICE: TM105
 * MODEL: TM105
 */
final class tm105_tm105 {
    public static final String MANUFACTURER = "Gigabyte";
    public static final String NAME = "TM105";
}
