// This file is automatically generated.

package adila.db;

/*
 * i-Buddie TM75A-V2
 *
 * DEVICE: TM75A-V2
 * MODEL: TM75A-V2
 */
final class tm75a2dv2_tm75a2dv2 {
    public static final String DATA = "i-Buddie|TM75A-V2|";
}
