// This file is automatically generated.

package adila.db;

/*
 * Gigabyte TM75A
 *
 * DEVICE: TM75A
 * MODEL: GSmart7Tab
 */
final class tm75a_gsmart7tab {
    public static final String MANUFACTURER = "Gigabyte";
    public static final String NAME = "TM75A";
}
