// This file is automatically generated.

package adila.db;

/*
 * Nuvision TM800A510L
 *
 * DEVICE: TM800A
 * MODEL: TM800A510L
 */
final class tm800a_tm800a510l {
    public static final String MANUFACTURER = "Nuvision";
    public static final String NAME = "TM800A510L";
}
