// This file is automatically generated.

package adila.db;

/*
 * KAZAM Tornado2 50
 *
 * DEVICE: Tornado2_50
 * MODEL: KAZAM Tornado2 50
 */
final class tornado25f50_kazam20tornado22050 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "Tornado2 50";
}
