// This file is automatically generated.

package adila.db;

/*
 * Toshiba A205
 *
 * DEVICE: tos15ast20
 * MODEL: A205
 */
final class tos15ast20 {
    public static final String MANUFACTURER = "Toshiba";
    public static final String NAME = "A205";
}
