// This file is automatically generated.

package adila.db;

/*
 * Toshiba AT7-C
 *
 * DEVICE: tos14riy20
 * MODEL: AT7-C
 */
final class tos14riy20_at72dc {
    public static final String MANUFACTURER = "Toshiba";
    public static final String NAME = "AT7-C";
}
