// This file is automatically generated.

package adila.db;

/*
 * Toshiba AT10-A/AT15-A (Japan: AT503)
 *
 * DEVICE: tostab12BL
 * MODEL: AT503
 */
final class tostab12bl_at503 {
    public static final String MANUFACTURER = "Toshiba";
    public static final String NAME = "AT10-A/AT15-A (Japan: AT503)";
}
