// This file is automatically generated.

package adila.db;

/*
 * Toshiba JP:REGZA Tablet AT570  Others:TOSHIBA AT270
 *
 * DEVICE: tostab11BS
 * MODEL: AT570
 */
final class tostab11bs_at570 {
    public static final String DATA = "Toshiba|JP:REGZA Tablet AT570  Others:TOSHIBA AT270|";
}
