// This file is automatically generated.

package adila.db;

/*
 * Toshiba JPN:REGZA Tablet AT500  Other countries:TOSHIBA AT300
 *
 * DEVICE: tostab11BA
 * MODEL: AT500
 */
final class tostab11ba_at500 {
    public static final String DATA = "Toshiba|JPN:REGZA Tablet AT500  Other countries:TOSHIBA AT300|";
}
