// This file is automatically generated.

package adila.db;

/*
 * Toshiba L5550/L5551/L5552
 *
 * DEVICE: tostv15rtk2
 * MODEL: l5550
 */
final class tostv15rtk2 {
    public static final String MANUFACTURER = "Toshiba";
    public static final String NAME = "L5550/L5551/L5552";
}
