// This file is automatically generated.

package adila.db;

/*
 * Panasonic FZ-A1B
 *
 * DEVICE: toughpad
 * MODEL: FZ-A1B
 */
final class toughpad {
    public static final String MANUFACTURER = "Panasonic";
    public static final String NAME = "FZ-A1B";
}
