// This file is automatically generated.

package adila.db;

/*
 * Hisense 
 *
 * DEVICE: TP9101
 * MODEL: HS-M170AT
 */
final class tp9101_hs2dm170at {
    public static final String MANUFACTURER = "Hisense";
}
