// This file is automatically generated.

package adila.db;

/*
 * MG series Any 303
 *
 * DEVICE: TR10CD2_3
 * MODEL: TR10CD2
 */
final class tr10cd25f3_tr10cd2 {
    public static final String MANUFACTURER = "MG series";
    public static final String NAME = "Any 303";
}
