// This file is automatically generated.

package adila.db;

/*
 * ECS TR10CS1
 *
 * DEVICE: TR10CS1_8
 * MODEL: TR10CS1
 */
final class tr10cs15f8_tr10cs1 {
    public static final String MANUFACTURER = "ECS";
    public static final String NAME = "TR10CS1";
}
