// This file is automatically generated.

package adila.db;

/*
 * i-Buddie TR10CS1
 *
 * DEVICE: TR10CS1_2
 * MODEL: TR10CS1
 */
final class tr10cs15f2_tr10cs1 {
    public static final String DATA = "i-Buddie|TR10CS1|";
}
