// This file is automatically generated.

package adila.db;

/*
 * Intel TR10CD1(PVT2)
 *
 * DEVICE: TR10CD1_6
 * MODEL: TR10CD1
 */
final class tr10cd15f6_tr10cd1 {
    public static final String MANUFACTURER = "Intel";
    public static final String NAME = "TR10CD1(PVT2)";
}
