// This file is automatically generated.

package adila.db;

/*
 * i-Buddie TR10CD1
 *
 * DEVICE: TR10CD1_2
 * MODEL: TR10CD1
 */
final class tr10cd15f2_tr10cd1 {
    public static final String MANUFACTURER = "i-Buddie";
    public static final String NAME = "TR10CD1";
}
