// This file is automatically generated.

package adila.db;

/*
 * Camelus Camelus L10
 *
 * DEVICE: TR-10HBT
 * MODEL: L10
 */
final class tr2d10hbt_l10 {
    public static final String DATA = "Camelus|Camelus L10|";
}
