// This file is automatically generated.

package adila.db;

/*
 * KAZAM Trooper 445L
 *
 * DEVICE: TR4L4544
 * MODEL: KAZAM Trooper 445L
 */
final class tr4l4544_kazam20trooper20445l {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "Trooper 445L";
}
