// This file is automatically generated.

package adila.db;

/*
 * KAZAM Trooper 540
 *
 * DEVICE: TR54015
 * MODEL: KAZAM Trooper 540
 */
final class tr54015_kazam20trooper20540 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "Trooper 540";
}
