// This file is automatically generated.

package adila.db;

/*
 * KAZAM Trooper 550L
 *
 * DEVICE: TR5L5025
 * MODEL: KAZAM Trooper 550L
 */
final class tr5l5025_kazam20trooper20550l {
    public static final String DATA = "KAZAM|Trooper 550L|";
}
