// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 4
 *
 * DEVICE: tre3caltektt
 * MODEL: SM-N916K
 */
final class tre3caltektt {
    public static final String DATA = "Samsung|Galaxy Note 4|Galaxy Note";
}
