// This file is automatically generated.

package adila.db;

/*
 * Trio Trio AXS 3G
 *
 * DEVICE: Trio_AXS_3G
 * MODEL: Trio AXS 3G
 */
final class trio5faxs5f3g_trio20axs203g {
    public static final String MANUFACTURER = "Trio";
    public static final String NAME = "Trio AXS 3G";
}
