// This file is automatically generated.

package adila.db;

/*
 * Trio Trio 7.85 vQ
 *
 * DEVICE: Trio-785-vQ
 * MODEL: Trio 7.85 vQ
 */
final class trio2d7852dvq_trio2072e8520vq {
    public static final String MANUFACTURER = "Trio";
    public static final String NAME = "Trio 7.85 vQ";
}
