// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 4
 *
 * DEVICE: trlteusc
 * MODEL: SM-N910R4
 */
final class trlteusc {
    public static final String DATA = "Samsung|Galaxy Note 4|Galaxy Note";
}
