// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 4
 *
 * DEVICE: trltechn
 * MODEL: SM-N9106W
 */
final class trltechn_sm2dn9106w {
    public static final String DATA = "Samsung|Galaxy Note 4|Galaxy Note";
}
