// This file is automatically generated.

package adila.db;

/*
 * KAZAM Trooper2 40
 *
 * DEVICE: Trooper2_40
 * MODEL: KAZAM Trooper2 40
 */
final class trooper25f40_kazam20trooper22040 {
    public static final String MANUFACTURER = "KAZAM";
    public static final String NAME = "Trooper2 40";
}
