// This file is automatically generated.

package adila.db;

/*
 * Haier AP54
 *
 * DEVICE: ts18_ap54_kliver
 * MODEL: AP54
 */
final class ts185fap545fkliver {
    public static final String DATA = "Haier|AP54|";
}
