// This file is automatically generated.

package adila.db;

/*
 * Motorola 
 *
 * DEVICE: ttu_skt
 * MODEL: XT800W
 */
final class ttu5fskt {
    public static final String MANUFACTURER = "Motorola";
}
