// This file is automatically generated.

package adila.db;

/*
 * Plaisio Turbo-X_pi_4G
 *
 * DEVICE: Turbo-X_pi_4G
 * MODEL: Turbo-X_pi_4G
 */
final class turbo2dx5fpi5f4g_turbo2dx5fpi5f4g {
    public static final String MANUFACTURER = "Plaisio";
    public static final String NAME = "Turbo-X_pi_4G";
}
