// This file is automatically generated.

package adila.db;

/*
 * ZTE T60
 *
 * DEVICE: turies
 * MODEL: ZTE T60
 */
final class turies_zte20t60 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "T60";
}
