// This file is automatically generated.

package adila.db;

/*
 * LGU+ U+ tv UHD
 *
 * DEVICE: tvg2
 * MODEL: ST940I-UP
 */
final class tvg2 {
    public static final String DATA = "LGU+|U+ tv UHD|";
}
