// This file is automatically generated.

package adila.db;

/*
 * Sony Xperia Tablet S
 *
 * DEVICE: txs03
 * MODEL: SGPT12
 */
final class txs03_sgpt12 {
    public static final String MANUFACTURER = "Sony";
    public static final String NAME = "Xperia Tablet S";
}
