// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L7
 *
 * DEVICE: u0
 * MODEL: LG-P708g
 */
final class u0_lg2dp708g {
    public static final String DATA = "LG|Optimus L7|";
}
