// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Camera
 *
 * DEVICE: u0lte
 * MODEL: EK-GN120
 */
final class u0lte_ek2dgn120 {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Camera";
}
