// This file is automatically generated.

package adila.db;

/*
 * U606 Hisense
 *
 * DEVICE: U606
 * MODEL: STARSHINE III
 */
final class u606_starshine20iii {
    public static final String DATA = "U606|Hisense|";
}
