// This file is automatically generated.

package adila.db;

/*
 * Hisense U606AE
 *
 * DEVICE: U606AE
 * MODEL: PHS-402
 */
final class u606ae_phs2d402 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "U606AE";
}
