// This file is automatically generated.

package adila.db;

/*
 * Hisense U610
 *
 * DEVICE: U610E_1
 * MODEL: HS-U610
 */
final class u610e5f1_hs2du610 {
    public static final String DATA = "Hisense|U610|";
}
