// This file is automatically generated.

package adila.db;

/*
 * Oppo U708
 *
 * DEVICE: U708
 * MODEL: U708
 */
final class u708_u708 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "U708";
}
