// This file is automatically generated.

package adila.db;

/*
 * Hisense 
 *
 * DEVICE: U820A
 * MODEL: HS-U820
 */
final class u820a_hs2du820 {
    public static final String MANUFACTURER = "Hisense";
}
