// This file is automatically generated.

package adila.db;

/*
 * Huawei U8230
 *
 * DEVICE: U8230
 * MODEL: U8230
 */
final class u8230_u8230 {
    public static final String MANUFACTURER = "Huawei";
    public static final String NAME = "U8230";
}
