// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U912
 *
 * DEVICE: U912A_1
 * MODEL: HS-U912
 */
final class u912a5f1_hs2du912 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-U912";
}
