// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U929
 *
 * DEVICE: u929de
 * MODEL: HS-U929
 */
final class u929de {
    public static final String DATA = "Hisense|HS-U929|";
}
