// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U936
 *
 * DEVICE: U936
 * MODEL: HS-U936
 */
final class u936_hs2du936 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-U936";
}
