// This file is automatically generated.

package adila.db;

/*
 * Condor HS-U939
 *
 * DEVICE: u939e_6
 * MODEL: HS-U939
 */
final class u939e5f6 {
    public static final String MANUFACTURER = "Condor";
    public static final String NAME = "HS-U939";
}
