// This file is automatically generated.

package adila.db;

/*
 * Hisense 
 *
 * DEVICE: U950_ae
 * MODEL: HS-U950
 */
final class u9505fae_hs2du950 {
    public static final String MANUFACTURER = "Hisense";
}
