// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: U960s3
 * MODEL: ZTE U960s3
 */
final class u960s3_zte20u960s3 {
    public static final String DATA = "ZTE||";
}
