// This file is automatically generated.

package adila.db;

/*
 * SKnetworks WA966
 *
 * DEVICE: u966e_2
 * MODEL: WA966
 */
final class u966e5f2 {
    public static final String MANUFACTURER = "SKnetworks";
    public static final String NAME = "WA966";
}
