// This file is automatically generated.

package adila.db;

/*
 * Etuline ETL-S5042
 *
 * DEVICE: u970_4
 * MODEL: ETL-S5042
 */
final class u9705f4 {
    public static final String DATA = "Etuline|ETL-S5042|";
}
