// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U970
 *
 * DEVICE: u970s_export
 * MODEL: HS-U970
 */
final class u970s5fexport {
    public static final String DATA = "Hisense|HS-U970|";
}
