// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U980
 *
 * DEVICE: u980b
 * MODEL: HS-U980
 */
final class u980b {
    public static final String DATA = "Hisense|HS-U980|";
}
