// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-U980
 *
 * DEVICE: u980ce_1
 * MODEL: HS-U980
 */
final class u980ce5f1 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-U980";
}
