// This file is automatically generated.

package adila.db;

/*
 * Hisense U988E-1
 *
 * DEVICE: U988E_1
 * MODEL: HS-U988
 */
final class u988e5f1_hs2du988 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "U988E-1";
}
