// This file is automatically generated.

package adila.db;

/*
 * Hyundai Ultra Energy Plus
 *
 * DEVICE: Ultra_Energy_Plus
 * MODEL: Ultra Energy Plus
 */
final class ultra5fenergy5fplus_ultra20energy20plus {
    public static final String DATA = "Hyundai|Ultra Energy Plus|";
}
