// This file is automatically generated.

package adila.db;

/*
 * Motorola XOOM
 *
 * DEVICE: umts_hubble
 * MODEL: MZ601
 */
final class umts5fhubble_mz601 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "XOOM";
}
