// This file is automatically generated.

package adila.db;

/*
 * Motorola Droid
 *
 * DEVICE: umts_sholes
 * MODEL: XT701
 */
final class umts5fsholes_xt701 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Droid";
}
