// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Hub
 *
 * DEVICE: univa_724-05
 * MODEL: LG-E510f
 */
final class univa5f7242d05 {
    public static final String DATA = "LG|Optimus Hub|";
}
