// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Hub
 *
 * DEVICE: univa_viv-br
 * MODEL: LG-E510f
 */
final class univa5fviv2dbr {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Hub";
}
