// This file is automatically generated.

package adila.db;

/*
 * LG Optimus HUB
 *
 * DEVICE: univa_eur-xx
 * MODEL: LG-E510
 */
final class univa5feur2dxx {
    public static final String DATA = "LG|Optimus HUB|";
}
