// This file is automatically generated.

package adila.db;

/*
 * LG Optimus HUB
 *
 * DEVICE: univa_cis-xxx
 * MODEL: LG-E510
 */
final class univa5fcis2dxxx {
    public static final String DATA = "LG|Optimus HUB|";
}
