// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Hub
 *
 * DEVICE: univa_ssv-xxx
 * MODEL: LG-E510g
 */
final class univa5fssv2dxxx {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Hub";
}
