// This file is automatically generated.

package adila.db;

/*
 * Odys ODYS UNO X10
 *
 * DEVICE: UNO_X10
 * MODEL: UNO X10
 */
final class uno5fx10_uno20x10 {
    public static final String DATA = "Odys|ODYS UNO X10|";
}
