// This file is automatically generated.

package adila.db;

/*
 * Odys ODYS UNO X8
 *
 * DEVICE: UNO_X8
 * MODEL: UNO_X8
 */
final class uno5fx8_uno5fx8 {
    public static final String DATA = "Odys|ODYS UNO X8|";
}
