// This file is automatically generated.

package adila.db;

/*
 * Tecno M3
 *
 * DEVICE: up11_tecno_m3s
 * MODEL: TECNO M3S
 */
final class up115ftecno5fm3s {
    public static final String DATA = "Tecno|M3|";
}
