// This file is automatically generated.

package adila.db;

/*
 * Hisense XOLO
 *
 * DEVICE: us9230e1
 * MODEL: XOLO T1000
 */
final class us9230e1 {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "XOLO";
}
