// This file is automatically generated.

package adila.db;

/*
 * Gigaset QV830
 *
 * DEVICE: UY8
 * MODEL: Gigaset QV830
 */
final class uy8_gigaset20qv830 {
    public static final String MANUFACTURER = "Gigaset";
    public static final String NAME = "QV830";
}
