// This file is automatically generated.

package adila.db;

/*
 * ENVIZEN DIGITAL V100MD
 *
 * DEVICE: V100MD
 * MODEL: V100MD
 */
final class v100md_v100md {
    public static final String DATA = "ENVIZEN DIGITAL|V100MD|";
}
