// This file is automatically generated.

package adila.db;

/*
 * AllView V1 Viper I4G
 *
 * DEVICE: V1_Viper_I4G
 * MODEL: V1_Viper_I4G
 */
final class v15fviper5fi4g_v15fviper5fi4g {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "V1 Viper I4G";
}
