// This file is automatically generated.

package adila.db;

/*
 * Wiko SUNNY
 *
 * DEVICE: V2504AN
 * MODEL: SUNNY
 */
final class v2504an_sunny {
    public static final String DATA = "Wiko|SUNNY|";
}
