// This file is automatically generated.

package adila.db;

/*
 * AllView V2 Viper I
 *
 * DEVICE: V2_Viper_I
 * MODEL: V2_Viper_I
 */
final class v25fviper5fi_v25fviper5fi {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "V2 Viper I";
}
