// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Tab Pro 12.2
 *
 * DEVICE: v2lte
 * MODEL: SM-T905
 */
final class v2lte {
    public static final String DATA = "Samsung|Galaxy Tab Pro 12.2|Galaxy Tab";
}
