// This file is automatically generated.

package adila.db;

/*
 * Lava V2s
 *
 * DEVICE: V2s
 * MODEL: V2s
 */
final class v2s_v2s {
    public static final String MANUFACTURER = "Lava";
    public static final String NAME = "V2s";
}
