// This file is automatically generated.

package adila.db;

/*
 * Wiko U FEEL FAB
 *
 * DEVICE: V3991AN
 * MODEL: SUGAR Y7 MAX
 */
final class v3991an_sugar20y720max {
    public static final String DATA = "Wiko|U FEEL FAB|";
}
