// This file is automatically generated.

package adila.db;

/*
 * Vivo V3
 *
 * DEVICE: V3
 * MODEL: vivo V3
 */
final class v3_vivo20v3 {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "V3";
}
