// This file is automatically generated.

package adila.db;

/*
 * ZTE V55
 *
 * DEVICE: V55
 * MODEL: V55
 */
final class v55_v55 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V55";
}
