// This file is automatically generated.

package adila.db;

/*
 * ZTE Q806T
 *
 * DEVICE: V_P635T30
 * MODEL: ZTE Q806T
 */
final class v5fp635t30_zte20q806t {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Q806T";
}
