// This file is automatically generated.

package adila.db;

/*
 * Vestel V TAB 8029
 *
 * DEVICE: V_TAB_8029
 * MODEL: V TAB 8029
 */
final class v5ftab5f8029_v20tab208029 {
    public static final String DATA = "Vestel|V TAB 8029|";
}
