// This file is automatically generated.

package adila.db;

/*
 * ZTE STARNAUTE II
 *
 * DEVICE: V6600
 * MODEL: STARNAUTE II
 */
final class v6600_starnaute20ii {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "STARNAUTE II";
}
