// This file is automatically generated.

package adila.db;

/*
 * Gionee ForwardZero
 *
 * DEVICE: V6L
 * MODEL: V6L
 */
final class v6l_v6l {
    public static final String DATA = "Gionee|ForwardZero|";
}
