// This file is automatically generated.

package adila.db;

/*
 * ZTE LEO M1
 *
 * DEVICE: V883M
 * MODEL: ZTE LEO M1
 */
final class v883m_zte20leo20m1 {
    public static final String DATA = "ZTE|LEO M1|";
}
