// This file is automatically generated.

package adila.db;

/*
 * ZTE LEO M1
 *
 * DEVICE: V883M
 * MODEL: V883M
 */
final class v883m_v883m {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "LEO M1";
}
