// This file is automatically generated.

package adila.db;

/*
 * ZTE LEO S1
 *
 * DEVICE: V972M
 * MODEL: ZTE LEO S1
 */
final class v972m_zte20leo20s1 {
    public static final String DATA = "ZTE|LEO S1|";
}
