// This file is automatically generated.

package adila.db;

/*
 * ZTE V9
 *
 * DEVICE: v9
 * MODEL: BLACK 03
 */
final class v9_black2003 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V9";
}
