// This file is automatically generated.

package adila.db;

/*
 * ZTE V9
 *
 * DEVICE: v9
 * MODEL: V9C
 */
final class v9_v9c {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V9";
}
