// This file is automatically generated.

package adila.db;

/*
 * ZTE V9A
 *
 * DEVICE: v9plus
 * MODEL: my Pad P3
 */
final class v9plus_my20pad20p3 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "V9A";
}
