// This file is automatically generated.

package adila.db;

/*
 * ZTE Light Tab 2
 *
 * DEVICE: v9plus
 * MODEL: Light Tab 2
 */
final class v9plus_light20tab202 {
    public static final String DATA = "ZTE|Light Tab 2|";
}
