// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Mega 2
 *
 * DEVICE: vastalte
 * MODEL: SM-G7508Q
 */
final class vastalte {
    public static final String DATA = "Samsung|Galaxy Mega 2|";
}
