// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L3 II
 *
 * DEVICE: vee3e
 * MODEL: LG-E430
 */
final class vee3e_lg2de430 {
    public static final String DATA = "LG|Optimus L3 II|";
}
