// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L5 II
 *
 * DEVICE: vee5ss
 * MODEL: LG-E450g
 */
final class vee5ss_lg2de450g {
    public static final String DATA = "LG|Optimus L5 II|";
}
