// This file is automatically generated.

package adila.db;

/*
 * LG Optimus L7 II
 *
 * DEVICE: vee7e
 * MODEL: LG-P714
 */
final class vee7e_lg2dp714 {
    public static final String DATA = "LG|Optimus L7 II|";
}
