// This file is automatically generated.

package adila.db;

/*
 * BlackBerry Priv
 *
 * DEVICE: venice
 * MODEL: STV100-3
 */
final class venice_stv1002d3 {
    public static final String MANUFACTURER = "BlackBerry";
    public static final String NAME = "Priv";
}
