// This file is automatically generated.

package adila.db;

/*
 * ZTE 
 *
 * DEVICE: ventana_U880F
 * MODEL: ZTE U880F
 */
final class ventana5fu880f_zte20u880f {
    public static final String MANUFACTURER = "ZTE";
}
