// This file is automatically generated.

package adila.db;

/*
 * Edcon VERSSED platinum vp.2.1
 *
 * DEVICE: VERSSEDvp2-1
 * MODEL: VERSSED vp2.1
 */
final class verssedvp22d1_verssed20vp22e1 {
    public static final String MANUFACTURER = "Edcon";
    public static final String NAME = "VERSSED platinum vp.2.1";
}
