// This file is automatically generated.

package adila.db;

/*
 * Vodafone VF695
 *
 * DEVICE: VF695
 * MODEL: VF695
 */
final class vf695_vf695 {
    public static final String DATA = "Vodafone|VF695|";
}
