// This file is automatically generated.

package adila.db;

/*
 * LG Wine Smart
 *
 * DEVICE: vfp
 * MODEL: LG-F480S
 */
final class vfp_lg2df480s {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Wine Smart";
}
