// This file is automatically generated.

package adila.db;

/*
 * Casper VIA T7D 3G
 *
 * DEVICE: VIA-T7D-3G
 * MODEL: VIA-T7D-3G
 */
final class via2dt7d2d3g_via2dt7d2d3g {
    public static final String DATA = "Casper|VIA T7D 3G|";
}
