// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Sol
 *
 * DEVICE: victor
 * MODEL: LG-E730
 */
final class victor_lg2de730 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Sol";
}
