// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Core Lite
 *
 * DEVICE: victorlte
 * MODEL: SM-G3586V
 */
final class victorlte_sm2dg3586v {
    public static final String DATA = "Samsung|Galaxy Core Lite|";
}
