// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note Pro 12.2
 *
 * DEVICE: viennalte
 * MODEL: SM-P905
 */
final class viennalte_sm2dp905 {
    public static final String DATA = "Samsung|Galaxy Note Pro 12.2|Galaxy Note";
}
