// This file is automatically generated.

package adila.db;

/*
 * ViewSonic Viewsonic
 *
 * DEVICE: ViewPad_IR8Q
 * MODEL: IR8Q
 */
final class viewpad5fir8q_ir8q {
    public static final String MANUFACTURER = "ViewSonic";
    public static final String NAME = "Viewsonic";
}
