// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace 4
 *
 * DEVICE: vivalto3g
 * MODEL: SM-G313ML
 */
final class vivalto3g_sm2dg313ml {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Ace 4";
}
