// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Ace 4 Lite
 *
 * DEVICE: vivalto3mveml3gsea
 * MODEL: SM-G318MZ
 */
final class vivalto3mveml3gsea_sm2dg318mz {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy Ace 4 Lite";
}
