// This file is automatically generated.

package adila.db;

/*
 * AllView Viva i7G
 *
 * DEVICE: Viva_i7G
 * MODEL: Viva_i7G
 */
final class viva5fi7g_viva5fi7g {
    public static final String MANUFACTURER = "AllView";
    public static final String NAME = "Viva i7G";
}
