// This file is automatically generated.

package adila.db;

/*
 * InFocus M810t
 *
 * DEVICE: VNA
 * MODEL: InFocus M810t
 */
final class vna_infocus20m810t {
    public static final String DATA = "InFocus|M810t|";
}
