// This file is automatically generated.

package adila.db;

/*
 * Coolpad VodafoneSmart4turbo
 *
 * DEVICE: VodafoneSmart4turbo
 * MODEL: Vodafone Smart 4 turbo
 */
final class vodafonesmart4turbo_vodafone20smart20420turbo {
    public static final String MANUFACTURER = "Coolpad";
    public static final String NAME = "VodafoneSmart4turbo";
}
