// This file is automatically generated.

package adila.db;

/*
 * Alcatel Vodafone Smart III
 *
 * DEVICE: Vodafone_975
 * MODEL: Vodafone 975
 */
final class vodafone5f975_vodafone20975 {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "Vodafone Smart III";
}
