// This file is automatically generated.

package adila.db;

/*
 * ViewSonic VSD241 Smart Display
 *
 * DEVICE: VSD241
 * MODEL: VSD241
 */
final class vsd241_vsd241 {
    public static final String MANUFACTURER = "ViewSonic";
    public static final String NAME = "VSD241 Smart Display";
}
