// This file is automatically generated.

package adila.db;

/*
 * Mobiwire V.45
 *
 * DEVICE: VSN
 * MODEL: V.45S
 */
final class vsn_v2e45s {
    public static final String MANUFACTURER = "Mobiwire";
    public static final String NAME = "V.45";
}
