// This file is automatically generated.

package adila.db;

/*
 * Vulcan Vulcan Pulse 7
 *
 * DEVICE: VT0701A08
 * MODEL: VT0701A08
 */
final class vt0701a08_vt0701a08 {
    public static final String MANUFACTURER = "Vulcan";
    public static final String NAME = "Vulcan Pulse 7";
}
