// This file is automatically generated.

package adila.db;

/*
 * Vulcan Vulcan Pulse 7S
 *
 * DEVICE: VT0702A16
 * MODEL: VT0702A16
 */
final class vt0702a16_vt0702a16 {
    public static final String MANUFACTURER = "Vulcan";
    public static final String NAME = "Vulcan Pulse 7S";
}
