// This file is automatically generated.

package adila.db;

/*
 * Vestel VT10E2
 *
 * DEVICE: VT10E2
 * MODEL: VT10E2
 */
final class vt10e2_vt10e2 {
    public static final String DATA = "Vestel|VT10E2|";
}
