// This file is automatically generated.

package adila.db;

/*
 * Panasonic Boukenkun-reciever
 *
 * DEVICE: VW_RCBKK1
 * MODEL: VW_RCBKK1
 */
final class vw5frcbkk1_vw5frcbkk1 {
    public static final String DATA = "Panasonic|Boukenkun-reciever|";
}
