// This file is automatically generated.

package adila.db;

/*
 * STK Storm 3
 *
 * DEVICE: W230
 * MODEL: STK Storm 3
 */
final class w230_stk20storm203 {
    public static final String DATA = "STK|Storm 3|Storm";
}
