// This file is automatically generated.

package adila.db;

/*
 * Santok Storm 3
 *
 * DEVICE: W230
 * MODEL: STK Storm 3
 */
final class w230_stk20storm203 {
    public static final String MANUFACTURER = "Santok";
    public static final String NAME = "Storm 3";
}
