// This file is automatically generated.

package adila.db;

/*
 * LG Optimus Zone 2
 *
 * DEVICE: w3c
 * MODEL: VS415PP
 */
final class w3c_vs415pp {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Optimus Zone 2";
}
