// This file is automatically generated.

package adila.db;

/*
 * LG L70
 *
 * DEVICE: w5
 * MODEL: LGMS323
 */
final class w5_lgms323 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "L70";
}
