// This file is automatically generated.

package adila.db;

/*
 * LG L70
 *
 * DEVICE: w5ts
 * MODEL: LG-D340f8
 */
final class w5ts {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "L70";
}
