// This file is automatically generated.

package adila.db;

/*
 * LG L80 Single
 *
 * DEVICE: w6
 * MODEL: LG-D373
 */
final class w6_lg2dd373 {
    public static final String DATA = "LG|L80 Single|";
}
