// This file is automatically generated.

package adila.db;

/*
 * QMobile W80
 *
 * DEVICE: WBW5615QM
 * MODEL: W80
 */
final class wbw5615qm_w80 {
    public static final String MANUFACTURER = "QMobile";
    public static final String NAME = "W80";
}
