// This file is automatically generated.

package adila.db;

/*
 * Vestel VP74
 *
 * DEVICE: wifionly-gms
 * MODEL: VP74-Orava
 */
final class wifionly2dgms_vp742dorava {
    public static final String MANUFACTURER = "Vestel";
    public static final String NAME = "VP74";
}
