// This file is automatically generated.

package adila.db;

/*
 * Vestel VP74
 *
 * DEVICE: wifionly-gms
 * MODEL: VP74-Finlux
 */
final class wifionly2dgms_vp742dfinlux {
    public static final String DATA = "Vestel|VP74|";
}
