// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Win Pro
 *
 * DEVICE: wilcoxctc
 * MODEL: SM-G3819
 */
final class wilcoxctc_sm2dg3819 {
    public static final String DATA = "Samsung|Galaxy Win Pro|";
}
