// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S3 Slim
 *
 * DEVICE: wilcoxds
 * MODEL: SM-G3812B
 */
final class wilcoxds_sm2dg3812b {
    public static final String DATA = "Samsung|Galaxy S3 Slim|Galaxy S";
}
