// This file is automatically generated.

package adila.db;

/*
 * Vestel VP73
 *
 * DEVICE: wing-ibt
 * MODEL: VP73_Myros
 */
final class wing2dibt_vp735fmyros {
    public static final String DATA = "Vestel|VP73|";
}
