// This file is automatically generated.

package adila.db;

/*
 * Polaroid A/S8
 *
 * DEVICE: wing-AS8
 * MODEL: A/S8
 */
final class wing2das8_a2fs8 {
    public static final String DATA = "Polaroid|A/S8|";
}
