// This file is automatically generated.

package adila.db;

/*
 * Wink City S
 *
 * DEVICE: Wink_City_S
 * MODEL: Wink_City_S
 */
final class wink5fcity5fs_wink5fcity5fs {
    public static final String DATA = "Wink|City S|";
}
