// This file is automatically generated.

package adila.db;

/*
 * Sourcing Creation Wooze I 5.5 Gris
 *
 * DEVICE: Wooze_I55
 * MODEL: Wooze_I55
 */
final class wooze5fi55_wooze5fi55 {
    public static final String DATA = "Sourcing Creation|Wooze I 5.5 Gris|";
}
