// This file is automatically generated.

package adila.db;

/*
 * Allview X2 Soul Style
 *
 * DEVICE: X2_Soul_Style
 * MODEL: X2_Soul_Style
 */
final class x25fsoul5fstyle_x25fsoul5fstyle {
    public static final String DATA = "Allview|X2 Soul Style|";
}
