// This file is automatically generated.

package adila.db;

/*
 * Aikun RX300
 *
 * DEVICE: X300
 * MODEL: X300
 */
final class x300_x300 {
    public static final String MANUFACTURER = "Aikun";
    public static final String NAME = "RX300";
}
