// This file is automatically generated.

package adila.db;

/*
 * QMobile X32
 *
 * DEVICE: X32
 * MODEL: QMobile X32
 */
final class x32_qmobile20x32 {
    public static final String MANUFACTURER = "QMobile";
    public static final String NAME = "X32";
}
