// This file is automatically generated.

package adila.db;

/*
 * LeTV Le X507
 *
 * DEVICE: X3_HK
 * MODEL: Le X507
 */
final class x35fhk_le20x507 {
    public static final String DATA = "LeTV|Le X507|";
}
