// This file is automatically generated.

package adila.db;

/*
 * Auchan Selecline X35T
 *
 * DEVICE: X35T
 * MODEL: X35T
 */
final class x35t_x35t {
    public static final String MANUFACTURER = "Auchan";
    public static final String NAME = "Selecline X35T";
}
