// This file is automatically generated.

package adila.db;

/*
 * Infinix HOT 4 PRO
 *
 * DEVICE: X556
 * MODEL: Infinix HOT 4 Pro
 */
final class x556_infinix20hot20420pro {
    public static final String DATA = "Infinix|HOT 4 PRO|";
}
