// This file is automatically generated.

package adila.db;

/*
 * Ashna X55
 *
 * DEVICE: X55
 * MODEL: X55
 */
final class x55_x55 {
    public static final String MANUFACTURER = "Ashna";
    public static final String NAME = "X55";
}
