// This file is automatically generated.

package adila.db;

/*
 * Cubot MAX
 *
 * DEVICE: x6069_cubot_5365u
 * MODEL: CUBOT MAX
 */
final class x60695fcubot5f5365u {
    public static final String DATA = "Cubot|MAX|";
}
