// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-X6T
 *
 * DEVICE: X6T
 * MODEL: HS-X6T
 */
final class x6t_hs2dx6t {
    public static final String DATA = "Hisense|HS-X6T|";
}
