// This file is automatically generated.

package adila.db;

/*
 * Lava X81
 *
 * DEVICE: X81
 * MODEL: X81
 */
final class x81_x81 {
    public static final String MANUFACTURER = "Lava";
    public static final String NAME = "X81";
}
