// This file is automatically generated.

package adila.db;

/*
 * Hisense HS-X8U
 *
 * DEVICE: x8u
 * MODEL: HS-X8U
 */
final class x8u {
    public static final String MANUFACTURER = "Hisense";
    public static final String NAME = "HS-X8U";
}
