// This file is automatically generated.

package adila.db;

/*
 * Oppo X9007
 *
 * DEVICE: X9007
 * MODEL: X9007
 */
final class x9007_x9007 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "X9007";
}
