// This file is automatically generated.

package adila.db;

/*
 * Oppo X9077
 *
 * DEVICE: X9077
 * MODEL: X9077
 */
final class x9077_x9077 {
    public static final String MANUFACTURER = "Oppo";
    public static final String NAME = "X9077";
}
