// This file is automatically generated.

package adila.db;

/*
 * BYD X910
 *
 * DEVICE: X910
 * MODEL: XOLO X910
 */
final class x910_xolo20x910 {
    public static final String MANUFACTURER = "BYD";
    public static final String NAME = "X910";
}
