// This file is automatically generated.

package adila.db;

/*
 * Alcatel TCL_Xess_P17AA
 *
 * DEVICE: Xess
 * MODEL: TCL Xess P17AA
 */
final class xess_tcl20xess20p17aa {
    public static final String DATA = "Alcatel|TCL_Xess_P17AA|";
}
