// This file is automatically generated.

package adila.db;

/*
 * Motorola 
 *
 * DEVICE: XT531
 * MODEL: XT531
 */
final class xt531_xt531 {
    public static final String MANUFACTURER = "Motorola";
}
