// This file is automatically generated.

package adila.db;

/*
 * Motorola Motoluxe
 *
 * DEVICE: XT615
 * MODEL: XT615
 */
final class xt615_xt615 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Motoluxe";
}
