// This file is automatically generated.

package adila.db;

/*
 * Vivo Y15S
 *
 * DEVICE: Y15S
 * MODEL: vivo Y15S
 */
final class y15s_vivo20y15s {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "Y15S";
}
