// This file is automatically generated.

package adila.db;

/*
 * LG Y25
 *
 * DEVICE: y25c
 * MODEL: LGL16C
 */
final class y25c {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "Y25";
}
