// This file is automatically generated.

package adila.db;

/*
 * Vivo Y28
 *
 * DEVICE: Y28
 * MODEL: vivo Y28
 */
final class y28_vivo20y28 {
    public static final String MANUFACTURER = "Vivo";
    public static final String NAME = "Y28";
}
