// This file is automatically generated.

package adila.db;

/*
 * Positivo BGH Y400
 *
 * DEVICE: Y400
 * MODEL: Y400
 */
final class y400_y400 {
    public static final String DATA = "Positivo|BGH Y400|";
}
