// This file is automatically generated.

package adila.db;

/*
 * Coolpad Y72-921
 *
 * DEVICE: Y72-921
 * MODEL: Coolpad Y72-921
 */
final class y722d921_coolpad20y722d921 {
    public static final String DATA = "Coolpad|Y72-921|";
}
