// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 7047D
 *
 * DEVICE: YARIS_55
 * MODEL: ALCATEL ONE TOUCH 7047D
 */
final class yaris5f55_alcatel20one20touch207047d {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 7047D";
}
