// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 4033X
 *
 * DEVICE: Yaris_M_GSM
 * MODEL: MS3B
 */
final class yaris5fm5fgsm_ms3b {
    public static final String DATA = "Alcatel|ONE TOUCH 4033X|";
}
