// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 7040E
 *
 * DEVICE: YARISXL
 * MODEL: ALCATEL ONE TOUCH 7040E
 */
final class yarisxl_alcatel20one20touch207040e {
    public static final String DATA = "Alcatel|ONE TOUCH 7040E|";
}
