// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 7041X
 *
 * DEVICE: YARISXL
 * MODEL: ALCATEL ONE TOUCH 7041X
 */
final class yarisxl_alcatel20one20touch207041x {
    public static final String DATA = "Alcatel|ONE TOUCH 7041X|";
}
