// This file is automatically generated.

package adila.db;

/*
 * Alcatel ONE TOUCH 7040K
 *
 * DEVICE: YARISXL
 * MODEL: ALCATEL ONE TOUCH 7040K
 */
final class yarisxl_alcatel20one20touch207040k {
    public static final String MANUFACTURER = "Alcatel";
    public static final String NAME = "ONE TOUCH 7040K";
}
