// This file is automatically generated.

package adila.db;

/*
 * Google Project Tango Tablet Development Kit
 *
 * DEVICE: yellowstone
 * MODEL: Project Tango Tablet Development Kit
 */
final class yellowstone_project20tango20tablet20development20kit {
    public static final String DATA = "Google|Project Tango Tablet Development Kit|";
}
