// This file is automatically generated.

package adila.db;

/*
 * Positivo Ypy 10FTB
 *
 * DEVICE: YPY_10FTB
 * MODEL: YPY_10FTB
 */
final class ypy5f10ftb_ypy5f10ftb {
    public static final String DATA = "Positivo|Ypy 10FTB|";
}
