// This file is automatically generated.

package adila.db;

/*
 * Positivo Ypy S500
 *
 * DEVICE: YPY_S500
 * MODEL: YPY_S500
 */
final class ypy5fs500_ypy5fs500 {
    public static final String MANUFACTURER = "Positivo";
    public static final String NAME = "Ypy S500";
}
