// This file is automatically generated.

package adila.db;

/*
 * Positivo Ypy 07STB
 *
 * DEVICE: YPY_07STB
 * MODEL: YPY_07STB
 */
final class ypy5f07stb_ypy5f07stb {
    public static final String DATA = "Positivo|Ypy 07STB|";
}
