// This file is automatically generated.

package adila.db;

/*
 * Positivo Ypy AB10i
 *
 * DEVICE: Ypy_AB10i
 * MODEL: Ypy AB10i
 */
final class ypy5fab10i_ypy20ab10i {
    public static final String DATA = "Positivo|Ypy AB10i|";
}
