// This file is automatically generated.

package adila.db;

/*
 * Positivo Ypy 10STB
 *
 * DEVICE: YPY_10STB
 * MODEL: YPY_10STB
 */
final class ypy5f10stb_ypy5f10stb {
    public static final String MANUFACTURER = "Positivo";
    public static final String NAME = "Ypy 10STB";
}
