// This file is automatically generated.

package adila.db;

/*
 * Lenovo YogaTablet2 -1050F
 *
 * DEVICE: YT2
 * MODEL: YOGA Tablet 2-1050F
 */
final class yt2_yoga20tablet2022d1050f {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "YogaTablet2 -1050F";
}
