// This file is automatically generated.

package adila.db;

/*
 * Lenovo YogaTbalet2-830F
 *
 * DEVICE: YT2
 * MODEL: YOGA Tablet 2-830F
 */
final class yt2_yoga20tablet2022d830f {
    public static final String MANUFACTURER = "Lenovo";
    public static final String NAME = "YogaTbalet2-830F";
}
