// This file is automatically generated.

package adila.db;

/*
 * Lenovo YT3-X90Y/YOGA3 Tablet Pro
 *
 * DEVICE: YT3
 * MODEL: Lenovo YT3-X90Y
 */
final class yt3_lenovo20yt32dx90y {
    public static final String DATA = "Lenovo|YT3-X90Y/YOGA3 Tablet Pro|";
}
