// This file is automatically generated.

package adila.db;

/*
 * HP 7 VoiceTab
 *
 * DEVICE: yukon
 * MODEL: HP 7 VoiceTab
 */
final class yukon {
    public static final String MANUFACTURER = "HP";
    public static final String NAME = "7 VoiceTab";
}
