// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone 2 (ZE551ML)
 *
 * DEVICE: Z00A
 * MODEL: ASUS_Z00ADA
 */
final class z00a_asus5fz00ada {
    public static final String MANUFACTURER = "Asus";
    public static final String NAME = "ZenFone 2 (ZE551ML)";
}
