// This file is automatically generated.

package adila.db;

/*
 * Asus ZenFone Zoom (ZX551ML)
 *
 * DEVICE: Z00X
 * MODEL: ASUS_Z00XSA
 */
final class z00x_asus5fz00xsa {
    public static final String DATA = "Asus|ZenFone Zoom (ZX551ML)|";
}
