// This file is automatically generated.

package adila.db;

/*
 * Acer Z110
 *
 * DEVICE: Z1
 * MODEL: Z110
 */
final class z1_z110 {
    public static final String MANUFACTURER = "Acer";
    public static final String NAME = "Z110";
}
