// This file is automatically generated.

package adila.db;

/*
 * Zuk Z2 Pro
 *
 * DEVICE: z2_row
 * MODEL: ZUK Z2121
 */
final class z25frow {
    public static final String MANUFACTURER = "Zuk";
    public static final String NAME = "Z2 Pro";
}
