// This file is automatically generated.

package adila.db;

/*
 * LG G Flex2
 *
 * DEVICE: z2
 * MODEL: LG-H959
 */
final class z2_lg2dh959 {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Flex2";
}
