// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 500 dual sim
 *
 * DEVICE: z4dug
 * MODEL: HTC Desire 500 dual sim
 */
final class z4dug_htc20desire2050020dual20sim {
    public static final String DATA = "HTC|Desire 500 dual sim|";
}
