// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 5088
 *
 * DEVICE: z4td
 * MODEL: HTC 5088
 */
final class z4td {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 5088";
}
