// This file is automatically generated.

package adila.db;

/*
 * Acer A3-A11
 *
 * DEVICE: zara
 * MODEL: A3-A11
 */
final class zara_a32da11 {
    public static final String DATA = "Acer|A3-A11|";
}
