// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 601
 *
 * DEVICE: zara
 * MODEL: HTC Desire 601
 */
final class zara_htc20desire20601 {
    public static final String DATA = "HTC|Desire 601|";
}
