// This file is automatically generated.

package adila.db;

/*
 * HTC Desire 601
 *
 * DEVICE: zaracl
 * MODEL: HTC0P4E1
 */
final class zaracl_htc0p4e1 {
    public static final String MANUFACTURER = "HTC";
    public static final String NAME = "Desire 601";
}
