// This file is automatically generated.

package adila.db;

/*
 * InFocus M550 3D
 *
 * DEVICE: ZD1
 * MODEL: InFocus M550 3D
 */
final class zd1_infocus20m550203d {
    public static final String DATA = "InFocus|M550 3D|";
}
