// This file is automatically generated.

package adila.db;

/*
 * LG G Flex
 *
 * DEVICE: zee
 * MODEL: LG-D950G
 */
final class zee_lg2dd950g {
    public static final String MANUFACTURER = "LG";
    public static final String NAME = "G Flex";
}
