// This file is automatically generated.

package adila.db;

/*
 * Motorola Cliq-XT
 *
 * DEVICE: zeppelin
 * MODEL: MB501
 */
final class zeppelin_mb501 {
    public static final String MANUFACTURER = "Motorola";
    public static final String NAME = "Cliq-XT";
}
