// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6 Edge
 *
 * DEVICE: zeroltelra
 * MODEL: SM-G925R6
 */
final class zeroltelra {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S6 Edge";
    public static final String SERIES = "Galaxy S";
}
