// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6
 *
 * DEVICE: zerofltelgt
 * MODEL: SM-G920L
 */
final class zerofltelgt {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S6";
    public static final String SERIES = "Galaxy S";
}
