// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6 Edge
 *
 * DEVICE: zeroltespr
 * MODEL: SM-G925P
 */
final class zeroltespr {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S6 Edge";
    public static final String SERIES = "Galaxy S";
}
