// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6 Edge
 *
 * DEVICE: zerolte
 * MODEL: SM-G925I
 */
final class zerolte_sm2dg925i {
    public static final String MANUFACTURER = "Samsung";
    public static final String NAME = "Galaxy S6 Edge";
    public static final String SERIES = "Galaxy S";
}
