// This file is automatically generated.

package adila.db;

/*
 * Lenovo Z90/VIBE Shot
 *
 * DEVICE: zoom_tdd
 * MODEL: Lenovo Z90-3
 */
final class zoom5ftdd {
    public static final String DATA = "Lenovo|Z90/VIBE Shot|";
}
