// This file is automatically generated.

package adila.db;

/*
 * ZTE N919D
 *
 * DEVICE: ZTE-N919D
 * MODEL: N919D
 */
final class zte2dn919d_n919d {
    public static final String DATA = "ZTE|N919D|";
}
