// This file is automatically generated.

package adila.db;

/*
 * ZTE A880
 *
 * DEVICE: ZTE-A880
 * MODEL: ZTE A880
 */
final class zte2da880_zte20a880 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "A880";
}
