// This file is automatically generated.

package adila.db;

/*
 * ZTE N799D
 *
 * DEVICE: ZTE-N799D
 * MODEL: N799D
 */
final class zte2dn799d_n799d {
    public static final String DATA = "ZTE|N799D|";
}
