// This file is automatically generated.

package adila.db;

/*
 * ZTE Kis 3
 *
 * DEVICE: ZTE-P821E10
 * MODEL: ZTE Kis 3
 */
final class zte2dp821e10_zte20kis203 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Kis 3";
}
