// This file is automatically generated.

package adila.db;

/*
 * ZTE T792
 *
 * DEVICE: ZTE-T792
 * MODEL: ZTE B792
 */
final class zte2dt792_zte20b792 {
    public static final String DATA = "ZTE|T792|";
}
