// This file is automatically generated.

package adila.db;

/*
 * ZTE Z795G
 *
 * DEVICE: ZTE-Z795G
 * MODEL: Z795G
 */
final class zte2dz795g_z795g {
    public static final String DATA = "ZTE|Z795G|";
}
