// This file is automatically generated.

package adila.db;

/*
 * ZTE N880G
 *
 * DEVICE: ZTE-N880G
 * MODEL: ZTE N880G
 */
final class zte2dn880g_zte20n880g {
    public static final String DATA = "ZTE|N880G|";
}
