// This file is automatically generated.

package adila.db;

/*
 * ZTE N900
 *
 * DEVICE: ZTE-N900
 * MODEL: ZTE N900
 */
final class zte2dn900_zte20n900 {
    public static final String DATA = "ZTE|N900|";
}
