// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade A601
 *
 * DEVICE: ZTE_BLADE_A601
 * MODEL: ZTE BLADE A601
 */
final class zte5fblade5fa601_zte20blade20a601 {
    public static final String DATA = "ZTE|Blade A601|";
}
