// This file is automatically generated.

package adila.db;

/*
 * ZTE Turk Telekom TT175
 *
 * DEVICE: ZTE_Blade_V580
 * MODEL: Blade V580
 */
final class zte5fblade5fv580_blade20v580 {
    public static final String DATA = "ZTE|Turk Telekom TT175|";
}
