// This file is automatically generated.

package adila.db;

/*
 * ZTE Turk Telekom TT175
 *
 * DEVICE: ZTE_Blade_V580
 * MODEL: Turk Telekom TT175
 */
final class zte5fblade5fv580_turk20telekom20tt175 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Turk Telekom TT175";
}
