// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade A465
 *
 * DEVICE: ZTE_Blade_A465
 * MODEL: ZTE Blade A465
 */
final class zte5fblade5fa465_zte20blade20a465 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Blade A465";
}
