// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade L110
 *
 * DEVICE: ZTE_BLADE_L110
 * MODEL: ZTE Blade L110
 */
final class zte5fblade5fl110_zte20blade20l110 {
    public static final String DATA = "ZTE|Blade L110|";
}
