// This file is automatically generated.

package adila.db;

/*
 * ZTE Blade A511
 *
 * DEVICE: ZTE_Blade_A511
 * MODEL: ZTE Blade A511
 */
final class zte5fblade5fa511_zte20blade20a511 {
    public static final String MANUFACTURER = "ZTE";
    public static final String NAME = "Blade A511";
}
