// This file is automatically generated.

package adila.db;

/*
 * ZTE U V760
 *
 * DEVICE: ztenj73_gb
 * MODEL: Telenor Touch Mini
 */
final class ztenj735fgb_telenor20touch20mini {
    public static final String DATA = "ZTE|U V760|";
}
