// This file is automatically generated.

package adila.db;

/*
 * Vonino ZUN XO
 *
 * DEVICE: Zun_XO
 * MODEL: ZUN XO
 */
final class zun5fxo_zun20xo {
    public static final String DATA = "Vonino|ZUN XO|";
}
