// This file is automatically generated.

package adila.db;

/*
 * Archos 55 Helium
 *
 * DEVICE: ac55he
 * MODEL: Archos 55 Helium
 */
final class ac55he {
    public static final String DATA = "Archos|55 Helium|Helium";
}
