// This file is automatically generated.

package adila.db;

/*
 * Archos 80 Oxygen
 *
 * DEVICE: ac80ox
 * MODEL: Archos 80 Oxygen
 */
final class ac80ox_archos208020oxygen {
    public static final String DATA = "Archos|80 Oxygen|Oxygen";
}
