// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 7
 *
 * DEVICE: graceqltebmc
 * MODEL: SM-N930W8
 */
final class graceqltebmc {
    public static final String DATA = "Samsung|Galaxy Note 7|Galaxy Note";
}
