// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 7
 *
 * DEVICE: gracelteskt
 * MODEL: SM-N930S
 */
final class gracelteskt {
    public static final String DATA = "Samsung|Galaxy Note 7|Galaxy Note";
}
