// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 7
 *
 * DEVICE: gracelte
 * MODEL: SM-N930F
 */
final class gracelte_sm2dn930f {
    public static final String DATA = "Samsung|Galaxy Note 7|Galaxy Note";
}
