// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy Note 7
 *
 * DEVICE: graceqltelra
 * MODEL: SM-N930R6
 */
final class graceqltelra {
    public static final String DATA = "Samsung|Galaxy Note 7|Galaxy Note";
}
