// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S7
 *
 * DEVICE: herolteskt
 * MODEL: SM-G930S
 */
final class herolteskt {
    public static final String DATA = "Samsung|Galaxy S7|Galaxy S";
}
