// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S7
 *
 * DEVICE: heroqltechn
 * MODEL: SM-G9308
 */
final class heroqltechn_sm2dg9308 {
    public static final String DATA = "Samsung|Galaxy S7|Galaxy S";
}
