// This file is automatically generated.

package adila.db;

/*
 * Allview P7 Pro
 *
 * DEVICE: P7_PRO
 * MODEL: P7_PRO
 */
final class p75fpro_p75fpro {
    public static final String DATA = "Allview|P7 Pro|P";
}
