// This file is automatically generated.

package adila.db;

/*
 * AllView P9 Energy
 *
 * DEVICE: P9_Energy
 * MODEL: P9_Energy
 */
final class p95fenergy_p95fenergy {
    public static final String DATA = "AllView|P9 Energy|Energy";
}
