// This file is automatically generated.

package adila.db;

/*
 * Allview X3 Soul Pro
 *
 * DEVICE: X3_Soul_PRO
 * MODEL: X3_Soul_PRO
 */
final class x35fsoul5fpro_x35fsoul5fpro {
    public static final String DATA = "Allview|X3 Soul Pro|Soul";
}
