// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6 Edge+
 *
 * DEVICE: zenlte
 * MODEL: SM-G928I
 */
final class zenlte_sm2dg928i {
    public static final String DATA = "Samsung|Galaxy S6 Edge+|Galaxy S";
}
