// This file is automatically generated.

package adila.db;

/*
 * Samsung Galaxy S6 Edge
 *
 * DEVICE: zerolte
 * MODEL: SM-G925X
 */
final class zerolte_sm2dg925x {
    public static final String DATA = "Samsung|Galaxy S6 Edge|Galaxy S";
}
